### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by the8472** [Quicksaver/Tab-Groups#10]
For example [this line](https://github.com/Quicksaver/Tab-Groups/blob/master/bootstrap.js#L129) is not valid utf8. It happens to display as `ª` in ISO-8859-1, but how do I know that's the correct charset.

I think it would be a good idea to convert to utf-8 or explicitly specify the charset somewhere.

**Comment by Quicksaver** [comment]
You have a point, I'll convert to UTF-8.
