### ISSUE TITLE
How To? Migrating TGM tabs into the same TG tabs

### ISSUE THREAD

**Issue by Hirnsausen** [Quicksaver/Tab-Groups#100]
Hi,

what is the exact procedure to migrate the entire tab group and tabs structure of the older Tab Groups Manager (TGM) into the new Tab Groups (TG)?

I installed it, and thus had both plugins running at the same time. I thought, that would make the new TG taking the existing TGM structure automatically. But it seems, it did not (there should be an extra button for that inside its OPTIONS). I then disabled the TGM. When I restarted Firefox, no groups were displayed, only endless tabs (over 390).

I enabled the older TGM again, restarted, my groups were back.

So, what is the procedure to migrate the entire structure of the TGM into TG? Is there any special "Migration" button? Or can I load the TGM-saved "*.tgmg" group files? Thanks.

PS:
Good idea to create a new version, I have too many tabs and groups that I need to keep.

Sven

**Comment by Kasijjuf** [comment]
Just to clarify, what is TGM?

**Comment by Hirnsausen** [comment]
TGM = Tab Group Manager (the original version)
TG = Tab Groups (the new replacement of the older TGM)

**Comment by Quicksaver** [comment]
Ah, just replied to your e-mail asking the same thing.

Have you tried [TabGroups Manager revived](https://addons.mozilla.org/firefox/addon/tabgroups-manager-revived/)?

**Comment by Quicksaver** [comment]
Please reopen if you still have any trouble.
