### ISSUE TITLE
Lost all tab groups after firefox freeze and reset

### ISSUE THREAD

**Issue by tanstaaf1** [Quicksaver/Tab-Groups#101]
I was in the tabgroups addon in firefox 45 on mac OSX and moving tabs between groups when everything froze - in the addon and firefox overall.  I was able to quit firefox, however (surprising no system kill of the app was required).  When I restarted there was NOT a restore of existing tabs AND all the tab groups (there where 4 groups with perhaps a hundred tabs all together) were totally gone.

I'm thinking there must be a backup file or files?  Where is it and can I restore the groups?

Thank you for taking over this feature from mozilla.   I hope you can help me, as the lost tabs are invaluable and built up over the past year or so.  Wondering why groups would disappear and, most of all, why there isn't an explicit backup which can explicitly be restored?  I do not have any known backup service.  I am running adblockers and noscript, but don't think these should have anything to do with the freeze nor loss.  Thanks.

**Comment by Quicksaver** [comment]
Usually in these cases if you go to the default homepage ("about:home" if you changed it) there should be a "restore previous session" button there. Hopefully, Firefox simply didn't restore the previous session after freezing, so that should bring back everything.

Worst case scenario is the session file was corrupted when Firefox froze, or even overwritten in the meantime. If you made any backup with the add-on's backup and restore built-in tool, you should be able to restore that. Right now the add-on doesn't have any kind of automated backup, although that's a planned feature that should help with these cases.

**Comment by Keridos** [comment]
This happens to me frequently as well. Sometimes when i quit it (or accidentally like shutdown my PC) it sometimes freezes and deletes my entire session. I can just load a backup, but that deletes all the cookies as well. Gonna test this without TGH and TG and see if it still happens.

**Comment by paleolith** [comment]
> Right now the add-on doesn't have any kind of automated backup, although that's a planned feature that should help with these cases.

Am I correct that you are talking about a copy of the session/groups information? That this information is saved when altered, or at least when FF quits, and loaded when FF restarts, but that there is currently only one copy? (This works well for me, as any such file on my computer is backed up at least once a day.)

Edward

**Comment by Keridos** [comment]
I refreshed my firefox and now it seems to work, looks as if my profile somehow got messed up over the last few months.

**Comment by Quicksaver** [comment]
> Am I correct that you are talking about a copy of the session/groups information?

I'm not sure yet how exactly it will work, to be honest. At most, it will only keep backups of tabs and groups information, no cookies/form data/etc. So it won't be an exact session backup feature, that's better suited for other session-related add-ons to do; [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/) comes to mind, although I don't remember off my head if it has any sort of auto-backup feature...

**Comment by beachdragon** [comment]
This just happened to me running Firefox 44.0.2. Firefox froze and when I restarted it all the Tab Groups had gone. Options are set to restore Windows and Tabs from previous session on startup.

This also happened to me a while back when Tab Groups were built into FF. Back then it was possible to copy a file called sessionstore.js from a backup folder to restore the groups. I've searched FF and neither the file nor the folder seem to be present in 44.0.2.

Are there any other solutions?

**Comment by Quicksaver** [comment]
Try going to the History menu and press on "Restore previous session". Hopefully that should successfully restore your groups and tabs, unless you have already restarted Firefox in the meantime.

If you use [Session Manager[(https://addons.mozilla.org/firefox/addon/session-manager/) or [Tab Mix Plus](https://addons.mozilla.org/firefox/addon/tab-mix-plus/)'s session manager, you can use those to easily recover a lost session.

If you don't use either of those add-ons, you can find the backup session files as described in https://support.mozilla.org/questions/1053113

**Comment by beachdragon** [comment]
History didn't work as I'd already restarted Firefox after it froze.
I don't use Session Manager but I probably will after this :-)
1053113 didn't work but I managed to find an old upgrade.js from February and used that so I'm partially back to where I was.

Thanks for the help

**Comment by Quicksaver** [comment]
I've changed my mind about this, I believe automated backups of the session is a little outside the scope of this add-on.

However, I have made several additions and enhancements to what kind of backups (including several automated backups Firefox and other add-ons make already) from which you can load groups (in the Backup/Restore pane in the options), and now the add-on creates a backup every time it updates as well.

You can try it out already in the latest [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1) if you want.
