### ISSUE TITLE
Extension doesn't use previous (Firefox default) OS X keybindings

### ISSUE THREAD

**Issue by fl0at** [Quicksaver/Tab-Groups#102]
```
OS X 10.11.3
Firefox 44.0.1
Tab Groups 1.02
```

In Firefox with native support for Tab Groups, the default OS X keybindings are:

* Command-Shift-E to show all groups (this is the same in the extension)
* Ctrl-Backtick for forward one group (This is **changed** to Command-backtick in the extension)
* Ctrl-Shift-Backtick for backwards one group (Also **changed**, to Command-shift-backtick)

Two problems with this:
* The new bindings don't work as a "drop-in replacement" for the old native tab groups
* The Command-(shift)-backtick hotkeys are already used by default on OS X, to change between application windows, so they won't work in almost all cases. (It would be akin to rebinding Alt-Tab on Windows!)

Is it possible to change the default back to what they should be?
Add-ons *do* seem to support detecting the end-user OS, so it might be worth making a test for OS to set defaults accordingly:

http://stackoverflow.com/questions/1418896/detect-operating-system-from-firefox-extensio

**Comment by Quicksaver** [comment]
You're right, I misread the initial code and thought the defaults were ```command+(shift+)"`"```, although it's just a simple matter of switching them in the preferences so it's not like you're losing anything.

And I was already planning to change those shortcuts anyway, because the ```"`"``` key isn't easily accessible in many non-US keyboard layouts.

**Comment by fl0at** [comment]
:+1: 
Yeah, it's definitely not a big deal because of the easy workaround. Just threw me for a loop at first.

And thank you for putting this together in the first place: I almost had a heart attack when I heard tab groups were getting deprecated!
