### ISSUE TITLE
Do not show Tabgroups when closing the last tab

### ISSUE THREAD

**Issue by allo-** [Quicksaver/Tab-Groups#106]
With ``browser.tabs.closeWindowWithLastTab;false`` you can close all tabs in a window, without closing the window, which is nice when you just want to close the last tab, but keep the browser to continue surfing.

When having more than one tabgroup, closing the last tab of a group opens the group chooser. I would like it better, if i would still have a blank tab and need to click the tabgroup icon to open the overview.
This avoids for example loading a previously not loaded tab from the next group, when i would open a new empty group anyway.

**Comment by KOTRET** [comment]
:+1:

**Comment by Inkobob** [comment]
I join the request! that would be good

**Comment by allo-** [comment]
Same for pinned tabs: Close a pinned tab with a middleclick, when it's the last tab of the tabgroup. Then not the expose is shown, but the next tabgroup (by which order?) is opened automatically.

**Comment by Quicksaver** [comment]
In [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) I have made some behavior changes that should (hopefully) help with your situation.

Closing the last visible tab of a group will no longer close the group if: a) you disable that option in the add-on's preferences; or b) if you give that group a name (if it has a name, it's never considered fully empty).

So, if you're not in groups view (just browsing normally) and you close the last tab, it will simply open a new tab (you can never not have any visible tabs). If you then close that new tab, it will take you to groups view where you'll be able to choose another group for instance.

In addition, it should no longer load a tab from another group, regardless of if it takes you to groups view or not.

Please give it a try and let me know if you have any problems with it. By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.

**Comment by allo-** [comment]
Seems to work fine :-)

**Comment by allo-** [comment]
I have the problem again with 2.0.1.
Closing the last tab switches to another group, but the old group stays open in the group view.

**Comment by Quicksaver** [comment]
That's not the original problem here, is it? Please open a new issue about it, otherwise I might lose/forget it.

**Comment by allo-** [comment]
It seems quite simliar, but i open a new bug, so the discussion isn't about a fixed and reopened bug.
