### ISSUE TITLE
Load all pages from all groups on startup

### ISSUE THREAD

**Issue by famfop** [Quicksaver/Tab-Groups#107]
Hi,
firefox has the option to load all pages on startup. This only affects the currently opened tab group. I'd love to have the option to load all tabs from all groups at startup (maybe starting with the current group). Hope I didn't miss that it's already implemented but I haven't found the option.

**Comment by Quicksaver** [comment]
Here's the thing, when considering the necessity for groups I always go picture a large amount of tabs open. That could lead to a severe slowdown in browser startup.

I do understand the necessity of loading all tabs for a few use cases, but wouldn't you rather have the browser more readily accessible/usable instead? I'm not sure "load all tabs at startup" and "group tabs in groups" use cases really go hand in hand.

**Comment by Quicksaver** [comment]
(BTW I'm not saying I won't look into this of course, I'm just trying to understand your point of view.)

**Comment by StevenSlater** [comment]
great addon, but i agree with this bug report. i don't mind some slowdown on browser startup, but i find it extremely annoying when already open tabs delay me by loading whenever i switch to them during the day. (also, not sure if this is related, but the "active" group that gets loaded on startup doesn't maintain its original position in the list of groups, but inexplicably moves to the last position.)

**Comment by freggeldoe** [comment]
I always considered this behaviour as a useful feature, because I won't always visit all tabgroups or tabs in any browsing session. If any work is to be done here, provide an option to choose the desired behaviour.

**Comment by Quicksaver** [comment]
Turns out this functionality already exists in Firefox. In about:config, disable ```browser.sessionstore.restore_on_demand``` so that your tabs are loaded on startup, and enable ```browser.sessionstore.restore_hidden_tabs``` so that hidden tabs (i.e. from other groups) are loaded as well.
