### ISSUE TITLE
resize triggers video

### ISSUE THREAD

**Issue by Kikimorra** [Quicksaver/Tab-Groups#109]
I'm using the Tab Groups addon, and when I resize the window while working in one of the tab groups, a youtube video that is in another tab group starts playing. It's always the video which is in the first youtube tab from left to right.

**Comment by Quicksaver** [comment]
Weird. Is the tab already loaded when this happens or is it unloaded? Because I can see loading a tab, and thus auto-playing the video when this happens, as a possibility, even though that shouldn't happen at all. But I don't see how the add-on would interact with the page itself at all.

**Comment by Kikimorra** [comment]
The tab is loaded and stopped, and it doesn't start playing under any other
conditions.

2016-02-18 1:50 GMT+03:00 Luís Miguel <notifications@github.com>:

**Comment by Quicksaver** [comment]
I can't reproduce this at all with the latest [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) at least. Please give it a try and let me know if you still have the issue with it.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.

**Comment by Kikimorra** [comment]
I think it's a Firefox issue actually.

2016-05-13 15:54 GMT+03:00 Luís Miguel <notifications@github.com>:
