### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by poke** [Quicksaver/Tab-Groups#11]
Since you took over a lot of the code from Firefox directly, I assume you are publishing this project also under the MPL? You might want to specify that somewhere so people willing to contribute know what license they are contributing under.

**Comment by Quicksaver** [comment]
It's right there on the [homepage](https://addons.mozilla.org/firefox/addon/tab-groups-panorama/):
> Released under Mozilla Public License, version 2.0

From my understanding of it, just that should cover all the code within it, and without any specific licensing blocks on each file, all files will be subject to that license info (which is the case). Am I wrong? (I do so hate all this licensing stuff...)

**Comment by Quicksaver** [comment]
After thinking about what I wrote, I realize I might have sounded too negative. That was an honest question I made, as my hate for all this licensing stuff comes from not really understanding most of it or even the necessity behind most formalities behind it.

**Comment by poke** [comment]
Don’t worry, I absolutely understand your sentiment; licensing stuff can be a PITA ;)

I didn’t check the addons page to be honest, I would assume that most people expect some note in the actual repository. And most licenses actually require that you distribute the license text as well.

For MPL, the easiest thing you could do is to just take [this file](https://mozorg.cdn.mozilla.net/media/MPL/2.0/index.txt) and add it to the root of the repository as a file named `LICENSE`. Then you’re fine and everything is clear :)
