### ISSUE TITLE
OS X Firefox 44 cannot load backup file of tab group

### ISSUE THREAD

**Issue by mxchai** [Quicksaver/Tab-Groups#110]
As stated in issue title, I am unable to load the backup files of my tab groups. Both the file selection and Open button appear to be greyed out, as seen in the attached screenshot.

![unable to select any backup](https://cloud.githubusercontent.com/assets/8462797/13105283/6e997c58-d59d-11e5-92d6-a3a8032f3512.jpg)

**Comment by Quicksaver** [comment]
That's a known problem that I intend to fix for the next update. For now, you'll have to manually rename those files to add the ".json" extension so the add-on recognizes them.

**Comment by mxchai** [comment]
Alright thanks for the swift response!
