### ISSUE TITLE
name of backup file

### ISSUE THREAD

**Issue by paleolith** [Quicksaver/Tab-Groups#114]
Just a small issue: I created a backup file a few minutes ago, and it is named tabGroups-2016-1-21-11-47-43.json. The year, day, and time are OK, but the month should be 2 (or better yet, 02) rather than 1.

**Comment by Quicksaver** [comment]
Already fixed in the code, it should save with the correct month when it next updates. :)

**Comment by paleolith** [comment]
Thanks!
