### ISSUE TITLE
Skipped group

### ISSUE THREAD

**Issue by trife** [Quicksaver/Tab-Groups#115]
I'm having a hard time consistently recreating the issue, so I apologize in advance.

I'm on 44.0.2 and always have three tab groups open. Occasionally, when switching between groups via the keyboard shortcut, group 1 is ignored and I'm only able to rotate back and forth between groups 2 and 3. In other words, I can move forward from group 2 to 3 and backward from group 3 to 2, but not forward from group 3 to 2. However, I'm able to rotate to group 1 if I'm in one of my four pinned tabs. Nothing is displaying in the browser console and I've disabled other addons in an attempt to diagnose any interference. 

I am still able to go into the panorama mode and enter group 1, but when in panorama, it appears that there are invisible tabs also included within the group being skipped; the last tab is two spaces away from the penultimate tab.

**Comment by Quicksaver** [comment]
I wonder if this is somehow related to #75. Please give that a once through, and especially try the beta version I linked to in my last comment there and see if that helps at all.

**Comment by trife** [comment]
I did see that and installed v1.0.3b3 but the issue persisted. It's odd because it comes and goes if I restart FF a few times. I thought it might be an interaction with Tab Mix Plus, but it has been disabled. I'll let you know if I figure out a way to replicate the behavior.

**Comment by trife** [comment]
I had to reinstall Firefox and significantly clean up my profile after moving to a new computer and I'm no longer experiencing the same issues. It's likely that it was due to some custom about:config flags or possibly due to an interaction with the older groups implementation (maybe?).

**Comment by Quicksaver** [comment]
It's more likely it was some sort of corruption of your session data that was "fixed" when you moved computers (as in, new session). If it ever happens again let me know. :)
