### ISSUE TITLE
Feature request: Toggle dynamic vs static layout/resizing of groups

### ISSUE THREAD

**Issue by nebaughman** [Quicksaver/Tab-Groups#116]
When moving or resizing a group, the current behavior is for other groups to dynamically reposition & resize to make space. This tends to cause many groups to be rearranged/repositioned/resized (and often ends poorly).

Consider adding a setting to choose between this dynamic behavior and static layout. In static layout mode, the tab groups will not resize or reposition on their own (only when the user moves/resizes them).

Note that this may result in groups overlapping. Consider a toggle that allows overlapping (or not). If overlapping groups is not allowed, then refuse to resize/reposition when overlapping would occur.

**Comment by Quicksaver** [comment]
While this is not impossible, all the gains you would possible get from this you can definitely also get from the grid layout (#13), without any of the losses (i.e. overlapping groups). So I don't think I'll add this.
