### ISSUE TITLE
Feature request:  Drop list of groups from button

### ISSUE THREAD

**Issue by irvinm** [Quicksaver/Tab-Groups#117]
I personally don't find it all that useful to display thumbnails of my tabs, but rather I usually know I want to go from one group to a specific group.  With the built in tab groups, I would select the downward carrot symbol to the right of the button and it would list the groups and the number of tabs in each group (helpful) and could select the group I wanted to go directly.

The add-on version does not seem to support this and I can either use keyboard short-cuts to go thru the groups or display the thumb-nailed groups and select the one I want from there.

![2016-02-23_15-32-01](https://cloud.githubusercontent.com/assets/979729/13265812/fe0dcc00-da42-11e5-949f-e14d8b17e226.png)

**Comment by Quicksaver** [comment]
The built-in Tab Groups doesn't have such a thing, that menu must come from another add-on. Also, already planned, see #5.

**Comment by irvinm** [comment]
You are absolutely correct.  (Sorry about not checking first on a clean profile)

I will have to research into which of my add-ons is providing that functionality and why it works with the built in version and not your add-on version.  (I don't have any tab-groups specific add-ons, but I do have some tab-related ones)

Thank you for the quick feedback.

**Comment by irvinm** [comment]
@Quicksaver, I narrowed down my add-ons and found that it was "Tab Utilities Fixed" ([https://addons.mozilla.org/en-US/firefox/addon/tab-utilities-fixed/](url)) that was providing the functionality.

I only tell you if that source code can help you when you get to working on [https://github.com/Quicksaver/Tab-Groups/issues/5](url).
