### ISSUE TITLE
Groups getting merged

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#118]
Hi!

There's this annoying bug that happens sporadically. It happens since the built in panorama days, and continues with this addon.

Sometimes two tabgroups merge into one. After startup everything seems fine. I enter panorama mode. And I see that the current group was merged with another. I guess this is when it actually gets merged. If I leave panorama mode I see all the tabs now of the formerly separate groups.

As for circumstances, there's nothing in particular. Only that I manipulated the groups in the previous session. Repositioned, resized them, maybe closed or created a group. Also I tend to have four groups or more.

**Comment by mzso** [comment]
I'm thinking this might be related-to/caused-by Session Manager. Using `Append to Current Window` feature in particular. Although I can't recreate a circumstance when this happens.

**Comment by Quicksaver** [comment]
Thanks for the extra info. If something in Session Manager is not saving groups data properly, it could easily lead to this situation. I'll be sure to check it out when I look into this.

**Comment by mzso** [comment]
Though the only evidence I have is that it certainly happened once right after I used the append feature.

**Comment by mzso** [comment]
Just happened again. I didn't check out the other groups for a while, but I'm quite certain I didn't use the append feature.
I recently started the profile in all versions from stable to central though. Which might be a factor.
It's also possible that it's crash related. FF has a tendency to not shut down properly during a system shutdonwn on FF45 and above. (As evidenced by Session Manager)

**Comment by Quicksaver** [comment]
Please check out #178. If you still see this issue with the beta I link in there, please let me know in that issue.
