### ISSUE TITLE
^⇧` not working with russian keyboard

### ISSUE THREAD

**Issue by ratijas** [Quicksaver/Tab-Groups#119]
however, ``` ^` ``` works normal.

Mac OS X 10.8.2, FF 44.0.2

**Comment by Quicksaver** [comment]
In a russian keyboard, ```shift+` ``` changes the ``` ` ``` to a ``` ~ ```. So that's what you have to define in the shortcut if you want to use that key.

**Comment by ratijas** [comment]
i can see.

but note that is normal Mac OS installation by default you can switch windows with ``` ⌘` ```, and it works for english and russian — however not for ISO spanish :( — w/o any changes.  i suppose, it adds `⇧` modificator automatically to do 'reverse' thing.  also note that it was working as i just described in FF before.

![2016-02-25 1 19 39](https://cloud.githubusercontent.com/assets/6737986/13294268/22832df2-db5e-11e5-889b-b7f891f1dee9.png)

**Comment by Quicksaver** [comment]
I'm not sure I fully understood your comment. I am aware that before the shortcuts used ctrl instead of command before if that's what you meant (#102).
