### ISSUE TITLE
Theme incompatibility

### ISSUE THREAD

**Issue by xjaven** [Quicksaver/Tab-Groups#120]
I am not entirely sure if I should report this to the theme's creator or the creator of tab groups. I think it should be here, sorry in advance if I am wrong. 
I am currently using the theme FT DeepDark ver. 14.0 with Firefox ver. 44.0.2 on Windows 7 64-bit. I disabled all add-ons and isolated this as the one that was preventing the theme's features from being shown at the tab group page.
Link to Add-on: [https://addons.mozilla.org/en-US/firefox/addon/ft-deepdark/](url)
Tab Groups Enabled:
![firefox theme issue](https://cloud.githubusercontent.com/assets/17463067/13304828/29437388-db25-11e5-97ef-c626362851cd.PNG)
Tab Groups Disabled:
![firefox theme working](https://cloud.githubusercontent.com/assets/17463067/13304833/2ceb5686-db25-11e5-9806-84e1c71028e6.PNG)

**Comment by Quicksaver** [comment]
#67 and #86.

**Comment by johngraciliano** [comment]
I see this is now closed. When I checked Firefox 44.0.2 in Windows 8 there was no such problem.  I believe this is probably more of a theme issue.  When I checked it looked as if the extension is using a transparent background.

**Comment by Quicksaver** [comment]
It's closed because it's a duplicate of #86. ;)
