### ISSUE TITLE
Alt key + number changes tab group, and cannot be disabled or changed

### ISSUE THREAD

**Issue by Relequestual** [Quicksaver/Tab-Groups#121]
On OS X, the hash symbal is typed using alt + 3. Trying to do this in Firefox (44.0.2) with Tab Groups plugin (1.0.2) changes tab group rather than allowing me to type hash.

**Comment by Kasijjuf** [comment]
~~I can understand [Shift]+[3] resulting in the # symbol, but [Alt]+[3]‽~~

Ok, I just found on Wikipedia: 

> On UK Mac keyboards, # is generated by ⌥ Opt+3, whereas on other European Mac keyboards, the # can be found above the right shift key.

@Quicksaver This will probably be important to know when writing a fix.

**Comment by Relequestual** [comment]
Looks like this is actually caused by the plugin Tab Group Helper (TGH), which does have the preferences to disable or change the shortcut. Only found it when it updated! So closing this issue.
