### ISSUE TITLE
All groups and tabs lost

### ISSUE THREAD

**Issue by jeffandq** [Quicksaver/Tab-Groups#124]
I opened firefox on leap day morning.  Every one of my roughly 20 groups was gone.  I had a group for each of my consulting projects, and one for my nephew who died in a helicopter crash last may.  These are impossible to re-create.

I want to know how to get that data back.

I was informed by firefox that they would be discontinuing tab groups, and that if I add this add on, it would work identically and seamlessly, and everything would be backed up into bookmarks if that was not the case.

So this is both an issue report, and a rating of 0 stars.  I mean, how ridiculous that you would release something that was intended for handling their upgrade, and it doesn't even make it to the upgrade?

Mainly, I want to know how to get the data back.  I mean, firefox must track and hold everything, right?  I need my tabs and groups back, if not in the form of groups, then in the form of bookmarks.

**Comment by Quicksaver** [comment]
I've replied to your e-mail, but I'll copy it here as well:

> First of all, I'm very sorry to hear that, of course I understand your difficult situation. I should clarify the bookmarks part though: your groups are backed up to your bookmarks by Firefox *only* when it updates from 44 to 45, but if you have the add-on it stops this migration as it is no longer necessary. Other than that, the add-on touches the bookmarks nowhere.

> I should also mention, you are pretty much the first person to have ever mentioned anything like this happening. Only one other user has had something similar happen, and that was caused by a session corruption (unrelated to the add-on) that made him lose all his session data as well. I'm fairly certain your case is very similar, there's still a big chance you can restore your previous session with all your groups.

> If you use any add-on like Tab Mix Plus or Session Manager, they should let you restore previous sessions with ease. If that's not your case, have you tried this: https://support.mozilla.org/questions/1053113 ?

> The add-on also lets you make backups of your tabs and groups, and while I do plan to add some sort of automated backups feature, for now you'll have to do it manually by going to the add-on's preference. I suggest you keep regular backups if you worry about this happening again.
