### ISSUE TITLE
Backup Files Not Working

### ISSUE THREAD

**Issue by designsimple** [Quicksaver/Tab-Groups#125]
First, thank you for continuing to develop this useful feature that really should be built into Firefox.

Couple odd things on the backup files:
Tab groups disappear on hard Firefox crashes (that's not the thing yet) which I blame on Firefox mostly, but no sweat because I do manual backups!

Problem is that when I go to Load Backup File in prefs, it does not recognize the backups I've saved, all of which have names like "tabGroups-2016-1-7-13-55-53" but no extension. How do I fix it so I can actually use my backups?

Second odd thing: The nomenclature of the backup files seem to be a month off. I'm assuming the first digits are the date of the backup. But Feb was saving as "1" and now March is saving as "2".

Thank you for any help.

**Comment by Quicksaver** [comment]
#110 (see this for how to use those backups you already have) and #114. Both already fixed locally, the next update will have fixed both issues.

**Comment by designsimple** [comment]
Thank you very much!
I searched articles before I posted, but apparently not well enough. That fixed everything.
