### ISSUE TITLE
Feature Request: Share tabgroups between devices via sync

### ISSUE THREAD

**Issue by timoc** [Quicksaver/Tab-Groups#126]
Hi,

I would like to be able to compose a tabgroup on my desktop, and view it on my phone or work desktop. I can already do this with for single pages,  history, bookmarks, settings etc. it would be nice to also do this with tabgroups.

**Comment by Quicksaver** [comment]
#44. Also I'm not sure how well it would work syncing for phones, at most I think it would just sync all tabs as if there were no groups (like it does now) since this add-on only works for Firefox desktop.
