### ISSUE TITLE
Restore groups doesnt seem to work

### ISSUE THREAD

**Issue by dennismccarthy** [Quicksaver/Tab-Groups#127]
Whenever I save and then try to restore tab groups, the files is greyed out. If this did work, I could save group in Dropbox and load in into FF on a different device?

**Comment by Quicksaver** [comment]
You'll have to manually rename the files to include the ```.json```extension before the add-on can recognize them. More details in #110. And yes, loading them in a different device should work just fine.

**Comment by dennismccarthy** [comment]
Wow. That makes this the best Moz add-on in the History of the World. I’m the
guy who was horrified when I heard FF was killing this feature and was ready to
sadly move onto another browser. Thanks so much for your contribution. I’ll
definitely donate to the cause.

Dennis McCarthy Web Tech Manager | The Augustine Institute [https://augustineinstitute.org] Transforming Catholic for the New Evangelization 6160 S. Syracuse Way | Greenwood Village, CO 80111 office: 303.937.4420 [tel:303.937.4420] ext 113 | mobile: 719.330.2039 [tel:719.330.2039]
via CloudMagic for Mac
[https://cloudmagic.com/k/d/mailapp?ct=dx&cv=7.4.173&pv=10.11.0&source=email_footer_2]
On Sat, Mar 5, 2016 at 8:28 AM, Luís Miguel <notifications@github.com> wrote:
Closed #127 [https://github.com/Quicksaver/Tab-Groups/issues/127] .

—
Reply to this email directly or view it on GitHub
[https://github.com/Quicksaver/Tab-Groups/issues/127#event-578846886] .[https://github.com/notifications/beacon/AOiJ-WtaR4gTz-_2p3MBeO3hFUvFiy9tks5pqaElgaJpZM4HqAzG.gif]
