### ISSUE TITLE
"Load migration backup" reverses tab order

### ISSUE THREAD

**Issue by Atario** [Quicksaver/Tab-Groups#128]
Within each group, after restoration, the tabs are in exactly the opposite order of what they were before migration.

**Comment by Atario** [comment]
In addition, the groups themselves are reversed in order (by hitting ctrl + `).

**Comment by Quicksaver** [comment]
Is this from the migration backup only, or from any other backups?

**Comment by Atario** [comment]
Haven't tried with other backups; this was from migration.

**Comment by Quicksaver** [comment]
It's possible that the migration backup stores the information in reverse for some reason, or that for whatever reason something went wrong when you restored from it.

Right now I can't reproduce this from any other type of backups, and seeing as it's very unlikely you'll need to use the migration backup more than once (and it will be removed by Firefox eventually anyway), there's probably no need to create special methods to reverse the order of the restored tabs now.

Also, the shortcut sorts the groups alphabetically (other options for this coming soon), so the order by which they are restored or created is irrelevant.
