### ISSUE TITLE
Open new external (e.g. from TB) links in a specific tab group

### ISSUE THREAD

**Issue by olivercarl** [Quicksaver/Tab-Groups#130]
Let me explain: I have tab groups like ProjectA, ProjectB. I now receive a BZ notification email in TB and click on the link https://bugzilla.projectA.com/show_bug=99
The link will now open in whatever tab group I have active (maybe ProjectB). I can now manually move the tab to tab group ProjectA and switch to tab group ProjectA (2 steps I'd like to avoid) - but probably I am too much distracted by the content of the bug to think of it. Or I get distracted by something else. So the tab that should be in the ProjectA tab group will stay in ProjectB and will never be found again...
The solution for me would be: Define a substring "bugzilla.projecta.com" to always open in tab group ProjectA. Whenever such link is clicked, FF would switch to the matching tab group and open the new tab there.

**Comment by Quicksaver** [comment]
This is how I was thinking #21 and #59 could be implemented actually.

**Comment by Quicksaver** [comment]
Basic implementation of this is in [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4), click each group's gear button to change its individual options, including its catch rules. Please let me know if you find any issues with it.

Might be worth giving the How To Use pane a once-through for all the new things in that beta as well. :)

**Comment by iShyboy** [comment]
@Quicksaver no context menu or basic shortcuts in the expression panels, its kinda weird, since the note in the panel blank out when you start typing and you can't cut to see it again, nor paste if you delete it to see.

**Comment by Quicksaver** [comment]
Yeah, there's none of those anywhere where you type text actually. It's one of the things I have to fix still. And that text is only a placeholder, you wouldn't be able to select it anyway.

**Comment by iShyboy** [comment]
I know @Quicksaver, but I'm not good with expressions so when i started typing I forgot so I had to delete and start again.

**Comment by Quicksaver** [comment]
Editing context menu and shortcuts should now work in [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5). Please give it a try and let me know if you find any problems.

**Comment by olivercarl** [comment]
Works very well for me. Many, many thanks!
A small problem I had was in junction with add-on Tab Group Helper: I was not able to get to the screen where you can configure the feature - I had to disable that add-on.

**Comment by Quicksaver** [comment]
Does that also happen with [beta version 2b10](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b10) and the latest version 1.0.28 of [Tab Groups Helper](https://addons.mozilla.org/firefox/addon/tab-groups-helper/)?

**Comment by olivercarl** [comment]
Yes. When I click "Manage my groups", it shows a two column popup window from Tab Groups Helper (see attachment). I was not able to find a setting or another link that would show the grid display or similar. So maybe it's just lack of instructions...

![tgh](https://cloud.githubusercontent.com/assets/11293216/15672886/9a83c6e2-2733-11e6-9a32-261f29950b51.png)

**Comment by Quicksaver** [comment]
Well, yeah that's working as expected. You can't change the catch rules from the TGH interface because it doesn't know about it, it's up to its developer to add a means to set those if he wants to.

But in the meantime, you can always go to TGH's preferences and disable the option found at TGH Options > General > "Firefox Tab Groups (Panorama) commands open main UI panel". Then you'll be able to access the main groups view through that menu.

**Comment by olivercarl** [comment]
Yes, this workaround is ok. I think I tried the setting but didn't restart FF, so it didn't work then.
Thanks again!

**Comment by leggewie** [comment]
This feature ROCKS!!

Thank you very much.
