### ISSUE TITLE
Suggestion: Allow more keys in "keyboard shortcut"

### ISSUE THREAD

**Issue by jerouy** [Quicksaver/Tab-Groups#131]
Hi there,

It appears that you have implemented some restrictions in "keyboard shortcut". For instance I cannot assign F12 without having any functional keys such as Ctrl or Alt.

Is this restriction placed due to possible key conflict(F12 is used for Development Tools in Firefox by default)?

Please consider remove this restriction(or at least provide an option). I really want to assign Tab Groups key to F12 and I am able to manage key conflict myself(by using another add-on called "customize shortcut").

Thanks for your work!

**Comment by Quicksaver** [comment]
> Is this restriction placed due to possible key conflict(F12 is used for Development Tools in Firefox by default)?

Exactly. The add-on doesn't let you assign any keyboard shortcuts that are already assigned to something else. But if you change/disable that key in Customize Shortcuts, F12 should then appear in the list of possible shortcuts (you'll have to reload the preferences page to refresh that list). Is this not happening?

**Comment by jerouy** [comment]
Wow that was a rather quick response:)

I just tried but no it doesn't happen. I disabled F12 in Customize shortcuts but F12 still doesn't show up in the list, unless I check Ctrl or Alt:(

![shortcut](https://cloud.githubusercontent.com/assets/8316523/13654866/14517b74-e6af-11e5-880d-40768f5b33fa.jpg)
![shortcut2](https://cloud.githubusercontent.com/assets/8316523/13654867/1454f650-e6af-11e5-9e33-15ab874bb58c.jpg)

BTW, interestingly I cannot find this "Customizable Shortcuts" addon from Mozilla.org website anymore. I swear it was downloaded from there :(

**Comment by Quicksaver** [comment]
You're right, that's recent, not so long ago I installed it from there. Apparently the developer discontinued it: https://github.com/ttaubert/customizable-shortcuts

This way, there's no way I can do anything about it. :(

**Comment by jerouy** [comment]
Thanks for that!

Hmmm... so still, can you recommend a way so that I can assign F12 alone to Group Tabs?

Thanks!

**Comment by Quicksaver** [comment]
To be honest, I only know of one other add-on that let you change default keyboard shortcuts: keyconfig, but that seems discontinued/abandoned as well, so it will stop working completely when signing is enforced in Firefox 46 (because no one is maintaining it so it can be uploaded to AMO to be signed).

So... no. :( I also can't let the add-on define keysets that are already defined because, well, it goes completely beyond the point of the add-on. I'm sorry to disappoint. But if you do find any other add-on that does this, please let me know if it works properly with this add-on; customizing existing keyboard shortcuts seems like a popular feature, so it's possible someone will create something new for it eventually.

**Comment by jerouy** [comment]
Thanks!

P.S. Your add-on rocks!

**Comment by Quicksaver** [comment]
Agreed. :)

Thanks, I'm glad you like it. Spoiler alert: it will rock even harder soon. ;)

**Comment by jerouy** [comment]
Good news, I managed to find another add-on: [https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/](url)

This addon is able to disable F12 from its default function then as you said F12 appears in the list without other keys checked.! It has to be set up in a certain order(I am still trying to figure out) but it works eventually!

Anyway I am happy :+1:

**Comment by Quicksaver** [comment]
That seems like a very nice add-on, I didn't know about it. Thanks for letting me know, I'm glad to hear it works well with Tab Groups. :)
