### ISSUE TITLE
Lost Icon based theme

### ISSUE THREAD

**Issue by GaryQld** [Quicksaver/Tab-Groups#132]
I have multiple FF windows open, and since an upgrade just now only one window has the icon style list of tabs. The other windows (2 of) use a drop down style list menu instead when i click the tab groups icon on the tool bar. Previously all 3 windows had the icon based look.

Am I missing a setting or is something going on?

**Comment by Quicksaver** [comment]
I have no idea of what you are talking about. Could it be another add-on giving you the dropdown menu?

**Comment by GaryQld** [comment]
Give me a sec, Ill attach some screengrabs. And, wow that was quick...

**Comment by GaryQld** [comment]
When i click this button
http://imgur.com/YTVpIlo

One of the FF windows will display this format of the tab groups
http://imgur.com/TkgjPvU

But the other 2 FF windows will only show this format, which Ive never seen until the last update.
http://imgur.com/TaY50yU


Hope that is clearer.

**Comment by Quicksaver** [comment]
That definitely doesn't come from this add-on, maybe [Tab Groups Helper](https://addons.mozilla.org/firefox/addon/tab-groups-helper/) from the looks of it?

**Comment by GaryQld** [comment]
Thankyou. You are 100% correct, it was the TGHelper. Disabled and all is as it was.

**Comment by Quicksaver** [comment]
You're very welcome, I'm glad to hear it. :)
