### ISSUE TITLE
Request: use mouse clicks on the panorama icon

### ISSUE THREAD

**Issue by Inkobob** [Quicksaver/Tab-Groups#133]
Please add the possibility of action on the mouse button
eg:
Left - the default action
middle - to open a new group and move into it
Right - to close the current group and go to previous
scroll up - go to the next group
scroll down - go to the previous group
P.S. I did this possibility earlier by addon Custom Buttons.  it was very comfortable!

**Comment by Quicksaver** [comment]
To be honest, I think that's a whole lot of functionality for just a button. So I doubt I'd add that. Also, I wouldn't replace right-click with a single action like that, it's supposed to show a context menu and it's better for everyone to keep it that way. And scrolling on the button would hardly work on a touchpad, so not everyone would be able to do that easily, which means it would be sort of a waste of code on my part.

Having said that, I do plan on adding easier ways to do all of those actions without having to enter groups mode. ;)

By the way, can't you use Custom Buttons to do the same anymore? You should be able to.

**Comment by Inkobob** [comment]
Yes, at first I wanted to do it by using Custom Buttons. I thought it would be useful to other people.
Thank you for your answer
