### ISSUE TITLE
Cannot switch tab groups if one of the tab groups has no windows

### ISSUE THREAD

**Issue by joshjackson5** [Quicksaver/Tab-Groups#136]
This bug represents functionality that worked with the native Firefox functionality, but was missed when developing the add-on.

Previously, if I had three tab groups and only two had windows inside, I could swap between the two without issue. Once the third tab groups had a window, I then started swapping between the three.

Now, with the add-on installed, I have to have a window open in every tab group before any amount of switching is allowed. If any single tab group is missing a window, switching between groups is disabled.

Reproduction:
- Open Firefox
- Press Command-Shift-E
- Create three tab groups, leave one without any windows
- Press Control-` to switch between them (there will be no action from Firefox with the addon installed)

**Comment by Quicksaver** [comment]
#75

**Comment by joshjackson5** [comment]
My mistake - I didn't read low enough through that comment chain. #75 is the same issue.

Thank you for responding to this so quickly.
