### ISSUE TITLE
Can't load about:tabgroups in Nightly

### ISSUE THREAD

**Issue by onemen** [Quicksaver/Tab-Groups#137]
**Tested on clean profile on Nightly**

When trying to open Tab Groups options in Nightly, new blank tab is opened, and these messages are in the Browser console:
`TypeError: Services.io.newChannelFromURI is not a function PrefPanes.jsm:82:18
[Exception... "Component returned failure code: 0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS) [nsIWebNavigation.loadURIWithOptions]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://browser/content/browser.js :: _loadURIWithFlags :: line 841"  data: no]
addTab()
 tabbrowser.xml:1974
loadOneTab()
 tabbrowser.xml:1472
openLinkIn()
 utilityOverlay.js:358
openUILinkIn()
 utilityOverlay.js:196
switchToTabHavingURI()
 browser.js:7427
openOptionsInTab()
 extensions.js:1464
gViewController.commands.cmd_showItemPreferences.doCommand()
 extensions.js:1092
gViewController.doCommand()
 extensions.js:1450
showPreferences()
 extensions.xml:1555
oncommand()
 /:1
 tabbrowser.xml:1974:0
`

**Comment by Quicksaver** [comment]
Already fixed locally. ;)

**Comment by Quicksaver** [comment]
https://github.com/Quicksaver/Tab-Groups/commit/a583e88601f37e5b260c1942bf31a72437d6a8f4
