### ISSUE TITLE
AZERTY Keyboard Shortcut

### ISSUE THREAD

**Issue by olivi55** [Quicksaver/Tab-Groups#139]
Hi, I'm using azerty keyboard, and the keys between "Right" and "F1" doesn't work for "Switch to the next group" and "Switch to the next group" functions...what should I do ?

**Comment by Quicksaver** [comment]
Azerty layouts usually don't even have "right" and "f1" anywhere close together. What keys do you mean?

**Comment by olivi55** [comment]
Sorry I made a bad explanation X)...in the Tab Groups settings we can custom the shortcuts : and for "Switch to the next group" and "Switch to the next group" functions, there are several keys to choose in the list...I meant the keys between "Right" and "F1" in these lists^^

**Comment by Quicksaver** [comment]
You have to play with shift basically. For instance ``` ctrl + * ``` and ``` ctrl + , ``` should work just fine, but to use ``` . ``` you need to define shift for that one as well. Same for ``` + ```, ``` / ```, etc. Does that not work?

**Comment by olivi55** [comment]
yes...it works but in fact I'd like to use the ² Key which is at the same location than ` on english keyboards...is there a way I could change manually the keys in the extension files ? (whose location I don't know by the way ^^)

**Comment by Quicksaver** [comment]
I'll add that key to the next version, and perhaps a few others from that layout as well. :)

**Comment by olivi55** [comment]
ok thx a lot !:)...what can I do for that until next version ?
(for azerty keyboard I could suggest you
  " ² " 
 " & "
 " é "
 " " "
 " ' "
 " ( "
 " - "
 " è "
 " _ " 
 " ç "
 " à " )

**Comment by Quicksaver** [comment]
Could you please do something testing for me? Install a key modifier add-on like [Keybinder](https://addons.mozilla.org/firefox/addon/keybinder/) and try to change any shortcut to use those keys. For instance, try changing "Reload current page" to something like ```Control + ²``` and see if it successfully reloads a webpage.

Try to check all of those keys you suggested and let me know which ones work.

**Comment by Quicksaver** [comment]
Actually, use [Dorando keyconfig](https://addons.mozilla.org/firefox/addon/dorando-keyconfig/?src=search), it'll be easier to extrapolate the values used later if necessary.

**Comment by iShyboy** [comment]
ç ' , etc working fine.

**Comment by olivi55** [comment]
works really nice with Dorando ! thx very much^^

**Comment by Quicksaver** [comment]
> works really nice with Dorando ! thx very much^^

Well, I'm glad to hear that, because unfortunately I think that will be your only option for now. I realized that adding support for that key can be confusing, because it looks too much like the actual 2 key. The only option would be to rewrite the current shortcuts implementation in the add-on to be more similar to one of those add-ons, where you can actually press the key you want instead of selecting it from a dropdown menu.

That won't happen any time soon though. I will be tracking that in #104, so you might want to follow that issue instead of this for when i do.
