### ISSUE TITLE
 TabContextMenu.contextTab is null

### ISSUE THREAD

**Issue by onemen** [Quicksaver/Tab-Groups#140]
`TypeError: TabContextMenu.contextTab is null TabView.jsm:110:7`

**Comment by Quicksaver** [comment]
That's not supposed to be null of course, how/when does that happen?

**Comment by onemen** [comment]
It look like [Menu Wizard](https://addons.mozilla.org/en-US/firefox/addon/s3menu-wizard/?src=search) fault
Menu Wizard extension version 4.02 dispatch popupshowing event for tabContextMenu and contentAreaContextMenu

Just make sure it doesn't break anything in your extension, you can check for aEvent.target.state

**Comment by Quicksaver** [comment]
I'll take a look, thanks for letting me know.

**Comment by Quicksaver** [comment]
I can't reproduce this in any way with Menu Wizard 4.04. Please reopen if you still have any issues, preferably with some steps to reproduce.
