### ISSUE TITLE
Tab groups not working with non-default style

### ISSUE THREAD

**Issue by msm-code** [Quicksaver/Tab-Groups#142]
I have my firefox style changed to Deep Dark theme (or whatever it's called right now).

Tab groups addon doesn't acknowledge this, and look mostly the same regardless of theme.

![screen0](https://cloud.githubusercontent.com/assets/7026881/13741217/6a4bb822-e9d5-11e5-9e4d-9790d1606541.PNG)

![screen1](https://cloud.githubusercontent.com/assets/7026881/13741248/8ffa0cd6-e9d5-11e5-9c72-772b17379ce5.PNG)

**Comment by Quicksaver** [comment]
See #67 and #86.
