### ISSUE TITLE
Tab Groups bar no longer scrolls

### ISSUE THREAD

**Issue by teryg93** [Quicksaver/Tab-Groups#143]
I probably have too many groups, but since the latest update, the tab groups bar doesn't scroll. I can't get to any groups to the left or right of what I can see in my browser window.

**Comment by Quicksaver** [comment]
Erm, what groups bar? All the groups should always be visible on screen.

**Comment by Quicksaver** [comment]
Although it's true that sometimes groups go beyond the window boundaries, I'm already working on ways to avoid that. But even so, there shouldn't be any scrollbars anywhere.

**Comment by teryg93** [comment]
There aren't any scrollbars, but I do have gropus to the left and right of the tabs I can see on the screen. Maybe I need to not have so many groups open at one time. I've always been able to move the bar with the groups tabs in it to the left and right, to get to whatever I can't see on the screen. I can no longer do that. I'm attaching two files--one with a snap of the tabs across the top of the screen and one with the list of tabs. 
![screen shot 2016-03-14 at 2 07 55 pm](https://cloud.githubusercontent.com/assets/17826117/13754695/54ad99d6-e9ee-11e5-9c2e-65b1ef2dc1b8.png)
![screen shot 2016-03-14 at 2 07 31 pm](https://cloud.githubusercontent.com/assets/17826117/13754696/54b1f198-e9ee-11e5-898f-78a029d8624f.png)

**Comment by Quicksaver** [comment]
That's from [Tab Groups Helper](https://addons.mozilla.org/firefox/addon/tab-groups-helper/).

**Comment by teryg93** [comment]
Ah! I'll contact them.
