### ISSUE TITLE
Alternate Keybinding 'ctrl' + 'E'

### ISSUE THREAD

**Issue by cruzzer** [Quicksaver/Tab-Groups#144]
Is it possible to use 'ctrl' + 'E' on windows or 'command' + 'E' on mac as keybinding? I've tried changing it in about:config(extensions.tabgroups.tabViewKeycode), but that didn't seam to work.

On Windows I can only select 'ctrl' + 'Q' and on Mac 'command' + 'Y'.

Might firefox be limiting certain bindings?

**Comment by Quicksaver** [comment]
The add-on only lets you select available shortcuts. Both of those are already bound to focusing the search bar, so they can't be used unless you use another add-on to disable them first. See #131 for a suggestion on how to do that.

**Comment by cruzzer** [comment]
Thank you, that worked for me.
I've contacted the successor to "Customize Shortcuts" and see if he'll release his work on Mozilla's website.

**Comment by cruzzer** [comment]
I've gotten an answer from the "Customize Shortcuts" successor and it's called "Keybinder" and can be found here: https://addons.mozilla.org/en-US/firefox/addon/keybinder/?src=search

There seams to be an issue with disabling the action "Web Search 2"=Ctrl+E, as it just resets itself when Firefox restarts. I've seen the same issue with Keybinder and with Menu-Wizard referred to in #131. This might need to be fixed on the Keybinder/Menu-Wizard front.

Thank for your great work and keeping Tab-groups going :+1:

**Comment by Quicksaver** [comment]
Cool, didn't know about that one either. Thanks for letting me know!
