### ISSUE TITLE
New User: TabGroups Not Being Saved On Exit of Firefox

### ISSUE THREAD

**Issue by CaseyKazan** [Quicksaver/Tab-Groups#145]
I don't know why they disappear.  I have checked all of the TabsGroup settings and can't find anything amiss.

Also, I am confused with the backup and restore--why is it trying to backup into my "My Pictures" folder?  I'm using Win XP SP3 and FF 45.0.

Thank you.

**Comment by Quicksaver** [comment]
> I don't know why they disappear. I have checked all of the TabsGroup settings and can't find anything amiss.

In your Firefox options, what is defined in "When Firefox starts"? It should be "Show my windows and tabs from last time". Are you using any session management add-ons like [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/) or [Tab Mix Plus](https://addons.mozilla.org/firefox/addon/tab-mix-plus/)?

> Also, I am confused with the backup and restore--why is it trying to backup into my "My Pictures" folder? 

Right now it's defaulting to the last folder you downloaded anything into, as if it were another download (although it doesn't actually download anything, it's all local of course). I have already changed this in the code to default to a specific backups folder in your profile, which will be in place in the next release.

**Comment by CaseyKazan** [comment]
Hey, Luis!
    
    Thanks for the fast reply.  Yes, in FF I do have "Show my windows
    and tabs from last time when Firefox starts" as the default in Tab
    Groups (and FF).  Note that in Tab Groups, I do not have any
    alternate choice (the box is "grayed-out").
    
    I do have Tab Groups Helper but it is disabled.
    
    And, of course, today, when I opened FF and clicked on Tab Groups,
    my last session was there.  Go figure.
    
    Thanks again,
    
    Evan
    
    
    On 3/17/2016 2:01 AM, Luís Miguel
      wrote:
    
    
      
        I don't know why they disappear. I have checked all of the
          TabsGroup settings and can't find anything amiss.
      
      In your Firefox options, what is defined in "When Firefox
        starts"? It should be "Show my windows and tabs from last time".
        Are you using any session management add-ons like Session
          Manager or Tab
          Mix Plus?
      
        Also, I am confused with the backup and restore--why is it
          trying to backup into my "My Pictures" folder? 
      
      Right now it's defaulting to the last folder you downloaded
        anything into, as if it were another download (although it
        doesn't actually download anything, it's all local of course). I
        have already changed this in the code to default to a specific
        backups folder in your profile, which will be in place in the
        next release.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly or view
          it on GitHub

**Comment by Quicksaver** [comment]
Well, let me know if it happens again.
