### ISSUE TITLE
Option to have the button on the left side of the title bar?

### ISSUE THREAD

**Issue by joshuastevenson** [Quicksaver/Tab-Groups#147]
Is that possible? In GNOME, "Activities" is in the top left and in Windows 10,  "Task View" is there when task bar is on the left. Not important as the button can be moved to the toolbar where it can be positioned to the left of the address bar. 

(not sure how to move it back to the title bar though)

**Comment by Quicksaver** [comment]
In customize mode you can move the button to the title bar, to the left and right of the tabs; the dotted line showing the area doesn't appear there like in the other toolbars, but it is movable there.
