### ISSUE TITLE
Request: Auto Save Backups of Tabs

### ISSUE THREAD

**Issue by bloodcrow777** [Quicksaver/Tab-Groups#148]
In a previous version of Firefox I was using an add on called "Save My Tabs" you can see the documentation on this github https://github.com/turian/save-my-browser-tabs 

Basically it allowed to auto save tabs, every so many minutes or however often one saw fit. It also allowed you to control how many saves would exist in your chosen folder. In short, you could decide how often, and how many backups were stored. 

I would love to see this implemented in tab-groups and here is why. Today I was having issues with my computer, I had to restart my computer a few times by holding my power button down. On one occasion I had my Firefox window open when I had to restart, and reopened it upon restarting my computer, however I then had another issue where my computer froze and had to restart during that second session and never restored the original session. It ultimately forced me to lose all my tabs as I couldn't restore two different sessions. I could only restore the previous session which did have a "restore session" window open, but because it was two sessions back, it lost it. 

I've had this issue a few times in the past and I feel like auto saves should be included by default, but it hasn't been implemented. So I would like to request this feature for future versions of tab-groups. 

Thanks!

**Comment by Quicksaver** [comment]
This won't make it exactly like this in the add-on, although the next version will have many enhancements to loading from other automated backups that Firefox and other add-ons do, which would have definitely helped in this case.

By the way, from what you describe, you may like [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/).

**Comment by Craigeniah** [comment]
Thanks for your response Quicksaver, I apologize for never responding. I use Session Manager regularly now as a result haha.
