### ISSUE TITLE
Tab Thumbnails

### ISSUE THREAD

**Issue by Deudanann** [Quicksaver/Tab-Groups#151]
The tab thumbnails only show the top-left corner of a tab, not the full width of them.

The 'Google' and 'Mozilla Firefox Start Page' tabs here demonstrate this most obviously:
https://addons.cdn.mozilla.net/user-media/previews/full/168/168647.png

Since this image is from the Add-On page for the project, I assume it is not a bug. It is, however, very annoying. A way to set the thumbnails to 'zoom to page width' would be useful.

I remember tab groups not having this issue when they were first introduced to Firefox, but that changed quickly. I assume there is some sort of technical reason why the thumbnails only show the top left of a tab.

**Comment by Quicksaver** [comment]
I agree completely, but I have no idea why it was made like this or if there is even a reason for it. I'll have to look into it.

**Comment by RobJ7** [comment]
I suspect it's a trade-off to improve page recognition from the tiny space available in a thumbnail.  By blowing up a corner, you may make words therein more readable.  This may work better for some users, with numerous very similar pages, a whole page thumbnail may work better for other users.  A trade-off either way ...

**Comment by Quicksaver** [comment]
> I suspect it's a trade-off to improve page recognition from the tiny space available in a thumbnail.

Honestly, I doubt it's that. The whole thing was designed with a high number of tabs in mind, which means small thumbnails. Whether they're full width or just a corner of the page doesn't make a difference in that case. Unless of course it was faulty logic that dictated the corner thumbnails to begin with. ;)

**Comment by Quicksaver** [comment]
3c7f366d3f65d1992f32fcc9eb982ae058b75fcf

**Comment by Quicksaver** [comment]
The tab thumbnails should show the full width view in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6). Please give it a try and let me know if you have any problems with it.

Note that sometimes, for cached thumbnails (unloaded tabs) or if you resize the window after grabbing the thumbnails, it will still only show a portion of the page. There isn't really much I can do in either case, but please do let me know if it becomes problematic or too annoying in any way.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.
