### ISSUE TITLE
Don't show warning when prompting at browser shutdown

### ISSUE THREAD

**Issue by Quicksaver** [Quicksaver/Tab-Groups#152]
@mirh [commented](https://github.com/Quicksaver/Tab-Groups/issues/141#issuecomment-198958203):
> I turned on browser.showQuitWarning and I also find the warning redundant, since Save and Quit already does the trick.

**Comment by Quicksaver** [comment]
True, I'll remove the warning when that is enabled, as it's expected that your tabs and groups are reset then and it acts as a warning (which lets you choose even).

**Comment by mirh** [comment]
Cool. 
Now roll out that on the official repositories :s

**Comment by Quicksaver** [comment]
Beta coming. Just a few more things to finish. ;)

**Comment by Quicksaver** [comment]
This should be fixed in [Beta version 2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2) if you'd like to try it out.
