### ISSUE TITLE
Tabs Changing To New Tab - No Go Back Page Option

### ISSUE THREAD

**Issue by titch71** [Quicksaver/Tab-Groups#153]
Just over the past few days i am getting random pages reverting to 'new page'

Not sure if this has just happened since moving to the latest version of firefox.

Anyone else seeing similar issues?

**Comment by Quicksaver** [comment]
Crashes could easily lead to corruption of the session file and subsequent loss of tab information. Having said that, is this related to Tab Groups?

**Comment by titch71** [comment]
I started to see this happen under normal usage without any crashes - quite possible this has nothing to do with tab-groups just wondered if anyone else had seen this issue when using the extension.  Problems started appearing with release of firefox 45.0.1 also recent updates with tab groups helper.  Will continue to monitor and obv if no-one else reports issues its unlikely to be tab groups.

**Comment by titch71** [comment]
It looks like this fault is being caused by the latest version of tab groups helper.

**Comment by titch71** [comment]
Hey looks like i have finally hopefully resolved this - looks like this problem is relate to another add-on unload tab - thanks again and sorry for clogging up your page
