### ISSUE TITLE
Many tabs are replaced with "New Tab" after restart

### ISSUE THREAD

**Issue by slinkp** [Quicksaver/Tab-Groups#154]
This has happened several times since switching from FF 44 with built-in tab groups to FF 45 with the add-on.  After firefox quit (ctrl-Q) and subsequent start of firefox, about half of my tabs in the currently active tab group come up with the right favicon but the title displayed on the tab is "New Tab". And when I switch to that tab, nothing loads, as if it was indeed a new tab.
Screenshot attached.

Could it be related to also using the Unload Tab extension? I never had this problem until this week.
I can try removing Unload Tab, but am worried about performance impact since I currently have about 100 tabs across 14 groups, and before installing Unload Tab  my laptop would often get very sluggish.

**Comment by slinkp** [comment]
Aha, I see people reporting this issue as an UnloadTab bug.  https://addons.mozilla.org/en-US/firefox/addon/unloadtab/?src=api 

I'll check whether removing UnloadTab fixes this, and if so, will close this.

**Comment by Quicksaver** [comment]
Yep this is likely due to UnloadTab. If after disabling it or if after it is fixed there you still have the issue please reopen this.
