### ISSUE TITLE
Tab Group Bar

### ISSUE THREAD

**Issue by WhiteSp1rit** [Quicksaver/Tab-Groups#155]
Is it possible to make Tab Groups represented on a new toolbar, similarly how it is done here:
[TabGroups Manager](https://addons.mozilla.org/en-US/firefox/addon/tabgroups-manager/?src=ss)
[Tab Group Bar](https://addons.mozilla.org/en-US/firefox/addon/tab-group-bar/?src=search)

This method of representation is much more intuitive than what was done with default Firefox tab groups, as it doesn't require you to switch to and out of a completely separate interface all the time, with tab groups on a toolbar you can always switch groups whenever you need, and drag tabs between groups and switch groups on the fly.

**Comment by Quicksaver** [comment]
#1.
