### ISSUE TITLE
[Request] Shortcut to show full group

### ISSUE THREAD

**Issue by iShyboy** [Quicksaver/Tab-Groups#157]
We all already had, in some time, too many tabs in one group.
![Fullview](http://i.imgur.com/zDQSJMb.png)

When this happen we must go to the group views and click on that 'fullscreen' ![button](http://i.imgur.com/ohHqX9x.png) like button, so, could we have a shortcut that take us directly to the fullview of the group? 

Or a floatwindow like on old firefox 
![oldffpanoramicview](http://i.imgur.com/aiKSvqE.png)

**Comment by Quicksaver** [comment]
I'm assuming you're using [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1).

Groups should still stack if they have too many tabs. Although from your screenshot that group should have stacked already. If you make the group smaller, does it stack then?

**Comment by iShyboy** [comment]
Nope, not an bug, just a request.
![screen](http://i.imgur.com/AvjS457.png)
If we use the shortcut ctrl+shift+e it take us to the group view, in this case, the grid layout.
What I want, it's just a aditional shortcut that take me to the fullview of the group that has too many tabs to show in the group view.

**Comment by Quicksaver** [comment]
Oh. But how would that work? Expand the active group directly if necessary?

**Comment by iShyboy** [comment]
Something like ctrl+alt+e (customizable) to take me to the groupview and expand the active group, or, if there's a way, just show me the full active group without have to take us to the groupview.

**Comment by Quicksaver** [comment]
Sounds interesting, I'll look into it.

**Comment by Quicksaver** [comment]
This will be largely unnecessary when I work in #46 I think. Please re-open after you try it out (and I finish it of course) if you think otherwise.
