### ISSUE TITLE
Some issues in v2b1

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/Tab-Groups#158]
1. This is no longer possible to create a new tab in both views by dragging a range.

2. After you expand a folded group, the group is automatically shrink when the mouse leaves the expanded scope. 
![a folded group](https://cloud.githubusercontent.com/assets/1769875/13974184/7e5c6648-f0e4-11e5-853e-80abfb275a3f.png)

3. These groups will become clutter and overlapping when you first enter to Free arrange view, instead of the previous arrangement automatically.
![first enter to Free arrange view](https://cloud.githubusercontent.com/assets/1769875/13974134/308fff9c-f0e4-11e5-888c-6f0fdbbf6a37.png)

**Comment by yfdyh000** [comment]
4. sessionRestoreNotice.dismiss not work.

**Comment by Quicksaver** [comment]
> This is no longer possible to create a new tab in both views by dragging a range.

This works for me (in free arrange mode only of course). Have you tried disabling all your other add-ons and see if that helps?

> After you expand a folded group, the group is automatically shrink when the mouse leaves the expanded scope. 

That's expected, and it's also been the case since always. If it wasn't happening for you before, that was a bug. ;)

**Comment by yfdyh000** [comment]
> This works for me (in free arrange mode only of course). Have you tried disabling all your other add-ons and see if that helps?

I was wrong, it seems be normal, I mistakenly thought it should create a new tab even dragging occurs within a group, but it should move the group.

> That's expected, and it's also been the case since always. If it wasn't happening for you before, that was a bug. ;)

It seems that you are right, though I don't remember this behavior.

**Comment by iShyboy** [comment]
If you have too many tabs, stack drag an create new group dont work.
https://waa.ai/k0td.mp4
![AddonsActive](http://i.imgur.com/XffOMvi.png)

**Comment by Quicksaver** [comment]
I see what you mean, it is indeed different behavior from before. Even though I didn't actually plan for that change, I intentionally left it in though. I found that it was harder to move a stacked group when you can still drag a tab out of it. And you can always expand it to drag tabs out of it.

I wonder what offers the best trade back, keep the current behavior to allow for better group management, or put back the previous behavior so that you can take tabs out from the groups more easily... Opinions?

**Comment by iShyboy** [comment]
It was still easy enough to drag back then, and it was easy to create a group with the stacked one.

**Comment by Quicksaver** [comment]
You have a point. ;)

**Comment by Quicksaver** [comment]
[Beta version 2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2) should address everything here. Let me know if I missed anything.
