### ISSUE TITLE
Mac Shortcuts to open tab groups aren't fully working

### ISSUE THREAD

**Issue by joshjackson5** [Quicksaver/Tab-Groups#159]
Command+Shift+E doesn't work when AdBlock Plus is enabled. This used to be the default, but now AdBlock Plus has taken it and is somehow given priority (they must have made this change once Firefox removed Tab Groups as part of its core). Disabling AdBlock Plus does resolve the issue. I'll leave it up to you if you want to talk to them about either changing their shortcut or allowing users to customize shortcuts.

Control-Shift-E doesn't work when focused on address bar. It does work any other time. The most common situation is creating a new tab group, where you immediately open a tab and focus the address bar. Instead of being able to immediately Control-Shift-E and create more tab groups, you have to manually click or tab out before doing so again. The issue could be that Firefox does something special with that shortcut, though I have no idea what that might be.

**Comment by Quicksaver** [comment]
I can't tell if that's one issue or two separate issues... The shortcut works just fine for me, with and without ABP. It also works when the cursor is in the location bar. Are you sure it's ABP causing this? Have you tried disabling all your other add-ons except for ABP and Tab Groups?

**Comment by palant** [comment]
Adblock Plus shortcuts are already customizable, see https://adblockplus.org/en/preferences#filters_key. However, there shouldn't be an issue - Adblock Plus should normally detect this shortcut as taken and switch to another one. So there is a strong suspicion that another extension forced Adblock Plus to initialize shortcut keys too early.

**Comment by Quicksaver** [comment]
I've closed this issue, but that's only a half-fix that's not guaranteed to work. As palant mentioned, there is likely another add-on causing the issue, but without any more information there's not really anything I can do. Please reopen if you can find out the culprit.
