### ISSUE TITLE
Remove Yellox bottom bar

### ISSUE THREAD

**Issue by akred** [Quicksaver/Tab-Groups#16]
Hi,

Is it possible to have the possibility to remove the yellow bottom bar when we show groups ?
For example, if we doesn't want to keep groups across the start, it makes no sense to keep this kind of bar.

Thanks.

**Comment by Quicksaver** [comment]
If you're using private windows, starting with the next version the notice will be much more subtle (no jarring yellow background) and will go away automatically after a few seconds.

If you're on normal windows, I'm still working on adding a way to remove the notice.

**Comment by akred** [comment]
Thanks a lot :)

**Comment by akred** [comment]
Hi,

Thanks for your work.
I notice that the yellow bar come back when I restart my browser.
It is normal ?

**Comment by Quicksaver** [comment]
Starting with version 1.0.2 which was just released, there is a dismiss button in the warning. Note that the warning will always be shown at least once per window, as a reminder.
