### ISSUE TITLE
tab pin from tabs group

### ISSUE THREAD

**Issue by Glaived** [Quicksaver/Tab-Groups#160]
![sans titre 2](https://cloud.githubusercontent.com/assets/1835170/14001547/c0ab31e8-f146-11e5-8a99-ad4085fc55ad.png)

**Comment by iShyboy** [comment]
Right, would be awesome.

**Comment by Quicksaver** [comment]
Already planned. ;)

**Comment by kidwm** [comment]
Ref: #34

**Comment by Quicksaver** [comment]
My brain stopped the other day, I completely forgot to duplicate this one, thanks @kidwm :)
