### ISSUE TITLE
Firefox restart and no Tabgroups

### ISSUE THREAD

**Issue by NeoSeeU** [Quicksaver/Tab-Groups#161]
I closed Firefox normally, no PC shutdown, hours later I started Firefox and all tabs where gone. To me its like the restart feature I enabled with a mark doesnt function always, isnt reliable. I lost added tabs of 5 days. Only 5 days, because I use the Session Manager in addition, the last saved session was 5 days ago. Is there a reliable automatic and independend session saving in Tab-Groups, I didnt see one, only the manual backup. Using Win8.1(1) 64bit and 4GB RAM, 450MB was used by Firefox process (45.0.1). I had 17 Tabgroups with alltogether 160 tabs. Is there a limit?
To me it is critical whenever I loose items and resources I thought are saved and kept.

**Comment by iShyboy** [comment]
Something should have happened with yer firefox.exe process on close.
If you have session manager here's a solution.
![SM](http://i.imgur.com/tT03lOa.png)
Just check the auto-backup option.

**Comment by Quicksaver** [comment]
Indeed, Session Manager will give you far better control over backups than Tab Groups ever will.

Having said that, right now there are no auto backups feature in the add-on. I have already added support locally for restoring groups from many types of automated backups (including from Session Manager backups), but I doubt that would have helped you in your case anyway. And I also believe that creating a whole new auto-backup system goes a little outside the scope of the add-on, so this probably won't make it in the add-on, at least not any time soon. And again, even if it did, it would be nowhere near close to what you can do with Session Manager.
