### ISSUE TITLE
Inconsistent switching between groups from different tabs in one group

### ISSUE THREAD

**Issue by jlinkes** [Quicksaver/Tab-Groups#162]
I have three tab groups, let's call them group 1, group 2 and group 3.

There are n tabs in group 1 and some tabs in the other groups. When I switch to the next group using a shortcut (tried with ctrl + F1 and the standard ctrl + `) from m tabs of group 1 I end up in group 2 and when I switch from the rest (n-m) I end up in group 3.

I tried to reproduce the issue from scratch with only this addon (v2b1) enabled and this is what happened:

I started with three groups, each with only one blank tab
group 1, open link 1
go to next group (let's call it group 2) (ctrl F1)
open link 2
go to next group (let's call it group 3) (ctrl F1)
open link 3
at this point, it seems that the order of groups is group 1, group 2 and then group 3

go to next group (ctrl F1)
expected tab 1, instead I see link 2 (which is group 2)
go to next group (ctrl F1)
I see link 1, which is group 1
go to next group (ctrl F1)
i see link 3, which is group 3
repeat go to next group (ctrl F1) a few times and this is the order: group 3, group 1, group 2

at group 2
open new link (link 4) in the same tab
go to next group (ctrl F1)
I see link 1, which is group 1
go to next group (ctrl F1)
I see link 3, which is group 3
go to next group (ctrl F1)
I see link 4, which is group 2
group order is unchanged

go to previous group, which is group 3 (ctrl F2)
open link 5
go to next group (ctrl F1)
I see link 1, which is group 1
go to next group (ctrl F1)
I see link 4, which is group 2
go to next group (ctrl F1)
I see link 5, which is group 3
go to next group (ctrl F1)

now the order is group 1, group 2, group 3

This behavior is quite unpredictable and, more importantly, very annoying.

I have an additional question: Is there any way to define/rearange the order of groups?

**Comment by Quicksaver** [comment]
Right now group switching sorts them alphabetically by name. If the group doesn't have a name, it takes the page title of its currently active tab. So if none of your groups has a name, and their active tabs keep changing, then the order will change as well.

Right now, you can define an order simply by naming your groups appropriately ("1", "2", "3" would work, but "a", "b", "c" would work as well).

I am already planning on adding more ways to sort them (and improve the alphabetical order as it's actually not perfect), for instance sort them in the order defined in grid layout.

**Comment by DuBistKomisch** [comment]
The workaround of adding numbers to the start of group names works great, just wish it was mentioned right on the preferences page! This was my only gripe with the add-on though, great work otherwise.

**Comment by tengwar** [comment]
@Quicksaver +1 for more ways to sort. In the 2b3 version in tabbed mode I found it weird that switching order was different from tab order.

**Comment by Quicksaver** [comment]
In [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4), switching between groups now follows their order as defined in single view and grid layout. I've disabled alphabetical sorting completely because it was hard to predict, and I had only implemented that before because there was no clear ordering in free arrange anyway.

For now I think I'll leave things like that, since there is now a clear sort order that can be easily customized by moving groups around. Feel free to re-open if you think of any better alternatives for your cases.

Let me know if you find any issues with it. It might also be worth giving the How To Use pane a read-through for all the new things in the beta. :)
