### ISSUE TITLE
(minor) Export of Tab Groups settings: generated file name has wrong month number

### ISSUE THREAD

**Issue by DonaldEPayne** [Quicksaver/Tab-Groups#163]
Hi, I'm a first-time poster of an issue. I don't know if this is an issue in Firefox or in the Tab Groups extension. Thanks for creating it.
On the Options page, in lower left there is a drop-down select list that includes "Export...". When you select that, a "File Save" dialog opens with an auto-generated file name. Today, on March 25, 2016, the file name was:

> tabgroups-prefs-2016-**2**-25-12-52-31.json

The month number is "**2**"; it should be "**3**" for March.
(This is even more minor) In addition, I would prefer a leading zero; this makes file names appear in correct chronological order when they are sorted by name:

> tabgroups-prefs-2016-**03**-25-12-52-31.json

This also happens when you export your tab groups (in the Backup / Restore tab):

> tabGroups-2016-**2**-25-13-13-16.json

should be

> tabGroups-2016-**03**-25-13-13-16.json

**Comment by Quicksaver** [comment]
Already fixed locally, #135.
