### ISSUE TITLE
Switching Groups Not Hiding Non-Group Tabs

### ISSUE THREAD

**Issue by valindria** [Quicksaver/Tab-Groups#165]
Hello,
TG stopped working for me today after I changed my monitor orientation to portrait. I don't know how to fix it because I don't understand why/how TG stopped working.
Background: I use ColorfulTabs, Tree Style Tabs and TG. I also had Too Many Tabs for a bit, but dropped it in favor of TG. All three existed happily together without problem while my monitor was in landscape mode.
The feature I love most about TG is when I select one group of tabs, only those tabs appear. Being able to sort tabs into groups and then bring them up by those groups is the rug in the room for me. But now, all of my tabs are up at once and changing the group doesn't do anything but render tabs not in that group unclickable. My monitor is 1200x1920 now, so I had to drop Tree Style Tabs because I don't have the width for the sidebar. This moved my tabs to the top again, but I have about 35 total tabs open most of the time so there's a lot of scrolling now to find the one I need. I partially remedied that by using ColorfulTab's mini tab mode, but it doesn't do the trick like TG does.
Sorry if that's a bit vague, I'm not sure how else to describe it.

**Comment by Quicksaver** [comment]
Screen orientation should be irrelevant to Tab Groups. Is it still enabled in the add-ons manager? Can you still access groups mode by using the keyboard shortcut or the toolbar button?

**Comment by valindria** [comment]
It is enabled, and the groups window is accessible via the toolbar button, and I can bring up the tabs in that group.
I've apparently fixed it by disabling ColorfulTabs, which I think may be an abandoned project now. I'm not sure why they began to conflict when I changed the orientation. I had to get creative about tab width to duplicate "mini-mode", but I'll take TB over ColorfulTabs and live with the non-coloring that I used for years. Here's what they look like now. I moved them to the bottom of the browser.

![tabgroupstabs](https://cloud.githubusercontent.com/assets/5544637/14182575/a705b8d2-f720-11e5-8887-017420a582dc.JPG)

**Comment by Quicksaver** [comment]
I'll take a look at ColorfulTabs and see if it's something that I can fix from my side. Also if you're speaking about this [ColorfulTabs](https://addons.mozilla.org/firefox/addon/colorfultabs/), it doesn't seem abandoned: Last Updated: March 28, 2016. You may want to bring this up with its developers as well, if they can fix it faster than I can, all the better.

**Comment by iShyboy** [comment]
[Prevent Tab Overflow](https://addons.mozilla.org/firefox/addon/noverflow/?src=ss) should do the same as colorful tabs and more, [tab mix plus](https://addons.mozilla.org/pt-BR/firefox/addon/tab-mix-plus/?src=ss) too can change tab width, without doing anything with tab groups.
![TMP] (http://i.imgur.com/F5uxtfT.png)

**Comment by Quicksaver** [comment]
It is definitely ColorfulTabs doing that, specifically its "Minify Tabs" setting, which forces all tabs to be visible even when they're not supposed to be.

This should definitely be fixed by ColorfulTabs itself, a simple ```:not([hidden="true"])``` selector in its CSS code will do the trick. Fixing this within Tab Groups by forcing those tabs to be hidden is just inviting more trouble with other incompatibilities down the line.

I tried e-mailing the author about this, so hopefully this should be fixed soon. If that doesn't happen, please re-open and I'll see if there's anything I can do on my end.
