### ISSUE TITLE
Hide "Merge Windows" Button

### ISSUE THREAD

**Issue by Manimap** [Quicksaver/Tab-Groups#167]
Hi,

I have a lot of open tabs, and this is the third time that I had inadvertently clicked on "merge windows" when right clicking to do something else, so I have to create proper groups again :(.
So, is it possible to :
- add the possibility to hide this button from the right click context?
- at least give us a warning when clicking to give the possibility to cancel it?

Thanks :)
--

**Comment by Quicksaver** [comment]
I don't know of any "merge windows" button. Is that perhaps from Tab Mix Plus? Either way, definitely not something that I can/should do in Tab Groups.

**Comment by Manimap** [comment]
Oh indeed, this was due to tab mix plus that I thought was disabled... I'm sorry, and thanks for the clarification.
