### ISSUE TITLE
Panorama icon disappears from toolbar if Firebug addon is active

### ISSUE THREAD

**Issue by Miguel-Alonso** [Quicksaver/Tab-Groups#169]
Hi, I'm not sure why, but I noticed that after the update to firefox 45.0.1 the panorama icon in the toolbar disappeared.

I tried disabling/enabling all the addons and noticed that it only happens if Firebug is active, if it's deactivated (and after a restart) the panorama icon will appear normally.

OSX 10.11.4
Firefox 45.0.1
Tab Groups 1.0.2
Firebug 2.0.15

Happy to send more info.

**Comment by Quicksaver** [comment]
That's weird. Does the icon appear in customize mode with Firebug enabled, or is it completely gone from everywhere?

**Comment by Miguel-Alonso** [comment]
It's completely gone, the only place it can be accessed is in the see all tabs dropdown that appears (the small triangle beside the '+' icon to create a new tab) and through the keyboard shortcut. I can take screenshots if you think it'll help.

Anyway, I think I have a workaround:
1. With Firebug disabled, go into customize and remove the panorama icon from the toolbar
2. Exit customize mode
3. Activate Firebug
4. Restart Firefox
5. Go into customize, the panorama icon should still be available and can be dragged back to the toolbar

After doing this, I can close and open firefox and everything is still where it should be.

**Comment by Quicksaver** [comment]
So, it's not disappearing anymore?

**Comment by Miguel-Alonso** [comment]
Not once you do the process I described before.

**Comment by Quicksaver** [comment]
So I can't reproduce this, not even in a clean profile. I'm not sure why it was getting rid of the button in the first place in your case, but apparently re-customizing it did the trick. Let me know if this happens again.
