### ISSUE TITLE
Issue with groups joined together on Firefox restart

### ISSUE THREAD

**Issue by Ivnst** [Quicksaver/Tab-Groups#170]
Hi,
Situation is next:
1. Have a lot of pages in several groups.
2. Close Firefox
3. Open Firefox
4. Have the same pages in ONE group.

Tab groups Version 1.0.2 
Firefox version 45.0.1
Issue is repeatable.

Please let me know if I need to provide more information.
Or let me know if this is some kind of feature, and I can configure it by myself.

**Comment by Quicksaver** [comment]
Are you using Session Manager by any chance?

**Comment by Ivnst** [comment]
Yes, you are right. I reviewed my add-ons and found Tab Mix Plus. After reinstalling it, the problem has been fixed. Thanks!

**Comment by Quicksaver** [comment]
Tab Mix Plus should be perfectly compatible with Tab Groups. But as long as it's fixed I guess that's good. Let me know if this happens again.
