### ISSUE TITLE
Shortcut ctrl+E

### ISSUE THREAD

**Issue by cruzzer** [Quicksaver/Tab-Groups#171]
Hello Quicksaver

After deactivating "Web search 2"=ctrl+e via [keybinder](https://github.com/Lord-Kamina/keybinder), I can assign ctrl+e to tabgroups and it works. Unfortunately after restarting Firefox it stops working. I have to set something else and then back to ctrl+e to make it work again. 

Might it by that tabgroups tries to grab ctrl+e quicker than keybinder had the time to deactivate it?

Regards

btw. thank you for overtaking this great plugin :+1: , it must although be quite a challenge

**Comment by Quicksaver** [comment]
It's very possible that that's what's happening. I'll take a look at keybinder and see if there's anything I can do on my side.

**Comment by cruzzer** [comment]
Thanks a lot.
Miss-clicked on closing the issue :)

**Comment by Quicksaver** [comment]
Turns out this won't be possible, for a whole lot of reasons, the most important of which is at the point Keybinder disables the key (the point we know that key is available) is already too late as by then we would have had needed ours already set up.

I'm trying some alternatives, but don't get your hopes up...

**Comment by cruzzer** [comment]
Thanks. I'm now just using an older version of the keybinder which works. Unfortunately the developer removed changing the hotkeys of tab-groups. But I'll see how things develop.

Thank you again.

**Comment by Quicksaver** [comment]
Apparently someone had success with doing something similar (#131) with another add-on called [Menu Wizard](https://addons.mozilla.org/firefox/addon/s3menu-wizard/). Might be worth trying it out.

**Comment by Quicksaver** [comment]
Also #186 for future reference about [(Dorando) keyconfig](https://addons.mozilla.org/firefox/addon/dorando-keyconfig/).

**Comment by iShyboy** [comment]
@Quicksaver there's a problem in using the same main key with another modifier to other shortcut?
As in: 
Ctrl+Q to Open/Exit Tab View (I use this)
Ctrl+Shift+Q to Open Quick panel (The main key Q is missing from the options)

And the thing about using the number row as shortcut:

Ctrl+1 to previous group
Ctrl+2 to Next group

It's an amazing combination for me who use an laptop with QWERTY layout.
Ctrl+Q = Open/Exit Tab View
Ctrl+Shift+Q = Open Quick Panel
Ctrl+1 = Previous group
Ctrl+2 = Next group

**Comment by Quicksaver** [comment]
> there's a problem in using the same main key with another modifier to other shortcut?

As long as they're available, there shouldn't be any problem with that.

> Ctrl+Shift+Q to Open Quick panel (The main key Q is missing from the options)

That's used by the devtools to open the Network panel, that's why it's not available.

> And the thing about using the number row as shortcut:
Ctrl+1 to previous group
Ctrl+2 to Next group

Used to switch tabs, also I much prefer your #181 on that one. ;)

**Comment by iShyboy** [comment]
> That's used by the devtools to open the Network panel, that's why it's not available.
:cry: 
I'm sad, I always go by F12 and then network, so far it's useless for me.
As for #181 i'm open but... well.

**Comment by jmain33** [comment]
One thing I forgot to mention in #442 is that, when <kbd>CTRL</kbd>•<kbd>E</kbd> is assigned to do the operation, DorKey does not show an entry for 'Manage my groups' after launch. So Firefox does not even acknowledge that there is supposed to be such an association.  Yet it still does not re-attach that hotkey to 'focus search', the one assigned by DorKey is what it recognizes.

So I don't know what the deal is with FF disallowing that hotkey :confounded:

**Comment by Quicksaver** [comment]
> DorKey does not show an entry for 'Manage my groups' after launch. So Firefox does not even acknowledge that there is supposed to be such an association.

**Comment by Quicksaver** [comment]
> DorKey does not show an entry for 'Manage my groups' after launch. So Firefox does not even acknowledge that there is supposed to be such an association.

I don't believe I understand what you mean. Firefox doesn't acknowledge Tab Groups' key at that point because it's not being set, it's not working right?

**Comment by jmain33** [comment]
Correct it's not working. I thought the fact that its entry ends up completely missing in Keyconfig might be useful to you in some way, [the last comment](#issuecomment-254925999) was about me forgetting to mention that over at #442.

**Comment by Quicksaver** [comment]
Yeah it's pretty much for the same reason as what I mentioned in the [comment above](https://github.com/Quicksaver/Tab-Groups/issues/171#issuecomment-217851874). It's a race condition: TG inits first, tries to setup its keys, fails because that key already exists, keyconfig only disables it afterwards (if I recall correctly, you need to press some key for keyconfig to initialize, or maybe that's keybinder? Either way, I remember there's some limitation that won't let TG "wait" for it. So, no go.

**Comment by iShyboy** [comment]
Coop with the other side like with fire-gestures it's a no-go?

**Comment by Quicksaver** [comment]
I doubt it, but it's possible. I haven't dedicated much time to it yet though, it would still need some work regardless, probably on both sides, and with WebExtensions approaching there's no point until we can confirm it will keep working then.
