### ISSUE TITLE
Swedish letters does not trigger search 

### ISSUE THREAD

**Issue by falolaf** [Quicksaver/Tab-Groups#172]
Hi,
When I in tab groups view try to do a search with any of the swedish letters å, ä or ö, search is not triggered. I.e. the search box is not shown. I click in the magnifying glass and type as a workaround though. But then I have to use my mouse...
Tested with Tab Groups 1.0.2 on FF 45.0.1, W7.

/Anders

**Comment by Quicksaver** [comment]
I'll see what I can do.

**Comment by Quicksaver** [comment]
I can't reproduce this in the latest [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) at least. Please give it a try and let me know if you still have the issue with that version.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.

**Comment by falolaf** [comment]
I have tested v2b6 and search indeed is now also triggered by swedish å, ä and ö! Thank you!
