### ISSUE TITLE
Cannot load backup file in Mac OS X

### ISSUE THREAD

**Issue by therealdano** [Quicksaver/Tab-Groups#173]
I am using Tab Groups 1.0.2 on Mac OS X El Capitan (10.11) and I can save tab groups to a backup file. On the computer that I save the backup file on, it does show the tab groups in the Backup/Restore section after the backup is saved. However, when I copy it to another computer I cannot select the backup file. It shows in the file picker, but is grayed out and not selectable. It is owned and readable by my account. 

Is there some sort of unique key that gets saved to the backup file that prevents it from being used in another account?

**Comment by Quicksaver** [comment]
See #110.
