### ISSUE TITLE
Feature Request: Show tab count in group title in panorama

### ISSUE THREAD

**Issue by hkockerbeck** [Quicksaver/Tab-Groups#175]
Is it possible to show the number of tabs in a group in the panorama view, something like "Groupname (123)"? 

One purpose I use tab groups for is to "store away" tabs that are interesting, but would clutter the work area at this very moment - a kind of short term "read it later" function. That way I tend to accumulate rather large tab groups. When I need to decide whether I've got the time to "work through" one of those groups or not, I found myself missing a crucial information from the panorama view: How many tabs are in this group? Are there, say, 15 tabs that I can look through before the next appointment, or are there 50, which would be too many. So I'd find it extremely helpful if it would be possible to display the number of tabs per group in the panorama view.

**Comment by Quicksaver** [comment]
Should be doable. :)

**Comment by iShyboy** [comment]
UPP,

I'm actually using [tab counter](https://addons.mozilla.org/firefox/addon/tab-counter/) with the setting %vn|%n to show the number of tabs in the group and in the session respectively ![tc](http://i.imgur.com/tiC2PP6.png). But I must be in the group to see its number of tabs, great suggestion.

**Comment by Quicksaver** [comment]
In [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) you can now see the number of tabs in a group in the quick access panel and in the groups themselves next to the title. Please give it a try and let me know if you have any problems with it.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.
