### ISSUE TITLE
Problem while switching groups

### ISSUE THREAD

**Issue by daverm** [Quicksaver/Tab-Groups#176]
Good morning

I love the add-on, only recently is started glitching, when I click to see the panorama view, it gets stucked on the multi-window view, and I am not able to select any groups, I can't even close the whole Firefox window, I have to start my taks manager end end the task.

Anyone else has that issue?

**Comment by Quicksaver** [comment]
Does that happen every time you enter groups mode? And does it still happen if you disable all your other add-ons and themes except for Tab Groups?

**Comment by daverm** [comment]
Hello Luis,

Thanks for the quick answer. I just deactivated a Google Maps and a Giphy add-on to see if that helps. It doesn’t happen all the time, I could be using it for half a day and then all of a sudden it just glitches there. I’ll click a group, it will zoom in and right out, like it can’t be selected, for all groups, and can’t close the main window either.



Merci / Thank you

David Bissonnette | RM Logistic<http://www.rmlogistic.com/> | david@rmlogistic.ca<mailto:david@rmlogistic.ca>
T. 514-484-7766 x310  F. 514-484-3118 C. 438-325-6491
60 St Jacques - Suite 600, Montreal, PQ, H2Y 1L5
[cid:image001.png@01CDBB47.F819E090]

**Comment by Quicksaver** [comment]
Please try disabling the zoom animation in Tab Groups preferences and let me know if that helps. It seems to cause a few issues, and if that helps then problem already solved: #23.

**Comment by daverm** [comment]
Hey Luis

So it worked fine for a while, now just before leaving the office issue is back, I can’t select any of the windows, I can close the groups, but I can’t focus them, and I can’t close my main window.

[cid:image001.png@01D18E93.CE6FB8A0]



Merci / Thank you

David Bissonnette | RM Logistic<http://www.rmlogistic.com/> | david@rmlogistic.ca<mailto:david@rmlogistic.ca>
T. 514-484-7766 x310  F. 514-484-3118 C. 438-325-6491
60 St Jacques - Suite 600, Montreal, PQ, H2Y 1L5
[cid:image001.png@01CDBB47.F819E090]

**Comment by Quicksaver** [comment]
Please give [beta version 2b2.1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2.1) a try and let me know if that still happens with it.

**Comment by daverm** [comment]
Hey Luis,

I don’t know if anyone else got this issue ? Keeps on happening, it is a tad annoying. Another suggestion I could have would be to offer and AUTO-SAVE of the tabs group data. I already started saving a back up from time to time, but if I save it at 11 AM, chances are a lot of tabs changed by 1 PM.

An auto-save of the current session every 1 or 2 minute would allow to bring it back after a crash



Merci / Thank you

David Bissonnette | RM Logistic<http://www.rmlogistic.com/> | david@rmlogistic.ca<mailto:david@rmlogistic.ca>
T. 514-484-7766 x310  F. 514-484-3118 C. 438-325-6491
60 St Jacques - Suite 600, Montreal, PQ, H2Y 1L5
[cid:image001.png@01CDBB47.F819E090]

**Comment by Quicksaver** [comment]
Did you try the beta I linked you to?

**Comment by daverm** [comment]
Hey man,

Thanks for the quick reply. Actually I think this one got lost, never received an email with a link.

Can you send it again ? Would love to try, it’s a wonderful feature in my lane of work !



Merci / Thank you

David Bissonnette | RM Logistic<http://www.rmlogistic.com/> | david@rmlogistic.ca<mailto:david@rmlogistic.ca>
T. 514-484-7766 x310  F. 514-484-3118 C. 438-325-6491
60 St Jacques - Suite 600, Montreal, PQ, H2Y 1L5
[cid:image001.png@01CDBB47.F819E090]

**Comment by Quicksaver** [comment]
Click the "view it on Github" link at the bottom to view the whole conversation. ;)

**Comment by daverm** [comment]
Oh, got it now.

Do I have to Override add-on signing (advanced users) ?? Basic install seems to be blocked

**Comment by Quicksaver** [comment]
I originally linked you to 2b2.1 which isn't signed, sorry about that (I just corrected my comment but I guess I was too late). Please try [beta version 2.2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2) which is signed and shouldn't give you any trouble about that.

**Comment by daverm** [comment]
Oh wow, that's a beautiful update!

Will use it for a while and keep you posted on the results. You guys rock at customer service, I have to say.

**Comment by Quicksaver** [comment]
It's still a work-in-progress. ;) But I'm glad you like it, let me know if you still get stuck in groups mode with that.

**Comment by daverm** [comment]
Good morning

So far the glitch hasn't come back, pretty much been a full day.

Nice work team!

**Comment by Quicksaver** [comment]
I'm glad to hear that. Let me know if it happens again. :)
