### ISSUE TITLE
Can't load the Tab-Groups-backup-file

### ISSUE THREAD

**Issue by chris1507** [Quicksaver/Tab-Groups#177]
I'm working with OSX10.10 and Firefox 45.0.1. The backup-file can be found in the Finder-window, but its not possible to load it, seems to have the wrong format.

**Comment by Quicksaver** [comment]
Please see #110.

**Comment by chris1507** [comment]
Thank you!

**Comment by Quicksaver** [comment]
You're very welcome. I'm sorry it's taking so long to release an update with this fixed.
