### ISSUE TITLE
(minor) ESC not working after calling group preferences.

### ISSUE THREAD

**Issue by mausalimi** [Quicksaver/Tab-Groups#180]
Hello Mr. Luís Miguel

I noticed a really minor thing.
- open group view
- click group prefs
- press esc to leave prefs
- press esc to leave group view ---> it doesn't work, we have to use the top right button.

tested with b4, but was also like this in b3.
...If this is the only bug... :)

have a nice day.

**Comment by Quicksaver** [comment]
Ah indeed, I noticed this before but I forgot to note it down. Thanks for reminding me.

**Comment by Quicksaver** [comment]
Fixed in [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5). Please give it a try and let me know if you find any problems.

**Comment by mausalimi** [comment]
sorry, forgot to report, it works just fine now.
