### ISSUE TITLE
Allow pinned tabs to be per-group

### ISSUE THREAD

**Issue by tieguy** [Quicksaver/Tab-Groups#184]
I'd love to have the ability to keep pinned tabs per-group. My use case is that I keep one set of tab groups per client I'm working on, and I'd like to keep a Google Docs and billing software tab pinned - but different ones for each client (so that I can quickly hit the right keyboard shortcut and get to the right docs for that group).

I suppose sadly this has to be an option, which I'm generally against, but I don't see any way to figure this out in a "smart" way. :(

**Comment by Quicksaver** [comment]
Unfortunately this is just not possible. Pinned tabs just aren't built to allow this behavior in Firefox itself, and it's a little outside of the scope of this add-on to modify their behavior to such an extent.

Plus, I've made several changes already to how pinned tabs are handled in the add-on (#34), which is just completely opposite to how you suggest. So it's even harder to implement now.

There's an add-on called [FaviconizeTab](https://addons.mozilla.org/firefox/addon/faviconizetab/) which could achieve the same effect as what you want. Sadly it seems it's no longer being developed, and it apparently now has a few bugs. You could try it out and see if it works for you. If not you'll probably have better luck in getting someone to fork it and fix it somehow.

**Comment by tieguy** [comment]
Too bad. Thanks, though!
