### ISSUE TITLE
Shortcut key not working across sessions

### ISSUE THREAD

**Issue by kswartz26** [Quicksaver/Tab-Groups#186]
Hi there,

With the latest Tab Groups addon installed, and Firefox ESR 45.0.2, I have been overriding the open tab groups shortcut to the old default of Ctrl+Shift+G. This works fine, until I close Firefox and reopen it. When I return, the command is still assigned to Tab Groups, but it is not functional. I have to reopen the Tab Groups options, unset it and set it again, and then it works again.

This might be related to issue #171 but in my case, the key combination is not assigned to anything else in my browser (verified using keyconfig).

**Comment by Quicksaver** [comment]
```Ctrl+Shift+G``` is to [find the previous match (findbar)](https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_search). Did you disable that one in keyconfig first?

**Comment by kswartz26** [comment]
Yes. It appears as "key_findPrevious" in keyconfig, and it is disabled. But I had forgotten about that setting, so now I'm thinking this is the same as issue #171 , and it's just a race condition.

**Comment by Quicksaver** [comment]
Still, keyconfig should always win that race, since it's not a restartless add-on. I definitely have to check it out.

**Comment by Quicksaver** [comment]
Unfortunately it's not possible to fix this, for a whole lot of reasons. But in short, by the time keyconfig initializes its custom keys (and disabled keys), Tab Groups already would have needed to set up its own, or that key wouldn't work. So it can't wait for keyconfig to initialize.

My suggestion is to use [Keybinder](https://addons.mozilla.org/firefox/addon/keybinder/), disable the find previous shortcut and set the Tab Groups shortcut **through Keybinder** to Ctrl+Shift+G and it should work and persist across restarts. Please let me know if that doesn't work for you for some reason.

**Comment by kswartz26** [comment]
Hi Luis,

Keybinder doesn't work at all. Ctrl+Shift+G is bound to key_findPrevious.
But if I reassign it to another shortcut, keybinder doesn't release the old
binding, so TabGroups doesn't see it. So this is actually a step backward,
because I can't even assign it manually. At least keyconfig would release
bindings after you reassigned them.

I remember looking at Keybinder once, but stayed with keyconfig, because it
allows shortcuts to javascript expressions. For example, in Thunderbird, I
assigned a shortcut key to toggle the header view by mapping a key to
org_mozdev_compactHeader.pane.coheToggleHeaderView();

That may be the solution here, since all the addons run in the same
namespace. What JavaScript call would I make to open up tab groups?

-Keith

On Fri, May 13, 2016 at 6:08 AM, Luís Miguel <notifications@github.com>
wrote:

> Closed #186 <https://github.com/Quicksaver/Tab-Groups/issues/186>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Quicksaver/Tab-Groups/issues/186#event-659887322>
>



-- 

Keith M Swartz
oneroadkms@gmail.com

**Comment by kswartz26** [comment]
Luis,

Turns out it was an even easier fix than that. It already does record the
JavaScript call for opening tab groups; I just had to define the shortcut
in keyconfig to be Global. Now it is working across sessions.

Thanks!
Keith

On Fri, May 13, 2016 at 11:38 AM, Keith M Swartz <oneroadkms@gmail.com>
wrote:

> Hi Luis,
>
> Keybinder doesn't work at all. Ctrl+Shift+G is bound to key_findPrevious.
> But if I reassign it to another shortcut, keybinder doesn't release the old
> binding, so TabGroups doesn't see it. So this is actually a step backward,
> because I can't even assign it manually. At least keyconfig would release
> bindings after you reassigned them.
>
> I remember looking at Keybinder once, but stayed with keyconfig, because
> it allows shortcuts to javascript expressions. For example, in Thunderbird,
> I assigned a shortcut key to toggle the header view by mapping a key to
> org_mozdev_compactHeader.pane.coheToggleHeaderView();
>
> That may be the solution here, since all the addons run in the same
> namespace. What JavaScript call would I make to open up tab groups?
>
> -Keith
>
> On Fri, May 13, 2016 at 6:08 AM, Luís Miguel <notifications@github.com>
> wrote:
>
>> Closed #186 <https://github.com/Quicksaver/Tab-Groups/issues/186>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Quicksaver/Tab-Groups/issues/186#event-659887322>
>>
>
>
>
> --
>
> Keith M Swartz
> oneroadkms@gmail.com
>
>


-- 

Keith M Swartz
oneroadkms@gmail.com
