### ISSUE TITLE
Respect new tab settings when creating a new group - SpeedDial

### ISSUE THREAD

**Issue by Eccenux** [Quicksaver/Tab-Groups#187]
I have a SpeedDial extension installed which has a `extensions.speeddial.loadInNewTab` setting (I have this set to true. Not sure if it does some magic to overwrite Firefox behavior or is this more standrad, but when I open a new tab the SpeedDial page is shown.

The problem is when I do:

1. Open tab groups.
2. Click in empty space

Then standard Firefox new-tab page is shown. I would expect the SpeedDial to be shown. Again not sure if this is doable on Tab-Groups side or on SpeedDial side. Maybe some different tab-opening function should be called when creating new group?

**Comment by Quicksaver** [comment]
Does it work correctly with [beta version 2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/2b4)?

**Comment by Eccenux** [comment]
> Does it work correctly with beta version 2b4?

Nope. Just tried it with FFdev and standard new tab is opened.

This is both when opening creating a new group and adding a new tab inside Tab Groups. I tried all 3 group arrange modes and the effect is the same - standard new tab is opened instead of new .

BTW. I like the RegExp tab catcher :-)

**Comment by Quicksaver** [comment]
This should be fixed in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6). Please give it a try and let me know if you have any problems with it.

**Comment by Eccenux** [comment]
That works great. Thanks!
