### ISSUE TITLE
[Feature] Select Tabs in Panorama/Panel

### ISSUE THREAD

**Issue by iShyboy** [Quicksaver/Tab-Groups#190]
With tab groups helper we can do this in the panel, but for visual sake, I would like to see it on panorama, we already have the context menu in panorama, and tabs go in the right order there, so would be cool if you could select several tabs, with behavior like file explorers. 
As in:
 ctrl + click on each tab > highlight them> right click > move/close/etc

**Comment by Quicksaver** [comment]
#55.
