### ISSUE TITLE
Make better use of groups available space for tabs

### ISSUE THREAD

**Issue by DuckOfDuckness** [Quicksaver/Tab-Groups#192]
(v2b5)

The 'Open new tab' button is the same size as a regular tab, which takes up a lot of space, especially for tab groups with few tabs in them. For example, using 'Grid display' if I only have 1 tab open in a group placed in the top row, 3/4 of the tab group is just empty space, and the button for opening a new tab takes up its own quarter:
![2016-04-28_14-10-45](https://cloud.githubusercontent.com/assets/1951003/14885380/50cf839e-0d4b-11e6-8ac5-479d460df31d.png)
Maybe the 'Open new tab' button could be made smaller and get placed in the bottom-right corner of the tab group instead.

**Comment by Quicksaver** [comment]
In that particular case that wouldn't work actually. If you were to stretch the tab thumb to fit into either edge of the group, that would leave absolutely no space for the new tab button. And making the new tab button appear inline but with different dimensions makes it look too out of place (not to mention the calculations would be hectic to get to those different sizes).

**Comment by Quicksaver** [comment]
I just did some quick tests locally, where I've already adapted the thumbnails sizes. The cases where showing the new tab button with different dimensions would help seem far too few (and wouldn't help a whole lot either) to be worth writing the code for it.

**Comment by DuckOfDuckness** [comment]
I can understand if it won't be worth the effort, I just find it a little bit annoying how much wasted space I have in my tab groups. My second row is arguably even worse than the above example :/
![firefox_2016-04-28_15-14-46](https://cloud.githubusercontent.com/assets/1951003/14887107/8b97738e-0d54-11e6-8144-71b9bffb942e.png)
Not really a big issue though, just an annoyance...

**Comment by Quicksaver** [comment]
I'll reopen this to remind me to link you to beta 6 when I upload it. I am positive most of that second row will benefit greatly from the redimensioned thumbs; perhaps even the first row might benefit a little as well. :)

**Comment by DuckOfDuckness** [comment]
Just throwing up another idea: What if the 'Open new tab' button was completely gone until you hovered over the tab group? Right now the button is just hidden when you're not hovering over the group, but it's still taking up space that it doesn't need.

**Comment by Quicksaver** [comment]
> Right now the button is just hidden when you're not hovering over the group, but it's still taking up space that it doesn't need.

Because that would require instant item resizing while simply moving the mouse. That's a large toll on processing just for the sake of hiding a new tab button, which is just not acceptable. ;)

**Comment by Quicksaver** [comment]
How does [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) look to you?

**Comment by DuckOfDuckness** [comment]
Not a whole lot better to be honest:
![firefox_2016-05-13_20-28-29](https://cloud.githubusercontent.com/assets/1951003/15257964/493a488a-1949-11e6-940a-b27462b623bc.png)
There is still an immense amount of empty space in tab groups that have 1 or 2 tabs, which seems to decrease as the number of tabs goes up. The second row looks especially bad; even with 3 and 4 tabs more than half of the group is empty space.

Ps. That Tab Mix Plus integration is interesting, will have to get used to that!

**Comment by Quicksaver** [comment]
Well I think it's a tad wee better. ;)

But I do agree that groups with a low number of tabs could probably make better use of that space. I've renamed the issue to better demonstrate that, and I'll see about trying to improve that. But it will probably go out as-is for the initial version 2 though, so I'll work on it later for a future update.

**Comment by DuckOfDuckness** [comment]
I agree that the individual tab thumbnails look better now, I was just commenting on the whole "wasted space" issue :P 

Good idea with the new title, was considering something like that too!

And yeah, this still isn't that much of a big issue, so get the important features ready first :)

**Comment by iShyboy** [comment]
The single view has the answer, just you didn't apply it on the group.
As in the single view, every group has a topbar (where the setting button and the name is), just put a new button there and that's it. As for grid/random view, just put the button for new group in the sidebar.
Ugly concept:
![Concept](http://i.imgur.com/4LqlPZA.png)
What's up to you is just how to make it obvious to new users, as I think it would be enough for the advanced ones.

**Comment by Quicksaver** [comment]
That's what I've considered before, but it's not the most obvious action there. What I mean is, that area should imply "actions about the group", and opening a tab is a bit outside that scope.

**Comment by iShyboy** [comment]
Shouldn't be,
Look, sidebar it's for general actions of tab groups, help, setting, exit and etc..
The menubar its for the action for the group, opening a tab **in the group** wouldn't be odd nor strange, and we have enough space in that minibar, no one would use that much for naming.

**Comment by iShyboy** [comment]
One more thing, as of now, the plus button **on the group** still taking his space, even when it's hidden because of it, the resizing of thumbs **on the group** still apply as if the button was a tab by itself quite dumb in my opinion, that's why it would be smart to put it where it shouldn't have anything to do with the thumbs.

**Comment by Quicksaver** [comment]
> Look, sidebar it's for general actions of tab groups, help, setting, exit and etc..

There are different areas in there to separate the different kind of actions.

> A newgroup button there isn't strange and would get us much more space.

I absolutely agree that it would. But I also believe you don't find it strange because you "already" know what that would do. It's just much more usual for any kind of tabbed application to have a "new [whatever]" next to that actual [whatever], and not "buried" somewhere next to other options.

Note that smartphone apps are an exception to this, and I'm also considering alternatives based on that.

> we have enough space in that minibar, no one would use that much for naming.

Not entirely true either. Groups can be made very small in free arrange, plus "x tabs" can take up quite a lot of space in other locales as well.

> the resizing of thumbs on the group still apply as if the button was a tab by itself quite dumb

It's necessary, otherwise tabs would have to be resized as that button was shown or hidden; that's just a big responsiveness and performance no-no as long as the new tab button is there.

**Comment by iShyboy** [comment]
It's resizing:
https://waa.ai/kZ2J.mp4
This is what I think its annoying.

> There are different areas in there to separate the different kind of actions.

A New group I think it's a action good enough to be there how could it not be important? And in the free arrange mode would be good.

>Not entirely true either. Groups can be made very small in free arrange, plus "x tabs" can take up quite a lot of space in other locales as well.

Common sense, how many groups you would have to manage and what's your need in free arrange mode, you could make the button only show 'on hover' if the name of the group touch it.

>I absolutely agree that it would. But I also believe you don't find it strange because you "already" know what that would do. It's just much more usual for any kind of tabbed application to have a "new [whatever]" next to that actual [whatever], and not "buried" somewhere next to other options.

Not exactly, how could? ppl sure like when its obvious, but it will **not** be buried, in the free arrange it would be too obvious as the sidebar don't go all the way down, and in the grid mode it **still** will be obvious as in: the button still just **on the side** is like the single view, not the top but the side.

**Comment by Quicksaver** [comment]
> It's resizing:
https://waa.ai/kZ2J.mp4
This is what I think its annoying.

That will happen with or without the new tab button. Immediate resizing was one of the things that severely slowed down the interface before.

> A New group I think it's a action good enough to be there how could it not be important? And in the free arrange mode would be good.

I was speaking about new tabs button. And I still wouldn't add a new group button there but for other reasons.

> you could make the button only show 'on hover' if the name of the group touch it.

Would make it inaccessible on touchscreens.

> Not exactly, how could? ppl sure like when its obvious, but it will not be buried, in the free arrange it would be too obvious as the sidebar don't go all the way down, and in the grid mode it still will be obvious as in: the button still just on the side is like the single view, not the top but the side.

Again, I was speaking about (not) moving the new tab button to the top of the group, not to the sidebar.

> Something like a "G" with a plus in the 'tail'.

Not bad.

**Comment by Quicksaver** [comment]
BTW don't misunderstand my negativity towards your suggestions. I do agree that this aspect needs some work, I just don't particularly agree any of those is the way to go.

On the plus side, a few minutes ago I thought of a new concept that might definitely be worth considering. I'll have to test things out a bit, but if it works out I'm absolutely sure it will help with everyone's case here. :)

**Comment by iShyboy** [comment]
>That will happen with or without the new tab button. Immediate resizing was one of the things that severely slowed down the interface before.

Not what I meant, is just it does use the place as if it is an tab, and this is unfair to the tab thumbs, when you resize the group it should make the tab thumbs smaller to have a place of itself.

>Would make it inaccessible on touchscreens.

It isn't already? 
![?](http://i.imgur.com/OD5ZpvU.png)
If the button was as I said it wouldn't made that much difference on the "X tabs" nor the Name of the group.

About the negativity its not wrong, is a discussion after all, your negativity make both of us think more deeply about the issue :)

The thing that's bothering me more is the language barrier that I can't always make up by myself :(

**Comment by Quicksaver** [comment]
> It isn't already? 

The new tab button is always visible on the active group. In that case, because the active is stacked, you'll have to expand it first, and then you'll see the new tab button there. If you click on the active group, you'll see that it will keep the new tab button then.

> The thing that's bothering me more is the language barrier that I can't always make up by myself :(

As a last resort, if you're having trouble, eu sou português ;), but I still would prefer to keep it in english so that everyone else reading can also understand and get involved in it.

**Comment by iShyboy** [comment]
Bom saber, qualquer coisa vou por email mesmo :D

![yes](http://i.imgur.com/qnhFiCo.png)
I saw it before, the tab numbering on the group should be better if you take a tan icon:
![badge](http://i.imgur.com/bwMJdAZ.png)
make a badge and put the number as an overlay. That is a cheap deal with the space.
And about the new tab button, just take it from where you put the tabs.

The new icon for the new group alone, solve the issue of confusion between new tab and new group.
I believe that you can make it good, if there's a beta, i'm in.

**Comment by Quicksaver** [comment]
Oooh! That's a very nice suggestion. Creative juices are flowing! :)

BTW this probably won't happen in the next couple of weeks, because I'm so swamped it's not even funny, but I'm definitely liking where this is going, even more than what I was thinking earlier.

**Comment by iShyboy** [comment]
No problem, my default browser still v42.0, I still use the updated one for most things, though I spend my time more in the v42 because I keep my novels stuffs there. :smiley:

**Comment by FatOrangutan** [comment]
Could it be a good idea to have the whole blank space in a tab group (after the tab thumbnails) work as a button to make a new tab?
I was going to make a new issue regarding how, in the latest release, if I create a new tab group in the tab view itself, I have to click the new tab button to go into that group and create a new tab; while the previous behaviour was that clicking anywhere in a newly created group would make a new tab and take you there. This isn't a problem really, but since usually I drag-click from top left to bottom right to create a group, it requires some additional mouse travel to get to the new tab button.

**Comment by Quicksaver** [comment]
> I have to click the new tab button to go into that group and create a new tab; while the previous behaviour was that clicking anywhere in a newly created group would make a new tab and take you there. 

Yes, that's a subtle behavior change that was made for other reasons (mostly integration across all different modes). I do understand that it will take some getting used to, but you can also double-click anywhere in the group to go directly into it (also opens a new tab if it doesn't have any).

**Comment by B00ze64** [comment]
Just adding my vote; taking-up a whole "tab thumbnail space" for a + button is really bad design. Space is at a premium with many groups, this is a complete waste, a waste which is multiplied by the number of groups one has - what's wrong with "entering" the group and _then_ pressing + next to the tabs if you need to open a new tab?

**Comment by bakkerthehacker** [comment]
This is still blocking me from upgrading past Tabgroups 1.x

I'm fine without having the ability to add a tab from the tab groups screen.  Adding it once inside the group is fine.  However wasting space for this button just seems wrong.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) only shows the new tab button on completely empty groups; you should still be able to open a new tab through each group's context menu though, by right-clicking anywhere in its empty area or at the top title area.

It also replaced the big tab counter label with just a small number. I haven't included any sort of image like suggested to stylize it further, because I couldn't figure out how to "blend" it in correctly with the rest of the interface, but I admit I didn't really want to lose much time on that right now. ;)

Please give it a try and let me know what you think.

**Comment by Quicksaver** [comment]
And please re-open if you have any suggestions to further improve the available space for tabs of course.

**Comment by Quicksaver** [comment]
BTW lots more improvements that allow for a larger number of tabs over even smaller groups.
