### ISSUE TITLE
los my pinned tabs and groups

### ISSUE THREAD

**Issue by Confetolog** [Quicksaver/Tab-Groups#193]
How can I restore groups?

**Comment by Quicksaver** [comment]
It depends on what happened. Have you tried opening the History menu and clicking on "Restore previous session"? Very often that is enough to get back to a previous session.

**Comment by Confetolog** [comment]
This menu is not active.

**Comment by Quicksaver** [comment]
Have you checked your Firefox's preferences to make sure that "When Firefox starts" is still set to "Show my tabs and windows from last time"?

If you made any backups using the add-on's own Backup & Restore page, you can simply restore them in the same place.

If you use any add-on like Tab Mix Plus or Session Manager, they should let you restore previous sessions with ease.

If neither of those applies to you, have you tried this: https://support.mozilla.org/questions/1053113 ? Exit Firefox, find one of the files referenced there, copy it to the root of your profile folder and rename it to ```sessionstore.js``` to replace the current file there. Then start Firefox again.

**Comment by dehoffmann** [comment]
I had the same problem today.
I do habe a back-up file and one backuppreference file .json
When I tried loading the pref.json nothing happend.
I had to change the name from my tabGroups-2016-3-27-0-6-13 to tabGroups-2016-3-27-0-6-13.json then I could use the load backup feature.

**Comment by Quicksaver** [comment]
@dehoffmann that's a separate issue: #110

**Comment by Confetolog** [comment]
Thank you, Quicksaver!
It was possible to restore the sessionstore.js of upgrade.js
