### ISSUE TITLE
New Group Button in the Quick Access Panel

### ISSUE THREAD

**Issue by maverick74** [Quicksaver/Tab-Groups#197]
Another idea:

Adding a New Group Button in the Quick Access Panel ;)

**Comment by Quicksaver** [comment]
Planned, but I'm leaving all group management related additions to the panel for a later time.

**Comment by maverick74** [comment]
if you prefer, i can submit this kind of ideas latter to avoid too many bug reports... :)

**Comment by Quicksaver** [comment]
Submit all the ideas you have, at least this way you'll definitely know when I work on it. :)

**Comment by Quicksaver** [comment]
And of course you may have some I haven't thought of either.

**Comment by Quicksaver** [comment]
I'm duping this one instead of #455 because I like the idea in the screenshot you posted there. ;)
