### ISSUE TITLE
CTRL + [keys] edit ability

### ISSUE THREAD

**Issue by rgavs** [Quicksaver/Tab-Groups#20]
Minor bug: When editing tab labels, the editor does not accept CTRL+DEL; CTRL+BACKSPACE; CTRL+RIGHT; CTRL+LEFT shortkeys

**Comment by Quicksaver** [comment]
I assume you mean group titles. I'll see if this is possible to add.

**Comment by rgavs** [comment]
Yes that's right, it's of little importance but if possible.
