### ISSUE TITLE
2.0 beta version disabled on FF beta because of signature checks.

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#200]
Hi!

I recently got screwed by this. Maybe you could prevent this by uploading the beta versions to addons.mozilla.org too. That way people on the Firefox beta channel could also test beta versions of this addon.

**Comment by Quicksaver** [comment]
All the betas here are signed, with the exception of a debug build that was meant only for a specific case. Which version do you have installed?

**Comment by mzso** [comment]
I think I had b5 which was linked in #56 
It's a bit uncertain, because I had to re-install the addons that got disabled to get them to work again.

**Comment by Quicksaver** [comment]
I believe there was an issue a while ago with certain add-on versions signed within a specific timeframe where their signatures wouldn't be valid for some reason, so they had to be signed again. I didn't think these betas would be affected (I'm using the latest myself in my main profile with signing enforcement enabled). Perhaps I could have been wrong...

Please let me know if it happens again.
