### ISSUE TITLE
More detail in tooltip for grous in Single View

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/Tab-Groups#203]
It currently only displays the group name with a single line, it should show more obvious information like the tabs title:
Groups 1:
Title 1
Title 2
Title 3
...  or +2...

It can be an option or pref for the number of lines.

**Comment by Quicksaver** [comment]
If anything, I would make it show the number of tabs, but that I will do as part of #175, so will do both at the same time probably.

**Comment by yfdyh000** [comment]
A note, I wish to identify the contents of the group without having to click the group, as this would result in a significant changes at screen and distinguish the thumbnails.

**Comment by Quicksaver** [comment]
Why not name the groups? :)

Personally, I don't believe tooltips will ever be a good method to do that. Not only do they require a "stop-action" for them to appear, slowing down your workflow, you also can't fit a whole lot of info in them. For instance, you wouldn't be able to fit all the tabs in them if you had a lot, so there's no guarantee you'd recognize the group only by the apparent random choice of tabs that appear there (of course it wouldn't be random, but more often than not it would seem that way).

Showing only "the most recent tab +##" was one of the things that was bad with the previous groups in Firefox (and still is in some other parts of the browser). That's just barely useful in most cases.

BTW I'm also planning on adding another way to visually distinguish the groups (color-based) but unfortunately that won't make it in the next update. But hopefully that will also help with distinguishing them without having to switch to each one.

**Comment by yfdyh000** [comment]
I don't use the "Show my windows and tabs from last time" and groups name, tab groups for me is a temporary drawer for organization so far. So, I hope can more quickly identify it.

Yes, tooltips need a little wait, but it reduces my eyes moving and deep distinguish the thumbnails, and a few groups title is usually sufficient for a recent group.

The reason for the demand is smaller size for thumbnail on the top. Display the larger thumbnails area when hover a group? It saves a click. Not a necessity, just an idea.

**Comment by yfdyh000** [comment]
I noticed the Grid view seems more suited to my needs, the Single view may be more suitable storage inactive groups, instead of frequent switching.

**Comment by Quicksaver** [comment]
I was about to mention that, but of course that doesn't mean that the top group selectors in single view can't better represent their groups somehow. ;)

**Comment by Quicksaver** [comment]
Actually, on second thought I'm going to work on adding that color-based system first (eventually). I'll revisit this issue after that if you (or someone else) still thinks it's worth revisiting.
