### ISSUE TITLE
one of th last commits breaks firefox newtab

### ISSUE THREAD

**Issue by mausalimi** [Quicksaver/Tab-Groups#207]
i gave the newest code a try, and since then firefox comes up just with an empty page when i open a new tab, this was different for me before.

in other words, before i got about:newtab, now i get about:blank

/ah, found it, had to set browser.newtab.url to about:newtab

i only wonder why this now is in bold, when it was the default value before.

**Comment by Quicksaver** [comment]
That's because that preference has gone away in Firefox 47 (or 48) and I forgot to take into account it still exists in the current release. I'm so glad you caught this so soon! Please try that patch to confirm that things go back to normal (not bold in about:config anymore).

**Comment by mausalimi** [comment]
ah, i see. i'm on firefox 45.1.1 ESR right now.

the patch is working on an older profile, browser.newtab.url isn't bold with about:newtab

the bold remained however on the profile where i applied the older version of the code, but that doesn't
worry me.

thanks. :)
