### ISSUE TITLE
Tabs from 7 Tab-Groups out of 18 appear in starting Tab-Group. 

### ISSUE THREAD

**Issue by NeoSeeU** [Quicksaver/Tab-Groups#208]
Hi

Another glitch in Firefox with Tab-Groups and Session-Mgr installed:
Tabs from 7 Tab-Groups out of 18 appear in starting Tab-Group. 
It happend after restart when my PC got stacked/freeze because of an audio driver fault, my guessing.
The said 7 Tab-Groups have been emty afterward.
Any idea avoiding this?

**Comment by Quicksaver** [comment]
I don't understand what you mean. Did those tabs disappear, did it create one group for each tab?

**Comment by Quicksaver** [comment]
Or do you mean those tabs were removed from their groups and put into the active group?

**Comment by NeoSeeU** [comment]
Yes the latter. Before this happened I had 18 Tab-Groups with tabs included saved. When this happened I still had 18 Tab-Groups, but 7 had been empty and the tabs out of this groups where added in serial to my aktive starting group.

Today I used the Session-Mgr to restore a complete session, thereafter the empty Tab-Groups where finally gone. But this doesnt matter to me since the tabs where alredy no more inside.

**Comment by Quicksaver** [comment]
That's strange. I think it's obvious that this happened when your PC froze, causing a corruption in your session. But usually when this happens it's not selectively like that, it's usually all groups that are gone and not just a few.

Either way, there's now real method to "avoid" this. Crashes happen from time to time. In almost all cases, the session can be restored, but if it's corrupted there's not a whole lot that can be done. I've already finished working on several extra restore options (to import back tabs and groups from automatically generated backups) for the next version, which could help in situations like these. But if you use Session Manager it will definitely be better to just restore any backups you have from it instead, like you did.

**Comment by NeoSeeU** [comment]
Did I get you right, its better using the Tab-Groups backup instead of the Session-Mgr restore?

**Comment by Quicksaver** [comment]
No, it's the other way around. The Tab Groups backup and restore features work just fine on their own, but if you have Session Manager you should definitely use that. ;)

**Comment by NeoSeeU** [comment]
But I noticed that day, the session popup when starting firefox didnt function, it didnt restore any tab. I had to go to the Session-Mgr management and then it restored what I said above.

**Comment by Quicksaver** [comment]
Yeah that's what you should do. That means the current session was corrupted when the freeze occurred. The only thing to do there is to restore a backup like you did.

**Comment by NeoSeeU** [comment]
Yes thanks for the outview on more import functions, very good loading the invironment I need depending on the browsing purpose. And yes freezeing happens with 4GB RAM and Firefox pagefile outsourcing. Its crazy how loading of tabs sometimes slow down. I know I need a new motherboard with more RAM for my browsing habbits. 

Have you experienced limits to how many groups or tabs Firefox can handle almost quick?

**Comment by Quicksaver** [comment]
It really depends on the system. The next version of the add-on will have huge optimizations in that aspect, so it should help at least a little. But the tabs themselves still require their own resources of course, and you may be nearing your limit. Myself, in my (very old) computer I can't even get to 100 tabs, my Firefox just can't handle that many. On the other hand I know of a few cases where it can run over 1000 tabs well enough. It just depends too much. ;)

**Comment by NeoSeeU** [comment]
Thx for caring, Hope it doesnt happen often. Have a nice day.
