### ISSUE TITLE
High CPU usage on normal use

### ISSUE THREAD

**Issue by GJRobert** [Quicksaver/Tab-Groups#209]
Causing 100% CPU usage of Firefox after installing this great addon (pity)
After disabling it, Firefox CPU drops to normal status.
I'm on Firefox 46.0.1, Mac OS X 10.9.
What kind of information should I provide further? Thanks a lot!

**Comment by Quicksaver** [comment]
Please try [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) and see if it still has that issue. If it does, also try disabling all your other add-ons except for Tab Groups and see if that helps.

**Comment by GJRobert** [comment]
Hi,
Having tried 2b6. Huge difference. No more 100% CPU usage.
I like the new features you are working on.
Thanks a million!

**Comment by Quicksaver** [comment]
That's great! Let me know if you run into any problems again.
