### ISSUE TITLE
Option to set a default group for opening external links

### ISSUE THREAD

**Issue by CIAvash** [Quicksaver/Tab-Groups#21]
Currently when you open a link outside Firefox it gets opened in the current tab group. It would be nice if I could set a group for opening these external links.

Example: I have a group named 'main', when I open a link outside Firefox, it switches to 'main' group and opens the link.

**Comment by Quicksaver** [comment]
When you say external links, do you mean for instance from e-mails or links in the desktop and such? I'm not actually sure if that's possible, I don't think it can distinguish "where links come from".

**Comment by CIAvash** [comment]
Yes. Links from other applications.

I thought it was possible because Tab Mix Plus add-on has an option for giving or not giving focus to tabs opened from "Other applications"(in Events>Tab Opening>Focus/Select tabs that open from).

**Comment by Quicksaver** [comment]
That's what I was thinking, "see what Tab Mix Plus" does. :) Yeah if it does that, it can be possible. I'll check it out.

**Comment by Quicksaver** [comment]
When I do work on this, I will set it up more as suggested in #130, so I'm duplicating this issue there.
