### ISSUE TITLE
Enters into Tab Groups View when new window opened. Any clues?

### ISSUE THREAD

**Issue by GJRobert** [Quicksaver/Tab-Groups#211]
Tried 2b6 and really like the new features and styles a lot!

One issue found:
Now when I open a new window of Firefox, the Tab Groups view is always shown first, and I have to leave the view.

Yeah I admit that **with new and clean profiles this is not happening**. So this should not be an issue with Tab Groups itself. But I have disabled all my other addons too and the problem still persists in my profile. I'm suspecting that some little difference in my pref.js is causing this, but this is really hard to track down.

Sorry to bother: would you have any ideas or insight about the probable reason causing my problem, so that I could eliminate it?

**Comment by Quicksaver** [comment]
Yeah, I saw that and forgot to fix it. Thank you for reminding me.

**Comment by Quicksaver** [comment]
This should be fixed in [beta version 2b8](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b8). Please give it a try and let me know if you still have any issues.

**Comment by GJRobert** [comment]
You rock!
Fixed as told.
Saw the new (dark?) style too.
