### ISSUE TITLE
Beta Version Auto-Update

### ISSUE THREAD

**Issue by klonamy** [Quicksaver/Tab-Groups#213]
I noticed that the Beta addon of this version has no "Auto-Update".
As i often install Beta-Addons on my Firefox, i would like to have that.

Maybe there it is a way to add that to the Addon page on https://addons.mozilla.org/de/firefox/addon/tab-groups-panorama/

Thanks for reading and keep up the great work!

**Comment by Quicksaver** [comment]
It will (or should) update to the final version once I upload it to AMO. I don't plan on keeping a separate beta channel, and if I wanted I could use AMO directly for that.

**Comment by klonamy** [comment]
ok
