### ISSUE TITLE
Extremely slow start with lots of tabs

### ISSUE THREAD

**Issue by sheepdestroyer** [Quicksaver/Tab-Groups#215]
Firefox starts extremely slowly on my system. It used to be blazing fast on original Mozilla's implementation of tab-groups (I have a fast system, core i7, lots of Ram and SSD), even with hundreds of tabs.

I currently have 586 tabs, in 19 groups. Tabs are set to load only when clicked on, so only one has to be loaded right when starting Firefox. 

Currently, UI is frozen for a very long while, waiting for tab-groups extension to load, each time I start FF.
I tried with all other add on deactivated to make sure.

I am on Version 2b6, Firefox Nightly 49, Fedora 23

**Comment by Quicksaver** [comment]
What about with [beta version 2b8](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b8)?

**Comment by iShyboy** [comment]
Just to say, safe mode ≠ disable all.

If i **disable** all my addons, I still have a slow start with many tabs, if I activate just TG my start is just a **bit** longer, not much.
But if I go in help and restart with safe mode my restart its a flash, and even the ram never go beyond 300mb.

**Comment by Quicksaver** [comment]
Exactly. That's because the add-on's startup shouldn't depend on the number of tabs you have (or anything else in your profile even). The only thing the number of tabs should affect, at least noticeably, is the first time you open groups view or the quick access panel, since it has to build everything at once then. But only that first time really, and there have been several improvements to even that first initialization as well.

**Comment by sheepdestroyer** [comment]
Same pb on 2.8
However, put that issue on hold. Will have to sleep on that and do more benchmarks between ff/nightly/safemode. I'll come back to you

**Comment by iShyboy** [comment]
Not much change, FF last beta tg 2b8, 244tabs 6 groups.
0 addons normal start: 15.73s
TG normal start: 16.52s
Safe mode: 07.32s

**Comment by GrayFace** [comment]
I've always experienced this. FF can't handle many tabs well despite the option not to load them. Didn't notice any change since Tab Groups became an extension and since I installed the beta.

**Comment by sheepdestroyer** [comment]
Sorry, can't reproduce for now. In fact I even tried with new profile but firefox seems crazy slow to start in all circumstances now when having a lot a tabs ; add-on or not... Did not have time for real measured benchmark. 

I do not remember it was always the case, especially when tab group was still natively supported ; but I may be wrong. Is there a way to load my current tabs and groups in an old firefox preremoval (FF44?) to test that?

**Comment by Quicksaver** [comment]
> Is there a way to load my current tabs and groups in an old firefox preremoval (FF44?) to test that?

Just download and reinstall Firefox 44 from somewhere.

> Sorry, can't reproduce for now. In fact I even tried with new profile but firefox seems crazy slow to start in all circumstances now when having a lot a tabs ; add-on or not...

I'm not sure what it is you're saying to be honest. I assume you confirmed that you have a slow startup regardless of if Tab Groups is enabled or not. If so, there are lot of factors that could be causing that, and of course the high number of tabs is one of them.

So, please reopen if on the other hand you can confirm that disabling the add-on (while still keeping your session - as in your tabs - across Firefox restarts) does give you a noticeable improvement in startup time.
