### ISSUE TITLE
Firefox crashes when recovering tab groups

### ISSUE THREAD

**Issue by forsate** [Quicksaver/Tab-Groups#216]
When I try to recover my tab groups after installing the new  tab groups extension to Firefox it crashes.  This happens when I click on the gear icon in tab groups mode.  All the tab groups are visible and Firefox shows them all under Bookmarked Tab Groups.  I have tried uninstalling and reinstalling Tab Groups, and uninstalling and reinstalling Firefox version 46.0.1.  What am I doing wrong?

Great pity, as I found this extension extremely useful before it was removed and would love to have its capaibilities restored.

**Comment by Quicksaver** [comment]
Can you try [beta version 2b8](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b8) and see if that works?

**Comment by forsate** [comment]
Hi Luis,

It still crashes.  After installing this version I ended up with several 
windows.  There were three with a new Tab Groups interface, all of which 
crashed when I tried to open them.  The fourth window was where I 
downloaded and installed beta 2v8.  Instead of the usual tab groups icon 
one of my original tab groups, seemingly plucked at random from the list 
of bookmarked tabs, appeared in the toolbar. That crashed as well when I 
tried to use it.

Jeremy Gale

**Comment by Quicksaver** [comment]
Have you tried disabling all your other add-ons except for Tab Groups? There could be a conflict somewhere.

**Comment by forsate** [comment]
Tried that.  No difference.  One thing I noticed before and I should have mentioned is that when I clicked on the Tab Groups icon and entered the screen for Backup/Restore there was no Load Migration Backup, only a facility for Loading from a previous session of file.  I didn't getting a chance to investigate this before Firefox crashed - again.

**Comment by Quicksaver** [comment]
It's possible your profile is corrupted somehow. Can you try in a [new profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles) and see if it crashes there too?

**Comment by LAOMUSIC** [comment]
I was having the same issue on Win & OSX until last Firefox update to 4601.
Now it seems to rum a bit moe stable.

**Comment by forsate** [comment]
I created a new profile and have spent some time exprimenting with it.  I can create and use tab groups created under the new profile but cannot recover the original tab groups,, which is what I want to do.  The Recovered Tab Groups folder is present under bookmarks in both the original and new profiles.  But under the original profile trying to recover them causes Firefox ro crash (this is the original issue), and I cannot see any way to recover them under the new profile.  Where am I going wrong?  What is interesting is that clicking on the Tab Groups icon and then the Options icon in the new profile leads to a different interface to the one I get when I repeat this procedure in the original profile.  The interface I see in the original profile is the one described in [https://support.mozilla.org/en-US/kb/tab-groups-removal](url).  Perhaps the interface I see in the new profile is the one generated by beta version 2b8?

**Comment by Quicksaver** [comment]
> but cannot recover the original tab groups,, which is what I want to do. The Recovered Tab Groups folder is present under bookmarks in both the original and new profiles. But under the original profile trying to recover them causes Firefox ro crash

This really doesn't make sense to me. In the new profile you shouldn't see the bookmarks from the old profile, unless you specifically migrated them when creating the new profile. Also, those are not used anywhere to restore or recover groups, they were created by Firefox itself when it upgraded to 45 as a way to keep all your tabs from other groups..

How exactly are you trying to recover your groups? I had thought you meant you were using the add-on's backup and restore feature in its options. Please give me a step by step as detailed as possible.

>  Perhaps the interface I see in the new profile is the one generated by beta version 2b8?

There are a lot of changes in the next version 2, yes. It's definitely worth it giving the "How to use" page in the add-on's options a read, to get acquainted with the new features.

**Comment by forsate** [comment]
The new profile did not include the Bookmarked Tab Groups, or indeed my other bookmarks and add-ons when I first set it up.  By synching the new profile with my original profile I was able to reproduce my original working environment in all its glory with the exception of the defunct Tab Groups add-on.  But although I could see the Bookmarked Tab Groups I could not find a way to import them into the add-on.

So to give you the step-by-step process that you asked for:

- Create the new profile. 
- Synch the new profile with the original profile.
- Add the Tab Groups add-on.
- Click on the Tab Groups icon.
- Open the interface.
And this is where I run into trouble.  What I see are two buttons.  One is to create the backup file; but how do I create the backup file when it does not exist in the new profile?  The other is to restore from a backup file, which I have not been able to create, as stated above.  As far as I recall, this backup file, if it exists, is a JSON file.  To try and get some idea of what I should be looking for I looked at the details of the two profiles but could not find anything that seemed appropriate or relevant to my problem.

Hope this clarifies things.

**Comment by forsate** [comment]
The new profile did not include the Bookmarked Tab Groups, or indeed my other bookmarks and add-ons when I first set it up.  By synching the new profile with my original profile I was able to reproduce my original working environment in all its glory with the exception of the defunct Tab Groups add-on.  But although I could see the Bookmarked Tab Groups I could not find a way to import them into the add-on.

So to give you the step-by-step process that you asked for:

- Create the new profile. 
- Synch the new profile with the original profile.
- Add the Tab Groups add-on.
- Click on the Tab Groups icon.
- Open the interface.
And this is where I run into trouble.  What I see are two buttons.  One is to create the backup file; but how do I create the backup file when it does not exist in the new profile?  The other is to restore from a backup file, which I have not been able to create, as stated above.  As far as I recall, this backup file, if it exists, is a JSON file.  To try and get some idea of what I should be looking for I looked at the details of the two profiles but could not find anything that seemed appropriate or relevant to my problem.

Hope this clarifies things.

**Comment by forsate** [comment]
The new profile did not include the Bookmarked Tab Groups, or indeed my other bookmarks and add-ons when I first set it up.  By synching the new profile with my original profile I was able to reproduce my original working environment in all its glory with the exception of the defunct Tab Groups add-on.  But although I could see the Bookmarked Tab Groups I could not find a way to import them into the add-on.

So to give you the step-by-step process that you asked for:

- Create the new profile. 
- Synch the new profile with the original profile.
- Add the Tab Groups add-on.
- Click on the Tab Groups icon.
- Open the interface.
And this is where I run into trouble.  What I see are two buttons.  One is to create the backup file; but how do I create the backup file when it does not exist in the new profile?  The other is to restore from a backup file, which I have not been able to create, as stated above.  As far as I recall, this backup file, if it exists, is a JSON file.  To try and get some idea of what I should be looking for I looked at the details of the two profiles but could not find anything that seemed appropriate or relevant to my problem.

Hope this clarifies things.

**Comment by Quicksaver** [comment]
>  By synching the new profile with my original profile I was able to reproduce my original working environment

The point is, by syncing profiles you're also syncing the session, add-ons, and any other factor that could possibly be causing the crashes. Basically, you could be syncing whatever is causing the crashes. ;)

When I asked you to try creating a new profile, it was to see if you could reproduce the crash without any of those other factors. Basically just create a fresh profile, install Tab Groups and create groups and open tabs in them for a minute or two to see if it crashes.
- If it does, we have a serious problem. ;)
- If it doesn't, then it's definitely either an incompatibility with another add-on, or a corruption in your profile, including possibly your session(s). In cases involving crashes like this, the solution often is to create new profiles and migrate your data, which is why I jumped ahead to try that from the beginning. But you'll have to start completely fresh (to make sure Tab Groups actually works by itself), and slowly migrate things to make sure you don't migrate whatever it is that is causing the crash.

By then, we'll have a better idea of what the reason is, and if it's something that can be addressed then I definitely will do my best. But session corruption is rarely recoverable, at least without some serious spelunking into the files themselves, and it's just better to start a new one and try to import the tabs and groups from a backup (see point below).

> But although I could see the Bookmarked Tab Groups I could not find a way to import them into the add-on.

As I mentioned, those are just bookmarks, they are not used by the add-on (or anything else) for restoring groups. The add-on restores from backup files of your session, including the tabgroups-session-backup.json file at the root of your profile folder (this is what it loads when you clicked the "Load from Migration Backup" before). I don't believe this file is synced automatically when you migrate data from other profiles, so you'll have to [manually open your profile folder(s)](http://kb.mozillazine.org/Profile_folder_-_Firefox) and copy it from the old profile to the new one, so the add-on finds it.

If you want to use the bookmarks though, there's really no way other than clicking them one at a time to open them as you create the groups.

> how do I create the backup file when it does not exist in the new profile?

I don't understand. What doesn't exist in the new profile?

Creating a backup is just that, it backs up your current tabs and groups into a JSON file. That backup will only exist after you create it... I really don't follow here.

**Comment by forsate** [comment]
OK; I have been missing the point here.  Creating the new profile, adding Tab Groups and then creating new tab groups works fine and there are no crashes.
What I am keen to do is to import my original tab groups (there are nearly 700 of them arranged into a tab goups tree) to avoid the chore of reconstructing them all and getting them back in the order I had them.  Also I did not appreciate that the old tree structure which I had found so useful does not exist in this new form.  Perhaps this might be available in a later version?  Anyway, thanks to your patience I have not so much solved the problem as developed a better understanding of how Tab Groups now works.  I suspect that at least part of the problem is caused by the fact that I am using a rather old computer with Vista SP 2 which is not good at handling the number of tabs and tab groups I am using.  In view of this limitation and what you have helped me to do I am happy to close this issue.  Many thanks.

**Comment by Quicksaver** [comment]
> arranged into a tab goups tree

There was never any "tree" design in any iteration of tab groups in Firefox. Could that have come from [TabGroups Menu](https://addons.mozilla.org/firefox/addon/tabgroups-menu/)?

> In view of this limitation and what you have helped me to do I am happy to close this issue.

Still, it should be perfectly possible to restore (most of) your groups from your original profile, in the way I described before. Have you tried or has that not worked?

**Comment by forsate** [comment]
You are right; I was thinking of TabGroups Menu.  Apologies.  I also transferred  tabgroups-session-backup.json as you suggested, and that did indeed work.  Many thanks.  Your suggestions gave me additional strings to my bow.  As I said in my last post, I am beginning to think that the scale of what I was trying to do occasionaly exceeded the limitations of my now ageing computer.  Time to upgrade, I think.

**Comment by Quicksaver** [comment]
I'm glad to hear things worked out in the end at least. Let me know if you run into any other problems. :)
