### ISSUE TITLE
Wording for "Enter and exit groups mode" hotkey

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/Tab-Groups#217]
It should be "Enter and exit groups view", this is more consistent, and "exit groups mode" like to switch a feature.

**Comment by Quicksaver** [comment]
True, changed it in Babelzilla already. Did you already translate correctly for your locale or do you need me to reset its string?

**Comment by yfdyh000** [comment]
Yes, it already translate correctly for zh-CN on Babelzilla.

**Comment by Quicksaver** [comment]
Great, thanks for the heads-up. :)
