### ISSUE TITLE
New private windows start in Tab Groups View

### ISSUE THREAD

**Issue by DuckOfDuckness** [Quicksaver/Tab-Groups#218]
When I open a new private window it goes into Tab Groups View right after the window has loaded. I'm assuming it shouldn't do that.

Tab Groups (2b6)
Firefox Beta (47.0b6)
Windows 10 (OS Build 10586.318)

**Comment by Quicksaver** [comment]
Should already be fixed, see #211.

**Comment by DuckOfDuckness** [comment]
Didn't realize it happened with all new windows. Explains why I couldn't find anything when I searched for it. My bad, sorry!

**Comment by Quicksaver** [comment]
No problem of course. ;)
