### ISSUE TITLE
On start Tab Groups view is loaded instead of last used tab.

### ISSUE THREAD

**Issue by GrayFace** [Quicksaver/Tab-Groups#220]
This bug only happens in v2 beta versions. One important note: FF always crashes when I close it, because I have many tabs.

**Comment by Quicksaver** [comment]
Does that happen with the latest [beta version 2b9](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b9)? Have you tried disabling all your other add-ons and see if it still happens?

Firefox crashing is not normal, you should try to find out what is causing those crashes. On the one hand, it could help explain why it takes you to groups view; and on another hand eventually a crash may cause your session to become corrupted and you will lose your tabs and groups, then you'll have to rely on backups to get them back.

**Comment by GrayFace** [comment]
Yes, it's 2b9. I don't know any convenient way to disable and then re-enable all other addons.

Session corruption isn't a problem, I use Session Manager. On a side note, the fact that FF doesn't lose session and options was the thing that got me to move from Opera (10 or 9 at the time) to FF in the first place.

**Comment by Quicksaver** [comment]
> Yes, it's 2b9. I don't know any convenient way to disable and then re-enable all other addons.

Add-ons manager (Ctrl+Shift+A). Disable all except for Tab Groups and see how it works.

**Comment by GrayFace** [comment]
Do you mean "make a screenshot of currently disabled extensions, click 60 Disable buttons, test, then do the reverse procedure"?
Does the bug reproduce when you kill FF with task manager?

**Comment by Quicksaver** [comment]
> Do you mean "make a screenshot of currently disabled extensions, click 60 Disable buttons, test, then do the reverse procedure"?

Unfortunately yeah. It's not convenient, but it is necessary, conflicts between add-ons are very often at the root of many problems, and unless you can rule that out or even figure out the specific add-on/options combination, there's very little to do. Because... (continued next).

> Does the bug reproduce when you kill FF with task manager?

No, and it's definitely not supposed to. (continued here) It shouldn't enter groups view unless you specifically tell it to. The very first step must be to figure out what's making it enter groups view, that may take some effort from both of us. :(

**Comment by Quicksaver** [comment]
> Session corruption isn't a problem, I use Session Manager.

BTW, what exactly did you mean by this? Does it automatically restore the session correctly on the next startup, or do you have to select a backup or something?

What exactly do you (and Firefox) do from the moment you shut down Firefox to the moment it enters groups view when it shouldn't? Can you walk me through every step? Any dialogs that appear, any actions you make...

**Comment by GrayFace** [comment]
I should have mentioned it from the get go. Yes, it shows its own dialog where you can select a different session to load. FF loads homepage at the same time. Then you click Restore button and the session is restored, but Tab Groups v2 enters groups view. I actually don't the moment at which it enters groups view, I'll do some experiments.

**Comment by Quicksaver** [comment]
Can you try [beta version 2b10](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b10) and see if it fixes the issue?

**Comment by GrayFace** [comment]
Thanks, it's fixed. I just understood by recognizing Tab Groups update screen that you're the author of some other cool addons I use (OmniSidebar and FindBar Tweak).

**Comment by Quicksaver** [comment]
Yes I am. :)
