### ISSUE TITLE
new tab "+" moves to the far right

### ISSUE THREAD

**Issue by dgodfather** [Quicksaver/Tab-Groups#221]
With this plugin active it pushes the "+" option to the far right of the window. I'm using Windows 10 and that puts it right beneath the minimize, maximize, and exit buttons in the program window.

**Comment by Quicksaver** [comment]
Can you attach a screenshot of this please?

**Comment by Quicksaver** [comment]
It's possible the browser just screwed up the button's placement somehow. The plus icon needs to be right next to the tabs. Please enter customize mode in Firefox and try moving it to be the first button in there (before Tab Groups or any other button in that area).

**Comment by Quicksaver** [comment]
Please reopen if that did not help.
