### ISSUE TITLE
importing tabs from multi-lines text of links

### ISSUE THREAD

**Issue by kidwm** [Quicksaver/Tab-Groups#222]
It is useful to support importing the exported links of OneTab or other multi-lines text of links.

https://www.one-tab.com/

That makes tabs migrating from Google Chrome more easier.

**Comment by Quicksaver** [comment]
It currently uses json data files (which are essentially text files) in a specific format to save and import groups. Importing from text files is just a matter of "open a new tab per line", so it's not really any different than #168.

**Comment by kidwm** [comment]
@Quicksaver But clicking each links manually is so cumbersome.

BTW, I just installed Firefox version of OneTab to do this job.

**Comment by Quicksaver** [comment]
I didn't mean you would have to click them, but of course that for now that's all you can do. What I meant was implementing #168 would also allow for a list of urls to be dragged, instead of a single one, so it would achieve the same goal.

**Comment by kidwm** [comment]
@Quicksaver Thanks for your explanation :+1:
