### ISSUE TITLE
auto-add .json extension to exports

### ISSUE THREAD

**Issue by Aaron432** [Quicksaver/Tab-Groups#224]
Could you make it append ".json" suffix to backups/exports on default ?
Example of outputs I'm getting: "tabGroups-2016-4-27-2-19-54", "tabgroups-prefs-2016-4-27-2-24-42" (perhaps a bug in my environment?)
Kinda troublesome that you have to append that extension manually every time you want to restore your stuff...

(Alternatively disable that "JSON" filter in "Load Backup" or set it to like "ALL")

**Comment by Quicksaver** [comment]
Already fixed, #110.
