### ISSUE TITLE
Ability to customize the look of the tab group "main" display page

### ISSUE THREAD

**Issue by LittleVulpix** [Quicksaver/Tab-Groups#226]
First of all, thanks for the plugin! Much appreciated :)

Old - actual - firefox tab groups
![Imgur](http://i.imgur.com/sbo1Zun.jpg)

New - plugin - tabgroups
![Imgur](http://i.imgur.com/vc7NFmR.png)

As you can see the new one is not transparent and the tab groups have this ugly colour :( It doesn't look good if you open such "bright" things late at night.

Would it be possible to bring back the dark+transparent "glass" display? Or at least let us select the background colour so that we can pick something less white?

Thanks!

**Comment by Quicksaver** [comment]
That transparent look is not one of the default styles that existed for tab groups. It must come from a theme or userstyle, so it's that theme or userstyle that should be applied to the new tab groups window (it's a different URI than the original).

**Comment by LittleVulpix** [comment]
@Quicksaver ah, well actually it looks like firefox no longer lets you use full themes so apparently the theme I was always using no longer applies to the tab groups, which is sad. Thanks for the reply!
