### ISSUE TITLE
Selecting "Menu, Add-ons" switches the current Group

### ISSUE THREAD

**Issue by Jaxx005** [Quicksaver/Tab-Groups#228]
Selected Menu (RHS) in FF, clicked "Add-ons".  The Add-ons screen appears, but all tabs changed.

It seems to switch to an existing "Add-ons" window, which if already open in another Group, seems to switch to that group also. 

If this is by design, then perhaps it needs to be 'selectable', or optional default.

It is quite useful in some ways, as it saves having duplicate Options tabs open across Groups.

Regards
L

**Comment by Quicksaver** [comment]
Re-using already opened tabs, even if they're in other groups, is indeed intentional. That's a Firefox feature, and it's not within the add-on's purpose to change that behavior.

I don't fully understand what it is you're asking though. You would rather this not happen? That's actually quite complex to do, and again it's not really within the add-on scope to change how these things work. If you absolutely must open a new tab even if you already have one open, you can always type "about:addons" in the location bar.

BTW, I don't know what "RHS" is.

**Comment by Jaxx005** [comment]
Hi Luis

 

Thanks for the reply. This is Lee here – we had a recent discussion about “Window Title” and my sons future computing career… etc!!  I’ve switched to my ‘techie’ email and created a GitHub account. 

 

I did suspect “re-opening” might be intentional, but I’ve never had it occur before. Hence it was somewhat confusing as I thought the other tabs had disappeared, until I noticed the Group button had changed name.

 

Once you know that FF works like that, then it does make sense, but it is confusing if you don’t.

 

I appreciate it’s a FF feature and not something the add-on controls.  So I am not sure how the user could be ‘notified’ of the change of group.    I might associate a sound with the change (if that’s possible?).

 

However… if it’s just the FF-focused pages that act like this (such as About:Addons, etc.) then it’s not such an issue. I suppose you can mark the thread as “closed” (or whatever the phrase is!?)   :)   Thanks.

 

(I don’t think other identical pages or URLs do this, which is good, as I think that would be more of a pain IMO.)

 

 

This has just reminded me of a thought I had some time ago, about organising tabs under higher-level tabs:  a top row of tabs for groups, each displaying the normal tabs for that group beneath (as now).    A bit like having a series of group-buttons.  

 

 

“RHS” – yes, sorry: “Right Hand Side”  (as opposed to LHS! :) )

 

 

Regards

Jaxx005 (aka Lee Russell)

**Comment by Quicksaver** [comment]
> I appreciate it’s a FF feature and not something the add-on controls. So I am not sure how the user could be ‘notified’ of the change of group.

That's one of the reasons for why the current group's name in the button is even more useful. :)

> I appreciate it’s a FF feature and not something the add-on controls. So I am not sure how the user could be ‘notified’ of the change of group.

It's not as simple as that. For instance, if you begin typing in the location bar an address of a tab that's already open, you'll have an option in the dropdown panel that appears to switch to that tab. That's basically what is happening with the Add-ons menu entry, except it does all that automatically.

That can happen for other special pages as well, like options for instance. Each one of them will have its own specific "check if already exists" controls. So to override that behavior for the add-ons menu entry, I'd have to do it specifically for that entry (which I already do in my OmniSidebar add-on, which would only complicate things even further if I wanted to control it here as well). And it would be inconsistent with other pages if I didn't do the same for everything else.

This to say, it's not really impossible. But I believe the very little gain you'd get from this isn't worth the effort.

> This has just reminded me of a thought I had some time ago, about organising tabs under higher-level tabs: a top row of tabs for groups, each displaying the normal tabs for that group beneath (as now). A bit like having a series of group-buttons.

This is already planned, see #1. Although it's very low in my priorities list, so I don't know when I'll get to it, if I'll do it at all to be honest.

**Comment by Jaxx005** [comment]
Thanks for the info. Once users are familiar with the ways things work, it’s fine. 

 

I’ve repositioned the TabGroup button to the right of the tabs row / + / v buttons – that way it’s more prominent.   

 

[I note that the button only appears ‘graphical’ (+ text) when it’s placed in the right-hand FF menu? Is there a way to make it graphical (icon) elsewhere, such as on the top menu bar, tabs row, etc.?]

 

I will try out the Tab Groups add-on some more: l like what I see so far, especially the layouts, scrolling vs stack, etc.   I like the menu of groups when Tag Group button is clicked. Do miss the Layouts view being shown immediately, but it is only another click on the menu.

 

You probably have a user request for coloured panels in Layout?  It’s a good visual aid (red for ‘work’, green for ‘fun’ stuff, etc.!?!?).

 

Just some feedback/thoughts - I won’t expect a reply :) 

Many thanks.

**Comment by Quicksaver** [comment]
>  [I note that the button only appears ‘graphical’ (+ text) when it’s placed in the right-hand FF menu? Is there a way to make it graphical (icon) elsewhere, such as on the top menu bar, tabs row, etc.?]

Just disable the option to show the current group's name in it in the add-on preferences.

> Do miss the Layouts view being shown immediately, but it is only another click on the menu.

You can change that behavior back in the add-on preferences as well.

> You probably have a user request for coloured panels in Layout? It’s a good visual aid (red for ‘work’, green for ‘fun’ stuff, etc.!?!?).

Already planned. :)
