### ISSUE TITLE
autogroup based on domain

### ISSUE THREAD

**Issue by Haikuch** [Quicksaver/Tab-Groups#231]
I would like to have my tabs/pages autogrouped based on special domains. For example a group for developing stuff (github.com, stackoverflow.com, symfony.com...) and one for newssites (newssite.com, anothernewsseite.net) etc.

When I open a domain like this, it should be grouped automatically in preconfigured groups

**Comment by Quicksaver** [comment]
Already implemented, see #130 and check out [beta version 2b10](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b10).

**Comment by Haikuch** [comment]
oh thx, didn't notice that. Maybe I can extend my issue to make this half-automatic by option. I feel, that the function is too much for normal surfing and doing stuff. I would like to have a general option/button/shortcut to switch on and off the whole grouping, when I feel that it becomes necessary (because to many tabs are open, or I want to focus on one category) this might be a new issue, but is also connected to the autogroup thing.

**Comment by Quicksaver** [comment]
I really don't understand what it is you want at all.

**Comment by Haikuch** [comment]
ok, I would like to have the following scenario: 

I open firefox and the grouped Tags are deactivated. Then I start surfing, to techsites, newssites and so on. Still everything in one Tab Panel (like normal, without the plugin). Then after some time I collected a lot of open tabs and Iam in a workflow, where I want to focus on my tech stuff. Then I can press a button/shortcut, switch on the grouping and my opened tabs are grouped in tech/newssites/other. I can use this for some time, but then my workflow changes again and I would like to switch off the grouping again so all tabs come back to one view (like it is in standard).

**Comment by Quicksaver** [comment]
That's incredibly difficult to implement actually. Right now, any changes you make (opening tabs, moving them, closing them, etc.) are handled immediately, so that the groups are always up to date. Ensuring all those actions are properly handled on a "queued up" system can become quite complex. Plus, there would be no maintaining of tab order as those tabs were shown/hidden. And all of this would only be useful in cases where you do use the catch rules (which already aren't that many to begin with); it would just adding a level of confusion for users who don't use those.

Honestly, I don't see enough gain here to justify the effort of implementing something like that, I hope you understand.

**Comment by Haikuch** [comment]
is it possible, to have copies of tabs in different groups? Then there could be one tabgroup, where all tabs are shown.

**Comment by Quicksaver** [comment]
The same tab can't appear in two different groups, unless you specifically open it in each one. It could be possible to implement some kind of "master group" that shows the tabs of all other groups, but I honestly don't see the gain of having it, much for the same reasons as I've explained before (in particular, it wouldn't keep a global tab order, only a per-group tab order), and the new quick access menu already lets you access tabs from all groups easily as well.

**Comment by Haikuch** [comment]
> It could be possible to implement some kind of "master group"

yes, thats what Iam thinking about. Ok, even if you dont see the gain, I do :) But of course its a thing of different workflows and user-behavior. Maybe I will find a solution by my own in the code.

**Comment by Quicksaver** [comment]
Please don't misunderstand me, I do see the advantage of having that behavior in some cases, as I'm sure you would benefit from it. What I meant was, none of it is so easily done. It would take more effort than it would be worth in the end. If I had unlimited availability to work on it, I wouldn't mind creating it at all, but I don't, so I have to prioritize and triage. :)

**Comment by Haikuch** [comment]
no problem, I fully understand this, I know this balancing-problem.. anyway, thx for the addon so long
