### ISSUE TITLE
Group Background color

### ISSUE THREAD

**Issue by maverick74** [Quicksaver/Tab-Groups#232]
When in Groups Manager, groups background color is black.

I can't seem to reset it!!!

![bug](https://cloud.githubusercontent.com/assets/14912461/15724739/624cc220-2840-11e6-890b-df97173f59fa.png)

**Comment by Quicksaver** [comment]
If you change the theme you're using, does it work?

**Comment by maverick74** [comment]
Hi.

Nop. Already tried that and resetting the addon settings. No luck. If i revert to 1.0.2 background is ok. 

This in Single View turns everything black, but i supposed this view would help you more to identify the problem

**Comment by Quicksaver** [comment]
Can you post a screenshot of how it looks with Firefox's default theme enabled, and with any stylish or custom styles or any other theme-related add-on disabled as well, please?

**Comment by Quicksaver** [comment]
(And restart Firefox after switching themes.)

**Comment by maverick74** [comment]
It's definitely theme related!!! If i set default theme and restart it returns to normal, any other theme - the ones i tried, at least - sets the background black - (img attached is a different theme from the first one)

![bug2](https://cloud.githubusercontent.com/assets/14912461/15729016/6471e4e6-2858-11e6-8238-d97dede8e397.png)

Also, in bug3.png, please note that the 3 top icons on the Groups Manager toolbar - on the right - are missing (the "-", the "Options" and the "?" icons). On mouse-over they get back again

![bug3](https://cloud.githubusercontent.com/assets/14912461/15729015/646a477c-2858-11e6-8945-310769499557.png)

**Comment by Quicksaver** [comment]
> It's definitely theme related!!! If i set default theme and restart it returns to normal, any other theme - the ones i tried, at least - sets the background black - (img attached is a different theme from the first one)

Can you link me to one of those themes please?

> Also, in bug3.png, please note that the 3 top icons on the Groups Manager toolbar - on the right - are missing (the "-", the "Options" and the "?" icons). On mouse-over they get back again

Yeah it does that if you restart often in a short amount of time. It's a weird effect that I'm not sure how to avoid. :/

**Comment by maverick74** [comment]
https://addons.mozilla.org/pt-PT/firefox/addon/a-little-irish-magic/
https://addons.mozilla.org/pt-PT/firefox/addon/green-with-luck/
https://addons.mozilla.org/pt-PT/firefox/addon/fractal-green-eyed-cat/

(by your name, i suppose you will feel right at home whit portuguese webpages ;)

**Comment by Quicksaver** [comment]
Yep. ;)

Thank you, Ill check those out as soon as I can. Might take a few days though, so I hope it's not an absolute deal breaker until then.

**Comment by jjspace** [comment]
I just wanted to add that I am getting the same issue and while its not a deal breaker because I LOVE tab groups it would be nice to be able to change it back. I have looked into theme design in the past and while I didn't go very in depth I think there was something like a "background-color" or a "bar-color" or something similar that never seemed to change anything so maybe people just don't set it or set it to black by default and that is bleeding over into the tab group styling. I don't know if that is anywhere near the real answer or not but it never hurts to throw out suggestions right?

**Comment by Quicksaver** [comment]
It's probably something very close to that, yes. Of course I would not have you use Tab Groups with an ugly look like that, this will be fixed for sure. :)

**Comment by lindhe** [comment]
I'm not 100% sure this is the same issue or not, but I have problems with using the dark GTK3-theme in Gnome with Tab Groups. Some fields get very light text on white background, which is less than ideal. Also, it looks terrible with that light background flashing my eyes after having the beautiful dark background I'm used to.

It looks like this:
![screenshot from 2016-06-02 13-29-35](https://cloud.githubusercontent.com/assets/7773090/15743481/138a485c-28c6-11e6-8f57-77bcbe639893.png)


Do you think this is the same issue, or should I report it as a separate issue?

**Comment by Quicksaver** [comment]
@lindhe It's a separate issue. Would you mind opening a new issue about it, so I don't forget to fix that? Of course it shouldn't look like that. ;)

**Comment by bs76** [comment]
Switching off any theme seems to work: the groups are rendered in the default colors. Switching any theme on, they get dark. Running on MintLinux

**Comment by lindhe** [comment]
I would love to. Here you go! #250

**Comment by maverick74** [comment]
Ok then... here's another one for you to crack your head :D 

On OpenSuse Linux + KDE i don't have any problem what so ever. I change themes, reboot do anything i want and it just keeps on working perfectly ;)

**Comment by purajit** [comment]
Any update on this? Also, on El Capitan, Firefox 48, even after the theme restoration+restart, it looks embossed and not the right shade of grey, like this (black shading added by me):

![screen shot 2016-09-20 at 10 41 21 am](https://cloud.githubusercontent.com/assets/7026198/18682054/a14e963e-7f1f-11e6-97bf-cf40132ccdc2.png)

**Comment by maverick74** [comment]
what i truly wonder is what happened to @Quicksaver ... either he took some looooong holidays or something's wrong...

I don't ear from him for a long time, neither do i see any activity lately...

**Comment by Quicksaver** [comment]
I'm here. ;)

Between my new computer having had to go back because of a defective processor (which I just got back today), and well, life, I haven't had any chance at all to work on my add-ons. Let's see if this time's the charm. :) I will of course be going through every issue and e-mail I have, so that everything is fixed for the next update; this one is one of my top priorities.

**Comment by maverick74** [comment]
Nice to see you're ok!!! (And that's just some life casualties that forced your absence :)

**Comment by Quicksaver** [comment]
Sorry this took so long. I'll post a beta with this fix for everyone to try in a few days; there's just a few more bugs to fix and changes I want to make before I do.

**Comment by Quicksaver** [comment]
@purajit oh and that's a different issue which I already plan to fix; lots of things look a lot out of place with OS X. ;)

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix this issue.

**Comment by purajit** [comment]
Hey! Got the update ... thank you so much! Works great :)
