### ISSUE TITLE
Tabs mixing across groups

### ISSUE THREAD

**Issue by Kinematics** [Quicksaver/Tab-Groups#233]
Got latest update today. (version 2)

Have a window with a number of open tabs.  Call this group Voting.

Create new group.  Called XAML.  Moved one tab from Voting group to XAML group in the groups management area (single view).

Click on XAML group.  It goes to that group, that tab.

Select Voting group from the dropdown.  Switches to the active tab of the Voting group, however -- there are only two tabs in view: the 1 tab from the XAML group, and the active tab from the Voting group.

In other instances, have had all tabs from the Voting group visible, but the tab from the XAML group is also visible at the left edge of the tab row.  Switching between groups via the dropdown simply changes which tab is selected on the row.

This doesn't seem to happen with existing groups, only newly created groups.

Screenshots:

Group management window:
http://i.imgur.com/tiUeN3R.png

Voting group (can see selected group name on right side of the control bar):
http://i.imgur.com/9BzxG6m.png

XAML group:
http://i.imgur.com/PmbNTwX.png

Other version, after selecting XAML group explicitly from management view, then using dropdown to switch to Voting:
http://i.imgur.com/d02T6JD.png

**Comment by Quicksaver** [comment]
Those steps seem to work fine for me, when I switch to the Voting group, all the tabs from that group are visible, and the tab(s) in XAML isn't/aren't.

Can you please try disabling all your other add-ons except for Tab Groups and see if that still happens?

**Comment by Kinematics** [comment]
Testing with other addons disabled.

Disabling all addons that don't require a restart: Problem still exists.

Restarting to disable remaining addons: Problem is gone.

Reenabling addons til problem reappears:

Classic Theme Restorer: No problem
Stylish: No problem
NoScript: Problem appears.

Re-enabling all addons except NoScript: No problem.

Appears to be a conflict with NoScript.  Using version 2.9.0.11

**Comment by Quicksaver** [comment]
I'll give NoScript a try, I wonder if it's blocking some Tab Groups action, although it shouldn't.

**Comment by leggewie** [comment]
I believe I've seen something similar after the update to version 2 but I believe it's been a transient issue.

**Comment by dizeee** [comment]
I have kind of a similar issue. When I open the browser with the group A and start typing URL of a tab that is in the group B in the address bar and select "Go to tab" (not sure if this is the right english title) from the drop-down menu, than the tab is opened in the group A. The bug continues to reproduce until I explicitly switch to the tab B in the Tab Groups drop-down at least once after browser startup.

**Comment by Quicksaver** [comment]
@dizeee I'm sorry, I must have completely missed your comment. But yeah, that's another thing, opened #418.

**Comment by Quicksaver** [comment]
@Kinematics I'm sorry it took me so long to get to this. I've just tried NoScript 2.9.0.14 and it seems to work fine for me. Could you try that updated version and see if it makes any difference for you?

**Comment by Kinematics** [comment]
Installed NoScript 2.9.0.14 and tested.  Am not seeing any of the earlier issues with tab group switching using the dropdown.  It does seem to have fixed things.

**Comment by Quicksaver** [comment]
Well, I guess that's it then. :) Let me know if it starts happening again.
