### ISSUE TITLE
New tab button (Big +) takes up and wastes most of the space in my tab groups

### ISSUE THREAD

**Issue by bakkerthehacker** [Quicksaver/Tab-Groups#234]
This is a pretty big regression from version 1 of Tab-Groups in my opinion.  All of my tab groups that only have 1 tab now take up double or more the space they used to take up.  

I would definitely donate if this gets fixed.  But until it is, I can't see myself using the new version.

**Comment by Quicksaver** [comment]
How can groups take up more space? I don't understand, can you please post a screenshot of this?

**Comment by bakkerthehacker** [comment]
Version 1:
http://i.imgur.com/fvoW96C.png

Version 2:
http://i.imgur.com/4c5Foti.png

Version 2 shrinking the group vertically a little bit:
http://i.imgur.com/eFG58Px.png

**Comment by Quicksaver** [comment]
Ah ok I understand. Yes, the new tab button takes up a "slot", so single-tab groups like that will of course be affected. I'm already planning to try and improve this behavior (although I have no idea how to do it yet). This is essentially the same as #192 though.
