### ISSUE TITLE
Text is vertically misaligned in the bookmarks toolbar

### ISSUE THREAD

**Issue by garyking** [Quicksaver/Tab-Groups#235]
If I move the new Tab Groups button to the bookmarks toolbar, then it's clearly vertically misaligned with the other text.

![firefox tab groups](https://cloud.githubusercontent.com/assets/343940/15727092/763c299c-2822-11e6-8f3c-7fac88734dfe.png)

Also, perhaps add the below icon to the text, so that it's not just plain text, which at first glance doesn't make it obvious that it represents Tab Groups?

![manage my groups](https://cloud.githubusercontent.com/assets/343940/15727093/763d0150-2822-11e6-8757-17109f3c3f46.png)

**Comment by Quicksaver** [comment]
> If I move the new Tab Groups button to the bookmarks toolbar, then it's clearly vertically misaligned with the other text.

Are you sure that's the bookmarks toolbar? Do you perhaps mean the navigation toolbar? The main one that contains the location bar?

> Also, perhaps add the below icon to the text, so that it's not just plain text

This is not possible, because of the way Firefox's native theme is applied.

**Comment by GaryKing** [comment]
Yeah I think I meant the location bar. I moved my bookmarks to the right of the address bar.

**Comment by Quicksaver** [comment]
It's still strange that it's misaligned like that. Could you try removing your other icons and buttons from it in customize mode, to see if it ever goes back to normal? It's possible one of them is enlarging the toolbar.

**Comment by GaryKing** [comment]
I tested in a new profile. Same problem. I put the Tab Groups button to the left of the bookmarks, in the bookmarks toolbar this time. Nothing else on the entire row, as it's a new profile. I'm on a Mac, if it matters.

![new profile](https://cloud.githubusercontent.com/assets/343940/15727372/eee19412-2823-11e6-8c2a-4775491b4c32.png)

**Comment by Quicksaver** [comment]
Yep, I'll definitely have to check it out. Thanks for letting me know.

**Comment by daiheitan** [comment]
Hope this would be fixed soon...

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) includes many fixes for the toolbar button. Please let me know if you still have any issues with it.

**Comment by Quicksaver** [comment]
Actually fixed by https://github.com/Quicksaver/Tab-Groups/commit/33c811b76e672978a1f15df411e61f4d001d74d4 and further corrected by https://github.com/Quicksaver/Tab-Groups/commit/8a662647bfa6af75095ff7b3f9975557e43bd140
