### ISSUE TITLE
Loses the customized tab stylings

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Tab-Groups#236]
The custom tab colorings, etc. (unread, unloaded) from TMP get lost. Restarting FF fixes it.
I'll investigate further to see if I can narrow down the cause.

**Comment by Quicksaver** [comment]
Indeed, they're not supposed to just be lost. Do the actual tabs keep their styling when this happens?

**Comment by jmain33** [comment]
Yes the tabs on the Firefox tab bar still retained their styling.
When lost, in tab groups view, they all possessed the default tab styling.

**Comment by Quicksaver** [comment]
If you can figure out an exact action that causes this to happen, that would be great. Can you tell if this happens when you disabled all other add-ons except for Tab Groups and TMP?

**Comment by jmain33** [comment]
I've been plugging away trying to reproduce this issue to no avail. I went through every action that I did previously, _post-update,_ but it has yet to resurface. I'll keep you posted if anything changes.

**Comment by Quicksaver** [comment]
I'm sorry it took me so long to get to this. I've still not seen this happen to me. Does this keep happening for you? Have you tried the [latest dev version of TMP](https://addons.mozilla.org/firefox/addon/tab-mix-plus/versions/) with the latest Firefox 49.0.1? Also, what operating system are you on?

**Comment by jmain33** [comment]
I wouldn't let this issue wrack my brain. It only occurred after the initial installation then once again, after several months, I noticed it (partially occur *on only a select few tabs*) after some heavy usage. I'm running Win7 Pro and FFox47.0.1 w/ TMP 0.5.0.0

It hasn't yet been reproducible from a known series of actions/circumstances. Don't sweat it :smile: .

**Comment by Quicksaver** [comment]
Well, if you ever find out if there's some specific set of actions to cause this, please let me know, otherwise I'm not sure there's anything I can do for now. :)
