### ISSUE TITLE
New icons are really low res.

### ISSUE THREAD

**Issue by CamJN** [Quicksaver/Tab-Groups#24]
Could we get some high dpi friendly icons please? The settings gear, help question mark and search magnifying glass are all really pixelated on a high dpi screen.

**Comment by pauricthelodger** [comment]
Currently trawling the panorama bugs on bugzilla and thought this might be interest -https://bugzilla.mozilla.org/show_bug.cgi?id=1189904

Maybe @alexploner would be up for sending in a patch? (Assuming it's the same Alexander =P)

**Comment by Quicksaver** [comment]
aa6ff8156e1cc27dc4bc9892677ee743ffa8bfe9

**Comment by Quicksaver** [comment]
There's a whole new set of icons in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6). Please give it a try and let me know if you have any problems with it.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.
