### ISSUE TITLE
Tab group shorcut button dropdown - text/groups not sorted alphabetically

### ISSUE THREAD

**Issue by shaunmavronicolas** [Quicksaver/Tab-Groups#241]
When you right click on a tab to move it to a new group the text is sorted alphabetically, as it should be. However, when using the shortcut tab group button, the groups are all mixed up. I've looked for a setting but found nothing to sort this properly so with dozens of groups, purposely named for ease of accessing them, it becomes a mess.

Hope there is a setting or perhaps this is a bug?

Many thanks.

**Comment by Quicksaver** [comment]
Ugh, it's not supposed to be sorted like that of course. It's supposed to be sorted in the order you define in either single view or grid layout. Thanks for letting me know, I'll have to fix that.

**Comment by always-depends** [comment]
It would be cool if you could sort the group names ascending/descending as well.  If you've got a lot of groups, it make it easier to find them.

**Comment by shaunmavronicolas** [comment]
Wishing this wasn't considered a "minor" bug. I have dozens of groups and before the 2.0 update, it was easy to find things as I purposely named them appropriately for sorting, it worked prior to 2.0. This plugin is the only reason I still use FF, it is such a wonderful tool, would be so great to see this sorting issue resolved, it sorts by oldest first, newest last, vs alphabetically...

Many thanks for a wonderful tool none-the-less.

**Comment by Quicksaver** [comment]
It's minor because it's mostly an aesthetic issue, since you can still use the list, just that instead of taking one second to get to where you want, it'll take you a few more. ;)

That's not saying I don't take the bug seriously, I will fix this one as soon as I can (for the next update). It's just not fixed yet because I haven't had any chance to work on it lately; and setting up my new work environment is proving a bit more difficult than I expected.

**Comment by shaunmavronicolas** [comment]
I understand Luis, very grateful for all your work on it. Look forward to the fix when ever it arrives, thank you.

**Comment by dgutov** [comment]
Could we include "Move to Group" in this bug's description? I've looked for it recently, and hadn't managed to find it.

**Comment by shaunmavronicolas** [comment]
I am not sure how that relates to this specific bug, this is purely a sorting thing in the text dropdown when accessing the groups from the shortcut icon (the list that is generated). Move to group is done within other places. Groups names are shown, not the pages within the groups.

**Comment by dgutov** [comment]
@shaunmavronicolas Quoting the author:

> It's supposed to be sorted in the order you define in either single view or grid layout.

According to this, the tab groups button dropdown behaves correctly. The "Move to Group" menu does not, however.

**Comment by shaunmavronicolas** [comment]
Perhaps we are speaking about different things.... this has to do with choosing another tab group from the icon in the Firefox tool bar. Right clicking on a Tab within the browser, then choosing "move to group" shows the correct Alphabetical sorting, this is what should happen from the shortcut for Group sorting when you wish to switch to another group via the this shortcut that brings up a dropdown listing all the groups, at the bottom is "Manage my groups and settings"

**Comment by Quicksaver** [comment]
I honestly can't remember from the top of my head how both are working right now, and I don't have a chance right now to properly test it. But I will look at both when I work on it. ;)

**Comment by dgutov** [comment]
@shaunmavronicolas 

No, I'm speaking about the same things.

> then choosing "move to group" shows the correct Alphabetical sorting, this is what should happen from the shortcut for Group sorting when you wish to switch to another group

Not correct, and not what should happen when switching to another group.

**Comment by Quicksaver** [comment]
Ok, there's some confusion here, and I'm to blame as I must not have expressed my response very well.

> When you right click on a tab to move it to a new group the text is sorted alphabetically, as it should be.

It should not. Groups should be sorted in the order you place them in single view / grid layout. So the quick access panel (when you click the toolbar button) shows them fine, and the "Move to group" menu does not. @dgutov is absolutely correct.

Although I've been planning to add a "sort by name" function for a while now. It's simple enough and most of the code is there already for the move to group menu, so I might as well get it over with here. :)

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) includes this new option, please try it out in the add-on's preferences page and let me know how it works for you.

**Comment by shaunmavronicolas** [comment]
Very BIG THANK YOU Luis! Wonderful to see the Alphabetical sorting, thank you so much.

**Comment by dgutov** [comment]
It works quite well, thank you! (With the default setting).

**Comment by Quicksaver** [comment]
Glad to hear it, on both counts. Thanks for letting me know. :)

**Comment by Quicksaver** [comment]
By the way, I had obviously missed sorting tabs in the quick access panel as well before. I've add that small change to [beta version 2.1b3](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b3). Although it should work just as fine, I thought you might want to try it out.

Sorting tabs will probably have its own preference in the future, along with more sorting abilities, but for now, given how simple the quick access panel still is, it obeys the same preference as the groups sorting one.
