### ISSUE TITLE
Wrong current tab label.

### ISSUE THREAD

**Issue by Amartel1986** [Quicksaver/Tab-Groups#244]
I have two tabs: **tab1** and **tab2**. Current tab is **tab1**. `Tab groups preferences` are opened in **tab1**. I go to *groups view* and activate **tab2** by single clicking it. When I then press `Change tab groups preferences`, I go to already opened preferences in **tab1**, but **tab2** name is shown as current.

This doesn't work all the time, but pretty often.

**Comment by Quicksaver** [comment]
First of all, I'm sorry it took me so long to get to this.

I don't fully understand. Where does it show tab2's name as current?

**Comment by Amartel1986** [comment]
In **ToolBar Button**, when **Show the name of the active group** is activated.

**Comment by Quicksaver** [comment]
Hmm I can't reproduce it at all. What operating system and Firefox version are you on?

When this happens, do the tabs actually change to the tabs that are in the group with the add-on's preferences tab, or does it show that tab in the current group?

**Comment by Amartel1986** [comment]
Let me show you an example. I have to tabs:

- **mail** (with your mail and Tab Groups Options opened);
- **gitlab** (with this issue opened).

Currently **mail** tab is opened with options as current site:

![tab-name-1](https://cloud.githubusercontent.com/assets/2173775/19258826/740b66e6-8f84-11e6-8f51-0f9dcf04117f.png)

I go to tab group manager and select **gitlab** tab by single-clicking it:

![tab-name-2](https://cloud.githubusercontent.com/assets/2173775/19258859/bb208aac-8f84-11e6-9773-1e4ac41126e2.png)

After that I press `Change tab group preferences` and this is what I got more than 50% of all times:

![tab-name-3](https://cloud.githubusercontent.com/assets/2173775/19258890/1c351bf0-8f85-11e6-87e8-e7e5c7b54955.png)

**Comment by Quicksaver** [comment]
Ah thank you for those steps, I wasn't trying it like that. Yep there's a problem there, I'll be sure to fix it for the next update.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix this issue, and thank you for those very precise steps! Please give it a try and let me know if you have any more issues with it.
