### ISSUE TITLE
The problem of the "default group name" for unnamed tab group

### ISSUE THREAD

**Issue by githubbmn** [Quicksaver/Tab-Groups#245]
I am a "Tab Groups" Add-on user, and I always using the "Move to Group" function for the tab group.

Before "Tab Groups" Add-on is update, When I using "Move to Group" function, the "default group name" of the unnamed tab group is look like this:
![default](https://cloud.githubusercontent.com/assets/17193735/15737192/58757bc4-28d7-11e6-8a92-28c344ada3d1.png)
So even though I don't rename tab group, I still can easy to know what is the meaning of the group that I will move to.

After "Tab Groups" Add-on is update, the "default group name" of the unnamed tab group is become a non-intuitive "group number":
![2](https://cloud.githubusercontent.com/assets/17193735/15737195/5f312116-28d7-11e6-9456-ccb8a807970f.png)
Now If I don't rename the tab group, I need to checking which group I am looking for before I do moving. I don't like rename the tab group, so that is inconvenient for my use habit!

I am sorry I am lazy to rename tab group, Is that possible to make "default group name" back to the past please? 
My english is not well, sorry for my poor english.

**Comment by Quicksaver** [comment]
Unfortunately that won't be possible. However, those group names won't actually change. As long as you keep that group, it should keep that name/number for the rest of its life, so it's really just a matter of getting used to it.
