### ISSUE TITLE
Can't find donate instructions

### ISSUE THREAD

**Issue by kparal** [Quicksaver/Tab-Groups#247]
I opened up your homepage http://fasezero.com/addons/ and there's written:

> Every five dollars is an hour I devote to these add-ons that you and I can no longer go without. Every contribution counts!

Also, there's this question in FAQ:

> The Paypal contribution page doesn't seem to work.

However, I can't find any instruction **how to actually donate**. Anywhere on that site I see a donate button. There's _Support_ and _Contribute_, none of that is the right button. I disabled adblock, I still don't see it. 

If you want to increase community contributions, I suggest to make it much clearer how people can donate.

**Comment by Quicksaver** [comment]
Contribute = donate. And as the answer to that same question says:
> Sometimes clearing your cookies and cache helps. And if you can still access Paypal's website itself, you can make a transfer directly to quicksaver.addons@gmail.com

Also, for what it's worth, the most direct donation button is the "contribute" button that exists on its main AMO page (the same as for any other Firefox add-on that accepts contributions): https://addons.mozilla.org/firefox/addon/tab-groups-panorama/

**Comment by kparal** [comment]
OK, I see it now on the _Contribute_ page. The _Add to Firefox_ button obscured my view of the _Donate_ button. Thanks.
