### ISSUE TITLE
Can't close tabs while in search mode

### ISSUE THREAD

**Issue by tshatrov** [Quicksaver/Tab-Groups#248]
Previously one could type in something like "google.com" and all the tabs that contain "google.com" would be highlighted. Then one could easily close them one by one. The new search interface doesn't allow this. This is actually the only thing I use tab search for, so it's pretty annoying. Maybe add a close tab button next to "View this tab in its group" button?

**Comment by Quicksaver** [comment]
You're right, a close button in those results would be useful.

**Comment by justinfiore** [comment]
Also, having a way to close from the dropdown menu would be great too!

**Comment by iShyboy** [comment]
Oh, I found it annoying when I was trying to delete some duplicates of chapters in the tab-view some time ago, I didn't think about opening a Issue, @Quicksaver the close button and middle click too please.
Take your time
:+1:

**Comment by Quicksaver** [comment]
@justinfiore that's #5.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) not only adds the close button to those listed search results, but also brings back the tab highlighting mode that existed before! Please give it a try and let me know what you think. Any suggestions to improve it further are greatly welcome.
