### ISSUE TITLE
Pinned tabs sometimes lose their favicons

### ISSUE THREAD

**Issue by genrix4444** [Quicksaver/Tab-Groups#249]
Hello. 
First of all, thank you for this very important add. 

But after new update I have some discomfort with it. 

![12](https://cloud.githubusercontent.com/assets/19707845/15743729/25fd678a-28d0-11e6-9dc7-50dc72ff284d.png)
1) My first problem concludes in unmixed colours of backgrounds of tabs. The old version with white background was better. 
![14](https://cloud.githubusercontent.com/assets/19707845/15743822/cb54dc90-28d0-11e6-9c8c-15a4aefe9920.jpg)

2) Also, as you can see, in the right list of tabs second icon should be youtube, but it dissapeared(
3) And third issue is unreadable numbers of quality tabs in the window of group of tabs: number is black and background is black. 

How can I fix these problems? Can you help me? 
Your earliest reply would be appreciated.

P.S. Sorry for my bad english.

**Comment by Quicksaver** [comment]
See #232.

> in the right list of tabs second icon should be youtube, but it dissapeared(

Does it reappear if you reload the tab?

**Comment by genrix4444** [comment]
![15](https://cloud.githubusercontent.com/assets/19707845/15744035/2b324926-28d2-11e6-917a-4eead6b2a7b7.png)
It was sold patially. In this time I have less invisible icons.

**Comment by Quicksaver** [comment]
It's possible that it's not always catching the updated favicons, I'll take a look.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) fixes an issue with the icons of pinned tabs not updating always. Could you give it a try and see if it also fixes it for you please?

**Comment by Quicksaver** [comment]
I'm fairly sure I found the actual culprit this time. If you still have this issue with [beta version 2.1b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b6) please let me know.
