### ISSUE TITLE
Little Issue with tab mix plus.

### ISSUE THREAD

**Issue by iShyboy** [Quicksaver/Tab-Groups#25]
Very low priority, since it's just a little issue that keep bothering for a while, when tabs overflow and with new tab next to the current, after opening the tab groups just once, the new tabs keep opening at the left most position of the window, and it is just after opening tab groups.
Here,
http://vgy.me/JCfBq3.jpg
New Tab, and there we go.
http://vgy.me/g02GWf.jpg

No hurry, and great addon, I would really miss this function in firefox.

**Comment by Quicksaver** [comment]
I can't reproduce this with the latest version of Tab Groups (1.0.1) and the latest [dev version of TMP](http://tmp.garyr.net/forum/viewtopic.php?f=3&t=15740). Maybe I've already fixed it without knowing. Could you please update and try them out?

If you still have this issue, please export your TMP preferences and attach them here in the github issue or send them directly to my e-mail. It may be a specific combination of its settings causing this.

**Comment by iShyboy** [comment]
Good, it's OK after 1.0.1, closing now.

**Comment by iShyboy** [comment]
ff

**Comment by Quicksaver** [comment]
Ok, so it's that the tabs are scrolling to the left, rather than the tab opening at the left. I still can't reproduce it though, I assume you are using the latest dev version of TMP I linked to above. Could you try also disabling all your other add-ons except for Tab Groups and TMP and see if that helps?

**Comment by iShyboy** [comment]
It's all new, a new Nightly with just TMP and TG, just that, and it's not the dev version of TMP, just the default, it's like this.

After the overflow of tabs, the tabs open in a normal way, just next to the current, but after opening the Panorama of TG, the tabs scroll to left, 

![ScreenTake](https://a.uguu.se/brclmd_Issue_25.mp4)

**Comment by Quicksaver** [comment]
I asked you to try the dev version because it might have been fixed in TMP already... Which seems to be the case, I can reproduce this in TMP 0.4.1.9 but not in [0.4.2.0pre.151127a1.1](https://addons.mozilla.org/firefox/addon/tab-mix-plus/versions/0.4.2.0pre.151127a1.1-let-fixed)

Please try it and let me know if it works for you or not.

**Comment by iShyboy** [comment]
Thank you, works fine with 0.4.2.0pre.151127a1, well, closing now.

**Comment by iShyboy** [comment]
I'm reopening this issue as it's another problem with TMP, I'm using the latest version of TMP and already tried with the latest version of dev channel.
FF 42.0
When I open the group view, and select a tab, anyone, after exiting the group view, the tabbar scroll itself back to the first tab, if the selected tab it's not out-of-sight and near the first tab, OK, but if the tab is far from the first tab then It's bad, I have to scroll all the way back to the active tab, or ctrl+tab to go to the next tab, that'll bring the tabbar back to the active tab.
It also happens when I open and close the groupview, even selecting nothing.

If you could not reproduce the issue, I'll try my profile in a newer version of firefox (43.0.4) and see if the problem it's my profile.

**Comment by Quicksaver** [comment]
You should definitely try in an updated version of Firefox (it's up to 45 now) and the latest of both TMP dev version and the latest Tab Groups beta as well.

BTW, you could have opened a new issue, since this is a different issue from the original. ;)

**Comment by iShyboy** [comment]
Sadly, I can't use the latest version, only up to the 43.0.4 because an addon that I use, just doesn't work with the newer ones, and it's the addon that I use the most.
It's something in my profile, it didn't happen, with a new one, even on FF 42.0.

**Comment by Quicksaver** [comment]
I should say, I'm dropping support for Firefox 44 and below with the next version, so it was unlikely I would have been able to do anything in this case then. :( Firefox 45 will be supported for the duration of its ESR life-cycle though.

**Comment by iShyboy** [comment]
If firefox doesn't want to let redirector work with about:pages, I dont want that firefox, that's why I'll, probably, not update in my main profile, I always have a portable one updated. Thanks for the support, though, the same issue with the latest FF, problem confirmed on my profile, only.
