### ISSUE TITLE
Unreadable text with dark GTK theme

### ISSUE THREAD

**Issue by lindhe** [Quicksaver/Tab-Groups#250]
I have problems when using the dark GTK3-theme in Gnome with Tab Groups. Some fields get very light text on white background, which is less than ideal. Also, it looks terrible with that light background flashing my eyes after having the beautiful dark background I'm used to.

It looks like this:
![screenshot from 2016-06-02 13-29-35](https://cloud.githubusercontent.com/assets/7773090/15743481/138a485c-28c6-11e6-8f57-77bcbe639893.png)

I would guess it could be resolved by simply setting a background color and text color explicitly, but there is probably a more flexible solution, allowing for different themes to have the intended effect.

I'm currently running Firefox 45 on Arch Linux with i3 and Gnome.

Ask if you wonder anything. Thanks for making this amazing software.

Cheers.

**Comment by Quicksaver** [comment]
Thanks for opening the new issue. I'll be sure to fix this as soon as I can. :)

**Comment by smichel17** [comment]
FWIW, Firefox generally doesn't work very well with the gnome gtk3 dark theme. Obviously I have no objections to you fixing it here, but I also feel like it's the kind of thing that should really be fixed upstream.

**Comment by lindhe** [comment]
Yes, indeed Firefox is broken with themes. But I'm afraid that Mozilla don't care. And since the big upgrade to Firefox that brings GTK3-integration to the table, it's basically "only" design elements inside Firefox that is broken; not web pages. That I am willing to deal with, and this screen is one of few issues I've found with it for the last little while.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) improves the display of the options dialog with the dark theme. Please give it a try and let me know how it looks for you.

**Comment by 15bart15** [comment]
Hi

this works OK for me. thanks for the fix

But somethingis wrong with option 2 and 3 the tooltip window isn't large 
enough and the text is cut (see screenshots)

Bst regards

**Comment by Quicksaver** [comment]
Please don't attach images when replying directly to the notification e-mail as it doesn't work. You'll have to attach the images directly in the github issue.
