### ISSUE TITLE
User option to control the tab group thumbnail border size?

### ISSUE THREAD

**Issue by december1981** [Quicksaver/Tab-Groups#251]
Since version 2.0, the border size between thumbnails has increased, taking up a lot of space overall. I noted this on the reviews page for the add-on.

One thing that I forgot to suggest in the review - but now that I think about it it could be the biggest win for getting more 'space' back - is that it would be good to have a user option to set the border size (within a range limit or something), to allow a more compact thumbnail arrangement before hitting a scroll or stack view.

**Comment by Quicksaver** [comment]
If by border you mean the spacing between thumbs, it's not totally impossible. But reducing the thumbs themselves more than the current lowest possible size is.

**Comment by december1981** [comment]
Yes, I appreciate from what you said that scaling the thumbs down is not possible. But I was refering to the border only here. It's what, 10 pixels around the thumb on all sides? So that's a space of 20 between two thumbs in both the horizontal and vertical direction. Add that up over a large array of them, and there's a lot of space used.

Maybe some people prefer them more spaced out, but I'm sure there are some (like myself), that'd prefer a border of 1 or 2 pixels width.

**Comment by iShyboy** [comment]
![border](http://i.imgur.com/EmPQVST.png) It's a bit much, but I want to see how it would be, maybe 1~2px seems a bit too congested.
![concept](http://i.imgur.com/VKK0mK3.png)
Oh, there's some space between the thumb and the name of the tab.

**Comment by december1981** [comment]
I guess from a user perspective it might be better to have a 'compact' mode setting, where these spacings are tightened, rather than exposing dimensions directly.

**Comment by Quicksaver** [comment]
Exactly what I was thinking. ;)

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) now adapts the border width according to the size of the tab thumbnails themselves, so that it's not too large on very small thumbnails and not too narrow on very large ones either. Please give it a try and let me know what you think. I think this should cover most (all?) cases where the border width can be an aesthetic hindrance, but If you believe a "manual" setting could help improve things further, please re-open.

**Comment by december1981** [comment]
Just tried it, and it looks good to me, thanks for the update.

Btw, one thing I notice with this update is that if the icons are small enough, the body of the page is not rendered - is that intentional now?

**Comment by Quicksaver** [comment]
Yeah, see #256. It's as explained in the release notes, it will tile the icons only if the thumbnails are too small, which of course you can still disable as usual if you prefer.
