### ISSUE TITLE
Add right-click menu for tabs in the quick access panel

### ISSUE THREAD

**Issue by Spitfire1900** [Quicksaver/Tab-Groups#252]
This was a feature in release 1 and was removed in release 2. The right click menu made it easy to rearrange, close, rename and move tabs/tab groups.

**Comment by Quicksaver** [comment]
There was no right-click menu in version 1... What are you talking about? Are you sure that didn't come from another add-on?

**Comment by Spitfire1900** [comment]
Wait, this is an issue with the add-on [TabGroups Menu|https://addons.mozilla.org/en-US/firefox/addon/tabgroups-menu/], which is not compatible with the new Tab Groups release.

**Comment by Quicksaver** [comment]
I'll see if there's anything I can do on my side. The last time I tried that, it worked (well enough) with v2 of Tab Groups.

**Comment by Spitfire1900** [comment]
Issue created over there as well, [#52] (https://github.com/char101/tabgroupsmenu/issues/52).

**Comment by Spitfire1900** [comment]
There are other compatibility issues as well:
https://github.com/char101/tabgroupsmenu/issues/created_by/Spitfire1900

**Comment by Quicksaver** [comment]
Oh wait, I confused TabGroups Menu with another thing... I'm sorry about that. I'm already planning to add many things from a groups management perspective into the quick access panel, see #5.
