### ISSUE TITLE
Middle click to close tabs in list view

### ISSUE THREAD

**Issue by DoctorJellyface** [Quicksaver/Tab-Groups#253]
It would be awesome if you could close tabs with a middle click the menu list tab view. I often end up with a ton of old tabs just waiting to be closed and the list view is a perfect place because you see much more of the label than in the group.

**Comment by Quicksaver** [comment]
I'm already planning to add many management functions to the panel, including this. :)

**Comment by Quicksaver** [comment]
Actually I'm tracking this in #5.
