### ISSUE TITLE
Retain inactive groups only across restart

### ISSUE THREAD

**Issue by smichel17** [Quicksaver/Tab-Groups#255]
The behavior I've always wished I could get with tab groups is that inactive groups are maintained across restarts, while the active group follows the behavior of the firefox setting 'When Firefox starts'.

For example: A is the active tab, making 1 the active group:

1 { **A**, B, C }
2 { D, E, F }

When I close and re-open firefox, if my 'When Firefox starts' setting is "Show my home page" and my home page is about:home, I'd like to see:

1 { **about:home** }
2 { D, E, F }

Now, about:home has a "restore my windows and tabs from last time" button. Clicking this should restore the state back to:

1 { **A**, B, C }
2 { D, E, F }

---

There are a couple of ways you could implement the setting to enable/disable this feature. My suggestion is that you add a single setting for whether background tab groups should persist, with the options of "Always", "Never", and "Same as the firefox global preference" <- phrasing subject to change

**Comment by Quicksaver** [comment]
Unfortunately that is not possible. Tabs (and groups) are kept in a session file, handled by Firefox. What the "When Firefox starts" - "Show my windows and tabs from last time" does is, it loads the session from before you started Firefox. If you don't use that, you're forcing Firefox to start with a completely clean session. There's no middle ground there.

**Comment by smichel17** [comment]
It seems like you could still implement this as a setting that is only available if "Show my windows and tabs from last time" is selected, that defines a custom behavior for the active group only. So Firefox saves everything, and then this addon provides an option to discard some of those tabs on close.

That may be outside the scope of what you'd like this addon to provide, which is totally your prerogative, but I think it is still technically possible (though of course, I may be wrong).

**Comment by Quicksaver** [comment]
It is possible like that of course. But isn't it just easier to close whatever groups you don't want when you don't want them?

**Comment by smichel17** [comment]
I prefer to see only `about:home` or `about:newtab` (with 'blank', not suggested sites) on startup, because otherwise it's very easy for me to get distracted from whatever I intended to do by a previous tab or suggested site. This is also why I love tab groups in the first place: it allows me to get other stuff out of my face so it won't distract me, without losing that page (I could bookmark, but that's kind of a pain, especially if I'm coming back in just a couple minutes).

When I close firefox, I am usually thinking about the tabs in the active group (am I ok with losing these?) but I often forget about inactive groups. Being able to save the inactive groups while maintaining a blank start page would be a dream :)
