### ISSUE TITLE
Increase the number of tabs viewable at one time on the "tab groups" view screen

### ISSUE THREAD

**Issue by FoxSox** [Quicksaver/Tab-Groups#256]
First off, thanks for the hard work that's clearly gone into this release!

The way I like to use tab groups is via the "free arrange" view, and I like to be able to see all of my tabs on the screen at once (I like to organise things clearly and visually). In the new release the minimum tab thumbnail size appears to have increased, meaning that less tabs can be seen at one time (although the "scroll the group" option is an improvement on "stacking"). Ideally I'd like to get as many of tabs on the screen as possible. I suggest:

1) Reducing the minimum thumbnail size further (as far as possible). (I think you may have already rejected this in another thread...?)
2) When thumbnail reaches a minimum and space is not sufficient to show all tabs in the group, show the website icon only (or make this an option).
3) When thumbnails are not displayed (ie icons only), show the page name below the icon (as is the case for thumbnails) rather than at the side (or make this an option). Currently the "no thumbnail" view shows the page names at the side of each icon which takes up too much space (and means they are in a list rather than a 2D grid).

**Comment by Quicksaver** [comment]
> 1) Reducing the minimum thumbnail size further (as far as possible). (I think you may have already rejected this in another thread...?)

Yes, this is just not possible at the moment.

As for the rest, I am already planning similar enhancements (I thought I already had an issue open for this, but apparently I don't).

**Comment by FoxSox** [comment]
Thanks! I'll keep an eye out for this. Where do you see these on your list of priorities?

**Comment by Quicksaver** [comment]
Not very high I'm afraid. :( But there are a few other things that I want to implement soon to optimize the display of thumbnails, so hopefully those should help in the meantime.

**Comment by FoxSox** [comment]
Thanks!

**Comment by Quicksaver** [comment]
Personal note: #56.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) includes an enhancement to show the page icons in a tile when the tab thumbnails are too small to be useful, allowing you to fit a lot more tabs in a smaller space. Please give it a try and let me know how it works for you.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 15. 00:37 CEST](https://github.com/Quicksaver/Tab-Groups/issues/256#issuecomment-253936382 "2016-10-14T22:37:31Z - Replied by Github Reply Comments"):
> [Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) includes an enhancement to show the page icons in a tile when the tab thumbnails are too small to be useful, allowing you to fit a lot more tabs in a smaller space. Please give it a try and let me know how it works for you.

Something occured to me. I think it would be more useful to also show the favicon when the tab is unloaded, but not too small. Having it mostly just show a blank white rectangle is useless.

**Comment by iShyboy** [comment]
@Quicksaver there's an css rule to control the max size of the width of the tile? So you can make the width it's good for you, like 350px of width and if there's too many tabs just scroll/stack?

**Comment by Quicksaver** [comment]
> I think it would be more useful to also show the favicon when the tab is unloaded

It already does. Or it should. I don't understand, can you give me a screenshot of what you're seeing when a tab is unloaded?

> Having it mostly just show a blank white rectangle is useless.

Most tabs should keep thumbnails saved on this, so that you don't need to load the tabs to have a thumbnail. However, it's likely that Firefox cleans up old thumbnails, so some end up being blank because those thumbnails are empty. I have yet to track down where this happens yet to see if I can prevent it from within the add-on.

**Comment by Quicksaver** [comment]
@iShyboy what width are you trying to limit exactly? The size of the tab items or the available space in a group for tabs? I don't fully understand.

**Comment by iShyboy** [comment]
@quicksaver it's the size of the tab tile in the tab view, the size of the tile it's auto according to the number of tabs in the group what I mean is: Even if I have one 1 tab in the group, if I limited the width of the tile to 300 it'll stay with 300 even if I have 1 or a 100 of tabs.

**Comment by iShyboy** [comment]
Like with the new tab of FF you can size the tiles using the width until you get the max number of columns in with the tile the size you like.

**Comment by Quicksaver** [comment]
That should be doable, although I'll have to leave it for the update after next. Can you open a new issue for it please, to track it properly?

**Comment by iShyboy** [comment]
Good

**Comment by Quicksaver** [comment]
@mzso hold on, I think I understand what you mean. Basically when there's no thumbnail saved on disk and the tab is still unloaded (so it can't fetch a new thumbnail), there's no point in showing the blank rectangle and it could just show the stylized favicon instead. Is that it?

It's an interesting suggestion. Can you open an issue for it to track it properly? I'd have to see how it could look with very large tabs, but I like where you're going with it.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 20. 01:18 CEST](https://github.com/Quicksaver/Tab-Groups/issues/256#issuecomment-254968325 "2016-10-19T23:18:43Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) hold on, I think I understand what you mean. Basically when there's no thumbnail saved on disk and the tab is still unloaded (so it can't fetch a new thumbnail), there's no point in showing the blank rectangle and it could just show the stylized favicon instead. Is that it?
> 
> It's an interesting suggestion. Can you open an issue for it to track it properly? I'd have to see how it could look with very large tabs, but I like where you're going with it.

Yes.

Okay. Here it is:  #447
