### ISSUE TITLE
Put "tab groups" button on the main menu bar instead of "choose another tab group"

### ISSUE THREAD

**Issue by FoxSox** [Quicksaver/Tab-Groups#257]
I like to be able to get to the full tab groups view screen as quickly as possible, so I'd prefer the "tab groups" button to be on the main menu bar as in the old release.

Perhaps the list of tab groups (as per "choose another tab group") could appear at the top of the bookmarks menu instead, so these could still be quickly available.

(Apologies if there's a user option for moving these buttons around which I'm not aware of)

**Comment by Quicksaver** [comment]
Go to the add-on's preferences, and disable the options "Click to show the quick access panel" and/or "Show the name of the active group", depending on how you want the toolbar button to behave.

**Comment by FoxSox** [comment]
Perfect - thanks!
