### ISSUE TITLE
Sort alphabetically

### ISSUE THREAD

**Issue by marchanddd** [Quicksaver/Tab-Groups#261]
Hello !

I love Tab Groups functionality and use it quite intensively. For example, I actually have 20 open tab groups with an average of 10 tabs on each group. 
It would be very nice to have an option to automatically sort groups alphabetically.

Thanks,

**Comment by Quicksaver** [comment]
You can sort them manually, by dragging them in either single view or grid layout when managing your groups, which is so much more powerful than simply sorting alphabetically. ;)
