### ISSUE TITLE
Less than the width of the window(about:tabgroups) is 1165px, ScrollBar disappears.

### ISSUE THREAD

**Issue by arigayas** [Quicksaver/Tab-Groups#263]
Textbox I think that it is the cause.

![tabgroups2 0_tab-groups](https://cloud.githubusercontent.com/assets/11251874/15750475/8b896116-2921-11e6-9da4-470bbbd26fb4.png)

![tabgroups2 0_session](https://cloud.githubusercontent.com/assets/11251874/15750470/891c40ba-2921-11e6-8c9d-8257e9864f5a.png)

![tabgroups2 0_howto](https://cloud.githubusercontent.com/assets/11251874/15750456/7c086a2a-2921-11e6-8714-8dda364efeb8.png)
![tabgroups2 0_about](https://cloud.githubusercontent.com/assets/11251874/15750452/7680e5fa-2921-11e6-917f-e793180e8184.png)

**Comment by Quicksaver** [comment]
That behavior can definitely be improved, thanks for letting me know.

**Comment by arigayas** [comment]
I expect it to be corrected by the next version. :)

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix this issue. Please give it a try and let me know if you still have any issues with it.

**Comment by arigayas** [comment]
I was confirmed  fix this issue. Good Job!!

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.
