### ISSUE TITLE
No margin on tab group selector on Mac

### ISSUE THREAD

**Issue by mtughan** [Quicksaver/Tab-Groups#264]
The new tab group selector works well on my Windows machine, but doesn't look quite so good on Macs. See the screenshot for an example.
<img width="1552" alt="screen shot 2016-06-02 at 12 04 12 pm" src="https://cloud.githubusercontent.com/assets/116812/15752112/97c94cdc-28ba-11e6-932a-0a05cc440b4e.png">
The icon is pressed right up against the right side of the window and needs some margin because it doesn't have the window controls to the right of it like on Windows. It's not a major impediment to usability, but looks sloppy and does make it slightly harder to hit the click area.

**Comment by Quicksaver** [comment]
Yes, it's apparently doing that, I'll need to take a look when I can properly test on OSX again. I'm sure there are other details that could be improved, so if you find any more please let me know.

**Comment by Quicksaver** [comment]
#235

**Comment by mtughan** [comment]
Confirmed in release 2.1. Thanks!
