### ISSUE TITLE
Where is the little box?  What is this menu thing?

### ISSUE THREAD

**Issue by plaws0** [Quicksaver/Tab-Groups#265]
I was really happy that when Mozilla removed tab groups from FF that someone jumped in with an add-on that replaced it seamlessly.  Now, with the latest update, that seamlessness is completely gone and I'm left with some menu thing that, if I dig around in it enough, I can get something that sort of resembles what was there before.  Even the toolbar icon is different.  

Since it was all just the default before, I don't even know what to search for in the help.  How do I make it look just like it did when it was part of FF?

This is on an Ubuntu system, if it makes a difference.

**Comment by Quicksaver** [comment]
As I've explained in the release notes, in the add-on description, and in the "how to use" page, all those new features are optional and can be easily disabled. The quick access panel can be disabled by going to the add-on's preferences and disabling the option "Click to show the quick access panel". You can get back the icon in the toolbar button by disabling the option "Show the name of the active group". And you still have the free arrange mode available, in addition to the single view that you see, and grid layout as well; read the "how to use" page.

**Comment by iShyboy** [comment]
The addon was improved it doesn't look like the default anymore, 
![options](http://i.imgur.com/Tnus98r.png)
uncheck those boxes and the icon should be like before.
![1](http://i.imgur.com/s1bLTm5.png)
Tap in "free arrange" to have the look as before.

**Comment by plaws0** [comment]
Typical programmer, deciding what is best for the users without asking.
Remember, this used to be a part of FF with basically no options.  THAT
FUNCTIONALITY SHOULD BE THE DEFAULT IN ALL CASES.  You want to add stuff?
GREAT!  I bet some of it is even useful but the DEFAULT IN ALL CASES should
be what it was before so that people can at least recognize that it's the
same add-on.

I went through this with KDE4 a number of years ago.  Fortunately, someone
that was equally pissed *and* had programming skills (I have none) forked
KDE3 so that people can still get work done.

I've lost 1/2 hour of work between trying to figure out what the hell
happened, open a Github account to file a bug, and file it.  And for that,
I get "well, we told you in an obscure README file that this would happen,
stupid user."

Ugh.

Thanks to iShyboy for taking the time to explain exactly what to click to
fix this issue!!




On Thu, Jun 2, 2016 at 12:10 PM, Luís Miguel <notifications@github.com>
wrote:

> As I've explained in the release notes, in the add-on description, and in
> the "how to use" page, all those new features are optional and can be
> easily disabled. The quick access panel can be disabled by going to the
> add-on's preferences and disabling the option "Click to show the quick
> access panel". You can get back the icon in the toolbar button by disabling
> the option "Show the name of the active group". And you still have the free
> arrange mode available, in addition to the single view that you see, and
> grid layout as well; read the "how to use" page.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Quicksaver/Tab-Groups/issues/265#issuecomment-223357713>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASzRR9Q0MoEKy4RIVFUjhzFVwKkCjxcfks5qHw6QgaJpZM4IsxjM>
> .
>



-- 
Peter Laws | N5UWY | plaws plaws net | Travel by Train!

**Comment by Quicksaver** [comment]
> Typical programmer, deciding what is best for the users without asking.

Every single feature you see has been suggested by users just like you, most of them right here on this forum.

> Remember, this used to be a part of FF with basically no options. THAT FUNCTIONALITY SHOULD BE THE DEFAULT IN ALL CASES.

That is irrelevant. I choose new default features based on how I feel they would benefit the majority of users, which is definitely the case. I still provided options for pretty much every one of them, so you can have the add-on behave exactly like it did before if you want it to.

> the DEFAULT IN ALL CASES should be what it was before so that people can at least recognize that it's the same add-on.

As I mentioned, you must have gotten an update notification describing all of this. Recognizing that it's the same, but enhanced, add-on should not have been a problem.

> I get "well, we told you in an obscure README file that this would happen, stupid user."

The add-on description is the first line of documentation for the add-on for every single user that installs it. The "How to use" page should be clearly recognized and, quite frankly, obvious of what information it contains. The release notes, again, should have been directly shown to you when the add-on updated. If you neglected to read those, then you can't accuse me of hiding the information.

BTW I never once insulted or mocked you in any way. I replied to every single question you made, providing you with the answers as well. If you failed to read those as well, then you can't accuse me of being a bad developer.
