### ISSUE TITLE
Grid layout drag and drop

### ISSUE THREAD

**Issue by jnvsor** [Quicksaver/Tab-Groups#266]
Currently the grid layout swaps tabs on drag and drop. This means that moving a tab group from the bottom of the grid to the top without messing up the order of the others requires as many drag and drops as there are tab groups. In my case - that's over 50.

Grid layout drag and drop should insert at the dropped position, not swap. This way swapping takes 2 drag and drops, and inserting only takes 1 (As opposed to 50)

**Comment by Quicksaver** [comment]
True, but unfortunately that's not possible. I tried that behavior at first, and it made things so jumpy it was just incredibly confusing to follow.

As a workaround for that particular case, you can quickly switch to single view, drag the group wherever you want, and go back to grid layout and it'll be there.

**Comment by jnvsor** [comment]
Jumpy? Couldn't you treat the drag and drop behaviour the exact same and just move the swapped one back afterwards?

**Comment by Quicksaver** [comment]
That's what I tried. What I meant by jumpy was, there are so many elements moving around when you do that, that it becomes increasingly taxing on the browser to animate/move properly, becoming also increasingly harder to follow. It was just a very bad experience.

**Comment by jnvsor** [comment]
I don't know about your development version but the one I just got updated to has no animations in grid view, it just shades the box you're hovering over..

**Comment by Quicksaver** [comment]
Yes, indicating that it will swap with it. Using the same animation would just be counter-intuitive, as in why should it highlight a group if it's meant to be placed before it, and not swap with it? I've never seen anything behave like that in any application.

**Comment by jnvsor** [comment]
I've never seen a drag and drop implementation that swaps myself.

I would perceive it less as swapping and more as "This is where the tab will end up when you let go" which would be accurate. If you could point me in the direction of the swapping logic I could take a crack at it myself - I think it would be more intuitive than you think

**Comment by Quicksaver** [comment]
The problem is not with the login, it's with showing it on screen. Moving so many elements (all groups AND all tabs) is very taxing on the browser. Things lag, jump around...

**Comment by Quicksaver** [comment]
Reopening because I like the behavior you suggested in #270.

**Comment by wraybowling** [comment]
Firefox's established drag-to-sort behavior on tabs involves a blank space that acts as a placeholder. When you release the tab, it slides into the allotted space. Typically the best way to make an interaction feel responsive is to show the result of the action before the action is complete. Placeholders do that.

**Comment by jnvsor** [comment]
@wraybowling The problem is that unlike tabs, tab groups take a lot of work to move.

Some of them resize when they move causing a redraw for all their contents - this isn't a problem if it's done a few times at the end of a drop but if you have to do it repeatedly during a drag it's going to tank performance (Manifesting in a noticeable stutter while you drag)

Tabs on the other hand don't need a redraw per tab, just the occasional move (And this is the behaviour tab groups assumes in single view mode)

**Comment by wraybowling** [comment]
[Have a look at Packery](http://packery.metafizzy.co/draggable.html). Dave made the placeholder default in v2, and after a twitter poll, most folks favored a snappy feel.

And as for performance problems, I'm just going to quote my old boss:
> Don't optimize early
Never compromise good design because of early performance tweaks. You'll always end up with garbage. We can reduce the number of draws some other way.

**Comment by jnvsor** [comment]
And your example once again misses the point - tab groups resize
