### ISSUE TITLE
Tab Groups icon lost

### ISSUE THREAD

**Issue by czackwaltz** [Quicksaver/Tab-Groups#267]
I have the following add-ons installed: Tab Groups, Tree Style Tab, and Tab Mix Plus. My current FF windows session has approximately 12 other groups with about 55 tabs throughout. The tab tree shows all the tabs in my current tab group. It used to also have tab group icon at the bottom of that tab tree, but that has now disappeared. So I have no way to navigate to the other tabs groups and the tabs with them. I know that these still exist because when click on the "X", I am warned there are approximately 55 open tabs. Any ideas on how to get the tab group  icon back?

**Comment by iShyboy** [comment]
There's some users having problems with the addon icon vanishing in this version, I've found a simple solution.
Uncheck those options:
![1](http://i.imgur.com/Tnus98r.png)
and tap "restore defaults" on customize menu.
The icon should appear, if it don't you may have another configuration (cck) that is having some compatibility problems in this version, as you can see in the issue #239.

**Comment by Quicksaver** [comment]
Yeah. :)

**Comment by czackwaltz** [comment]
Thanks to all. IBM CCK 2.2.4 (updated 2015-12-22) seems to be the culprit. After I disable and restarted, I got the Tab Group icon back. If I reenabled IBM CCK 2.2.4, the Tab Group icon disappeared. For anyone else with this problem, it is also being discussed as issues #230 and #239.
