### ISSUE TITLE
Don't immediately switch to group when moving tab from one group to another

### ISSUE THREAD

**Issue by garyking** [Quicksaver/Tab-Groups#268]
Is there a way to prevent it from immediately switching to a group when moving a tab from one group to another? Because sometimes I want to move multiple tabs from one group to another, and it will take longer if it keeps switching focus to the new group immediately.

**Comment by Quicksaver** [comment]
Do you mean by right-clicking a tab? It may be possible to only switch groups if you're moving the active tab. I'll take a look and see what I can do.

In the meantime, it'll probably be easier to move multiple tabs like that in groups view.

**Comment by Quicksaver** [comment]
@iShyboy I don't understand, do you mean from searching? That's significantly harder...

**Comment by iShyboy** [comment]
@Quicksaver nope, it's the behavior,
If you are in a group and open various tabs of something, and then you want to create a group for that something, you go to Tab view and start moving.
But if you move the **active tab** it would automatically switch to the group that you moved, if it was before you finished moving all it can be annoying.

**Comment by GaryKing** [comment]
Yep exactly what @iShyboy said. I didn't realize that it only changes the active group if I'm moving the active tab, so that's not as big a problem as I thought, though.

**Comment by Quicksaver** [comment]
Oh! That's not supposed to happen of course. Thanks for the heads-up both of you! I'll be sure to check it out.

**Comment by B00ze64** [comment]
I can confirm that I stay in the current group, if I send the active tab, from the browser to another group by right-click on the tab and Move-To-Group, on FF38. So this is new behavior...

**Comment by Quicksaver** [comment]
It's not new behavior, it's a bug. ;)

**Comment by GaryKing** [comment]
Another related issue. When moving a tab from one group to another, as I said, focus is immediately switched to the target group. Also, the group thumbnails don't update, until I click to another group and click back to the previous group. I assuming this is related.

**Comment by GaryKing** [comment]
I also notice that when moving a tab from one group to another, it will occasionally NOT be inserted at the end of the group.

**Comment by Quicksaver** [comment]
> I also notice that when moving a tab from one group to another, it will occasionally NOT be inserted at the end of the group.

Single view?

**Comment by GaryKing** [comment]
Yep in Single view.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should no longer switch groups when dragging tabs onto their thumbs at the top, and their thumbs should now update accordingly more reliably. Please give it a try and let me know how it works for you.
