### ISSUE TITLE
newly created groups continue false enumeration

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Tab-Groups#271]
When creating new groups the defaulted naming scheme keeps adding successive enumeration, in the specific case of, when former groups have been removed.
I.E. if I currently have two groups and create a new group it will be named Group 7 if I have previously created up to six new groups, as opposed to correctly being named Group 3.
In other words, when it comes to naming, Tab Groups has no way of realizing that former groups have been removed.

**Comment by Quicksaver** [comment]
It's not just former groups, but existing groups also have their number id, even if you don't see it because you've named them. I left this in because it will greatly help when adding Firefox sync support later. So it is fully expected.
