### ISSUE TITLE
Latest update to Tab Groups (or is it just Tab Groups 2) is crashing Firefox

### ISSUE THREAD

**Issue by SteveChessin** [Quicksaver/Tab-Groups#272]
I had the original Tab Groups add-on as I love tab groups. But it upgraded itself to Tab Groups 2 and now almost every time I display my tab groups (especially if I try to change the display from the default to the free space kind) it crashes Firefox. How do I get the previous version of Tab Groups back?

**Comment by Quicksaver** [comment]
You may have some kind of incompatibility or corruption in your profile. Could you try quickly creating a [new profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles) and see if that also happens there?

**Comment by leggewie** [comment]
@SteveChessin how many tabs do you have open?

**Comment by SteveChessin** [comment]
@leggewie I usually have 3 windows open. One window has only one tab. Another one has six. My main window has 26 tab groups, with anywhere from 1 to 107 tabs each.

I did find a workaround. I can use the "Choose another tab group" drop down menu to choose a tab group, as in this image:
![1 tab group list](https://cloud.githubusercontent.com/assets/19721058/16248205/b2c14140-37c2-11e6-9881-ea6096a0a63e.png) and once in a tab group I can use the "List all tabs" drop down to go directly to the tab I want, as in this image: 
![2 tab menu](https://cloud.githubusercontent.com/assets/19721058/16248241/e9eebcba-37c2-11e6-8db6-4209d65e6b9e.png)

(I also discovered I can go directly to the tab via the "Choose another tab group" and clicking on the NN tabs portion of the group I want.) But if I select "Tab Groups" from the "List all tabs" drop down and then mouse over the window the browser crashes. (I'm going to post this comment before I go test that so I can describe the exact actions.)

**Comment by SteveChessin** [comment]
Before I run a test that crashes Firefox, I thought I'd post the links to the existing crash reports. They are:
https://crash-stats.mozilla.com/report/index/bp-6fb5def2-64b6-4566-a415-a10252160602
https://crash-stats.mozilla.com/report/index/bp-28c055d2-2a04-4195-80fe-d7e932160602
https://crash-stats.mozilla.com/report/index/bp-20203123-e03e-4173-8899-42ef72160603
https://crash-stats.mozilla.com/report/index/bp-14b7f920-3392-48be-bba2-013f82160603
https://crash-stats.mozilla.com/report/index/bp-8c3ba254-b7d3-4f6f-b19d-ec0af2160609

**Comment by iShyboy** [comment]
I've tried the steps you said earlier but, nothing happened here. 3 Windows. 30 tab groups in the main window with 2~30 tabs in each. New Profile. 4 Addons in my profile; TG, TMP, uBlock and Restart. Nothing happened at all, selection, interaction, changes,  goes smoothly as ever.

**Comment by Quicksaver** [comment]
> You may have some kind of incompatibility or corruption in your profile. Could you try quickly creating a new profile and see if that also happens there?

Seriously try that. Or you can begin by disabling all your other add-ons except for Tab Groups and see if it still happens then.

**Comment by SteveChessin** [comment]
Well, what do you know? It didn't crash! I tried all the ways to display the tab groups and it didn't crash. The crashes were with Firefox 46.0.1 and Firefox 46.0. I'm now using Firefox 47.0 and I guess Tab Groups 2 tickled a bug in Firefox 46 that was fixed in Firefox 47.

@Quicksaver I was going to create a new profile after Firefox crashed (since the instructions say that one has to quit out of Firefox in order to create a profile), but since it didn't crash that won't be necessary.

**Comment by iShyboy** [comment]
*tried with FF 46.0.1* Only now I'm updating to the last version

**Comment by Quicksaver** [comment]
Well, that's good at least. Let me know if it starts happening again.
