### ISSUE TITLE
Missing the Group Button . . . but Color Background more important!

### ISSUE THREAD

**Issue by Zeeker46** [Quicksaver/Tab-Groups#273]
This button was convenient as it opened the groups and let me move tabs from one to another group.  It was also user friendly in that it had a light blue background.  Now I have a black background with white blocks . . . I can deal with the new menu button since it gets me to the "Manage My Groups" tab; however, the black and white contrast is annoying.  Louis, is there any way to change the colors in the "Manage My Groups" screen?

**Comment by Quicksaver** [comment]
You can disable the "Click to show the quick access panel" option in the add-on's preferences, so that clicking the button takes you directly to groups view.

As for the background, please if that's the same issue as #232 , if not please re-open this.

**Comment by Zeeker46** [comment]
232 is the same issue . . . love your work and will make a donation today!  Tried default theme without any change; but when I move to new group, the format is an improvement and the color combination is great.  I can live with that!  Went to contribution page, entered $5, make contribution . . . and nothing happened, expected PayPal to come up and verify donation.  What's up?

**Comment by Quicksaver** [comment]
> Tried default theme without any change

Do you mean that switching to the default theme didn't give you the original color scheme as expected? Remember that you may have to restart Firefox in order for that to happen.

>  Went to contribution page, entered $5, make contribution . . . and nothing happened, 

I really appreciate this first of all. :) The PayPal dialog in AMO's pages doesn't work for some people apparently. If you go directly to the PayPal website, you should still be able to make a direct transfer to my PayPal account: quicksaver.addons@gmail.com

**Comment by Zeeker46** [comment]
Got it, thanks!  Went to contribution page, entered $5, make contribution . . . and nothing happened, expected PayPal to come up and verify donation. What's up?

**Comment by Zeeker46** [comment]
Luis – Donation is on its way!  Restarted Firefox and light blue is back, my theme wasn’t all that important . . .  Klaus
