### ISSUE TITLE
Backup tabgroups on regular basis (timer)

### ISSUE THREAD

**Issue by deroby** [Quicksaver/Tab-Groups#274]
Hi there, I'm using version 2 now and like it a lot. (the auto-grabbing filter is great!)
I noticed there now (?) is a way to backup the tab-groups to a file which feels like a great idea because my main gripe with tabGroups always was that now-and-then firefox would get killed (e.g. because it was too slow/hanging while shutting down) and then next time I started it up again I MIGHT still have the current tabs open, but certainly all other tabgroups were gone =(
Maybe the way these things are saved is different now and less prone to such situation, but having a backup file always is a good thing. So I was thinking, if we'd be able to create such a backup file every 4 hours or so, this would minimize the amount of work potentially lost.
The files could be timestamped, or simply not and the OS/DropBox/OneDrive/GoogleDrive etc could keep track of the versions over time.

Just a (low priority) idea...

**Comment by Quicksaver** [comment]
I thought about implementing auto backups on a timer like that (you're not the first to suggest it). But eventually decided against it, at least for now, in favor of something else. Now Tab Groups creates a backup every time it is updated (before updating), to prevent losses in case anything goes wrong for some reason; this is really the biggest possibility of when things could be lost, so it should cover most cases.

You can also restore groups and tabs from several other types of automated backups, such as a similar backup created when Firefox updates itself for instance. And also from a few other backups like the current and previous session backup files. (See the [add-on description](https://addons.mozilla.org/firefox/addon/tab-groups-panorama/) for details on which files exactly the add-on can use.)

Add all that up and you should have a pretty recent backup at any point. I also believe that a finer control over this doesn't really fit in with the scope of the add-on, you may want to consider using something like [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/) which is especially designed for handling backups of your session.

**Comment by deroby** [comment]
Fair enough. I hadn't thought about the idea of a more generic add-on that might help out here but after having a quick look at the referenced Session Manager I think you are right that this would be re-inventing the wheel. Thanks for the tip!
