### ISSUE TITLE
When navigating with keyboard, remove mouseover window shadow.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [Quicksaver/Tab-Groups#277]
![shadow-bug](https://cloud.githubusercontent.com/assets/5187404/15779786/b7129bcc-299e-11e6-9a30-26ce7407c4ea.gif)

It's confusing to see two "highlighted" windows. When I start to navigate with the keyboard, I would expect the mouseover window shadow to be removed.

**Comment by Quicksaver** [comment]
Agreed.

**Comment by Quicksaver** [comment]
In the next update, the currently active tab will have a small blueish border around it, while moving the cursor over other tabs only gives them the usual shadow as before (except it's also a little lighter now). By the way, judging from your screenshot, you're on OS X, is that correct? I've also made other color corrections that should also improve the experience.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2), please try it and let me know how it looks for you.

**Comment by AndrewSouthpaw** [comment]
Looks great, thank you!
