### ISSUE TITLE
Quick-access shortcut should "toggle", not "enable"

### ISSUE THREAD

**Issue by WorldsEndless** [Quicksaver/Tab-Groups#279]
It would be best if a second pressing of my quick-access shortcut would cancel the quick access; right now after one keystroke the quick-access/search mode pops up, but I must move to the mouse and click somewhere or press "esc" to cancel the action.

**Comment by Quicksaver** [comment]
That's what it does for me actually. A second press of the shortcut closes it for me, is this not happening for you? What operating system and Firefox version are you on? Does that also happen if you disable all your other add-ons except for Tab Groups?

**Comment by leggewie** [comment]
We are talking the shortcut that is Shift-Ctrl-E, right? To go into group view.  Like @Quicksaver, pressing that key combo twice goes in and then out of Group View.

**Comment by Quicksaver** [comment]
@leggewie no, in the add-on preferences, you can specify a keyboard shortcut to open the quick access panel as well.

**Comment by WorldsEndless** [comment]
Yeah, second press does not close it for me. System info: 

{
  "application": {
    "name": "Firefox",
    "version": "46.0.1",
    "buildID": "2016050300",
    "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0",
    "safeMode": false,
    "supportURL": "https://support.mozilla.org/1/firefox/46.0.1/Linux/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 0,
    "remoteAutoStart": false,
    "autoStartStatus": 2
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.capacity": 358400,
    "browser.cache.frecency_experiment": 1,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.cache.disk.smart_size_cached_value": 358400,
    "browser.download.importedFromSqlite": true,
    "browser.download.manager.showWhenStarting": false,
    "browser.download.useDownloadDir": false,
    "browser.places.importBookmarksHTML": false,
    "browser.places.smartBookmarksVersion": 7,
    "browser.search.useDBForOrder": true,
    "browser.sessionstore.upgradeBackup.latestBuildID": "2016050300",
    "browser.startup.homepage_override.mstone": "46.0.1",
    "browser.startup.homepage_override.buildID": "2016050300",
    "browser.tabs.warnOnClose": false,
    "browser.urlbar.suggest.searches": true,
    "browser.urlbar.userMadeSearchSuggestionsChoice": true,
    "dom.apps.reset-permissions": true,
    "dom.w3c_touch_events.expose": false,
    "dom.mozApps.used": true,
    "extensions.lastAppVersion": "46.0.1",
    "gfx.crash-guard.glcontext.driverVersion": "3.0 Mesa 10.3.7",
    "gfx.crash-guard.glcontext.deviceID": "Mesa DRI Intel(R) Haswell Desktop ",
    "gfx.crash-guard.glcontext.appVersion": "45.0.2",
    "gfx.crash-guard.status.glcontext": 3,
    "media.webrtc.debug.aec_log_dir": "/tmp",
    "media.webrtc.debug.log_file": "/tmp/WebRTC.log",
    "media.gmp-gmpopenh264.lastUpdate": 1451922832,
    "media.gmp-gmpopenh264.version": "1.5.3",
    "media.gmp-manager.lastCheck": 1465224959,
    "media.youtube-ua.override.to": "43",
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.buildID": "2016050300",
    "network.predictor.cleaned-up": true,
    "network.auth.allow-subresource-auth": 2,
    "network.cookie.prefsMigrated": true,
    "places.history.expiration.transient_current_max_pages": 104858,
    "places.database.lastMaintenance": 1465022580,
    "plugin.importedState": true,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_jobtitle": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_spoolercommand": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.4.is_inch": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.5.name": "Tabloid",
    "print.print_paper_width": "215.90",
    "print.print_paper_size_unit": 1,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.3.is_inch": true,
    "print.print_to_file": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.1.name": "A4",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.colorspace.count": 1,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.1.height_mm": 297,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.plex.0.name": "default",
    "print.print_oddpages": true,
    "print.print_footerright": "",
    "print.print_footerleft": "",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.0.name": "A5",
    "print.print_orientation": 0,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.0.height_mm": 210,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.orientation.count": 2,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_printincolor_change": true,
    "print.print_headerright": "",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.6.is_inch": true,
    "print.print_margin_top": "0.5",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_printincolor": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.6.name": "Executive",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.has_special_printerfeatures": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_num_copies": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_spoolercommand_change": false,
    "print.print_resolution_name": "default",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.2.width_mm": 297,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.4.height_mm": 355,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_jobtitle_change": false,
    "print.print_paper_height": "279.40",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_orientation_change": true,
    "print.print_scaling": "  1.00",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_resolution_change": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.3.height_mm": 279,
    "print.print_unwriteable_margin_right": 25,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_colorspace": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.3.name": "Letter",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.0.width_mm": 148,
    "print.print_unwriteable_margin_left": 25,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.0.is_inch": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.4.width_mm": 215,
    "print.print_paper_data": 0,
    "print.print_plex_name": "default",
    "print.print_unwriteable_margin_bottom": 56,
    "print.print_paper_name": "na_letter",
    "print.print_headerleft": "",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_downloadfonts_change": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_plex_change": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_paper_size": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_colorspace_change": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.1.width_mm": 210,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.3.width_mm": 215,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_resolution": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.2.is_inch": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_orientation": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.resolution.0.name": "default",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.5.width_mm": 279,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.supports_paper_size_change": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.1.is_inch": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.4.name": "Legal",
    "print.print_bgimages": false,
    "print.print_downloadfonts": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.count": 7,
    "print.print_duplex": 1,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.2.height_mm": 420,
    "print.print_evenpages": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.plex.count": 1,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.5.height_mm": 431,
    "print.print_margin_left": "0.5",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.6.height_mm": 254,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.6.width_mm": 190,
    "print.print_colorspace": "default",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.colorspace.0.name": "default",
    "print.print_shrink_to_fit": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.orientation.0.name": "portrait",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.2.name": "A3",
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.orientation.1.name": "landscape",
    "print.print_margin_right": "0.5",
    "print.print_unwriteable_margin_top": 25,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.resolution.count": 1,
    "print.print_bgcolor": false,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_plex": false,
    "print.print_margin_bottom": "0.5",
    "print.print_in_color": true,
    "print.print_paper_size_type": 1,
    "print.print_page_delay": 50,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.paper.5.is_inch": true,
    "print.tmp.printerfeatures.Officejet-6500-E709n-2.can_change_downloadfonts": false,
    "privacy.sanitize.migrateClearSavedPwdsOnExit": true,
    "privacy.sanitize.migrateFx3Prefs": true,
    "services.sync.declinedEngines": "",
    "services.sync.lastPing": 1465157596,
    "services.sync.lastSync": "Mon Jun 06 2016 09:06:44 GMT-0600 (MDT)",
    "services.sync.numClients": 2,
    "services.sync.engine.prefs.modified": false,
    "storage.vacuum.last.index": 1,
    "storage.vacuum.last.places.sqlite": 1462938614
  },
  "lockedPreferences": {},
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 0,
    "windowLayerManagerType": "Basic",
    "windowLayerManagerRemote": true,
    "supportsHardwareH264": "No; ",
    "numAcceleratedWindowsMessage": [
      ""
    ],
    "adapterDescription": "Intel Open Source Technology Center -- Mesa DRI Intel(R) Haswell Desktop ",
    "adapterVendorID": "Intel Open Source Technology Center",
    "adapterDeviceID": "Mesa DRI Intel(R) Haswell Desktop ",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "3.0 Mesa 10.3.7",
    "driverDate": "",
    "webglRenderer": "Intel Open Source Technology Center -- Mesa DRI Intel(R) Haswell Desktop ",
    "info": {
      "AzureCanvasBackend": "cairo",
      "AzureSkiaAccelerated": 0,
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "cairo",
      "CairoUseXRender": 1
    }
  },
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.12",
      "version": "4.12"
    },
    "NSS": {
      "minVersion": "3.22.3 Basic ECC",
      "version": "3.22.3 Basic ECC"
    },
    "NSSUTIL": {
      "minVersion": "3.22.3",
      "version": "3.22.3"
    },
    "NSSSSL": {
      "minVersion": "3.22.3 Basic ECC",
      "version": "3.22.3 Basic ECC"
    },
    "NSSSMIME": {
      "minVersion": "3.22.3 Basic ECC",
      "version": "3.22.3 Basic ECC"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "hasSeccompBPF": true,
    "hasSeccompTSync": false,
    "hasPrivilegedUserNamespaces": true,
    "hasUserNamespaces": true,
    "canSandboxMedia": true
  },
  "extensions": [
    {
      "name": "Add to Search Bar",
      "version": "2.9",
      "isActive": true,
      "id": "add-to-searchbox@maltekraus.de"
    },
    {
      "name": "Diigo Toolbar",
      "version": "5.1.0.38.1-signed.1-signed",
      "isActive": true,
      "id": "{fc2b8f80-d9a5-4f51-8076-7c7ce3c67ee3}"
    },
    {
      "name": "DownThemAll!",
      "version": "2.0.19",
      "isActive": true,
      "id": "{DDC359D1-844A-42a7-9AA1-88A850A938A8}"
    },
    {
      "name": "Firebug",
      "version": "2.0.16",
      "isActive": true,
      "id": "firebug@software.joehewitt.com"
    },
    {
      "name": "JSONView",
      "version": "1.1.1",
      "isActive": true,
      "id": "jsonview@brh.numbera.com"
    },
    {
      "name": "Location Bar Enhancer",
      "version": "5.3",
      "isActive": true,
      "id": "UIEnhancer@girishsharma"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "1.0",
      "isActive": true,
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "Multifox",
      "version": "3.2.2.1-let-fixed",
      "isActive": true,
      "id": "multifox@hultmann"
    },
    {
      "name": "Pocket",
      "version": "1.0",
      "isActive": true,
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Send Tab to Device",
      "version": "0.7.1-signed.1-signed",
      "isActive": true,
      "id": "jid1-mdjmA7if6lo8lA@jetpack"
    },
    {
      "name": "Tab Groups",
      "version": "2.0.1",
      "isActive": true,
      "id": "tabgroups@quicksaver"
    },
    {
      "name": "Valence",
      "version": "0.3.5",
      "isActive": true,
      "id": "fxdevtools-adapters@mozilla.org"
    },
    {
      "name": "Video DownloadHelper",
      "version": "5.6.1",
      "isActive": true,
      "id": "{b9db16a4-6edc-47ec-a1f4-b86292ed211d}"
    },
    {
      "name": "Web Developer",
      "version": "1.2.5.1-signed.1-signed",
      "isActive": true,
      "id": "{c45c406e-ab73-11d8-be73-000a95be3b12}"
    },
    {
      "name": "ADB Helper",
      "version": "0.8.7",
      "isActive": false,
      "id": "adbhelper@mozilla.org"
    },
    {
      "name": "Bluhell Firewall",
      "version": "2.5.3",
      "isActive": false,
      "id": "{6BB5760D-F97E-421B-AF5B-8457A90C3CED}"
    },
    {
      "name": "Cache Status",
      "version": "0.9.1",
      "isActive": false,
      "id": "cache@status.org"
    },
    {
      "name": "CacheToggle",
      "version": "0.6.1-signed.1-signed",
      "isActive": false,
      "id": "cachetoggle@pau.santesmasses.net"
    },
    {
      "name": "Clear Cache Button",
      "version": "0.9f.1-signed.1-signed",
      "isActive": false,
      "id": "{563e4790-7e70-11da-a72b-0800200c9a66}"
    },
    {
      "name": "Firefox Hello Beta",
      "version": "1.4.0",
      "isActive": false,
      "id": "loop@mozilla.org"
    },
    {
      "name": "ProfileSwitcher",
      "version": "1.7.5.1-signed",
      "isActive": false,
      "id": "{fa8476cf-a98c-4e08-99b4-65a69cb4b7d4}"
    }
  ],
  "experiments": []
}

**Comment by leggewie** [comment]
Quick Access menu toggles on and off for me as well. Cannot confirm the problem that @WorldsEndless is experiencing

**Comment by WorldsEndless** [comment]
Ok, I isolated it. I verified it was nothign to do with other addons. Rather, it had to do with my binding the toggle key to involve "CTRL". (I had it as CTRL+/ but also tried CTRL+\ and other things). In these cases it would not toggle. However, by simply making it a bare <F4> it toggles as it should. 

I suppose you guys might have more insight into why this might be.

**Comment by Quicksaver** [comment]
Actually I believe this is because <kbd>/</kbd> is a global hotkey to quick search a webpage. <kbd>Ctrl</kbd>+<kbd>/</kbd> may be triggering something there that's interfering with the panel's shortcut (although it shouldn't).

Can you confirm by trying the shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>/</kbd>? I can't really test myself as in my keyboard the <kbd>/</kbd> character already needs <kbd>shift</kbd> key.

**Comment by Quicksaver** [comment]
Please re-open if you believe what I mentioned was not the case.
