### ISSUE TITLE
Tab Groups button only shows up when it's in menu (reproducible in clean profile)

### ISSUE THREAD

**Issue by Aetf** [Quicksaver/Tab-Groups#28]
As the title says, the button only appears as a small rectangle when it is placed in the toolbar or in the tab list. It seems to me that the small size icon is missing. Can reproduce this in a clean profile.

Tab-Groups version: 1.0.1
Firefox version: Nightly (45.0a1 2015-12-10)
OS: Archlinux with kernel 4.2.5

I have also checked the browser console output. This is what I got.
```
No chrome package registered for chrome://tabgroups/skin/icon.png
```
Oddly enough, I can only get this perhaps relevant output after a clean install of the add-on (first remove it, restart browser, then install it), and it has to be installed from the about:addons page's search result list. When installed directly from AMO webpage, there's no relevant output at all.

Screenshots:

![menu](https://cloud.githubusercontent.com/assets/1519759/11754873/49b49424-a01c-11e5-95ed-e00c14ef20ad.png)

![tablist](https://cloud.githubusercontent.com/assets/1519759/11754847/1bf3104c-a01c-11e5-8ae8-d86cc5e7334b.png)

![toolbar](https://cloud.githubusercontent.com/assets/1519759/11754848/1d74d446-a01c-11e5-8dbf-b9990133e236.png)

**Comment by Quicksaver** [comment]
chrome://tabgroups/skin/icon.png is not for the button, it's for the image in the add-ons manager (and that message is usually irrelevant, as the icon usually shows up anyway in that case).

Did that start happening only in 1.0.1 or did it happen before?

**Comment by Aetf** [comment]
It also happens in the first version (1.0.0)

**Comment by Quicksaver** [comment]
Your icons are pixelated. Are you on a HiDPI screen of some sort? Maybe that's what's causing this.

**Comment by Aetf** [comment]
Yes, it's a Retina Display on Macbook Pro 13. I'm setting `layout.css.devPixelsPerPx` to 2 in `about:config`, as well as the environment variables
```
GDK_SCALE = 2
GDK_DPI_SCALE = 0.5
```

**Comment by Quicksaver** [comment]
This should be fixed in the next version, thanks for letting me know. By the way, it should still appear pixelated as it doesn't have any high resolution icons for linux. I'll probably work on that in #24.

**Comment by Aetf** [comment]
Thank you!

Actually I'm almost accustomed to the pixelated icons :joy: and didn't realize they were pixelated until you pointed that out...

**Comment by Quicksaver** [comment]
Sorry about that. :P
