### ISSUE TITLE
In Single view, when adding a new group and there are too many, then scroll the scroll bar to the far right

### ISSUE THREAD

**Issue by garyking** [Quicksaver/Tab-Groups#283]
In Single view, if there are so many groups that there is a scroll bar, and I add another group by clicking the big plus sign, then the scroll bar should automatically scroll to the far right so that the new group I just created is visible. 

This would therefore make it act the same way as Firefox does, when there are so many tabs that it scrolls, and you add a new tab, then it immediately scrolls into view.

**Comment by Quicksaver** [comment]
Doesn't this happen already? You click the plus sign and a new group is created right under your mouse, where the plus sign was.

**Comment by GaryKing** [comment]
That's different from Firefox tabs, where when you open a new tab with the new tab button, AND there are too many tabs, then the cursor remains on the new tab button.

This is mostly useful when creating two or more tab groups at the same time, so we don't have to scroll. For instance, when organizing one tab group by splitting its tabs into multiple groups.

**Comment by Quicksaver** [comment]
True, making sure the new group button stays visible should probably help in all cases.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should keep the plus button visible when creating new groups. Please give it a try and let me know how it works for you.
