### ISSUE TITLE
how to get browser with no tabs

### ISSUE THREAD

**Issue by ycgtech** [Quicksaver/Tab-Groups#29]
Hi

I am wondering.  With Tab-Groups is there an option to go back to browser with no tabs viewable.  I wish to open new tabs that I know will not belong to group appearing in the browser.

Hope  I have made myself clear.

Thank you.

**Comment by Quicksaver** [comment]
Hmm, I'm not sure I understand... Just create a new group?

**Comment by ycgtech** [comment]
OK sorry for my confusion.  Let me provide scenario.  I am in tab groups screen.  I wish to go back to the browser without loading any of my existing groups.  I want browser with no tabs.  Is it possible?

**Comment by Quicksaver** [comment]
Yeah, create a new group and switch to it, it will have no tabs except for only the "New tab" tab. Isn't that what you want?

**Comment by Quicksaver** [comment]
I mean, just click and drag in the empty area of the tab groups screen, it will create a new blank group. Click it again and it will switch to it.

**Comment by ycgtech** [comment]
Got it.  Thanks for the quick replies.

**Comment by Quicksaver** [comment]
You're welcome. :)
