### ISSUE TITLE
Increasing group size makes it stack tabs

### ISSUE THREAD

**Issue by halftone1** [Quicksaver/Tab-Groups#292]
In some cases the tabs fit in the group fine without being stacked, but increasing the size of the group makes them stack, even though there is enough space.
![tabgroup_unstacked](https://cloud.githubusercontent.com/assets/19715628/15801897/6606bbc2-2aa3-11e6-9929-abe9c161e1f0.png)
![tabgroup_stacked](https://cloud.githubusercontent.com/assets/19715628/15801898/6628cafa-2aa3-11e6-8a24-0bff4cd55866.png)

**Comment by Quicksaver** [comment]
Of course that's not supposed to happen. I'll take a look.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should hopefully fix any similar issues with stacked groups like this. Please give it a try and let me know how it works for you. Note that with the new ability to tile page icons when their thumbnails become too small, it will be harder to stack groups unless you disable that behavior as described in the release notes.

**Comment by halftone1** [comment]
I tried version 2.1b3, since it appears to be the most recent, and it works fine now. Thanks!

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.
