### ISSUE TITLE
Tab group button becomes nonfunctional after short periods of browser use

### ISSUE THREAD

**Issue by Geostationary** [Quicksaver/Tab-Groups#293]
I use firefox 46.0.1, and I repeatedly have the problem that the group tab button in the top right corner ceases to respond/function when I click it until I close and open the browser again; the drop down menu also doesn't let me enter the tab overview.

**Comment by Quicksaver** [comment]
Can you try disabling all your other add-ons for a while and see if that still happens? Can you tell if there's a specific action you take that causes this to happen?

**Comment by Quicksaver** [comment]
The next time this happens, please open the browser console (Ctrl+Shift+J), clear it, then try clicking on the button. Does any error or warning appear in the console then? Also, can you use the keyboard shortcut (Ctrl+Shift+E by default unless you've changed it) to enter groups view when this happens?

**Comment by dcaravana** [comment]
I've got the same problem, but I've force-enabled e10s so that may be the problem (or not, depending on if @Geostationary did the same).

In fact I get a number of complains related to CPOWs in the browser console.

I've disabled e10s for now and let you know if this issue happens again.

**Comment by Quicksaver** [comment]
The add-on should be perfectly compatible with e10s and does not use any CPOWs at all (unless I missed any of course).

**Comment by Quicksaver** [comment]
Without more info, there's nothing I can do.
