### ISSUE TITLE
New tab button in stack exapand doesn't work

### ISSUE THREAD

**Issue by jnvsor** [Quicksaver/Tab-Groups#296]
In grid and free arrange view, expanding a stacked group the new tab button won't work

**Comment by Quicksaver** [comment]
Indeed, I must have missed that. Thanks for letting me know.

**Comment by Quicksaver** [comment]
That button will be gone in the next update.

**Comment by Quicksaver** [comment]
Actually scratch that, this is still relevant even without the button.

**Comment by Quicksaver** [comment]
In [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) you should be able to create a new tab in a stacked group through its context menu now, either by right-clicking the group itself while it's stacked, or somewhere in an empty area while it's expanded. Please give it a try and let me know how it works for you.

**Comment by jnvsor** [comment]
Yeah works great! The extra space also means an extra tab can fit before needing a group resize.

Little css nitpick - no left padding in groups in grid and free arrange mode so there's a gap on the right but tabs are flush on the left

**Comment by Quicksaver** [comment]
That will happen sometimes. Tabs are sized equally, so if each one were to grow by 1 pixel, they wouldn't be able to fit into that space. It always picks the highest width possible for the tabs so that they don't overflow, which means depending on the number of tabs and the size of the group, sometimes there will be a 1 or 2 pixel gap that can't be properly divided across all tabs.

**Comment by jnvsor** [comment]
It's flexbox isn't it? `align-items: center`?

**Comment by Quicksaver** [comment]
With that, the last row will be center aligned as well, and if it has less items than the others which is very common, it would look... Weird I think.

**Comment by jnvsor** [comment]
Ah good point. I tried a quick codepen to see if there was a way to make a wrapper div but it seems it isn't possible without supplying the sum of the tab widths ahead of time
