### ISSUE TITLE
Scroll tab groups with the mouse wheel in single view

### ISSUE THREAD

**Issue by leodag** [Quicksaver/Tab-Groups#297]
Currently, in single view, when you use the scroll wheel while hovering tab groups, nothing happens. Since it has no vertical content, it should scroll to the sides, like with Firefox's tabs (scroll down -> to the right, scroll up -> to the left)

**Comment by Quicksaver** [comment]
That happens sometimes, other times it works. I still can't figure out why sometimes it won't register the scroll event properly...

**Comment by leodag** [comment]
Oh, I wasn't aware it was a bug. I'm currently using Firefox Developer Edition 48.0a2 (2016-06-04) on Windows 10, if that helps.

**Comment by Quicksaver** [comment]
Yep it's a bug. ;) I do want to fix it, but I lost a whole day on it when I first implemented it way back when. That's just to say, it won't be easy apparently. :(

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) changes the method used to horizontally scroll groups with the mouse wheel. It's not exactly what I had wanted, but it's what works I guess. Please give it a try and let me know how it works for you.

**Comment by leodag** [comment]
I'm now on Firefox 49.0.1 on Linux, and still had this bug before using the beta. But it works now. Thanks yet again!

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.

**Comment by r2rien** [comment]
thanks!
fixed it for me in FF nightly:
Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
