### ISSUE TITLE
Keyboard shortcut ctrl-` does not work as in firefox tab-groups

### ISSUE THREAD

**Issue by udovdh** [Quicksaver/Tab-Groups#30]
I discovered that the keyboard shortcut ctrl-` does not work as in firefox original tab-groups.
This keybaord shortcut advances to the next tab-group.
Did I overlook the option to do this same thing in the plugin version?

**Comment by Quicksaver** [comment]
Have you updated to version 1.0.1?

**Comment by udovdh** [comment]
I installed the add-on via the browser.
So probably not.  (where can I see the version?)
Does using the git version fix this issue?

**Comment by udovdh** [comment]
It says tab groups 1 so I guess it is 1.0.0, at least not 1.0.1

**Comment by Quicksaver** [comment]
Yeah, you'll have to update. Just open the add-ons manager and update from there. The shortcut should work fine in 1.0.1

**Comment by udovdh** [comment]
1.0.1 is here...

**Comment by udovdh** [comment]
And after a browser restart the keybaord shortcut works. Thanks!

**Comment by Quicksaver** [comment]
It shouldn't have needed a restart, but maybe that was a fault of the previous version not removing itself properly. Either way, nothing that can be done about that. I'm glad it's working now. :)
