### ISSUE TITLE
Tab Groups are not shown in all windows

### ISSUE THREAD

**Issue by liayn** [Quicksaver/Tab-Groups#301]
If you have multiple windows open (e.g on different desktops on Win10) only the first windows actually displays the tab groups in the menu. In all other windows there is only a group called "Group 2".

**Comment by Quicksaver** [comment]
Groups aren't shared across windows (yet, see #174). New windows start empty, so what you're seeing is expected.

**Comment by liayn** [comment]
Thanks for the fast reply. My search keywords didn't find the other ticket, so sorry for the duplicate.
Thanks for keeping up the work on this really essential add-on.
Cheers.
