### ISSUE TITLE
Select Multiple Tabs at Once in Group Manager [+ MTH Conflict]

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Tab-Groups#304]
I've been using [Multiple Tab Handler] (https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/) to move several tabs at once over to a new/existing group. Unfortunately, there is now a conflict with v2 of Tab Groups, [see here >> MTH issue #118] (https://github.com/piroor/multipletab/issues/118), and the developer has no plans of fixing/maintaining compatibility with your add-on since its function is no longer a built in Firefox ability.

In short, after selecting several tabs, I can no longer move them all-at-once to another group.

1. For future consideration, it would be warmly welcomed to be able to use Ctrl & Shift modifiers in tab groups manager to select a lot of tabs at once. Another useful alternative could be to allow drag-selection.

2. As you can see at the link to the MTH issue, the developer is open to collaborating with someone willing to maintain the required functionality which will keep it compatible w/ Tab Groups. So if you're so inclined.....  :smirk:

**Comment by Quicksaver** [comment]
See #55. In the meantime, I'll see if I can fix compatibility with MTH.

**Comment by Quicksaver** [comment]
You can install a [previous version](https://addons.mozilla.org/developers/addon/tab-groups-panorama/versions) if you want, although I really don't recommend it, as it will become increasingly buggy and unreliable with each Firefox update (and other updated add-ons as well).

**Comment by whismerhill** [comment]
for future refence or anyone passing by : correct url for users is : https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/versions/
Thanks quicksaver. I'm well aware of the potential issues but deem them minor compared to losing the ability to handle multiple tabs at once.

**Comment by Quicksaver** [comment]
Good catch, corrected my post. ;)

**Comment by whismerhill** [comment]
news flash... reverted to 1.02 didn't solve the issue, multiple tabs selection works but movetogroup shows no groups

**Comment by whismerhill** [comment]
with the addon "menu wizard", found out there's actually two different menu items for a single tab or for multiple tabs. tried waterfox v44 (equivalent of firefox 44) with same profile => MTH move to group works
back to firefox 46 => broken again. I'm not certain this bug is related to v2 of Tab-Groups anymore.

**Comment by jmain33** [comment]
@whismerhill you should report your findings to @piroor at either of these locations: https://github.com/piroor/multipletab/issues/116 or https://github.com/piroor/multipletab/issues/118

**Comment by malnvenshorn** [comment]
It would be bad if the issue is not related to the Tab-Groups-Addon. @piroor said that its unlikely that he is going to fix/investigate this issue since tab group is not a build-in feature of Firefox anymore.
https://github.com/piroor/multipletab/issues/118#issuecomment-223768578

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix all compatibility issues with MTH. Please give it a try and let me know how it works for you.

**Comment by jmain33** [comment]
#### :smile: you're upgrading TabGroups, I'm on FF v47.0.1 & I tried v2.1b2 & b3.
Sad to say that they don't seem to have fixed my issue with MTH.  I restarted after both installations but one still gets no current group entries listed in the 'Move to Group' menu when using MTH.

I uninstalled then reinstalled MTH with no positive effects to the issue _(I believe a complete wipe of MTH may be necessary, **any tips on clearing all its stored data would be appreciated, a standard removal doesn't suffice**)_.
***
But, worst of all the new betas are very buggy, I have close to 700 open tabs divided into 5 groups across my session. The main group has over 350 tabs and uses thumbnail view w/ grid display. Entering the group manager makes FF become ≈97% unresponsive, as it tries to load the visuals. My only solution is to kill the browser. Reverting to 2.0.1 reclaimed group manager access.

BTW, the new minimum thumbnail size is unreasonably small! Not that I was able to see one generate, but the boxes are now miniscule :roll_eyes: .

Sorry I wasn't able to properly evaluate your changes in the betas.

**Comment by whismerhill** [comment]
beta version 2.1b2 fixed it immediately for me without any restarts on FF 46.0.1
thanks a lot.

**Comment by jmain33** [comment]
#### UPDATE
After having reverted to v2.0.1, I noticed *to my amazement!* that, the right-click menu of MTH was once again populated with TabGroups sessions. So, in short order, I reinstalled v2.1b3 to take advantage of this. I'm delighted to say that the beta did indeed work well with MTH's 'Move to Group' feature. It moved 14 tabs (all at once) from my main group and appended them to the end of the desired destination group. The move did take longer than I would like ~roughly 10 seconds ~, **but it did as instructed**.
***
Regarding the hung 'Group Manager' page, I exhibited some patience and after about 10 minutes it loaded the icons and became fully responsive. Refreshing every icon at once, _not my previous claim of generating thumbnail images_, seems to be what caused the heavy loading experience. You should consider not automatically activating the new icon tiling in the official release. Once all the graphic elements were there it was & has been gtg.

**Comment by Quicksaver** [comment]
> Sad to say that they don't seem to have fixed my issue with MTH. I restarted after both installations but one still gets no current group entries listed in the 'Move to Group' menu when using MTH.

MTH still has an issue which I can't fix from within Tab Groups unfortunately. In short, the menu won't appear if you have any groups without a name. Its developer already accepted my patch (https://github.com/piroor/multipletab/pull/136) to fix this, but until a new version of MTH is released so you can update, you'll have to give all your groups a name if you want to use the Move to group menu.

> Refreshing every icon at once, not my previous claim of generating thumbnail images, seems to be what caused the heavy loading experience.

Exactly. That was an oversight I made which I've already fixed for [beta version 2.1b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b4), things should be much more responsive with it. I'm sorry about the bother before.

**Comment by jmain33** [comment]
Everything seems OK on your side. TG is doing its part when it comes to working with MTH and moving tabs in general.

Thanks for the time/effort :+1:
