### ISSUE TITLE
tab groups no longer working since upgrades

### ISSUE THREAD

**Issue by gcovell** [Quicksaver/Tab-Groups#306]
I neither see the toolbar icon and the keyboard shortcuts do not work. I have tried removing and reinstalling and disabling other add-ons to no avail. Is there a preferences file I could delete or something else I should do to get the functionality working again?

**Comment by Quicksaver** [comment]
Please see if any of the suggestion sin #239 works for you (basically, if you have CCK2, try disabling it).
