### ISSUE TITLE
No Tabgroups Icon in FF 47

### ISSUE THREAD

**Issue by hramasub** [Quicksaver/Tab-Groups#307]
Tabgroups *Icon* is *not visible* in FF47 and neither is it available for selection from the FF customize menu. Further the shortcuts (alt-shift-e etc) do not work.

Here are the list of Extensions installed on my FF:
Extensions
----------
Name: Tab Groups
Version: 2.0.1
Enabled: true
ID: tabgroups@quicksaver

Name: Bluhell Firewall
Version: 2.5.3
Enabled: true
ID: {6BB5760D-F97E-421B-AF5B-8457A90C3CED}
![ff-no-tabgroups-button](https://cloud.githubusercontent.com/assets/14544262/15890797/f99b30dc-2d8e-11e6-9428-2dbc8512359c.gif)
![ff-no-toolbar-button](https://cloud.githubusercontent.com/assets/14544262/15890798/f99e59b0-2d8e-11e6-8a3c-827ef7766315.gif)

Name: Bookmark Favicon Changer
Version: 2.29
Enabled: true
ID: bookmarkfaviconchanger@sonthakit

Name: Duplicate Tabs Closer
Version: 2.1.3
Enabled: true
ID: jid0-RvYT2rGWfM8q5yWxIxAHYAeo5Qg@jetpack

Name: ERail Plugin for Firefox
Version: 6.0.rev142
Enabled: true
ID: ERAIL.IN.FFPLUGIN@jetpack

Name: Firebug
Version: 2.0.16
Enabled: true
ID: firebug@software.joehewitt.com

Name: Firefox Hello
Version: 1.3.2
Enabled: true
ID: loop@mozilla.org

Name: FoxClocks
Version: 4.2.3
Enabled: true
ID: {d37dc5d0-431d-44e5-8c91-49419370caa1}

Name: Greasemonkey
Version: 3.8
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: LastPass
Version: 3.3.1
Enabled: true
ID: support@lastpass.com

Name: Logitech SetPoint
Version: 6.5
Enabled: true
ID: {F003DA68-8256-4b37-A6C4-350FA04494DF}

Name: Lucifox
Version: 0.9.13
Enabled: true
ID: Lucifox@lucidor.org

Name: Multi-process staged rollout
Version: 1.0
Enabled: true
ID: e10srollout@mozilla.org

Name: NoScript
Version: 2.9.0.11
Enabled: true
ID: {73a6fe31-595d-460b-a920-fcc0f8843232}

Name: Places Maintenance
Version: 2.0.1
Enabled: true
ID: places-maintenance@bonardo.net

Name: Pocket
Version: 1.0.2
Enabled: true
ID: firefox@getpocket.com

Name: RESTClient
Version: 2.0.5
Enabled: true
ID: {ad0d925d-88f8-47f1-85ea-8463569e756e}

Name: Save to Google Drive
Version: 0.1.1-signed.1-signed
Enabled: true
ID: jid1-oN9DnHLeslAVJA@jetpack

Name: Vertical Toolbar
Version: 1.0.12
Enabled: true
ID: verticaltoolbar@xuldev.org

**Comment by Quicksaver** [comment]
Can you please check out #239 and see if it's the same (if you CCK2)?

**Comment by hramasub** [comment]
@Quicksaver : Of course it turns out to be same as #239. I shouldn't have edited my add-ons list (which I did to omit IBM internal plugins). Though I had never expected IBM CCK to have messed with TG.

For now I have disabled CCK2 and cross-posted this issue to CCK maintainer.

I can provide debug info (is this possible with the enable debug option for addon ?) if it would help you fix what is messing up TG. Please help me help you with the debug info.

**Comment by Quicksaver** [comment]
We already know the problem, CCK2 is blocking the loading of certain Firefox resources that Tab Groups relies on. There's no need for you to do any extra work at the moment. :)
