### ISSUE TITLE
time lag in "raise window" when selecting group

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#309]
Sometimes I have more than one window open.  When selecting a group in single view, then switching to the other window I will often be taken back to the first window a few seconds later (1-2s).  This also happens when closing the group rather than selecting it.

**Comment by Quicksaver** [comment]
What do you mean "selecting a group"? Do you go back to your tabs, or do you switch windows without leaving groups view in the first window?

Can you give me a specific set of steps to reproduce this? I'm having trouble reproducing it (as in, not at all).

**Comment by Quicksaver** [comment]
Also, please try [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and let me know if it helps with this issue at all.

**Comment by Quicksaver** [comment]
Is this the same as #342? Either way, please re-open if you still have this issue with the latest version 2.1.
