### ISSUE TITLE
Clicking a tab in groups view sometimes doesn't register

### ISSUE THREAD

**Issue by guniu** [Quicksaver/Tab-Groups#311]
Since the v2 update, sometimes when I click a tab in groups view the page doesn't open, like it doesn't register it. I have to click a second time to open it.

**Comment by Quicksaver** [comment]
Can you tell if there's anything special condition for when this happen? Maybe a specific action you did just before clicking the tab.

**Comment by guniu** [comment]
Unfortunately nothing special. I simply click the Groups View button and click a tab I want to go to next. And sometimes nothing happens, so I have to click again. It's either not registering the click, or it thinks I clicked and grabbed the tab to move it (maybe I click when the mouse is still moving over the tab) - but that never happened in the previous version.

**Comment by Quicksaver** [comment]
The add-on now uses HTML5 drag events for tabs, which may be a little more sensitive perhaps. There's nothing I can do about it if that's the case though, as the add-on can't prevent drag events from happening. Can I ask you to keep an eye on when this happens and see if the tab is being dragged even slightly?

**Comment by guniu** [comment]
I can't seem to pinpoint it. I tried deliberately moving my mouse slightly while clicking, and it still switches the tab. So I don't know what's causing it.

**Comment by Quicksaver** [comment]
Could you give [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) a try and see if you still have this issue?

**Comment by guniu** [comment]
So far, so good. Using it for few minutes only thought, but it feels snappier, more responsive. Will comment if the issue still exists.

**Comment by Quicksaver** [comment]
Great, I'll take that as a good sign, please re-open if it starts happening again. :)

**Comment by guniu** [comment]
So it still happens, but nowhere near as often. Before, during heavy usage it was like 15 times per hour. Now, after almost 2 days of usage, it happened like 3 times. It's very rare, so if there is nothing you can do about it, I'm fine with that.

**Comment by Quicksaver** [comment]
If it becomes troublesome and more frequent again please let me know and I'll try taking a look at it again.

**Comment by guniu** [comment]
I have new info on this issue. I basically found a culprit. One of my addons, Classic Theme Restorer, updated to a newer version (1.6.0.1) few days ago and I started to have a really bad memory leaks and high CPU usage. So I disabled it to confirm if it was the cause and at the same time I noticed that the issue described in this topic is gone. It registers my every click now. So it was CTR all along (I hope, still testing ofc).

**Comment by Quicksaver** [comment]
As far as I know, CTR should work just fine with Tab Groups, I test with it frequently and I never have any problems clicking groups. Although if you have leaks with it, I suggest you try contacting its developer to see if anything can be done about that, perhaps that's also the cause of your trouble here.
