### ISSUE TITLE
Integrate Tab Group Bar functionality from Tab-Group-Bar plugin

### ISSUE THREAD

**Issue by CyberTech** [Quicksaver/Tab-Groups#312]
https://github.com/IIUJ-KrzysztofDawidowicz/Tab-Group-Bar

The above plugin adds a second set of tabs to the browser, representing the tab groups. I absolutely love this behavior, but now that Tab-Groups is a separate addon, I think it makes sense to integrate them.

Screenshot of the final functionality can be seen on https://addons.mozilla.org/en-US/firefox/addon/tab-group-bar/

**Comment by iShyboy** [comment]
Unfair, it was working with firefox 43 or less
Since v44 of firefox, that updated some core things in the browser, it stopped working, It wasn't the TG fault, their side isn't updated since 2014.

**Comment by Quicksaver** [comment]
#1.
