### ISSUE TITLE
Crazy flashing tooltips in prefs tab

### ISSUE THREAD

**Issue by DNied** [Quicksaver/Tab-Groups#313]
I had written a long and detailed bug report. GitHub server error -> Back button -> Lost ALL MY FUCKING TEXT.

Linux + Xorg + Firefox ESR 45.1.1. Fuck this, I'm not rewriting it.

**Comment by Quicksaver** [comment]
Well, what's the issue? The tooltips appear when you mouse over a specific option. Is that not happening?

**Comment by DNied** [comment]
Linux/x86_64 + Xorg 1.18.3 + Firefox ESR 45.1.1:

When hovering on checkbox options in Tab-Groups' preferences tab: fast-flashing, CPU-
hogging tooltips appear, often in the wrong place and incompletely rendered.

This was tested and confirmed on 2 different window managers: mwm and ratpoison. With
 the latter, the mouse pointer also gets thrown to some random place.

Issue observed in Tab-Groups 2.0.1 and 2. There, I rewrote it.

Thanks,
DN


P.S.: This site doesn't deserve your work.  This site only deserves insults.

**Comment by Quicksaver** [comment]
I'll check it out, thanks for letting me know. It's possible the tooltips are having trouble on Linux systems.

> P.S.: This site doesn't deserve your work. This site only deserves insults.

That doesn't usually happen at all. Small temporary glitches can happen on any website. ;)

**Comment by Quicksaver** [comment]
First of all, I'm sorry I took so long to get to this.

I must admit I don't see any flashing issues like those, although I've only really tried on Ubuntu 16 which is what I have available. Could you please try [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and see if you still have that issue? If you do, please try making a screencast of it.

**Comment by Quicksaver** [comment]
Please re-open if this still happens with the latest version 2.1 and with the latest version of Firefox as well.
