### ISSUE TITLE
Feat Request: gesture to display tab group view

### ISSUE THREAD

**Issue by klint** [Quicksaver/Tab-Groups#314]
Hi
This is already achievable with existing addons (firegesture+tab-groups), but could be a plus if integrated with Tab-Groups.
I'm using a "Swipe Down+Right click" mouse combination to display the tab groups view (panorama). Quite handy indeed :)
Just a suggestion to make this excellent addon even better...
Thanks

**Comment by Quicksaver** [comment]
This likely won't happen. It would require creating a whole system for defining gestures (which would probably conflict with other similar add-ons like that), so it's just not worth since you can do the same by using FireGestures.

**Comment by klint** [comment]
Hi
Yes, I perfectly understand :)
Yet it could maybe be useful to share this in the "how to use" section of
the addon. The gesture is really a handy one (I actually use only 2
gestures, but very often : left to go back to the previous page, and down
to display panorama) and even users of addons like FireGesture may not be
aware that they can write a simple script there to display the panorama
view *( TabView.toggle();* )
Cheers
Olivier



2016-06-09 10:42 GMT+02:00 Luís Miguel <notifications@github.com>:

**Comment by Quicksaver** [comment]
I think FireGestures already has/shows a note about this. I'll double-check though.
