### ISSUE TITLE
Tab Group does not start in OSX El Capitan

### ISSUE THREAD

**Issue by BarthoD** [Quicksaver/Tab-Groups#317]
Using FF 45.2.0 esr on a brand new Mac. Using FF for ages (with Groups) coming from Windows.
OSX El Capitan 10.11.5

Anyone using it with success .... ?/ I am desperate ... :-(

Thanks, 
bartho

**Comment by Quicksaver** [comment]
Can you check if this is the same as #239 (problem with CCK2)?

What exactly do you mean it won't start? Can you see the toolbar button in the toolbar? Can you use the keyboard shortcut (Ctrl+Shift+E)?

**Comment by BarthoD** [comment]
Yes, that was exatly the problem. The IBM CCK internal Add-on as described by  gerhardh63 . 
Thanks mate!
