### ISSUE TITLE
Disable live update on thumbnails with many tabs

### ISSUE THREAD

**Issue by macmladen** [Quicksaver/Tab-Groups#319]
It may be a good idea to disable refreshing thumbnail preview when there is a high load from pages, big number of tabs, lot of JS moving animating things.

I propose:
* Checkbox to disable live update of thumbnails completely
* Number of tabs after live preview is automatically disabled (40 by default, lets say).

**Comment by Quicksaver** [comment]
Thumbnails are already updated one at a time, most of that work is done off main-thread, and asynchronous for the most part. So it should not sacrifice any responsiveness at all.

What would you expect to gain from this?

**Comment by macmladen** [comment]
You are quite fast in reply!

I asked because I have like 20 thumbnails in one windows and 150 in another on iMac with i5 and 16GB of memory and I noticed that live update was so slowing Firefox that Tab Groups UI was blinking all the time.

**Comment by Quicksaver** [comment]
What exactly do you mean by blinking? When thumbnails update, sometimes you may see them update visually, but that's about it.
