### ISSUE TITLE
Pinned tabs not showing up in panorama on first use after upgrading to 1.0.1

### ISSUE THREAD

**Issue by kidwm** [Quicksaver/Tab-Groups#32]
Although it show show up again after restart Firefox.

**Comment by Quicksaver** [comment]
I wonder if something's not (de)initializing properly. I'll be sure to check it out so it doesn't happen again on the next update.

**Comment by Quicksaver** [comment]
Did this happen on the latest update to 1.0.2?

**Comment by kidwm** [comment]
@Quicksaver Oops, I didn't check this after auto updating finished.

So I reinstalled 1.0.1 in aurora (45.0a2) and manual updated again, and it did not happen this time.

**Comment by kidwm** [comment]
I did a fresh new 1.0.2 installation on Firefox 44 and it happened again.

**Comment by Quicksaver** [comment]
This is actually hard to reproduce (I still wasn't able to so far). But looking through the code for a completely unrelated matter I ran across a mistake that **could** have caused this.

I'll keep this open to remind me (and you) to confirm if this still happens in next version I upload (might take a few weeks though).

**Comment by Quicksaver** [comment]
Can you try installing [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1) over your existing version and see if this happens?

**Comment by kidwm** [comment]
Looks good to me.
![2016-03-23 12-50-41](https://cloud.githubusercontent.com/assets/822446/13975976/1e053780-f089-11e5-832a-fef5a6453944.png)
