### ISSUE TITLE
first group automatically named "Group 2"

### ISSUE THREAD

**Issue by ces42** [Quicksaver/Tab-Groups#321]
The default Group in which my tabs are in is named "Group 2". If I open another groups its default name is "Group 3". Am I missing something or shouldn't the first group be called "Group 1" or "Group 0"?
This issue has existed since the 2.0 update.

I'm using FF 47.0 on Ubuntu 16.04 and some of my Add-ons are
* Better Reader
* Beyond Australis
* Dom Inspector
* FindBar Tweak
* Ghostery
* Greasemonkey
* NoScript
* TabMixPlus

**Comment by Quicksaver** [comment]
It may be incorrectly starting with 2 rather than 1. I'll check it out, thanks for letting me know.

**Comment by leggewie** [comment]
confirming

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) fixes this issue. Note that in existing windows, the group ids will be left unchanged to avoid any trouble in keeping their tabs data in sync and such. So the fix only really affects new windows. Please give it a try and let me know how it works for you.

**Comment by ces42** [comment]
Works for me now

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.
