### ISSUE TITLE
Can only toggle between two groups in Single View

### ISSUE THREAD

**Issue by Noexpert** [Quicksaver/Tab-Groups#323]
The issue is as described in the title.

Despite which group I'm in, once I navigate to the top row then it jumps to Group X. After that it will only toggle between that and Group Y. So Group X to Y and nothing else.

I have disabled all addons but the problem persists.
Thanks

**Comment by Quicksaver** [comment]
That's very weird. Are the groups still accessible in other modes (grid layout and free arrange)?

**Comment by Noexpert** [comment]
Hi,

in Grid Display it seems to be fine.

In Free Arrange the cursor (using the keyboard) gets stuck between A and B groups when they are next two each other, i.e. the selected group goes from left to right and back again but will not move to the other groups.

Hope this makes sense.

**Comment by Noexpert** [comment]
Duplicate of #356

**Comment by Noexpert** [comment]
Apologies if I were not entirely clear: this issue (#323) too relates to the arrow keys.

**Comment by Quicksaver** [comment]
Ah, I misunderstood you then, I believed you were speaking about the keyboard shortcuts. I'll mark this one as a duplicate then, as #356 has more information.
