### ISSUE TITLE
The Tab Group 2 eats tab addresses "under custody" of the Tile Tabs

### ISSUE THREAD

**Issue by P2O2** [Quicksaver/Tab-Groups#326]
The title above sets the issue. E.g. open 2 tabs, join them with Tile Tabs, close Firefox (Debian GNU/Linux) then open Firefox. The second tab will be empty. You may check other multi-tab layouts. Always one or few hyperlinks are erased. Perhaps it is the Tile Tabs idiosyncrasy but the issue was opened _after_ auto upgrade to Tab Group 2. I was able to recreate the same "bad manner" with Firefox for Windows 7. It emerges as well within all Firefox latest releases - Firefox 47.x beta and 48.1 beta.

Regards

**Comment by Quicksaver** [comment]
It's possible there's some incompatibility with Tile Tabs, I'll have to check it out. Thanks for letting me know.

**Comment by P2O2** [comment]
Ooops, bad news for me.
BTW. Thanks for your prompt reaction. I've changed Debian Jessie to Debian Stretch in last few days. Back to the point.

I'm always saving few Firefox generations (I got 45,46,47 and 48 at present), so I took your 1.0.2 xpi file and copied it to the new installed virgin Firefox 48 beta 1 build 2 and then I did quickly turn off auto update (I disconnected rig from home LAN for sure as well). To my surprise I've found today a lost tab again in TT 13.9 + TG 1.0.2 "combo". :(

Perhaps the malicious culprit is not TG2 but the Tile Tabs? Damn it. I'll check the issue with the previous TT versions 13.5 (in Firefox 45 archive) and 13.7 (from FF 46 archive). FF 47 and 48 contain in my archives Tile Tabs 13.9 (latest).

Anyway TT 13.9 claims:
Version 13.9
•   Fixes the bug that locks up tab selection with Firefox 48.0 or later on Mac OS X

So expect few days delay for the results of the search as I will check the two add-ons together during my daily routine works.

Regards

**Comment by P2O2** [comment]
Quicksaver,
My way of checking I conjured up "in promptu" was naive and wrong. TT 13.9 MUST be installed, it fixed very serious bug as described above in my former mail.

So, I'm going back to the latest versions of all add-ons.

But let me point one thing.
Why such simple issue, if not trivial, concerning saving tab hyperlinks is so complex as it leads to "erased tabs" issue? Why nobody is using text config files (TXT not XML/XUL!) as only text ones are easiest to edit, to keep their copies and to read them in the quickest and most reliable way during opening Firefox?

Regards

**Comment by Quicksaver** [comment]
You are seriously losing me here... I still haven't checked out TIle Tabs (I will soon), but if you can provide direct steps to reproduce I would appreciate it (I'm assuming from your later comments that what you wrote in the first comment is not fully valid).

> Why such simple issue, if not trivial, concerning saving tab hyperlinks is so complex task as it leads to "erased tabs" issue? Why nobody is using text config files (TXT not XML/XUL!) as only text ones are easiest to edit, to keep their copies and to read them in the quickest and most reliable way during opening Firefox?

What does this have to do with anything?

XML and XUL are also text files, with a structure. It's not as simple as keeping a list of open urls. There is a whole lot of information to be saved so that you can retain your session. That information so that it can be later read.

**Comment by P2O2** [comment]
I was gonna be helpful, I hope you read my intention correctly. :)
Most of my tiles may be divided into two camps - "constant" tile/tabs mainly with weather maps and other layouts created ad hoc, with commodities published on Internet shops' pages for example.

As my rig works 24/7, I close Firefox rarely but I had to do it from time to time. Only then, if I'm right, the tabs vanish. It may be happening during changes between tab groups as well but I must to check it to be sure.

Perhaps my bug report was not 100% valid but the issue occurred _after_ TG was updated to v. 2.0.1.

As you see I tried to help but it appears the latest versions of the xpi files are essential. So it's obvious now that any cross checking should be done by the authors only, as they are the only ones having enough knowledge of the add-ons.

Quote - "What does this have to do with anything?"

Frankly writing the tabs are not destroyed but erased, they are still in the Tile Tabs' layouts/structures but empty. Such behavior means the page address(es) was/were erased. That part of code IS simple - no matter what type of file you create for the task (storing the data, SQL is good too, etc.) - the structure and acting on them and around them is more compound only.

Knowing where the data are stores right away aka creating txt files for the data, it'd be easier to check what was going on with them as their corresponding pages went astray.

But of course, you are the boss! :)

Have a nice day.
Regards

Example:
http://tiny.pl/grsv9
http://tiny.pl/grsvw

**Comment by P2O2** [comment]
You asked for "provide direct steps to reproduce" the bug. Here it is (one of them).

http://tiny.pl/gr69g
http://tiny.pl/gr69t
http://tiny.pl/gr697
http://tiny.pl/gr69r
http://tiny.pl/gr699

1) Create 4(!) tabs:
a) a map (img)
b) empty tab
c) a map (img)
d) a map (img)
Open 1 tab, open Create New Layout -> 4 Tabs - Horizontal Grid
Then go to the second (2) e.g. empty tab and in context menu invoke Untie Tab to remove the empty tab from the layout. That way 1 map (top, left img) was spread on two columns in the first row, see the first screenshot (http://tiny.pl/gr69g).

2) Open second window, I did and moved it to the second monitor (I have desktop covering 2 different monitors).
Repeat the same steps, but with only two images. Use "2 Tabs - Vertical" option. See the second screenshot (http://tiny.pl/gr69t).

Close Firefox now.
BTW. I've changed Tab Gropus several times prier to the FF closing and I got nothing wrong. The Tile Tabs' layouts were kept.

Open Firefox. The results.
1) 4 grid lost 3 images (http://tiny.pl/gr697)
2) "2 Tabs - Vertical" grid was lost. In other words the Tile Tabs' layout was removed, I got two untied tabs.
The 5th screenshot (http://tiny.pl/gr699) shows what happened to the first screen.

Apart from Debian 9.0 aka Stretch I use Nvidia GT520 video card and original Nvidia driver - processed and supported by Debian DEB team (installed via Aptitude).

Those two add-ons - Tile Tabs and Tab Groups - are the most heavily used here. Both were used for translation works, among others.

Regards

**Comment by Quicksaver** [comment]
First of all, I'm sorry I took so long to get to this.

I'm afraid I haven't been able to reproduce this at all, although Tile Tabs has been updated a few times since. Could you please make sure you have the most recent version, and also try it with [Tab Groups beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and let me know if you still have this issue?

**Comment by Quicksaver** [comment]
Please re-open if you still have any of these issues with the latest version 2.1.
