### ISSUE TITLE
Links to http://fasezero.com/ return an "Unable to connect" error in Firefox

### ISSUE THREAD

**Issue by RBLevin** [Quicksaver/Tab-Groups#327]
Links to http://fasezero.com/ return an "Unable to connect" error in Firefox. They work in other browsers. The "donate" and other options are on http://fasezero.com/ and so users cannot connect.

**Comment by Quicksaver** [comment]
Just replied to your e-mail.
> I just checked and it seems to load fine for me? Could you try again, please? It's possible there was a temporary outage at the time you tried.
>
> If it still doesn't work, could you be behind some kind of firewall preventing the connection? Even a security/privacy type Firefox add-on could cause this if configured to not allow http (no "s") connections.

**Comment by leggewie** [comment]
works fine here now
