### ISSUE TITLE
Make current/highlighted tab group more obvious in Grid Display

### ISSUE THREAD

**Issue by kidwm** [Quicksaver/Tab-Groups#33]
Current group should apply different style.

**Comment by Quicksaver** [comment]
It does, notice the shadows. But you're right that it should be more obvious.

**Comment by MailYouLater** [comment]
The title of this issue should be changed to something like "Make current/highlighted tab group more obvious".

**Comment by Quicksaver** [comment]
A midst a ton of changes, [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1) kind of revamps the whole interface, including making the current tab (and thus the current group) more prominent. Please try it out and let me know what you think or if you find any problems with it.

**Comment by kidwm** [comment]
@Quicksaver Looks good for the current tab but are not thus the current group in my case.
![2016-03-23 12-55-34](https://cloud.githubusercontent.com/assets/822446/13976054/f17ed31e-f089-11e5-88a2-5cb3cf80a337.png)

The current group looks no different with the adding group area.

**Comment by Quicksaver** [comment]
The current tab is always in the active group; i.e. you know the group "TEST" is the active group because it has the current tab. But in your case I can see how it is more subtle than it should be, because of your dark theme. Is that a theme or a userstyle you're using?

**Comment by kidwm** [comment]
@Quicksaver It is dark variant theme of GTK3 on Linux Platform.
FYI: http://worldofgnome.org/running-gtk-applications-different-themes-per-app/

> The current tab is always in the active group;
That's the problem. It is hard to find the grid which has current active group in GRID DISPLAY mode.
If I could find the active group grid sooner, the sooner I can find the current tab, isn't it?

**Comment by Quicksaver** [comment]
> That's the problem. It is hard to find the grid which has current active group in GRID DISPLAY mode.
If I could find the active group grid sooner, the sooner I can find the current tab, isn't it?

True. But I didn't want to simply change the background color of the active group for instance (this would be harder with different themes, plus it would conflict with something else I'm working on: organize groups by choosing a different color for each).

I think fading the other groups is a bit out of the question as well, as then it will be even harder finding other tabs in them. Do you have any suggestions on this? I'm completely open to ideas. :)

**Comment by kidwm** [comment]
> I think fading the other groups is a bit out of the question as well, as then it will be even harder finding other tabs in them. Do you have any suggestions on this? I'm completely open to ideas. :)

How about ordering group grid dynamically? Make current group be always at the most top-left grid.

Or just make current group grid bigger than other?

**Comment by kidwm** [comment]
> True. But I didn't want to simply change the background color of the active group for instance (this would be harder with different themes, plus it would conflict with something else I'm working on: organize groups by choosing a different color for each).

BTW, the color label could apply on group title bar instead of the whole group background.

**Comment by Quicksaver** [comment]
> How about ordering group grid dynamically? Make current group be always at the most top-left grid.

That would constantly disorganize your groups, you would never know where things are (because they would keep moving around), it would bring more harm than good.

> Or just make current group grid bigger than other?

To be honest, that's so complex I don't even want to begin to figure out a way to do that. Plus on slower machines, it would take a very heavy toll, having to constantly shift things around.

> BTW, the color label could apply on group title bar instead of the whole group background.

In theory, not a bad idea. But it could defeat the point of color coding groups. We'll see.

**Comment by kidwm** [comment]
> In theory, not a bad idea. But it could defeat the point of color coding groups. We'll see.
Then how about adding some highlight enhancement on title bar of current group?

BTW, could you also add proper indent to text of group title and make it align with the boundary of tab thumbnail image?

**Comment by Quicksaver** [comment]
I only tweaked a little the colors for [Beta version 2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2). I still plan on making further enhancements, but I thought I'd ask if you think that makes some difference for you at least.

**Comment by MailYouLater** [comment]
:confused: I don't know if this is actually any help or not, but I would recommend adding the same kind of lighter shading you have on the active tab, but at about half (or less) the opacity, so the difference between active group & inactive group is similar to the difference between active tab, and inactive tab within the active group. :smirk:

**Comment by Quicksaver** [comment]
I've added a border to the active group in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6). It should be noticeable enough to find it quickly if you're looking for it, but subtle enough that it shouldn't be distracting either. Please give it a try and let me know if you have any problems with it.

Also, I assume from your screenshots that you're using FT DeepDark, I also added some styling to help with compatibility with that theme. If however you're using a custom style to apply that look, it will probably still need to be adjusted.

**Comment by kidwm** [comment]
@Quicksaver It is so sad that it did not look noticeable in my case.

And this is default dark theme of GTK3 version on Linux platform, not FT DeepDark.
![2016-05-13 23-14-41](https://cloud.githubusercontent.com/assets/822446/15252442/8a4e362a-18f3-11e6-8e72-9d29d65e6501.png)

**Comment by Quicksaver** [comment]
Ah right, you said that already, I missed that comment, I'm so sorry about that.

I wonder if it's possible to activate FT DeepDark's styling in your case. It would definitely look better.

**Comment by kidwm** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1158076

Maybe we can ask Firefox to offer an API for detecting GTK3 dark theme.

**Comment by Quicksaver** [comment]
In [beta version 2b7](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b7) the interface should be styled with FT DeepDark's theme tweaks on dark OS themes (and others) as well. Can you please try it out and confirm that it works?

I would love to make it look more native of course, but I don't have a linux machine to test things on right now. So unfortunately this will have to do for now, until I can create a look that adapts properly to each theme's unique settings.

**Comment by kidwm** [comment]
Thank you! it looks better now.
![tabgroup](https://cloud.githubusercontent.com/assets/822446/15274811/67b9d7f6-1a81-11e6-9085-f2885d1371c6.png)

**Comment by Quicksaver** [comment]
I'll assume that screenshot was just a bit of bad luck because github's favicon is black, so it won't show on a black background like that. I hope other favicons are appearing as usual, please let me know if they aren't. :)

**Comment by kidwm** [comment]
@Quicksaver yes, other favicons are appearing as usual.
