### ISSUE TITLE
Option to get back the old groups button

### ISSUE THREAD

**Issue by iahvector** [Quicksaver/Tab-Groups#330]
The new changes are awesome, but I really hate having to do 2 click to get to the "Manage my groups view". It'd be really appreciated if there's an option to switch the add-on button to the old style with out the groups list.

**Comment by Quicksaver** [comment]
As explained in the release notes, you can disable the "Click to show the quick access panel" option in the add-on's preferences, so that clicking the button takes you directly to groups view.

**Comment by iahvector** [comment]
Found it. I must have missed it. Sorry :D
