### ISSUE TITLE
All tab groups suddenly empty

### ISSUE THREAD

**Issue by maanemann** [Quicksaver/Tab-Groups#331]
I just opened the tab group overview to switch to another one (obviously), and was horrified to find all my groups visible, but empty. All my tabs in the current group are still there, but the group is displayed as empty as well as all the others.

If I click another group the same thing happens, as when I click the current one: It opens a new tab in the current one, except the group name in the tool bar changes to the one I clicked. It doesn't open a blank window, just a new tab in the current window. Same thing if I double click to make a new group, the name changes to "group 9", but it's still the same window.

So all my tabs in the other existing tab groups are lost, and I can't use the plug-in for anything.

I'm running FF 47.0 on MacOS 10.11.3. These are the other plug-ins, I got installed and activated:
AudioMonitor,
BarTab Plus,
DownThemAll!,
Lazarus,
Multiple Tab Handler,
New Tab Override (doesn't work),
raindropio (doesn't work),
ratings-preview-for-youtube,
Seach by Image for Google,
Session Manager,
Tree Style Tab,
uBlock

Hope someone can help me, or the bug gets squished.

**Comment by Quicksaver** [comment]
It's likely your session was corrupted somehow, possibly from a crash during the last shutdown. Did this happen?

Since you sue Session Manager, you should be able to restore to one of its backups easily.

On alternative, go to the Tab Groups preferences - Backup & Restore and try to find a recent backup of your session there.

**Comment by maanemann** [comment]
Okay, I fixed it. Wanna know what I did? Restarted the browser. I know I should have tried this before posting, but it usually takes ages for Firefox to restart, I have to wait for unresponsive scripts, and sometimes something doesn't work as it should after the restart.

This time however, it opened pretty fast without any script crashes, and it fixed Tab Groups as well as the two mentioned recently broken plug-ins. I hope that's the new standard.

But Quicksaver, thanks a lot for the very quick and helpful response (that didn't help much, but had potentials to do so, if I hadn't helped myself)!! Do you have that name, because you save people like me so quickly as you do? :)

**Comment by Quicksaver** [comment]
Actually the name comes from a funny school story from a long time ago, but I have to admit it's nice that you think that. :)

I'm glad it all worked out in the end. Please let me know if it starts happening frequently again.
