### ISSUE TITLE
Sort groups in quick access panel

### ISSUE THREAD

**Issue by jurgenhaas** [Quicksaver/Tab-Groups#334]
Would be great if the groups could be sorted alphabetically in the quick access panel.

**Comment by leggewie** [comment]
There's actually at least three ways to sort
- order of tab groups in single view (this is what it currently is)
- order alphabetically
- order by number of open tabs

and possibly "order by last accessed time"

**Comment by Quicksaver** [comment]
See #261.

**Comment by leggewie** [comment]
This is not #261 

Why is this closed (as wontfix, I suppose)?  Being able to slice and dice your data and providing different views to it is quite important, I think.

**Comment by Quicksaver** [comment]
Yes, I'm not planning to add any extra ways to sort groups any time soon. It is only adding complexity to the panel. I'd rather focus on adding actual tab and group management capabilities, which includes being able to drag the groups in there into the order you want.

**Comment by bitseeker** [comment]
I think, that being able to sort the quick access list alphabetically would be a huge benefit for the addon. I just imported 41 tabgroups with over 600 tabs all together from another addon called "Tabgroups Menu" but got messed up a little bit. So getting a quick alphab sorting would be great in near future.
