### ISSUE TITLE
Show total tab count

### ISSUE THREAD

**Issue by Aralun** [Quicksaver/Tab-Groups#336]
What do you think about showing the total tab count, for example in the group view document title?

This would somewhat match the `Show number of tabs next to group title` option.

**Comment by Quicksaver** [comment]
What do you mean document title?

**Comment by Aralun** [comment]
The top bar:

![Screenshot with marvellous free-hand red circle](https://i.imgur.com/7Q8LZcT.png)

Now that I think about it, it might be an issue for full-screen users.

**Comment by Quicksaver** [comment]
And you won't really get any more info than you already have. It would probably only be marginally useful in single view even. I don't think it brings enough benefit to do it.

**Comment by arigayas** [comment]
I was going to a proposal that was similar.
![totaltabcounts](https://cloud.githubusercontent.com/assets/11251874/16138946/936d6c08-347d-11e6-8998-aef1fb85dde9.png)

I will comment as a memo.
