### ISSUE TITLE
Increase group title area

### ISSUE THREAD

**Issue by maliayas** [Quicksaver/Tab-Groups#337]
I prefer to use small group boxes (because there are many of them). This causes to this:

![current](https://cloud.githubusercontent.com/assets/844008/16118789/54f609a4-33e1-11e6-8cad-41e4180bdfbb.png)

Is something like this possible for larger title space?

![proposed](https://cloud.githubusercontent.com/assets/844008/16118791/5907f05c-33e1-11e6-8c8d-07124e9dfec9.png)

**Comment by Quicksaver** [comment]
I'm actually already planning to reimplement the way the number of tabs is shown, so this won't really be a problem in the future (and that would only work with stacked groups, I don't think differentiating those so much in this way would be a good idea).
