### ISSUE TITLE
cut name in pop-up

### ISSUE THREAD

**Issue by zetok** [Quicksaver/Tab-Groups#338]
Probably due to zoom, or something, dunno. FF 45.2 ESR

![cut name](https://cloud.githubusercontent.com/assets/3148759/16128906/745e9eb4-33fa-11e6-8c1d-4127ee297dab.png)

**Comment by Quicksaver** [comment]
That's weird. But it doesn't really matter, I'm likely removing that message in the next version since almost everyone has definitely seen it already.

**Comment by zetok** [comment]
I just got it again – you might want to reopen, or release newer version sooner..?
![cut again](https://cloud.githubusercontent.com/assets/3148759/16357726/8873d3c6-3af6-11e6-8119-bec2de6ef06a.png)

**Comment by Quicksaver** [comment]
You're not supposed to get that any more than once. At all. Did you create a new profile or something similar?

**Comment by zetok** [comment]
I use >10 FF profiles, and usually I run simultaneously 3-4 of them.

Mostly because a single FF instance can't handle the amount of pages well. E.g. the GH one uses ~3-4 GB of ram, and becomes rather unresponsive when its ram usage grows even more. Additionally FF's interface has a tendency to break, and the only way to "fix" it is restart – all that causes me to run separate stuff in separate instances, to get minimum of stability, and when one starts to misbehave, other stuff isn't affected.

As for your question, it might have happened on a different profile, I don't really remember on which one I had first pop-up.

Don't worry though, I'll make sure to report every instance of bug in pop-ups happening ;)

Btw, thanks for the awesome improvements to Tab Groups, the search functionality & layouts are really great :)

**Comment by zetok** [comment]
It was displayed again, and I'm >90% sure that it happened on ff profile that already displayed this earlier.

As for cut letter, I've noticed that for like half of a second it was displayed correctly, and then for some reason part of it disappeared.
