### ISSUE TITLE
Can't see the text on the groups options window

### ISSUE THREAD

**Issue by 15bart15** [Quicksaver/Tab-Groups#339]
Background color of the groups options window is white. I use a dark theme and font color is white too.
So white on white.... I can't read. If I choose a theme with black font it's ok.

![capture](https://cloud.githubusercontent.com/assets/17881601/16133292/4db159ec-3417-11e6-9613-89b2bdce60de.png)

What I don't understand is why the background don't care of the system color?
Is this a limitation of firefox?

Thanks for your support

**Comment by Quicksaver** [comment]
See #250
