### ISSUE TITLE
Group for pinned tabs

### ISSUE THREAD

**Issue by kidwm** [Quicksaver/Tab-Groups#34]
Currently in panorama, all groups show pinned tabs, but it is not possible to pin tab in or do any other action.
Maybe introducing a special pinned tabs group would solve this problem and remove visual clutter of duplicate pinned tabs in every groups.

**Comment by Quicksaver** [comment]
It is one of the things I was already planning. :)

**Comment by tengwar** [comment]
Personally I use the fact that pinned tabs are shown on every group to switch to a different tab group without loading any of its tabs. It's useful for groups that have too many tabs to be displayed normally. I also use this fact to combine switching the tab group with switching to the pinned tab into one operation.

Considering how important this addon is, I suggest user consultations for bigger changes to avoid possible unnecessary drama. ;)

**Comment by Quicksaver** [comment]
I don't really understand what you are gaining there, if you are switching tab groups then you likely want to open one of its tabs there, so you might as well load it directly, no?

Either way, this won't be done "alone", it's part of a larger plan to make it easier to manage a large number of tabs in a single group.

**Comment by NiklasGollenstede** [comment]
For those who are interested in a temporary fix:
I have written a user style that (besides turning the tabview page Developer-Edition-like darkisch) displays the pinned tabs once on the left side of the page.
https://userstyles.org/styles/118781/tabview-dark

Unfortunately it is not possible to insert a margin/padding because the reflowing of the tab tiles is done entirely with JavaScript, not CSS. Therefore the tabgroups have to be moved a bit to the right by hand.

**Comment by MailYouLater** [comment]
+1:+1:

**Comment by Speravir** [comment]
Maybe I do not understand correctly what the OP wants to have, but I’m interested in group specific pinned tabs. I could live with doubled tabs, if for whatever reasons I’d need the same in two or more groups (did never happen here until now).

_By the way: The current behaviour is inherited from Firefox code I think, and I wouldn’t be astonished, if there would be an old bug message on Bugzilla regarding this._

**Comment by MailYouLater** [comment]
@Speravir What you're talking about is almost exactly the opposite of what this issue is about.

Current behavior is for all Tab Groups to include all Pinned Tabs, thus this issue asks that rather than showing all the Pinned Tabs on every Tab Group, there be a visually separate group for Pinned Tabs, which would show all Pinned Tabs, and the Pinned Tabs then get removed from the visual representation of each group.

**Comment by MailYouLater** [comment]
This isn't asking that the behavior be changed (all Pinned Tabs would still be present in all Tab Groups), but rather the UI (the Pinned Tabs only get shown in one place, instead of showing them on every Tab Group).

**Comment by Quicksaver** [comment]
> I’m interested in group specific pinned tabs.

In addition to what was already said on this point, this is just not possible either, that's just not how pinned tabs work in Firefox and it would far too much effort to implement something like this in this add-on.

**Comment by Speravir** [comment]
OK, thanks MailYouLater and QuickSaver for information.

I think I could live with the suggestion as second best solution then, if any. I’d had to anyway. ;-)

**Comment by kidwm** [comment]
@Quicksaver 2b1 did good job! but still need to be able to rearranging tabs.

I suggest put pinned group in a horizontal area and make it on the top-left position would be more intuitive.

**Comment by Quicksaver** [comment]
> BTW, maybe make it appear larger could also help solve #33 for the pinned tabs group.

> Currently, it is no any visual clue when current tab is a pinned tab.

For now I just added the same kind of background highlight other tabs have. I will definitely make the pinned tabs buttons larger, but I'll leave that for when I work in #50.

**Comment by tengwar** [comment]
I'm curious how it's going to look like. Can anyone post a screenshot? :)

**Comment by Quicksaver** [comment]
There's already a few screenshots of the pinned tabs "group" on the right at #13. I should upload a new beta here with that whole functionality finished within the next few days. ;)

**Comment by Quicksaver** [comment]
Unless I missed something, the new pinned tabs area should now be fully functional. Please try [beta version 2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b2) and let me know if you find any issues with it.

**Comment by Quicksaver** [comment]
However you prefer. ;)
