### ISSUE TITLE
Sugerence: Include an option to make the thumbnails visible by default

### ISSUE THREAD

**Issue by Zeioth** [Quicksaver/Tab-Groups#340]
Just like the previous versions please. I dont care about groups and stuff. Some people just want tab thumbnails. Thank you.

**Comment by Quicksaver** [comment]
As explained in the release notes, you can set it to go directly to the groups view when you click the toolbar button, by going into the add-on's preferences and disable "Click to open the quick access panel". Please re-open if that's not what you meant.

**Comment by Zeioth** [comment]
You are right, sorry for the silly issue. Thank you Quicksaver!
