### ISSUE TITLE
Can we have search results shown from other windows

### ISSUE THREAD

**Issue by lc99sj** [Quicksaver/Tab-Groups#341]
Hi Luis, Tab Groups is looking fantastic.  I used the predecessor tab groups / panorama extensions for about 3 years, and one feature that is a huge time saver for me is that when I perform a quick search for a tab, all results would be shown from *other* windows.  In other words, I have Tab Groups active for this window, but the actual target of my quick search is located in a different, minimized window.  In the past, I would be shown that search result ("results from other windows").  But lately, I am not seeing it function this way when I use Tab Groups version *2*.  Can the search function be enhanced along the line that I am asking, or is the function still there and perhaps there is a preference that could re-enable that behavior?  Thanks ... Larry

**Comment by Quicksaver** [comment]
See #275.
