### ISSUE TITLE
raise window event on final closing of tab group

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#342]
I'm carving out this one issue from #310 as this is not an RFE but a genuine and pretty annoying bug.  It seems there is a "raise window" trigger when the "Undo Close Group" is expiring.  I don't see any reason why this should happen.  It certainly is surprising and jumps in my face at the most inopportune moments.

Thanks again for an awesome extension.

**Comment by Quicksaver** [comment]
What do you mean by "raise window"?

**Comment by leggewie** [comment]
You have two windows open.  You close one group in Window A and then go to Window B.  After a few seconds, the "Undo close group" option in Window A expires.  When that happens, Window A is raised to the front which of course will be irritating when you are working in Window B.  A becomes the active window.  I believe this is called a "raise window" trigger in desktop managers.  I use Ubuntu Unity as my DM.

**Comment by Quicksaver** [comment]
Ah yes that's not supposed to happen.

**Comment by Quicksaver** [comment]
I'm afraid I haven't been able to reproduce this at all.

Could you please try [beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and let me know if you still have this issue with it?

**Comment by Quicksaver** [comment]
Please re-open if you still have this issue with the latest version 2.1.
