### ISSUE TITLE
Global Tabgroups?

### ISSUE THREAD

**Issue by allo-** [Quicksaver/Tab-Groups#344]
Currently tab groups are associated to one window. This means for example, when you close your "main" window and keep using your second window, you lose all open background tabgroups.

Maybe tab groups should be global and a new window is just a new tab group? A tab group in an open window could be grayed out in the tab chooser of all others, but an background tabgroup can be selected in the group chooser of another (i.e. new) window.

The groups open in other windows could have options like:
- open group and close other window
- open group and open a new empty group in the other window

Together with an auto save, this could further make sure, that you do not unexpectedly lose your tab groups, no matter which windows you close.

**Comment by Quicksaver** [comment]
#174.
