### ISSUE TITLE
Move To Group is buggy

### ISSUE THREAD

**Issue by GrayFace** [Quicksaver/Tab-Groups#345]
When I use Move To Group on current tab, the group isn't switched and the tab appears in the same group. When I switch to other tabs and then switch back to the moved tab, it appears in proper group, but sometimes disappears when I switch to other tabs. I think this started with v2 betas, but I'm not sure.

I encountered the disappearance only once and under specific circumstances, right now. I first tried to move 2 tabs at the same time (using Multiple Tab Handler's menu. It wasn't able to list tab groups at all since Tab Groups became an extension, but now it did list them). It moved one of the tabs. Then I moved the other tab while it was still selected. Both tabs now only appear when I switch to them.

**Comment by Quicksaver** [comment]
So can you confirm this is specific to Multiple Tab Handler? As in, can you reproduce it if you disable that add-on?

**Comment by GrayFace** [comment]
The part not specific to Multiple Tab Handler: When I use Move To Group on current tab, the group isn't switched and the tab appears in the same group (as if it wasn't moved). When I switch to any other tab, the moved tab appears in proper group. So, it's a minor issue.
There's also an exception to this: When moving the last tab of the group, the "Manage groups" dialog appears, which is fine.

The problem specific to Multiple Tab Handler: tabs moved using it disappear. After reboot I saw the 2 disappearing tabs landed in 2 new groups ("Group 29" and "Group 30"). Before the reboot these groups didn't exist.

**Comment by jmain33** [comment]
I can corroborate all the MTH aspects of this issue {see >> #304 & https://github.com/piroor/multipletab/issues/118}.

As to moving the current tab, I don't believe it is supposed to switch groups, it just moves the tab to the desired group. If you want to view the moved tab you need to switch there yourself. I haven't experienced any difficulties moving a single tab under any circumstances though - *just the MTH conflict*.

**Comment by GrayFace** [comment]
You don't need to switch to moved tab, because you continue viewing it after you've moved it. It just shows in its previous group and that's counter-intuitive. It's true that it can be beneficial in some situations.

**Comment by GrayFace** [comment]
I can confirm now that this is a bug, as its implications are certainly unwanted. Due to the tab staying in the old group until deactivated you get the following:
- When you navigate within the tab, it gets moved to a different position within the old group. That position is supposedly the place where it should be in the new group.
- When you open links in new tab they are opened in the old group.

**Comment by Quicksaver** [comment]
I admit I have never been able to reproduce this exact bug, although I have fixed some similar bugs.

[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) fixes the incompatibility with MTH, and also has those small fixes for when moving tabs between groups. Please give it a try and re-open this if you still have any issues with it.

**Comment by davidmach14** [comment]
Currently I cannot move more than 1 selected tabs to another group than "New Group". None of existing groups has been offered in menu. I'm using beta version 2.1b6 and 2.1b4.

**Comment by Quicksaver** [comment]
That's #304, read my last comment there.

**Comment by Quicksaver** [comment]
Please re-open if you still have any of these issues with the latest version 2.1.
