### ISSUE TITLE
order of tab placement when moving to different group seems to be erratic

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#346]
When I move a tab in single view to a different group I would expect the tab be added as the last tab in that group.  It seems the position of insertion is random, though, mostly towards the first few tabs in that group.  Is Tab Group 2.0 trying to position it according to position in the "group screenshot" up top?  That wouldn't be a good idea IMHO.  I'm trying to avoid this issue altogether by dropping the tab on the title of the new group but the tab still doesn't end up at the end.

**Comment by Quicksaver** [comment]
The tab will be dropped in the "last" place where you dragged it in the group. This should be shown by the other tabs in the group being moved ahead, creating an empty space where the tab will be dropped; this happens even if you only hover one of those tabs by a single pixel, it will remember it as the "last" placed where it was dragged.

When there is no such "last" place, for instance when you drag out of the group and then back in, or drag directly onto the group's title without going through its tabs, it will be appended last.

Is this not happening?

**Comment by leggewie** [comment]
Thank you for the reply.

But I'm not dragging it in the group, unless I misunderstand what you refer to with that. The tab bar shows the different groups in single view.  The lower 80% of the screen show the tabs in the current group.  At no point in time will this show the tabs in the other groups so I don't see how they "should be shown by the other tabs in the group being moved ahead, creating an empty space where the tab will be dropped;".  I am now dragging one tab from the current group unto the group space holder on the top bar of another group and release the drag.  The tab is moved to the other group but its position within that group appears to be random.  I hope this clears it up.

**Comment by danielfmeier** [comment]
A workaround for this bug is to right-click the tab you want to move, hover over "Move to Group" until the tab groups list flyout emerges, move the cursor to the group you want to move the tab to, and left-click on that group. The tab will be appended to the end of the selected group. This can also be done from within a tab group, no need to be in the "Manage my groups" window. Problem solved, this bug becomes insignificant.

**Comment by danielfmeier** [comment]
A suggested fix for this bug would be to add the ability to move tabs within a tab group by dragging & dropping. This would make the behavior of tab groups to be to position the tab wherever it is when it is dropped, which would kill this bug.

**Comment by leggewie** [comment]
> Problem solved, this bug becomes insignificant.

For one tab? Maybe.  For a number of tabs, not insignificant at all.

**Comment by Quicksaver** [comment]
Forget my initial comment, I completely misread what you meant, I'm sorry about that.

This was fixed by https://github.com/Quicksaver/Tab-Groups/commit/1cd3444cde3bc2e4b880e7e6221b33ea7a593bba

> A suggested fix for this bug would be to add the ability to move tabs within a tab group by dragging & dropping.

If you mean within the quick access panel, that's #5.
