### ISSUE TITLE
TabGroups & MultipleTabHandler ??

### ISSUE THREAD

**Issue by whismerhill** [Quicksaver/Tab-Groups#348]
This is more a question than anything else
I have tabgroups 2.0.1 & Multiple Tab Handler Ver.0.8.2015113001 

it seems when trying to move multiple tabs at once the "moveto" grouplist is just empty. so it no longer works like it used to.
Is this only a problem on my side ? Is this expected ? Is it multiple tab handler which needs an update ?

Thanks.

**Comment by Quicksaver** [comment]
#304

**Comment by whismerhill** [comment]
ha really sorry I didn't see issue #304
