### ISSUE TITLE
Bogus "Your tabs and groups will not be restored the next time[...]" message

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#349]
Hi!

When using Session Manager I get this message. But it's false, SM saves the group data.

**Comment by Quicksaver** [comment]
What do you have defined in session manager to happen for when FIrefox starts? Load a session automatically, choose one, etc?

**Comment by mzso** [comment]
It's set to show the SM window to load a session.

**Comment by Quicksaver** [comment]
That's weird, it shouldn't show you that message then. I'll have to take a look.

**Comment by mzso** [comment]
This is still happening. (v2.0.1 FF47)

**Comment by Quicksaver** [comment]
Is this still happening? I can't reproduce it at all, if SM is set to prompt or to load automatically, I don't get a warning.

**Comment by Quicksaver** [comment]
Oh hold on, I'm seeing it, had to tweak it a little to get it to show.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should no longer show the warnings when it shouldn't. Please give it a try and let me know how it works for you.
