### ISSUE TITLE
FireGestures Support?

### ISSUE THREAD

**Issue by gowong** [Quicksaver/Tab-Groups#35]
This is a really awesome addon.

One thing that I'm missing is FireGestures' built-in support for toggling Tab Groups with a mouse gesture. Any ideas how to do this with this addon?

I suppose one could write a custom script for FireGestures that simulates pressing the Tab Groups keyboard shortcut, but was wondering if there's a better way to do it.

**Comment by Quicksaver** [comment]
You can ask FireGestures developers to call the add-on's command when the native one is disabled/removed; it should actually be very simple from their side. But of course, if they can't do it for some reason I'll look into adding this to the add-on itself somehow.

In the meantime a custom script will be your only choice, which should be very simple to create as well. :)

**Comment by gowong** [comment]
Cool, I used a custom script like this:
`gBrowser.ownerGlobal.tabGroups.TabView.toggle();`

**Comment by m0n** [comment]
Hi!

I like to toggle quickAccess panel by a FireGesture script. I tried `TabView.toggleQuickAccess();` but that won't work. No error is displayed in the statusbar, and I already set a keyboard shortcut in TabGroups preferences.

Thanks for Your help!
