### ISSUE TITLE
ctrl-shift-esc should cycle tab groups in reverse

### ISSUE THREAD

**Issue by jhuckelba** [Quicksaver/Tab-Groups#350]
This is how the original "out of the box" extension worked in Firefox before they removed it.  Would be nice to have it back.

**Comment by Quicksaver** [comment]
There was never such a shortcut in the original panorama. Furthermore, Ctrl+Shift+Esc conflicts with Windows (brings up Task Manager), and it could conflict with several other esc-related shortcuts in all systems. So this won't be happening, and I'm not sure how you could have been using that shortcut at all anyway.

**Comment by jhuckelba** [comment]
This is my mistake.  I'm going to blame it on not having finished my first cup of coffee this morning before logging this.  

I means to say ctrl-shift-~.  Shift being the modifier to reverse the order of the group switching that ctrl-~ normally executes.

I see that you've closed this issue already.  Let me know if it makes sense to open a separate one.

**Comment by Quicksaver** [comment]
That also wasn't the default shortcut by default in Firefox, are you sure you didn't customize it somehow using another add-on? Either way, can you not for some reason define that specific shortcut in the add-on's preferences? It should work, provided it's available (as in, that shortcut isn't already defined for something else).

**Comment by jhuckelba** [comment]
I will give customizing it a shot.  Thanks.  

I am fairly confident that it was a default, reason being is that I've been using firefox for years across several (no fewer than 10) machines and have _never_ used the shared account settings in the browser such that they would be available across different machines once they were customized.  If I find some time I'll see if I can get an older build to install and verify.

Thanks for the responses.

**Comment by jhuckelba** [comment]
http://lifehacker.com/5719596/switch-between-tab-groups-in-firefox-with-a-keyboard-shortcut

shift modifier to CTRL+` mentioned in the article.  This was in 2010.
