### ISSUE TITLE
Scroll bar disappear in about:tabgroups

### ISSUE THREAD

**Issue by foomin10** [Quicksaver/Tab-Groups#351]
I use Tab Groups 2.0.1 on

- Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:45.0) Gecko/20100101 Firefox/45.0
- Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

Full screen mode: Ok

![Imgur](http://i.imgur.com/NXvjcOj.png)

Not full screen mode: Disappeared scroll bar

![Imgur](http://i.imgur.com/0pAlU1Z.png)

**Comment by Quicksaver** [comment]
#263
