### ISSUE TITLE
CSS customization (scroll bar mainly)

### ISSUE THREAD

**Issue by DHammarberg** [Quicksaver/Tab-Groups#355]
I really love the new Tab-Groups plugin and I'm using it in groups view. But one thing I find a bit annoying is that it takes a bit of accuracy to hit the scroll bar. I would like to be able to make it at least twice as wide for it to be more convenient using it, but when I try manually editing the CSS file inside the package, it drops the plugin upon starting Firefox. I assume that's some checksum used for plugin validation, I really don't know much about FF development. This means I can't fix it myself though.

What I would like is the ability to customize the UI CSS and have it stored permanently. That would help my need and probably other people's as well. Here's how my scroll bar looks the way it is now:

![My screenshot][screenshot]
[screenshot]: http://dl.dropboxusercontent.com/u/15060859/2016-06-27_16-32-39.jpg "My screenshot"

**Comment by Quicksaver** [comment]
Yeah, changing any file inside the add-on will invalidate its signature, and Firefox will disable it. You could use [Stylish](https://addons.mozilla.org/firefox/addon/stylish/) for that, basically just copy those changes you made into a new userstyle there and it should apply them over the originals in the add-on.

Let me know if you need any extra help with this.

**Comment by DHammarberg** [comment]
Thanks for info. I've been playing around a little with Stylish and have managed to change certain things, like the background colour of a tab thumbnail - but I've not been able to find the selector and stuff to access the scroll bar. There are a number of such CSS classes inside the addon, but it doesn't seem changing any of them has any effect on the bar in question. Do you have any idea which one changes it? What I want to do is set a much higher min-height, of course.  Or make the bar not overlap with the group thumbnails above, which makes it harder clicking.

**Comment by Quicksaver** [comment]
Scrollbars can only be styled by agent sheets, and by default Stylish sheets are user sheets (I think). Just add this line to the beginning (first line) of your stylesheet and your scrollbar code should work:
```CSS
/* AGENT_SHEET */
```

**Comment by DHammarberg** [comment]
Thanks, will try that out.
