### ISSUE TITLE
browser constantly freezes for minutes when switching between groups using a quick selector

### ISSUE THREAD

**Issue by vladzcloudius** [Quicksaver/Tab-Groups#358]
To reproduce:
1) create a few tab groups with a lot (more than 40) tabs in each.
2) Close a browser.
3) Open a browser.
4) Switch between groups using a quick selector (don't open **Manage my groups**).

Every time you switch between groups, even if you switch between the same two groups every time the browser freezes for a few seconds (sometimes minutes).

A workaround: open **Manage my groups** once and select a group from there. 
After that it never freezes again.

**Comment by Quicksaver** [comment]
By "quick selector", do you mean from the quick access panel?

**Comment by vladzcloudius** [comment]
On 06/28/2016 05:00 PM, Luís Miguel wrote:
>
> By "quick selector", do you mean from the quick access panel?
>

Yes, sir ;)

**Comment by Quicksaver** [comment]
I never noticed that, I'll have to check it out. Can you tell if it also happens if you disable all your other add-ons except or Tab Groups? How about in [a new profile](https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles)?

**Comment by vladzcloudius** [comment]
On 06/28/2016 05:47 PM, Luís Miguel wrote:
>
> I never noticed that, I'll have to check it out. Can you tell if it 
> also happens if you disable all your other add-ons except or Tab 
> Groups? How about in a new profile 
> <https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles>?
>

I noticed that it never happens with a "Simple Tab Groups" add-on, so i 
immediately blamed "Tab Group".
After I played with my add-ons - the one that is causing your add-on to 
behave as described in the issue is a "Gnome Keyring Integration 0.11" 
add-on.

**Comment by vladzcloudius** [comment]
On 06/28/2016 06:13 PM, Vlad Zolotarov wrote:
>
>
> On 06/28/2016 05:47 PM, Luís Miguel wrote:
>>
>> I never noticed that, I'll have to check it out. Can you tell if it 
>> also happens if you disable all your other add-ons except or Tab 
>> Groups? How about in a new profile 
>> <https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles>?
>>
>
> I noticed that it never happens with a "Simple Tab Groups" add-on, so 
> i immediately blamed "Tab Group".

It's "Simplified Tab Groups"

**Comment by Quicksaver** [comment]
First of all, I'm sorry I took so long to get to this.

I've tried Gnome Keyring Integration, but I haven't been able to reproduce any slowdowns like that. But it has been updated since then. So could you please confirm that you have its most up-to-date version 0.12 and also try it with [Tab Groups beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and see if it helps with this issue?

**Comment by vladzcloudius** [comment]
On 10/14/2016 07:26 PM, Luís Miguel wrote:
>
> First of all, I'm sorry I took so long to get to this.
>
> I've tried Gnome Keyring Integration, but I haven't been able to 
> reproduce any slowdowns like that. But it has been updated since then. 
> So could you please confirm that you have its most up-to-date version 
> 0.12 and also try it with Tab Groups beta version 2.1b2 
> <https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2> and see 
> if it helps with this issue?
>

Frankly speaking it's a lot less annoying recently. The version of a 
"GNOME keyring password integration" is 0.2.1.

**Comment by Quicksaver** [comment]
Do you mean that it doesn't freeze as often or as noticeably recently?

**Comment by vladzcloudius** [comment]
On 10/14/2016 07:50 PM, Luís Miguel wrote:
>
> Do you mean that it doesn't freeze as often or as noticeably recently?
>

Exactly

**Comment by Quicksaver** [comment]
Ok. I thought it was strange your version number was so different from mine, so I checked, and apparently you're using [GNOME keyring password integration](https://addons.mozilla.org/firefox/addon/gnome-keyring-integration/), whose latest version is now almost three years old. That's quite frankly a lot, and it's not surprising that it would often cause issues like those.

I admit that's not the one I tried, I tried [GNOME Keyring Integration](https://addons.mozilla.org/firefox/addon/mozilla-gnome-keyring/), which is much more recent, and at least for me it seems to work just fine with Tab Groups.

If you believe everything is running smoothly, or at least not slowing down or freezing enough to be a nuisance, then I'll leave the decision to switch up to you of course. But if you start experiencing heavy freezes like before again, please try disabling the one you have and install that other one first, and re-open this issue if you continue to have problems with it.

**Comment by vladzcloudius** [comment]
.

On Oct 15, 2016 05:25, "Luís Miguel" <notifications@github.com> wrote:
>
> Ok. I thought it was strange your version number was so different from
mine, so I checked, and apparently you're using GNOME keyring password
integration, whose latest version is now almost three years old. That's
quite frankly a lot, and it's not surprising that it would often cause
issues like those.
>
> I admit that's not the one I tried, I tried GNOME Keyring Integration,
which is much more recent, and at least for me it seems to work just fine
with Tab Groups.
>
> If you believe everything is running smoothly, or at least not slowing
down or freezing enough to be a nuisance, then I'll leave the decision to
switch up to you of course. But if you start experiencing heavy freezes
like before again, please try disabling the one you have and install that
other one first, and re-open this issue if you continue to have problems
with it.

Sure. Thanks a lot for your help
