### ISSUE TITLE
Move To Group changes tab order in the destination group

### ISSUE THREAD

**Issue by GrayFace** [Quicksaver/Tab-Groups#364]
Here's what I've done:
- Dragged 2 tabs to the right side of tab bar in Main group
- Moved a tab from another group to the Main group
- 2 tabs that I've moved returned to their initial positions

This also happened while I was filling this issue:
- I opened New Issue in new tab. I have tabs open next to current tab rather than at the end of tab bar (with Open Tabs Next to Current extension).
- After moving a tab around between groups I've noticed the new issue tab has moved to the far right of the tab bar.

**Comment by Quicksaver** [comment]
Just to confirm, does that also happen if you disable "Open Tabs Next to Current"?

**Comment by GrayFace** [comment]
Checked it with "Open Tabs Next to Current" and "Multiple Tab Handler" disabled, still happens. The first time I moved them now they stayed in that place, but second re-position was reset. Here's the exact sequence:
1) Move these 2 tabs
2) Switch to group #2, use Move To Group to move a tab to Main group.
3) In the Main group move the 2 tabs somewhere else, move the tab that came from group #2 back to group #2.
4) Switch to group #2, use Move To Group to move that tab to Main group again.

**Comment by zetapulse** [comment]
Just a suggestion, but it'd be a great feature if tab group ordering can be manually set, say a number in the management window & drag&drop in the quick access panel.
Even greater would be if the quick access panel were merged with the features of All Tabs Helper (https://addons.mozilla.org/en-us/firefox/addon/all-tabs-helper/), so both your & their add-ons can have proper sidebar integration (it screws around a bit in OmniSideBar, not sure about Firefox's default sidebar).

**Comment by Quicksaver** [comment]
> it'd be a great feature if tab group ordering can be manually set

The order of the groups in the quick access panel will be the same as what you define in groups management (single view or grid layout). Just drag the groups themselves to the order you want, and that's the order in which they should appear everywhere (apart a couple of existing bugs in menus I still need to fix).

> drag&drop in the quick access panel

Already planned (can't find the issue to link to at the moment), but again the order here will be the same as what you defined as I explained above.

> Even greater would be if the quick access panel were merged with the features of All Tabs Helper 

Also already planned (can't find the issue either, lack of time at the moment).

Also, none of those have to do with the original issue reported here. Please open new ones in the future for these different things, there's no need to spam other threads and thus other people's emails that have nothing to do with the discussion. ;)

**Comment by Quicksaver** [comment]
@GrayFace working on it right now. I still don't know exactly what's happening, but I just had to say, those are some incredibly specific steps! Great catch! Without those steps I don't think I'd ever have been able to do anything about it.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix this behavior. Please give it a try and let me know how it works for you.
