### ISSUE TITLE
"Search for a tab" does NOT work with all tabs

### ISSUE THREAD

**Issue by duyanning** [Quicksaver/Tab-Groups#365]
Sometimes it works and sometimes it does NOT, regardless Chinese or English.

firefox 47.0   (64 bits)
windows 10  x64

![bug](https://cloud.githubusercontent.com/assets/748776/16577124/ec8e6b06-42c5-11e6-85db-0d9bff8044c2.gif)

**Comment by Quicksaver** [comment]
That's weird. Does it work if you disable all your other add-ons except for Tab Groups?

**Comment by Quicksaver** [comment]
And perhaps more importantly, does english search always work if you have no tabs with chinese characters at all?

**Comment by duyanning** [comment]
I disabled all other add-ons except for Tab Groups as you said and restart, but I got the same weird behavior.
I found that newly created tabs can NOT be searched for, while old tabs which are restored from last session can be searched for.

**Comment by duyanning** [comment]
This time, I disabled all other add-ons and created a new session with only one group which has only one tab in English, but the problem remains.
![only](https://cloud.githubusercontent.com/assets/748776/16581463/2a98ec62-42dc-11e6-9755-63f5243285ae.gif)

**Comment by leggewie** [comment]
OT: I love thos animations, how do you create them?

**Comment by duyanning** [comment]
GifCam @leggewie

**Comment by duyanning** [comment]
I have refreshed my firefox, the problem remains.
I have uninstalled and reinstalled my firefox, the problem remains.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should now properly find all tabs. Please give it a try and let me know how it works for you.

**Comment by duyanning** [comment]
It works.
Cool!
Thank you very much!!!

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.
