### ISSUE TITLE
Browser start issue

### ISSUE THREAD

**Issue by ivankiselevich** [Quicksaver/Tab-Groups#366]
My english is bad, but i try to explain. When i start browser (Mozilla Firerox 47.0) group 13 opens, but first tab from group 14. it happens always, when i start browser.

**Comment by Quicksaver** [comment]
(I was almost sure there was an issue for this already, but I can't find it at the moment...)

Does that also happen if you disable all your other add-on's except for Tab Groups?

**Comment by MechanoRealist** [comment]
I don't know if this is related but sometimes when I start FF it will show all the groups at once as if I didn't use Tab-Groups. That is, all the tabs from all groups are in one big line.
I'm using Session Manager.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) has a fix for a bug similar to this. If you can confirm if you still have this issue with it I would appreciate it.

**Comment by Quicksaver** [comment]
Please re-open if you still have this problem with the latest version 2.1.
