### ISSUE TITLE
Are Tabs Inactive

### ISSUE THREAD

**Issue by KitchM** [Quicksaver/Tab-Groups#367]
I could not find your e-mail address, so I had to go here.

I went way too far to keep my tab bar cluttered up with dozens of tabs.  My browser seemed to slow way down because of that.

So here's my question:  Does grouping the tabs take them out of the picture when starting up Firefox, or do they all still have to load?  In other words, do they become inactive in groups that are not currently open?

Thank you.

**Comment by Quicksaver** [comment]
By default, Firefox doesn't load any tabs until they are selected, unless you changed preference ```browser.sessionstore.restore_on_demand``` in about:config. This of course also applies to tabs from other groups, until you actually select them, they won't be loaded.

Tabs aren't unloaded when switching groups though, so they remain loaded after switching to anohter group if you selected them already. There are other add-ons that can help with that, just search for something like "unload" in the add-ons website and see if any of them can help you.

**Comment by KitchM** [comment]
Thank you very much.
