### ISSUE TITLE
Not able to open "manage groups" on LinkedIn and other sites

### ISSUE THREAD

**Issue by obiwandb** [Quicksaver/Tab-Groups#368]
Nothing happens with either clicking "manage groups" or using keyboard shortcut. Perfectly fine on others. Any idea? FF 47 MAC

**Comment by Quicksaver** [comment]
The website you're on should really matter at all, that's very strange. Does that also happen if you disable all your other add-ons except for Tab Groups?

**Comment by obiwandb** [comment]
Seems to have fixed itself on restarting the computer. I'll keep you posted.
