### ISSUE TITLE
TabMixPlus Compatibility

### ISSUE THREAD

**Issue by truncsphere** [Quicksaver/Tab-Groups#37]
When starting FF I have TMP set to automatically restore my previous session. However, once this add-on was enabled it will not function properly anymore.
It does not auto save the current session like it used too and won't restore the previous session upon FF starting. 
Instead I'm greeted with the following every time I start FF:
![tmp](https://cloud.githubusercontent.com/assets/16292618/11786735/04cedd42-a23d-11e5-9e4d-e5dc4fc59767.JPG)

Disabling the Tab Group add-on restores the functionality of TMP as it was before.

**Comment by Quicksaver** [comment]
I can't seem to reproduce this. Could you please export your TMP's preferences and attach them here so I can try with your configuration?

**Comment by truncsphere** [comment]
Here you go. 
[TMPpref.txt](https://github.com/Quicksaver/Tab-Groups/files/62542/TMPpref.txt)

**Comment by Quicksaver** [comment]
So there are a few incompatibilities with TMP that I can't fix from within my add-on, I believe your case is one of them. They're all around mostly the same reason though: TMP isn't aware of the add-on.

Unfortunately TMP's support page is down today for some reason, so I can't reach its devs through the usual means. But I'll be sure to keep trying and I'm also trying by e-mail as well. I definitely want to fix this as soon as possible.

**Comment by truncsphere** [comment]
Thank your for checking and verifying that there was indeed a compatibility issue. I will be keeping an eye out on this issue.

**Comment by WilDieteren** [comment]
Quicksaver,

Will Tab-groups now work with TMP? I have a different problem from truncsphere: both Tab-groups and TMP are installed and active, but Tab-groups keeps telling me that tab groups will not be saved. Everything however seems to be fine, i.e. tab groups are restored, most likely by Firefox. I am on a iMac OSX 10.11.2, using Firefox 44b1.

Wil Dieteren

**Comment by Quicksaver** [comment]
Not yet, there's still a lot to do on this front, on both this add-on and in TMP as well. For now if you want to use both you'll have to disable TMP's session manager and use Firefox's built-in session restore.

**Comment by WilDieteren** [comment]
Quicksaver,

Thanks for your quick reply. I have already tried this nut am having a problem with the built-in session restore: it does not actually restore the session but loads my home pages. So I will wait till the issues between this add-on ad TMP are resolved. Will you update this thread then?

Wil Dieteren

**Comment by snowbound** [comment]
Just a FYI. As I posted here, I was having the same issue as truncsphere is seeing that pop up window coming up in FFox 43. Even after revering back to FF buil-in session manager I kept seeing it. I disabled Tab-Groups altogether without any effect. 

Even after uninstalling Tab-Groups, the FF session manager was not working. It would never restore the previous session tabs. Neither would TMP session manager when I looked at its sessions it had ones from the prior day. Turned out my FF profile was corrupted and I had to recreate it from scratch. Hopefully the installtion of Tab-Groups had no part in corrupting my FF profile.

**Comment by Quicksaver** [comment]
> Hopefully the installtion of Tab-Groups had no part in corrupting my FF profile.

By itself it definitely shouldn't. The only information the add-on saves/uses in your profile is just the groups and what tabs are in them, so at most you'd lose some groups and related things.

But TMP's session manager doesn't really recognize the add-on at all, so there may be some more serious issues there. I am trying to work on this, and TMP's devs are looking into what needs to be done on their side as well. But realistically speaking, I don't think we will be able to do anything before new year's at least (at least for myself, this is being a very busy month). :(

**Comment by snowbound** [comment]
Regarding Tab Mix Plus updated to 

0.4.2.1pre.151226a1

Change log shows this:

    Fixed: d181198 Incompatibility with new TabGroup extension that replaced Firefox build-in panorama.

**Comment by Quicksaver** [comment]
Can everyone please try the latest [TMP prebuild](https://addons.mozilla.org/firefox/addon/tab-mix-plus/versions/) that snowbound mentioned, together with [Tab Groups beta version 1.0.2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v1.0.2b1) that I've just uploaded? (Note that this beta is not signed, so you'll have to flip the preference "xpinstall.signatures.required" to "false" in about:config in order to use it. You can flip it back later when updating to the stable release when I upload it.)

If you still have any of these issues, please let me know. I hope you understand the delay with this, the holidays kept me pretty busy unfortunately, but I'm slowly getting back to coding. :)

**Comment by Quicksaver** [comment]
@snowbound [yep](http://tmp.garyr.net/forum/viewtopic.php?f=5&t=19424) ;)

**Comment by snowbound** [comment]
Can you remind me how to install these files since FFox requires .XPI extensions for local file install and renaming the beta .zip file to .xpi gives a file corruption error from FF 34 when I try to install it

**Comment by Quicksaver** [comment]
Check that link again, it should have an xpi listed there now that you can click on to install directly. (It's weird that it wasn't there before, I wonder if the initial upload failed somehow... Either way, re-uploaded it so it should work now.)

**Comment by truncsphere** [comment]
Updated to TMP Version 0.4.2.1pre.151226a1 as well as manually updated Tab Groups Beta. 
TMP is saving the session and restoring it properly on re-opening FF. I will test it throughout the rest of the day and report any further issues if needed.

**Comment by snowbound** [comment]
Well this morning I opened up firefox and none of my tabs were restored by FFox restore session. Lost all of my current tabs plus all of my Group Tabs. Luckily I had a week old TMP backup. Also Tab Groups was displaying its Yellow Warning bar in its options.

**Comment by Quicksaver** [comment]
Did you change any of the session-related preferences in your previous run? Which session manager are you using, Firefox's or TMP's?

**Comment by Quicksaver** [comment]
If you mean the yellow warning was shown before you last quit Firefox, then yeah that's expected as it means the session manager wasn't set to restore your tabs automatically.

**Comment by snowbound** [comment]
I had been using Firefox session manager along with Group Tabs. I changed nothing in the session-related preferences in my previous run. The Yellow warning showed up in Group Tabs this morning after FF failed to restore any of my tabs.

**Comment by Quicksaver** [comment]
The only case where Tab Groups changes that preference is when it is manually disabled/uninstalled AND when it had previously enabled it through the button in the add-on preferences (or automatically on first-use).

I am assuming that is not your case, which means something else must have changed that preference. Can you remember if you installed/enabled any new add-ons or change any preferences on any add-on? For instance, it's possibly that when toggling back and forth between TMP's session manager and Firefox's built-in session restore, the preference could be reverted incorrectly (by TMP).

By the way, when that happens, you can just click the "Restore previous session" button in Firefox's default homepage - about:home

**Comment by snowbound** [comment]
This is a reason why I had been using TMP session manager before installing Group Tabs. With TMP session manager I always had a previous session save to resort back to should anything happen with my last save. 

I was not in any of the extensions all day yesterday. Was just using Firefox normally

**Comment by snowbound** [comment]
Should About:Home show Restore Previous Session even when FFox has already restored the session properly? I just checked after restarting FFox here and allowing it to restore tabs on startup and the Restore Previous Session option is not on About:Home.

**Comment by Quicksaver** [comment]
> Should About:Home show Restore Previous Session even when FFox has already restored the session properly?

No since it restored the previous session automatically already, there's nothing to restore at this point (technically TMP could save the session previous to last, but that button doesn't know about that so it can't use it).

I'm considering what to do here... I'm not even sure TMP played a part in this.

**Comment by truncsphere** [comment]
For what it's worth I'm on day 2 with the new builds of TMP and Tab Groups and haven't had any issues with tab restores as of yet.

**Comment by snowbound** [comment]
May have figured out what the problem was in my case. Was still using the older 1.01 signed version of Tab Groups on the affected computer. I just now installed the beta build of Tab Groups and will see how that works.

**Comment by Quicksaver** [comment]
I will interpret no news as good news. :)
