### ISSUE TITLE
inconsistent tiling

### ISSUE THREAD

**Issue by leggewie** [Quicksaver/Tab-Groups#372]
At times I have the need to verify that if a window or session has been properly saved.  I do this by visual inspection.  It is very unfortunate that tab groups does not seem to have any consistency in how it tiles.  Please have a look at the attached screenshots.  They show completely identical tab groups albeit in different windows.  One is tiled in a 8 by 3 raster, the other one in 6 by 4.

![screen1](https://cloud.githubusercontent.com/assets/2387015/16959649/afb887da-4e18-11e6-8d5e-8b8346981f1e.png)
![screen2](https://cloud.githubusercontent.com/assets/2387015/16959650/afbfd4ea-4e18-11e6-98be-fa5cb1017b49.png)

**Comment by leggewie** [comment]
It seems as if going into grid view once and then back to single view might provide for consistency in the tiling raster.

**Comment by Quicksaver** [comment]
Did the window have a different size the first time you opened Tab Groups in it since the last time you closed it (the window/Firefox)? It's possible it's not updating the stored dimensions, do the thumbnails assume the correct aspect ratio if you resize the window?

**Comment by leggewie** [comment]
I cannot say what size the window was last time it was opened. I also had the suspicion it had something to do with some crufty old, obsolete dimension that for some reason had failed to update.  Sometimes, but not always the dimensions get corrected when changing views or the size of the windows.

In a nutshell, it sounds like you are on the right track in your analysis.

**Comment by Quicksaver** [comment]
Note: 980e49a5e0ee95ff1b6e88f249e743cef1fbe222 may have fixed this.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) may have fixed this behavior. Please give it a try and let me know how it works for you.

**Comment by Quicksaver** [comment]
Please re-open if you still have this problem with the latest version 2.1.
