### ISSUE TITLE
"Rules to catch tabs into this group" frequently stops working

### ISSUE THREAD

**Issue by olivercarl** [Quicksaver/Tab-Groups#373]
I use TabGroups 2.0.1 (I hope the latest)
The rules to catch a new tab into a specific group frequently (1-5 times/day) stop working (e.g. new tab opens in current group). I don't see a pattern what is causing it.
Restarting the browser does **not** fix the issue.
I found only one way to fix the issue: Modify any rule (e.g. attaching a CR at the end of any rule set)

**Comment by Quicksaver** [comment]
Sounds like something is preventing the rules from being applied properly at startup. Does that also happen if you disable all your other add-ons except for Tab Groups? Is there any action in specific that you think could be causing it? A way to reproduce this with some certainty would really help.

**Comment by olivercarl** [comment]
Thanks for your quick response.
I have disabled all other addins (restart was needed).
- (I think I had to do the edit trick to enable rules - not sure any more)
- Rules are working
- Close FF and reopen
- Rules are not working any more
- Edit any rule: it works again
Happened 2/2

**Comment by Quicksaver** [comment]
I'll have to check that out. What operating system and Firefox version are you on?

**Comment by spinda** [comment]
I'm also having this issue, with Tab Groups 2.0.1 on Firefox Developer Edition (`49.0a2 (2016-07-24)`) and Windows 10 Pro (version 1511, build 10586.494).

**Comment by gigabit942007** [comment]
I have this issue as well, with Tab Groups 2.0.1 on Cyberfox 48, had this problem on Cyberfox 47 as well, the same trick is required for it to work. Also WIndows 10 Pro.

**Comment by piyushsoni** [comment]
Came here to report the same issue. It is very important for my workflow with hundreds of tabs :( . I have three groups only, where two tab groups match the presence of one word each, the third 'Default' tab group tries to match the 'absence' of both of these words using regular expression. Works perfectly, only until it decides to stop. Is there any automatic work around?

**Comment by piyushsoni** [comment]
Are we any near to finding out why does this happen and how to fix? Thanks !

**Comment by Quicksaver** [comment]
I haven't had a chance to check it out yet. I hope to get to it soon.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should properly initialize the catch rules at startup now. Please give it a try and re-open if you still have this issue with it.

**Comment by olivercarl** [comment]
Tested on Linux and Win10 (both where I experienced the problem): Works fine! Thanks!

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.

**Comment by piyushsoni** [comment]
Works for me too! Thank you very much! 

How it suits my use case: 
At work, I have three tab groups which keep my browser organized. Two tab groups include only the pages that have a specific word each in their URL. Regular expression for that was easy to write. The third rule that I wanted to write was 'everything else' (that doesn't go to any of these two previous tab groups) and was a little difficult to find in the beginning. So, it should include any page that does NOT contain the previous two words. If anyone else is facing a similar problem, this is how I solved it:

Catch rules for : 
Tab Group 1:   **word1**
Tab Group 2:   **word2**
Tab Group 3 :   **^(?:(?!(word1|word2)).)*$**
