### ISSUE TITLE
Load groups and tabs at startup

### ISSUE THREAD

**Issue by Otiel** [Quicksaver/Tab-Groups#374]
I'm using the Firefox option "Clear history when Firefox closes" in order to delete all browsing history, cache... when I close Firefox.

With that in mind, is it possible to load some specific groups and tabs by default at Firefox startup?

**Comment by Quicksaver** [comment]
No, you can only choose to load all or none (there is a bug currently where if you choose to load all tabs, it will only load tabs from the current group and not all groups, but that will be fixed soon).

**Comment by Otiel** [comment]
What do you mean by "load all"? Where can I find this option?

**Comment by Quicksaver** [comment]
In about:config disable preference "browser.sessionstore.restore_on_demand"

**Comment by Otiel** [comment]
I see thanks. But I'm more looking for a way to automatically open some tabs/groups at startup. Could it be a new feature? For instance, to automatically restore tab groups from a backup file at startup?

**Comment by Quicksaver** [comment]
That you'll have to do manually, as the overhead of creating a whole system just to automatically load backup files (while possible) would probably bring far too little benefit to be worth maintaining it. Isn't it better to use pinned tabs in your case?

**Comment by Otiel** [comment]
I understand. Pinned tabs aren't remembered because I choose to automatically delete all history when closing Firefox.

**Comment by Quicksaver** [comment]
Oh, I had thought those would be kept. Is there no setting to keep pinned tabs while discarding all others? (I haven't checked and can't at the moment.) If that's not possible, then it's definitely worth it to try and create something like that, although it would probably work better as a stand-alone add-on (I may not be able to do it myself, at least not any time soon by the way) as I really don't believe it's a good idea to mess with "keeping/discarding history" functions in Tab Groups.

**Comment by Otiel** [comment]
No, I don't think it's possible to force Firefox to keep pinned tabs.

I understand you don't want to add such a feature to Tab Groups, no worries.

I was previously using [Session Manager](https://addons.mozilla.org/en-US/firefox/addon/session-manager/) and it worked fine until Tab Groups were removed from the Firefox base. Now it simply opens my tabs in the same tab group.

**Comment by Quicksaver** [comment]
Session Manager should work the same way with groups, it should be perfectly compatible with Tab Groups. Is it restoring a session from before you installed this add-on/updated Firefox? You could try creating a new session from scratch with the tabs that you want, or at least saving it again after you set them up how you want them. Although it's very unlikely, it's possible that something in Session Manager's session files isn't playing well with the current versions of both add-ons.

**Comment by Otiel** [comment]
> You could try creating a new session from scratch with the tabs that you want
Already tried that, unfortunately I still get the same behavior.

**Comment by Quicksaver** [comment]
Hmm, there's something weird going on there, of course it should restore your groups as well when it restores your tabs. I'll try to take a look and see if I can reproduce it somehow with those settings. Does that happen every time you try to restore a backup through Session Manager, or only the first time right after you start Firefox? For instance, after you use it for a while and create a few groups with tabs, then try to switch to another session (that also has groups), do the correct groups appear or do all their tabs get merged into a single group?

**Comment by Otiel** [comment]
*(I can open a new bug if you prefer to keep this separate from my original question, just let me know)*

Here's what's happening:

1. I have the following session saved:
 * The Trello page is opened in Group 1
 * The Feedly page is opened in Group 2
 ![session](http://i.imgur.com/UrrqAHt.png)
2. I have set this session to be automatically opened with Session Manager when I open Firefox:
 ![session manager options](http://i.imgur.com/E49kDK5.png)
3. When I close/open Firefox, I see directly both tabs (so letting me think both are opened in the same group).
4. If I hit my shortcut (set in Tab Groups options) to cycle through groups, nothing happens (letting me think that there is only one group opened).
5. When I open the Tab Group manager, I see that there is in fact two groups opened and the Feedly tab is moved automatically to Group 2.
6. If I immediately exit the Tab Group manager (without having moved any tab), both my tabs are correctly sorted in the two groups.

Not sure if this is related: I've noticed that in the Session Manager window, there was previously an indicator (an asterisk `*`) in front of pages that were not in the current group. So in my case, there was an asterisk in front of the Feedly page when I was in Group 1.
![asterisk in session](http://i.imgur.com/XVB23ZB.png)

If I try to restore the session without closing Firefox, the same is happening:
* Both my tabs in group 1,
* No group 2 by shortcut,
* Opening Tab Group manager solves it.

**Comment by Quicksaver** [comment]
Ah ok, I had suspected before but couldn't be sure, but now with your explanation that's definitely #286.

**Comment by Otiel** [comment]
Yes I confirm, sorry I didn't see this issue before posting.
