### ISSUE TITLE
Tab-Groups doesn't work with current Firefox Tab Center 1.22

### ISSUE THREAD

**Issue by gusowski1** [Quicksaver/Tab-Groups#375]
If the Firefox Expirement Tab-Center https://testpilot.firefox.com/experiments/tab-center is enabled, the Tab-Groups doesn't work anymore

**Comment by iShyboy** [comment]
Talk a bit more about this, I'm using FF 47.0.1 and Tab Center 1.22 with latest TG and it's working fine. Just that my TG icon was in the tab bar when I added Tab Center so I had to tap restore on Customize menu to TG buttom get back to the buttons box. But the shortcut and the rest worked fine even before.

**Comment by gusowski1** [comment]
hm - the Tab Group itself is displayed and the tab in the groups to - but all tabs of the other tab-groups to

probaly i should try the nice disable all and enable only some addons to track the issue down

**Comment by iShyboy** [comment]
Oh, I saw that too, but in a odd way, the tabs of other groups appeared on the actual group totally at random, and disappeared too. And I only have TG, Tab Center and uBlock Origin.

**Comment by gusowski1** [comment]
oh ok - then it is an issue and i doesn't need to try this enable/disable game

**Comment by Quicksaver** [comment]
I'll have to check it out. If I understood correctly, all tabs (from other groups as well) are always visible, is that it?

**Comment by Quicksaver** [comment]
For reference: https://github.com/bwinton/VerticalTabs/issues/424

**Comment by talha131** [comment]
@Quicksaver here are few images to explain the issue.

There are the tabs I have in group 1

<img width="239" alt="screen shot 2016-08-10 at 08 39 33" src="https://cloud.githubusercontent.com/assets/1094724/17541151/01689a98-5ed6-11e6-89f5-da9f36ffd545.png">

Now say I move to all tabs group page using `⌘Command+⇧Shift+E` key, and then press `⎋Escape` without clicking anywhere. Tabs from all the groups appear in the sidebar.

<img width="254" alt="screen shot 2016-08-10 at 08 37 25" src="https://cloud.githubusercontent.com/assets/1094724/17541175/48f00c0c-5ed6-11e6-84ca-fb33cdbe6204.png">

The only way I can get back the *filtered* list i.e. tabs of only group 1, is by going into tabs group selection page and there clicking on a tab from group 1.

I am using  **Firefox 48.0** (Build ID 20160726073904) on OS X 10.11.6 with **Tab Groups 2.0.1**.

Please let me know if you need more info to reproduce the issue. I can upload a video if you feel necessary.

**Comment by febcrash** [comment]
Same problem here!

**Comment by rahiel** [comment]
> Same problem here!

If it helps anyone: I've switched from the Tab Center experiment to the [Vertical Tabs Reloaded](https://addons.mozilla.org/firefox/addon/vertical-tabs-reloaded/) add-on, which is compatible with tab groups.

**Comment by Turkal** [comment]
I have the same problem with TabCenter 1.24

Actually, just pressing the Escape key show all the tabs from all groups.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix compatibility with Tab Center, only tabs from the current group should be shown, and the groups button should now be visible again in the tabs toolbar as well. Please give it a try and let me know how it works for you.

**Comment by Dimas-sc** [comment]
It works for me, thx!

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know.

**Comment by Turkal** [comment]
Same here, everything works fine now. Thanks !

**Comment by jeanblanchard** [comment]
Here it works fine when the sidebar is locked, but all tabs are shown as soon as it is shrinked.

**Comment by Quicksaver** [comment]
@jeanblanchard The last version of Tab Center was released just a few days ago, so it's possible you could have been using an older version of Tab Center that got updated in the meantime. Please let me know if it starts happening again.

**Comment by jeanblanchard** [comment]
@Quicksaver I updated manually to the 2.1b3 version. Maybe the hot update missed something that was fixed by doing a platform restart ?

**Comment by Quicksaver** [comment]
It's possible but I doubt it, and I meant that about Tab Center, not Tab Groups.

**Comment by jeanblanchard** [comment]
Oh right, it appears my brain cannot distinguish between "Tab center" and "Tab groups". Indeed Tab Center was last updated today in my Firefox, so it must be that.
(sorry everyone about the notification spam)
