### ISSUE TITLE
Select All highlights all text and images with no obvious way of unselecting

### ISSUE THREAD

**Issue by skhzhang** [Quicksaver/Tab-Groups#38]
Ctrl + A selects all text, icons, and unloaded tab images with no obvious way of unselecting them all. This goes the same for selecting everything by clicking part of the "Undo Close Group" text and dragging outside of the borders.
![screenshot 2015-12-15 00 20 29](https://cloud.githubusercontent.com/assets/4945652/11802833/e31e8ef0-a2c2-11e5-8d26-39f1438b1b0c.png)
(This appears a lot more striking when there are many tab groups and tabs open.)

Clicking a tab and coming back to the Tab Groups view won't unselect anything, it looks like the only way to unselect them is by making a new tab group.

Also, FWIW, from my limited testing, this also seems to occur in the (now) old implementation of Panorama.

**Comment by Quicksaver** [comment]
Text selections are probably not being handled correctly. Thanks for the heads up, I'll look into it.
