### ISSUE TITLE
drag-and-drop between windows

### ISSUE THREAD

**Issue by wraybowling** [Quicksaver/Tab-Groups#380]
Despite the fact that tab groups helps me manage all the tabs I have open... I have more than one window open usually because I have multiple monitors and it's handy to split things up.

I can think of a number of features we could split this into
- [ ] dragging a tab group from the manager out of the window creates a new window with those tabs
- [ ] dragging a tab from another window onto the manager, moves that tab into the respective group on the target window
- [ ] dragging a tab group from one window onto another tab group manager moves that tab group from window to window

**Comment by Quicksaver** [comment]
#82 and #174
