### ISSUE TITLE
List view scrolling issues: Can't scroll while dragging an item, not scrolling to active tab

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#387]
Hi!

I noticed these while using panorama extensively the past week or two.

Unlike with the miniatures when I enter panorama mode the group always shows the first tabs and never scrolls to the active one.
I can't use the mousewheel at all to scroll when I drag an item. Which is aggravated by the fact that scrolling fails to activate sometimes when I drag it to the edge. I noticed this in the tiled view, but not with all groups. Can't really narrow it down further. (Note: I'd actually prefer if I could disable the autoscrolling when dragging an item to the edge, if I can have scrolling via mousewheel)

**Comment by Quicksaver** [comment]
> Unlike with the miniatures when I enter panorama mode the group always shows the first tabs and never scrolls to the active one.

I don't understand this, you are contradicting yourself... Does it scroll or doesn't it?

> I can't use the mousewheel at all to scroll when I drag an item.

This may or may not be possible, I'll have to investigate before I give you a more concrete answer, but it could well be a limitation of your Firefox/Operating system.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. aug. 18. 10:37 CEST](https://github.com/Quicksaver/Tab-Groups/issues/387#issuecomment-240659576 "2016-08-18T08:37:26Z - Replied by Github Reply Comments"):
> > Unlike with the miniatures when I enter panorama mode the group always shows the first tabs and never scrolls to the active one.
> 
> I don't understand this, you are contradicting yourself... Does it scroll or doesn't it?

I'm most certainly not. With the miniatures hidden always the first tabs that fit are shown and not the selected tab.

**Comment by iShyboy** [comment]
I don't have this issue with scrolling, in any views, or options enabled. Strange it does go to the active tab thumbnails or list it doesn't matter at all.

Add scroll to tab view drag and drop should be a enhancement?

**Comment by mzso** [comment]
When I filed this, I was suing the free arrange view. Now I'm using the tiled view and still experience this.

**Comment by Quicksaver** [comment]
ddea3df124fa7108ad5dcdcc29934ee10b819c03 fixed groups not scrolling automatically to the active tab.

**Comment by mzso** [comment]
It'd be nice if you pushed beta/dev builds sometimes. :)

**Comment by Quicksaver** [comment]
I will soon, I'm almost finished with the bugs. :)

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should now scroll properly to the active tab and when dragging tabs to the edges of the group. Please give it a try and let me know how it works for you.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 15. 01:12 CEST](https://github.com/Quicksaver/Tab-Groups/issues/387#issuecomment-253941198 "2016-10-14T23:12:33Z - Replied by Github Reply Comments"):
> [Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should now scroll properly to the active tab and when dragging tabs to the edges of the group. Please give it a try and let me know how it works for you.

The scrolling to active tab now works flawlessly.

The scrolling while dragging at least works when I hover around the top/bottom. Though it's a bit awkward. It speeds up (jumps practically), then slows down, or stops, or scrolls with a medium rate. If I move a pixel it speeds up again.
I still think mousewheel scolling would be a gain.

**Comment by Quicksaver** [comment]
The problem is the wheel event doesn't seem to fire when you're dragging something, which is the problem. It can't scroll if it can't detect the wheel is being scrolled. :(

**Comment by r2rien** [comment]
fyi, this 2.1b2 version fixes a bug I was about to open:
ff nightly: no more mousewheel scrolling in single view

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 15. 14:46 CEST](https://github.com/Quicksaver/Tab-Groups/issues/387#issuecomment-253982185 "2016-10-15T12:46:07Z - Replied by Github Reply Comments"):
> The problem is the wheel event doesn't seem to fire when you're dragging something, which is the problem. It can't scroll if it can't detect the wheel is being scrolled. :(

I see. I wouldn't be surprised that there's a 10+ year bug for this, somewhere in the dark corners of bugzilla. I guess it would require extensive hacking to make it work.
Well, I'm hoping the scroll on hover thing'll be improved to be more predictable.

**Comment by Quicksaver** [comment]
Can you please open a new issue about it, so I don't forget to check it out? (It probably won't happen for the very next update though.)

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 16. 12:12 CEST](https://github.com/Quicksaver/Tab-Groups/issues/387#issuecomment-254038358 "2016-10-16T10:12:40Z - Replied by Github Reply Comments"):
> Can you please open a new issue about it, so I don't forget to check it out? (It probably won't happen for the very next update though.)

Well, I opened #435. Though I don't know gain me opening it did. :)

**Comment by Quicksaver** [comment]
Organization mostly. Thanks. :)
