### ISSUE TITLE
Keyboard Shortcut for Fr Layout

### ISSUE THREAD

**Issue by Acrimonis** [Quicksaver/Tab-Groups#388]
Hello,

I am trying to map:
- switch to next group to [CTRL+²]
- switch to previous group to  [CTRL+SHIFT+²]

** The ² being the key above the TAB key on the fr keyboard layout. ** 

See [AZERTY layout used in France](https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/KB_France.svg/500px-KB_France.svg.png) on Wikipedia (also below).
This option, of course is not available in the options to select...

Is there a way to manage this?
I also try [keybinder](https://addons.mozilla.org/en-US/firefox/addon/keybinder/) (replacement for the discontinued [Customizable Shortcuts](https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/) add-on), but the shortcuts associated to Tab-Groups are not available in there.
Note: the "Customizable Shortcuts" add-on used to let me map those on some "next tabs group" exposed shortcut.

Thank you very much in advacne,

-n

PS: thank you for a great addon in any case.
PS2: Azerty fr layout:
![500px-kb_france svg 1](https://cloud.githubusercontent.com/assets/6048235/17809339/34dee142-6616-11e6-9dff-a234f23d075a.png)

**Comment by Quicksaver** [comment]
Please read #139 for a (possible) solution.

**Comment by Acrimonis** [comment]
Yes thank you, "Dorando keyconfig
<https://addons.mozilla.org/en-US/firefox/addon/dorando-keyconfig/?src=userprofile>"
addressed the issue.

Thanks again.

-n
