### ISSUE TITLE
Closing the tab of one tab group switches to the last tab of another tab group

### ISSUE THREAD

**Issue by SebastianZ** [Quicksaver/Tab-Groups#389]
Sometimes it happens that when you close a tab from a tab group, a tab in the first tab group is opened.
It doesn't happen all the time, but unfortunately I couldn't find a pattern yet.

#369 may be related, though I have set `browser.tabs.closeWindowWithLastTab` to `true`.

I _think_ this started after the update to Firefox 48.0. FWIW, e10s is still disabled in that profile.

Sebastian

**Comment by Quicksaver** [comment]
I have to admit I don't know from the top of my head if this behavior is desired or even expected. I'll have to investigate and do some testing so that I can give you a proper answer/fix.

**Comment by SebastianZ** [comment]
> I have to admit I don't know from the top of my head if this behavior is desired or even expected.

Well, for me it is unexpected and undesired. Note that there are still other tabs open in that tab group, so it should switch to them - what it does sometimes.

Another thing to note is that this happens in my default profile with different add-ons installed and settings changed.
On weekend I tried to reproduce this issue on a clean profile, but I couldn't. So, maybe it is related to some conflict with a setting or another add-on. I'll continue to find some steps.

Sebastian

**Comment by SebastianZ** [comment]
Sorry for the delay! Unfortunately I couldn't find steps to reproduce this issue yet, I only tested a bit, though.

Sebastian

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) has some fixes for similar behavior bugs. If you could try it out and confirm if your issue still exists with it I would appreciate it.

**Comment by SebastianZ** [comment]
I've installed the beta version and so far I couldn't reproduce the issue anymore by testing different scenarios. So I close this issue now. If it reappears, I'll try to find proper steps and then post a new issue.

Thank you fixing the issues and getting back to me!

Sebastian

**Comment by Quicksaver** [comment]
Great! Thanks for letting me know. :)
