### ISSUE TITLE
Single View: Tab resizing after moving to another group

### ISSUE THREAD

**Issue by famfop** [Quicksaver/Tab-Groups#390]
Say you have 2 tab groups and you are in single view. Now you move one tab from one group to the other one. When you switch to this group, the sizes of the tabs will be as before adding the tab hence sometimes too big. I guess the expected behaviour should be that the resize happens when switching to this tab group?
This happens to me in firefox 48.0 on linux without any other addons activated.

**Comment by Quicksaver** [comment]
I'll check it out, thanks for letting me know.

**Comment by iShyboy** [comment]
![xd](http://i.imgur.com/7hXVtfe.png)

If you mean the thumb, it does change, low res or too high to the tile, but it change a while after, and didn't take long.

**Comment by Quicksaver** [comment]
Fixed by 1cd3444cde3bc2e4b880e7e6221b33ea7a593bba
