### ISSUE TITLE
Feature request: Right-click on link -> "Open link in tab group..."

### ISSUE THREAD

**Issue by slinkp** [Quicksaver/Tab-Groups#391]
I do this a lot, since I use groups as workspaces for different tasks:

1. Find a link I want to look at later.
2. Right-click -> "Open link in new tab"
3. Right-click on the new tab -> "Move to Group"  -> select group

It would be a nice shortcut if there were a context menu item to open the new tab directly in another group, skipping step 2.  So:

1. Find a link I want to look at later.
2. Right-click link -> "Open link in tab group..." -> select group

Example: I am checking work email, and get a notification that somebody wants me to do a code review, but I don't want to start that right away. I have a group for code review.  The quicker I can get the link into that group without interrupting what I'm doing, the better.
Even better if it gets a keyboard shortcut!

**Comment by Quicksaver** [comment]
I like that!

**Comment by nhantrn** [comment]
+1 for this request

**Comment by Manimap** [comment]
I was going for the same thing!

**Comment by Keith94** [comment]
Same as that: #360?

**Comment by Quicksaver** [comment]
Yep, good catch.
