### ISSUE TITLE
Shim for Tab Groups Button plugin?

### ISSUE THREAD

**Issue by PrototypeNM1** [Quicksaver/Tab-Groups#393]
Some of the Tab Groups Button plugin functionality was broken with recent updates. The features broken by changes include the following.

- Closing a tab group via the plugin's tab group bar does not close the group
- The tab group bar no longer sees that tab groups have been closed and is not updated until it is reloaded
- Merge To... functionality moves but does not close the prior tab group

The point in time when the issue began is noted in [this review](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-button/reviews/814775/).

**Comment by iShyboy** [comment]
Wrong repo. This is for Tab Groups (TG), not Tab Groups Button (TGB).

**Comment by PrototypeNM1** [comment]
The issue is breaking changes in TG, not the TGB. This seems appropriate given shims exist for other plugins broken by changes, see [Tab Groups Menu](https://github.com/Quicksaver/Tab-Groups/commit/3fd93653ddd696b961a5b860202c955fa8d78ceb) and [Tab Groups Helper](https://github.com/Quicksaver/Tab-Groups/commit/7f2df564ea40ef5df2aa1e31ad9a26a7981dd98a)

**Comment by Quicksaver** [comment]
I'll take a look and see if I can do anything about it. It might be easier to contact Tab Groups Button developers and see if they can update their add-on to work with the new version though.

**Comment by PrototypeNM1** [comment]
Thanks, the Tab Groups Button developer is releasing updates but hasn't been responsive to the Github issue tracker recently. Quick cross reference: char101/tabgroupsbtn#16

**Comment by char101** [comment]
Hi,

What method should I call to close a group without causing the `TabView` to appear? 

I use `groupItem.close({immediately: true})` but it does not close the group (it reappears on browser restart) and the `TabView` still appears after closing.

**Comment by Quicksaver** [comment]
In fact there is no "proper" way to close a group from outside TabView (because it doesn't expect that to happen at all). I definitely need to address that for the next update, this is a huge flaw in the system.

You could maneuver around it instead, by calling ```groupItem.tryToClose({ immediately: true });``` instead. This will in turn call groupItem.close() when necessary. Note that this closes the tabs, but the tabs themselves may refuse to close (other add-ons could cancel the closing), so the group will also refuse to close at this point. I'm not sure if this is important to your case so I thought I'd mention it.

I'll be sure to create a proper way of doing this, and I'll let you know as soon as I do, but of course I won't be removing .tryToClose, so that it doesn't break again if you end up using that.

**Comment by char101** [comment]
Thanks for the explanation. With `tryToClose` the groupitem is indeed removed (it does not reappear on browser restart) but the `TabView` is still being displayed after closing the group.

**Comment by Quicksaver** [comment]
Is this when you close the active group or any group at all (inactive ones)?

**Comment by char101** [comment]
The TabView opened when closing both active group or inactive group.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) includes changes to the ```groupItem.tryToClose()``` method. You should now call it without arguments to close any group you want at any time, but keep in mind that the group may not actually close (i.e. protected tabs from Tab Mix Plus, "Are you sure you want to navigate away?"-type of dialogs, etc.)

Please try doing that with that beta, and let me know if there's anything else you need for Tab Groups Button compatibility.

**Comment by Quicksaver** [comment]
All the changes I mentioned will be in Tab Groups 2.1. @char101 please re-open if there's still anything else you'll need for compatibility. @PrototypeNM1 also please re-open if you still have any problems with it.
