### ISSUE TITLE
Keyboard shortcuts: support square "²" key on AZERTY keyboards

### ISSUE THREAD

**Issue by Otiel** [Quicksaver/Tab-Groups#394]
I'd like to use the square key <kbd>²</kbd> on an AZERTY keyboard to set a shortcut, but it isn't proposed in the list of keys. Could you add it to the list?

![640px-kb_france svg](https://cloud.githubusercontent.com/assets/3851902/18055715/3d47eafe-6e09-11e6-83c3-3266cb5304f4.png)

My aim is to set a keyboard shortcut to <kbd>Ctrl</kbd> + <kbd>²</kbd> to switch to the next group, because it is close to <kbd>Ctrl</kbd> + <kbd>Tab</kbd>.

**Comment by Quicksaver** [comment]
Please read #139 for a (possible) solution.

**Comment by Otiel** [comment]
Thanks, I was able to set the shortcut to <Ctrl>+<²> using [Dorando keyconfig](https://addons.mozilla.org/en-US/firefox/addon/dorando-keyconfig/) as suggested.

For information, in the past I tried Customizable Shortcut (discontinued now) and Keybinder but they do not offer a way to change the tab groups shortcuts anymore.

Thanks a lot!
