### ISSUE TITLE
Failure to work (at all) in Firefox ESR 45.1.1, OSX

### ISSUE THREAD

**Issue by LinuxGuyInVA** [Quicksaver/Tab-Groups#395]
I've been using Panorama for years, and Tab-Groups since it came out.  Platforms: Linux (both Red Hat and Ubuntu) and both regular and ESR versions of Firefox.  On my Mac (managed), I'm supplied with FF ESR, currently at 45.1.1.  Prior to this version, Tab-Groups worked fine.

I have tested a clean profile, with no other add-ons (except Classic Theme Restorer, supplied 
by the system packaging by my workplace; and I've subsequently disabled it to no avail).  The tab groups button is nowhere to be found, nor does the default hot key (Cmd-Shift-E) do anything.

My workaround so far is to use the Tab Groups Helper add-on, which at least gives me access to the old tab groups I've already created.

Additional details (configuration, etc). on request.  Newbie to github (but not in general; online since the ArpaNet).

**Comment by Quicksaver** [comment]
Does your Firefox come bundled with CCK2? (I believe you can see it either in the add-ons manager or in the about dialog if it is.)

**Comment by LinuxGuyInVA** [comment]
On Aug 29, 2016 7:23 PM, "Luís Miguel" <notifications@github.com> wrote:

> Does your Firefox come bundled with CCK2?

Affirmative.

- Pat

**Comment by Quicksaver** [comment]
Then this is #239. You need to disable CCK2 for now, until either it updates or I fix it within a new update of Tab Groups.
