### ISSUE TITLE
Feature request:Display tab groups as a tab with thumbnails

### ISSUE THREAD

**Issue by molstrangler** [Quicksaver/Tab-Groups#396]
I would like to be able to:

1. Allow tab group to be displayed as a tab
2. Hovering over the tab will display thumbnails of the open pages in that tab groups
3. Clicking on the tab opens the last active page in that tab group
4. Right-click on the tab and save the tab group to be loaded later

**Comment by Quicksaver** [comment]
This is pretty much the same as what Tab Groups Helper and Tab Groups Manager do. So #1.
