### ISSUE TITLE
New Feature request: Auto create a tab group

### ISSUE THREAD

**Issue by molstrangler** [Quicksaver/Tab-Groups#397]
These would be very useful.

1. Option to auto add pages to a tab group based on its domain/IP address
2. Option to auto create a new tab group when opening more than one page from the same domain.  With auto naming of the tab group

**Comment by Quicksaver** [comment]
1. Use Catch Rules.
2. This would be just an incredibly convoluted feature. It's almost impossible for it to just "guess" what it is what groups you want and what groups you don't. I don't see any (simple) way to do this, it's just much simpler to use Catch Rules for this as well, by keeping groups with rules for websites you know you keep visiting,
