### ISSUE TITLE
Save group to Pocket

### ISSUE THREAD

**Issue by isyara** [Quicksaver/Tab-Groups#399]
Hi,

In the native version of firefox it was possible to send all the tabs from one group to the icon of the Pocket service ( http://www.getpocket.com ). The pocket button appeared then to middle right group. it was enough to click on this icon to send any tabs . 

Would it be possible to have this feature ? # #

**Comment by Quicksaver** [comment]
I've never seen this button so I believe it was implemented by Pocket itself. Have you tried contacting its developers about this? If it implemented this feature before, I'm sure it would be much easier for them to re-implement it for this add-on (i.e. groups and tabs information still exist and are stored in exactly the same way as before, they probably only need to place the button a bit differently).
