### ISSUE TITLE
sort groups in "Move to Groups" dialog

### ISSUE THREAD

**Issue by rahiel** [Quicksaver/Tab-Groups#40]
When you right-click a tab and go to "Move to Group", it shows a list of groups, but they aren't sorted alphabetically. That would help if you have many groups and know which one you want to send the tab to.

Thanks for saving tab groups!

**Comment by rahiel** [comment]
Thanks! :smile:

**Comment by Quicksaver** [comment]
You're welcome. :)

**Comment by dgutov** [comment]
I think they're currently sorted by "last changed" or "last accessed"? I'd like to keep them that way.

**Comment by Quicksaver** [comment]
They are sorted by creation order currently.

**Comment by Quicksaver** [comment]
I'm almost sure they are sorted by creation order and not by any sort of "last changed" action. But I will confirm later.

**Comment by dgutov** [comment]
Creation order would also be better than alphabetical, as far as I'm concerned.

Basically, if you could pref the new change out, that would be great. Thanks!

**Comment by Quicksaver** [comment]
You can just add a number at the beginning of the group title to sort them however you want. I don't understand what benefits disadvantages that has over manually ordering your groups?

**Comment by dgutov** [comment]
I'm lazy, like how my groups are set up now, and don't want anything to change? :) Putting numbers in the names is kinda ugly.

But never mind if it's too hard, it's not a major deal breaker.
