### ISSUE TITLE
Conflict with ColourfulTabs extension

### ISSUE THREAD

**Issue by xiwi** [Quicksaver/Tab-Groups#400]
Hi,

I've noticed that if you jave both extensions enabled, you will see tabs from other groups, not only the currently selected one (although those "extra tabs" won't be selectable).

Is it feasible to make both extensions work together better?

I would be willing to donate some $ if it can be fixed ad I would love using both together :)
Let me Know if I I din't explain myself clearly, my frist language isn't english

great work with the extension, it's amazing how it has developed .

**Comment by Quicksaver** [comment]
#165. Please try to contact its developer. I haven't heard back from them (unless I completely forgot). If they can't/won't fix it, then I'll take a look at it.
