### ISSUE TITLE
Migrating tab groups from FF 44.0... How?

### ISSUE THREAD

**Issue by pico--** [Quicksaver/Tab-Groups#401]
I haven't yet upgraded from FF 44.0, but I was interested in moving to FF 47.0 using Tab Groups as an add-on to manage my tab groups in FF 44.0. However, the Tab Groups 2 add-on page says "Not available for Firefox 44.0". 

How can I migrate my tab groups to a FF 47.0 and Tab Groups? Is the  code for Tab Groups 1 still available for download, and still compatible with FF 44.0? If I install Tab Groups 1 in FF 44.0, will I be able to migrate to Tab Groups 2 in FF 47.0? Or is there a better way to achieve this?

**Comment by Quicksaver** [comment]
> Is the code for Tab Groups 1 still available for download, and still compatible with FF 44.0? If I install Tab Groups 1 in FF 44.0, will I be able to migrate to Tab Groups 2 in FF 47.0?

Yep, you can do that easily: [all versions](https://addons.mozilla.org/firefox/addon/tab-groups-panorama/versions/). Just install TG 1.0.2, update Firefox, update TG.

Even if that doesn't work and you end up losing your tabs/groups for some reason, there are all sorts of automatic backups created when you update your Firefox and the Tab Groups add-on, including a special one created by Firefox the first time you upgrade to a version 45 or higher. You'll be able to restore any tabs or groups you want from it easily, using the Backup and Restore page in the add-on's preferences.
