### ISSUE TITLE
First time switching to a different tab group and back doesn't remember last open tab.

### ISSUE THREAD

**Issue by NJC2** [Quicksaver/Tab-Groups#402]
I don't see this listed, and it's just a minor annoyance.   I have one main tab group for regular browsing and three other tab groups where I save related tabs for certain things.  When I switch to one of those tabs, it always remembers the last open tab and goes to it, like it should, but when I switch back to the main tab group, rather than going back to the last open tab, it goes to the first tab.  This only happens after starting the browser for the first time, after that it remembers the last open tab when switching back and forth.

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) should fix this behavior. Please give it a try and let me know how it works for you.
