### ISSUE TITLE
Save bookmarks bar to group

### ISSUE THREAD

**Issue by Oralordos** [Quicksaver/Tab-Groups#404]
Bookmarks in your bookmark bar should be able to be saved to your tab groups. If you change your group, you should have a different set of bookmarks in your bookmark view. Perhaps a way to pin bookmarks too like we do tabs.

This would be helpful in the case where you use your computer for work and at home, and you could change everything with a simple group change.

**Comment by Quicksaver** [comment]
I understand what you mean, but that's beyond the scope of the add-on. If you want to have completely different environments, you are much better off using different profiles completely ([Profilist](https://addons.mozilla.org/firefox/addon/profilist/) comes to mind). I would rather keep Tab Groups more to the point: groups of tabs.
