### ISSUE TITLE
Switching group remains old tabs in tab bar

### ISSUE THREAD

**Issue by tobiasKaminsky** [Quicksaver/Tab-Groups#405]
- enable multithread: browser.tabs.remote.force-enable = true
- currently in group with 10 tabs
- switch group
- current tab is displayed correct in tab bar, but not other tabs of the new group are shown but the old ones

maybe related
- switch tabs 
- caption in firefox is sometimes the old one

**Comment by Quicksaver** [comment]
Does that also happen if you disable all your other add-ons except for Tab Groups?

**Comment by tobiasKaminsky** [comment]
A quick test (~ 5min) results in a working behaviour.
Do you know some add-ons that are known for causing problems?

**Comment by Quicksaver** [comment]
No, you'll have to disable one/a few at a time to figure out which one is causing the conflict, so that I know what to fix. :)

**Comment by tobiasKaminsky** [comment]
It seems to be a conflict with http://tabmixplus.org
If I disable this it is working as expected. With tabmixplus I have configured that the tab bar is 2 lines.
Maybe this is related?

**Comment by Quicksaver** [comment]
It's working fine for me currently. Is this still happening for you? If yes, what operating system, Firefox version, Tab Groups version and Tab Mix Plus version are you using?

**Comment by Quicksaver** [comment]
If this is still happening for you, please try the latest version of TMP with [Tab Groups beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2) and let me know if you still have any issues.

**Comment by Quicksaver** [comment]
Please re-open if you still have any issues with the latest version.
