### ISSUE TITLE
Tab Groups fails to start after manual installation due to unknown conflict with Https Everywhere

### ISSUE THREAD

**Issue by Dinnanid** [Quicksaver/Tab-Groups#406]
If HTTPS Everywhere is installed and you manually install Tab Groups (by dropping it in the extensions folder of that profile) when Firefox starts it thinks Tab Groups has been loaded even though it clearly has failed to. This can be permanently fixed by disabling and re-enabling Tab Groups or by restarting Firefox.

I have no idea what sort of conflict could possibly cause this and I haven't noticed any other addons that have this issue.

I discovered this while trying to setup a template that could be used automatically generate Firefox profiles with pre-installed addons and preset preferences. I was very confused as to why the Tab Groups icon wouldn't appear on the first run of the profile. I have attached the most minimal template that reproduces the issue. (setting extensions.autoDisableScopes to 14 prevents Firefox from automatically disabling the addons that have been manually installed) I have also actually tested by installing HTTPS Everywhere normally and then manually installing Tab Groups.

I understand if you decide not to pursue this since it is an extreme edge case.

[test.tar.gz](https://github.com/Quicksaver/Tab-Groups/files/465758/test.tar.gz)

**Comment by Quicksaver** [comment]
I will definitely check it out. Could I ask you to try it again and get some debug info while you're at it? Just before installing Tab Groups, open the browser console (Ctrl+Shift+J), clear it, then install Tab Groups and see if anything appears in the console when TG's button fails to appear like it should.

**Comment by Dinnanid** [comment]
But that's the thing. This doesn't happen when installing Tab Groups normally. It only happens when you manually put it in the extensions folder and then restart Firefox. Unless there is any way to have Firefox search for new extensions without restarting you can't debug it normally.

**Comment by Quicksaver** [comment]
I'll try to reproduce it when I can, I've never tried installing it by dragging to the folder so I'm not even sure how it's supposed to behave then.

**Comment by Quicksaver** [comment]
Yeah that commit wasn't meant for this issue, my bad.

**Comment by Quicksaver** [comment]
Hmm, I can reproduce it. Although I have no idea why that's happening. Also, I don't need HTTPS Everywhere to reproduce it, Tab Groups doesn't start the first time on its own either for me.

The curious part is I tried other restartless add-ons and they seem to work fine that way. So it seems like it's something in the add-on's initialization that's not really happening, although I haven't investigated further than that.

Honestly, it's like you said, this is an extremely edge case. And there's an easy way around it for you as well, just include the extensions.ini and extension.json files in the profile, and the preferences "extensions.bootstrappedAddons" and "extensions.xpiState" in the profile and it should work out of the box. (You may not actually need all that, or even the entire preferences, I just did a quick copy-paste test and it worked for me at least.
