### ISSUE TITLE
Toggle quickAccess panel by FireGesture 

### ISSUE THREAD

**Issue by m0n** [Quicksaver/Tab-Groups#409]
Hi!

I like to toggle quickAccess panel by a FireGesture script. I tried TabView.toggleQuickAccess(); but that won't work. No error is displayed in the statusbar and a keyboard shortcut is set in TabGroups preferences (as I saw in Your source it's mandatory)

Thanks for Your help!

**Comment by Quicksaver** [comment]
I did see your earlier comment in the other thread, but I hadn't responded because I don't know it off my head and I have no way to check it out at the moment. I'll be sure to let you know as soon as I can.

**Comment by m0n** [comment]
Thank You! I though that closed issues are "dead" and this is the reason I opened a new one.

Have a nice weekend!

**Comment by Quicksaver** [comment]
I'm sorry it took me so long to respond to this.

That's the wrong method to call, that method initializes the panel script, but doesn't actually open it (it does need to have the keyboard shortcut set, that part is correct).

Try calling ```tabGroups.quickAccess.toggle();```

**Comment by m0n** [comment]
Thanks Quicksilver, that calling just WORKS!
