### ISSUE TITLE
Some websites do not have a preview after restarting Firefox

### ISSUE THREAD

**Issue by DuckOfDuckness** [Quicksaver/Tab-Groups#41]
After restarting Firefox, most websites still have a preview image in the tab groups view, but some just have a blank white image.

Some websites I've experienced this on (white image after restarting):

* http://www.last.fm/
* https://www.instagram.com/
* https://keep.google.com/
* https://fit.google.com/
* https://photos.google.com/
* https://calendar.google.com/

**Comment by biowiet** [comment]
i have the same problem with quite a lot of them and it doesn't seem to be related to websites as I have the same website on more tabs and some of them shows thumbs some of them doesn't. I have to individually open them from the groups window to get them. 
Have you managed to fix it somehow?

**Comment by Quicksaver** [comment]
it's possible that the thumbnail was saved while the canvas was still blank for some reason. I've made some (minor) changes to how this works in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6), which hopefully should avoid situations like these. Please give it a try and let me know if you have any problems with it.

And remember that you won't see a difference immediately, as thumbnails are only saved once every couple of days at most (i.e., it only saves a thumbnail for a loaded tab if the previously saved thumbnail is at least 2 days old). So give it a few days of using and let me know if blank thumbnails keep appearing on previously loaded tabs (but now unloaded).

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.

**Comment by DuckOfDuckness** [comment]
I'll test it out for some days and let you know! Thank you :)
