### ISSUE TITLE
Suggestion: Export Tab Group option

### ISSUE THREAD

**Issue by JmsWhitlow** [Quicksaver/Tab-Groups#412]
I would like to be able to export an individual tab group, remove it and then have the ability to re-import it at a later time.

**Comment by Quicksaver** [comment]
You can already use the Backup & Restore page in the add-on's preferences to backup your groups to a file (right now it can only backup all of your groups, but I may add the ability to select which specific groups to backup in the future). You can create that backup, close whatever groups you want, then import them back whenever you want them.
