### ISSUE TITLE
Tab group indicator disappears in latest nightly

### ISSUE THREAD

**Issue by grinapo** [Quicksaver/Tab-Groups#420]
The top right indicator (either icon or group name) disappears. If I entered TG settings and switch on and off "show the name of the active group" it came back last time in every window, now some windows get it back and some doesn't. (Happens for some weeks now, but yesterday's FF update is the first where I cannot get it back no matter what.)

Hotkey only works in window with the icon visible, either.

**Comment by Quicksaver** [comment]
It seems to work fine for me. Could you try disabling all your other add-ons except for Tab Groups and see if it helps at all? It could be a conflict with one causing it.

**Comment by grinapo** [comment]
You are asking for a quite lengthy process, since restarting probably resolves it for a while. :-)
I try to disable non-restart-hungry ones. But it's been working for a while and I don't remember upgrading any of the addons recently.

**Comment by Quicksaver** [comment]
If it hasn't disappeared yet, it seems like it could be one of those add-ons. I'll need to know which one in order to check it out. :)

**Comment by grinapo** [comment]
I have disabled all the addons which doesn't require restart, nothing changed. I have restarted and it's only back in one out of 5 windows. I try to disable the rest, but there is also Session-Manager involved and I can't say what is the interaction between these but I cannot disable it without losing a few (500+) tabs. :-)

**Comment by grinapo** [comment]
Nope. **All** addons but TG are disabled, same effect. 
As a sidenote: toggling "show the name" by clicking the text is ok while by clicking the checkbox puts 
  (firefox:13627): Gtk-CRITICAL **: gtk_clipboard_set_with_data: assertion 'targets != NULL' failed
on the console (and do the toggle).

But it's not addon related. Now I have 2 windows out of 5 which do have the icon, and I cannot make the other 3 to have one. Since not even the hotkey work I suspect that the addon isn't active in that window, but I cannot debug you further without suggestions. Nothing relevant's on the console.

**Comment by grinapo** [comment]
Nope. **All** addons but TG are disabled, same effect. 
As a sidenote: toggling "show the name" by clicking the text is ok while by clicking the checkbox puts 
  (firefox:13627): Gtk-CRITICAL **: gtk_clipboard_set_with_data: assertion 'targets != NULL' failed
on the console (and do the toggle).

But it's not addon related. Now I have 2 windows out of 5 which do have the icon, and I cannot make the other 3 to have one. Since not even the hotkey work I suspect that the addon isn't active in that window, but I cannot debug you further without suggestions. Nothing relevant's on the console.

**Comment by Quicksaver** [comment]
Hmm. I have a small suspicion, could you try opening an "about:home" tab in all of your windows, so that when you start Firefox all of the windows start with that tab, and see if it makes a difference. You don't need to reset your session of course, just make sure that the first loaded tab in all windows is about:home.

**Comment by Quicksaver** [comment]
(I'm asking this because I see something similar when one of my windows starts with a "Write style" page from the Stylish add-on, but that doesn't happen all the time which is making it hard for me to debug. You seem to be able to reproduce it more directly, so I'm not sure it's the same issue...)

**Comment by grinapo** [comment]
#include <BeeGees/you_win_again.ogg>
Bingo. All windows now have the icon.

**Comment by Quicksaver** [comment]
Can you try and find out which tab was causing it? If it is more reproducible than with the stylish tab I'm using, it'll definitely be a big help.

**Comment by grinapo** [comment]
You mean that the one which is used as first tab kills it? So I should restart with a given tab as first?
All of them were on various webpages, no extension configs. And since it was reproduced with addons disabled, I don't quite see what I'm looking for.
Or is it the session restore functionality?

**Comment by grinapo** [comment]
I did a few restarts with various "first" tabs but now all of the icons are there. I don't know what would you really want me to try. :-)

**Comment by Quicksaver** [comment]
Any sort of patterns you can see. For instance if you find that this starts happening again and it always happens with one specific tab first opened in one of the windows. I realize it can be a wild goose chase though...

I'm going to try and fix the bug I (sometimes) see, and I'll link you to a beta when I do to see if it also helps for you as well.

**Comment by grinapo** [comment]
If I notice it again I will note which tab it has used to load first and try to reboot it again.
But one window contains pages from only one site (internal website), and it was faulty before and now it's good. Could it be the session restoration process? 
I'm sorry that I cannot offer a nice, simple bug instead of this sneaky one. ;-)

**Comment by Quicksaver** [comment]
> Could it be the session restoration process? 

It's a possibility, although I honestly can't tell how it could possibly interfere with the add-on initialization; at most it would prevent your tabs or groups from loading correctly, but not the whole add-on like that. I need to investigate this.

> I'm sorry that I cannot offer a nice, simple bug instead of this sneaky one. ;-)

Oh I've seen much, much worse, at least the first hunch actually helped this time. ;)

**Comment by grinapo** [comment]
Ohhh-kay.... I have got caught a tab, which, when replaced by about:home seem to fix the icon for all the windows. Now what?
It's an absolutely nothingspecial one: non http auth protected [nonpublic] mediawiki. However when I remove the about:home, select the mediawiki again and restart again I have all the tabs again.
The order of windows restored is seemingly random, or at least the top is not the same as the one I was using to quit FF.
At start I have a nondescript exception, most possibly absolutely unrelated:
```
$ firefox
ARTUR: - SHOW 
ARTUR: - SHOW 
ExceptionHandler::GenerateDump cloned child 1334
ExceptionHandler::SendContinueSignalToChild sent continue signal to child
ExceptionHandler::WaitForContinueSignal waiting for continue signal...
ARTUR: - SHOW 
ARTUR: - SHOW 
ARTUR: - SHOW 

###!!! [Parent][MessageChannel] Error: (msgtype=0x4C0043,name=PContent::Msg_Shutdown) Channel error: cannot send/recv
```

And now I have removed other about:home instances I was putting while trying, no more about:home and the icon is there everywhere now, after repeated restarts.
If you want to create a debug version of the addon with lots of console shit just feel free... I can't see any trends.

**Comment by Quicksaver** [comment]
Actually I think I've fixed my similar issue just a few minutes ago. I'll upload a beta for you to try out soon (there's a few more bugs I want to get out of the way first).

**Comment by Quicksaver** [comment]
[Beta version 2.1b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b2), please give it a try and let me know if you still have any trouble with it.

**Comment by grinapo** [comment]
Througout 3 restarts I have seen no problem, but it's obviously hard to say it's "fixed", though it appears to be so.

**Comment by Quicksaver** [comment]
Well that's a good indicator at least. Please do re-open this and let me know if it starts happening again.
