### ISSUE TITLE
Not working with Firefox 52

### ISSUE THREAD

**Issue by MoOx** [Quicksaver/Tab-Groups#421]
I am currently using Firefox Nightly (52.0a1 (2016-10-04) (64-bit)) and the button in the right top corner does not work anymore.

![image](https://cloud.githubusercontent.com/assets/157534/19088423/55ccbeea-8a76-11e6-98e0-e2d4456fb37d.png)

I closed FF 52, opened latest stable ff, it's working.

Not sure how I can debug this.

**Comment by Quicksaver** [comment]
(I assume that "w" character is the name of the current group.)

So basically if you click the button, nothing appears. Could you try disabling all your other add-ons except for Tab Groups and see if it works then? Just to rule out any incompatibility with any of them.

**Comment by MoOx** [comment]
Oh you are right, this is a problem with another add-on. Very weird. I disable all others: working. I enable Stylish, React devtools, uBlock origins, restarted: not working. I tried to isolate which one: impossible, now it's working with all the add-ons I was using before. Super weird...

**Comment by MoOx** [comment]
Thanks for you help and your awesome plugin!

**Comment by Quicksaver** [comment]
Hmm that's weird, yeah, but at least it's working for now. :)

If it starts happening again, try opening the browser console (Ctrl+Shift+J, Command+Shift+J on mac), clear it and then press on the tab groups button and let me know if anything appears in the console then.
