### ISSUE TITLE
FYI - Not a Bug. Contribute doesn't work.

### ISSUE THREAD

**Issue by StuAtGit** [Quicksaver/Tab-Groups#423]
Just FYI, I tried to contribute/donate via the firefox portal, and it first pops up with a dialog with a suggested amount, or a custom amount. I fill that out, and note that it briefly says "contacting paypal" before the dialog goes away, and nothing happens.

Checked my paypal account, and no contribution was sent...
This is obviously a bug somewhere else (not sure where I should report it), but thought you would want to know.

**Comment by Quicksaver** [comment]
First of all, thank you very much! I really appreciate your intention.

That's a bug with the addons.mozilla.org website, of which I believe they're already aware but I'm sure they would still appreciate it if you could contact them directly about it in case they need any info about it. In the meantime, you should be able to login directly to your PayPal account make a direct transfer to mine: quicksaver.addons@gmail.com
