### ISSUE TITLE
Abillity to make Tab-Groups work across multiple Firefox Instances/windows

### ISSUE THREAD

**Issue by damiongans** [Quicksaver/Tab-Groups#424]
I would like to see Tab-Groups work across multiple Firefox instances/windows.
Now,, with Windows 10 having multiple desktop support, I would like assign for each (virtual) desktop a specific Firefox window with a Tab-group. When I switch to another tab-group I would like to switch to the other window on the other virtual desktop.

Thanks, That'd be awesome :-)

**Comment by Quicksaver** [comment]
#82, #174 and #275.
