### ISSUE TITLE
Firefox 50, e10s - tab groups unable to pick, they all start to mix/blend

### ISSUE THREAD

**Issue by rjameson3** [Quicksaver/Tab-Groups#426]
Not sure if this is tab groups issue, or the TGHelper - but I forced the e10s enabled to see if FF gets better, faster, better memory management per tab - but after a period of time - the group tabs (this may be TGHelper) start to all get mixed up..I can no longer select either group on left or right and when  pick one in the middle, for example, all the FF tabs in that group are tabs from the other groups I could not select.  If I disable the e10s tabs features - it works, enable - it will fail.  I have done this on 3 different pc's - including MAC.

Is this a known issue, is this TG or TGH?

**Comment by Quicksaver** [comment]
It's TGH. Please contact it's developer about it. In the meantime I don't mind taking a look, but I don't believe this is something I can fix on my side.

**Comment by Quicksaver** [comment]
Also, have you tried disabling all other add-ons, except for TG and TGH? I don't recall ever hearing about it behaving that way, even with e10s enabled.

**Comment by Quicksaver** [comment]
Please let me know if you hear back from TGH's developer, or if it starts to happen if you disable TGH.
