### ISSUE TITLE
settings button brings up "how-to" instead.

### ISSUE THREAD

**Issue by mausalimi** [Quicksaver/Tab-Groups#427]
hiho,

as title says. press the settings button (not the one in the groups) opens the tab with the "how-to" pages.

tested with code up to https://github.com/Quicksaver/Tab-Groups/commit/37c70d6cd0def139db36f36d9aec9afba71c1adf

nothing serious, but shouldn't be to hard to fix, just in case you get bored. ;)

**Comment by Quicksaver** [comment]
It's supposed to bring up the pane that was visible when you last opened the preferences. For example, if you open the preferences, go to the backups and restore pane, close that tab, then re-open it, it should stay in that tab. Is this not happening?

**Comment by Quicksaver** [comment]
*it should stay in the backup and restore pane

**Comment by mausalimi** [comment]
it does exactly what it should. i forgot the "howto" pane is integrated in the preferences.

silly me, please close this and bury it in the deepest place of the net. :(

thanks for the great extension btw.

**Comment by Quicksaver** [comment]
You're very welcome, I'm glad you like it. :)
