### ISSUE TITLE
[Request] Optionally show the number of groups in a badge on the toolbar icon

### ISSUE THREAD

**Issue by FatOrangutan** [Quicksaver/Tab-Groups#430]
I was able to find a workaround to do so using Stylish and the `groups` attribute of the icon:
![jcapture](https://cloud.githubusercontent.com/assets/8336638/19405785/59048b30-9299-11e6-9059-6b065a3ef3d4.PNG)
but I think it might be a good idea to have a proper badged icon.

**Comment by Quicksaver** [comment]
#134.
