### ISSUE TITLE
Hide Caption Titlebar Plus compatability

### ISSUE THREAD

**Issue by sanyarnd** [Quicksaver/Tab-Groups#431]
Miscellaneous bug: minimize/maximize/close buttons overlap with icons and main window. It is actualy does not rely on any settings, to get such behaviour, just install addon.
[![bug](https://s22.postimg.org/pt5olvsg1/2016_10_15_124815.png)](https://postimg.org/image/5yjmzrd8d/)

Still, if you need settings:
[![2016-10-15_131509.png](https://s11.postimg.org/o9h0zs903/2016_10_15_131509.png)](https://postimg.org/image/k0caxm5qn/)

setup:
Win10, FF45 ESR, Hide Caption Titlebar Plus, Tabs Groups

**Comment by Quicksaver** [comment]
I haven't tried it yet, but you may have to disable "System TitleBar always hidden" for it to appear correctly.

**Comment by sanyarnd** [comment]
That's exactly why I installed this addon :)

**Comment by Quicksaver** [comment]
I'm not sure I can fix this from my side, looking at HCTP code I don't really know where to start to be honest. I've opened https://github.com/Javier-DarthPalpatine/firefox-hide-caption-titlebar-plus/issues/333.

**Comment by Javier-DarthPalpatine** [comment]
I'm fixing it  (HCTP)
Luck this just appeared right before a new HCTP release :-)

**Comment by iShyboy** [comment]
I have this issue ever since old times, never thought about opening this here.
![ff42](http://i.imgur.com/f1CdBCv.png)
![FF49](http://i.imgur.com/IEaZN26.png)
Good to know that it'll be solved :)

**Comment by Javier-DarthPalpatine** [comment]
Fix is out already in HCTP versions 315rc  and  315 !!

**Comment by Quicksaver** [comment]
Awesome! Thanks for working on it so quickly. :)

**Comment by iShyboy** [comment]
Nice, working in the latest and even in FF42 thanks.
