### ISSUE TITLE
Don't switch the active tab when a search is cancelled

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#436]
When you do a search then cancel it the first result of that search will be the active tab, and you loose the the tab that was active at the start of the search. As such going back to normal view will take you somewhere unexpected.

**Comment by Quicksaver** [comment]
I assume this is on a 2.1 beta.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 16. 15:45 CEST](https://github.com/Quicksaver/Tab-Groups/issues/436#issuecomment-254047840 "2016-10-16T13:45:25Z - Replied by Github Reply Comments"):
> I assume this is on a 2.1 beta.

Yes.

**Comment by Quicksaver** [comment]
Should also be fixed in [beta version 2.1b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b4). As always, let me know.
