### ISSUE TITLE
Search bar in quick access panel is not working

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#437]
Hi!

The search field of the quick access bar is rather crude compared to the normal search. It doesn't show anything and takes you somewhere if it has a hit. You don't even know where. Or does nothing. And you certainly don't know what will happen when you press enter.

I think it could just use the same thing as the ctrl+f search from groups mode, only from normal view. AKA showing panorama and highlighting the results. closing it or deleting the search phrase could take you back to normal view.

Alternatively it could show it's own specific results in normal mode, but that needs to be made, while the tab groups search is already implemented.

**Comment by Quicksaver** [comment]
It should show you the results right there as you type, as shown in the eighth screenshot at https://addons.mozilla.org/firefox/addon/tab-groups-panorama/. Doesn't it?

**Comment by mzso** [comment]
I get nothing. (I'm on mozilla central)

**Comment by iShyboy** [comment]
Working as usual in the latest beta (FF48)
Same group:
![1](https://vgy.me/Qqw2Ht.png)
Another group:
![2](https://vgy.me/qzsa4k.png)

**Comment by Quicksaver** [comment]
It's working just fine for me too. I did fix an issue where some tabs in there wouldn't show updated labels, so it's possible you had "invisible" tabs appearing. Could you try [beta version 2.1b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b4) and see if it helps at all with your issue?

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 17. 18:19 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254256183 "2016-10-17T16:19:09Z - Replied by Github Reply Comments"):
> It's working just fine for me too. I did fix an issue where some tabs in there wouldn't show updated labels, so it's possible you had "invisible" tabs appearing if they never had their labels updated during the current session. Could you try [beta version 2.1b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b4) and see if it helps at all with your issue?

Nope. I didn't know that you can bring this up with the icon though. I removed that ages ago. (The doorhanger pointing at nothing was a bit weird)
So maybe it only happens when you don't have the icon on the UI? (I'll try)

**Comment by Quicksaver** [comment]
Erm... Wot? O.o I'm sorry about my crudeness, but it was my honest reaction. :)

I'm either not understanding what you mean at all or we're speaking about completely different things. Can you post a few screenshots of what you mean, and maybe the exact steps of what you're doing? And can you see if by disabling all your other add-ons you get the behavior shown in the screenshots above? I wouldn't think any add-on would interfere with that actually, but from your words I'm at a complete loss.

> Nope. I didn't know that you can bring this up with the icon though. I removed that ages ago.

Removed what? The toolbar button? Or did you set in the add-on's options to show the name of the active group instead of the icon (which is the default behavior)?

> (The doorhanger pointing at nothing was a bit weird)

How are you opening that panel then, through a keyboard shortcut? It should anchor to Firefox's main menu button (the three bars button) if there's no groups button anywhere.

> So maybe it only happens when you don't have the icon on the UI?

The panel should work regardless of anything I mentioned above though. Showing the icon or the active group name is irrelevant, it's just an anchor to where the panel should open from, as is the main menu button in case that's used instead. The actual panel itself really doesn't care at all where it's opening.

**Comment by mzso** [comment]
I'm not doing anything mysterious. Just using the "Open quick access panel" shortcut while not having the TG button.

**Comment by Quicksaver** [comment]
Works fine for me like that. Have you tried without other add-ons? That's just weird. Could you also try in a new profile, just to confirm it's something specific that you have enabled currently?

**Comment by iShyboy** [comment]
![49](http://i.imgur.com/IP6NDei.png)
Still working

**Comment by mzso** [comment]
[**@iShyboy**](https://github.com/iShyboy) commented on [2016. okt. 17. 20:32 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254293118 "2016-10-17T18:32:30Z - Replied by Github Reply Comments"):
> [![49](https://camo.githubusercontent.com/8eff40db8dfc85cb909e65083b5ade4d9a417311/687474703a2f2f692e696d6775722e636f6d2f4950364e4465692e706e67)](https://camo.githubusercontent.com/8eff40db8dfc85cb909e65083b5ade4d9a417311/687474703a2f2f692e696d6775722e636f6d2f4950364e4465692e706e67)  
> 
> Still working

I don't have that button either. Removed by "Classic Theme Restorer"

**Comment by iShyboy** [comment]
@mzso 
Still Working even with CTR:

![49-3](http://i.imgur.com/hmT7qVF.png)

**Comment by mzso** [comment]
[**@iShyboy**](https://github.com/iShyboy) commented on [2016. okt. 17. 20:39 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254294959 "2016-10-17T18:39:24Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso)   
> 
> Still Working even with CTR:
> 
> (https://camo.githubusercontent.com/9bcc20b2f364b372de7aba96f65ec8453056cc88/687474703a2f2f692e696d6775722e636f6d2f686d54377156462e706e67)

Well, what does it attach itself to then? :) To me having the button and not having it seem to be the difference.

**Comment by iShyboy** [comment]
I doesn't attach to anything, just float in the top left when I press the shortcut. All functions of the panel appear to be normal here.

**Comment by Quicksaver** [comment]
> To me having the button and not having it seem to be the difference.

I will try removing that button as well a bit later, but as I said it seems very strange that would make any difference at all. The contents of the panel simply don't care where it's attaching itself to. Is it only the search box that doesn't work? Do the groups appear and can you click on them normally?

**Comment by mzso** [comment]
Huh...
To me the results are totally missing:
![tg-dh](https://cloud.githubusercontent.com/assets/4479090/19451556/fa059ffe-94ad-11e6-99e8-7309f06f054d.png)

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 17. 21:09 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254303251 "2016-10-17T19:09:31Z - Replied by Github Reply Comments"):
> > To me having the button and not having it seem to be the difference.
> 
> I will try removing that button as well a bit later, but as I said it seems very strange that would make any difference at all. The contents of the panel simply don't care where it's attaching itself to. Is it only the search box that doesn't work? Do the groups appear and can you click on them normally?

Nope just the search field and the manage groups bar. See above.

**Comment by iShyboy** [comment]
Just Floating:
![49-4](http://i.imgur.com/zpOCtwj.png) 

Pretty frustrating for yourself. maybe because the quick panel it's opening upward instead of downwards?

**Comment by Quicksaver** [comment]
Hmm... Do you have anything at all that could be messing with the layout of panels such as those? It's not supposed to be that small, even if empty. Sounds to me like it's actually working right, but you just don't see the results or anything else because the panel isn't big enough to show them.

A userstyle? Any other add-on? (Maybe something else in CTR?) Can you remind me what operating system you are on?

**Comment by Quicksaver** [comment]
> Pretty frustrating for yourself. maybe because the quick panel it's opening upward instead of downwards?

Hmm... Usually I would say that's unlikely as well, but at this point I'm up for anything.

**Comment by iShyboy** [comment]
@mzso try putting the menu in the addonbar of ctr to see if the search dont work at all or if it's just the panel it's opening upwards.
Like:
![49-5](http://i.imgur.com/Fd9pht7.png)

**Comment by Quicksaver** [comment]
Also, I don't remember right now if CTR has an export settings function but if it does can you attach yours here please?

**Comment by iShyboy** [comment]
![Export](http://i.imgur.com/vDIrcRU.png)
It does, he can export it to txt or json and default it to see if solve the problem.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 17. 21:13 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254304315 "2016-10-17T19:13:33Z - Replied by Github Reply Comments"):
> Hmm... Do you have anything at all that could be messing with the layout of panels such as those? It's not supposed to be that small, even if empty. Sounds to me like it's actually working right, but you just don't see the results or anything else because the panel isn't big enough to show them.
> 
> A userstyle? Any other add-on? (Maybe something else in CTR?) Can you remind me what operating system you are on?

Can't think of anything. I did disable stylish, but it didn't make a difference.

Here are the ctr preferences:
[CTRpreferences.txt](https://github.com/Quicksaver/Tab-Groups/files/534561/CTRpreferences.txt)

**Comment by iShyboy** [comment]
@mzso did you try with the icon in the addon bar, jut to see if the panel it's really opening upwards.

**Comment by mzso** [comment]
[**@iShyboy**](https://github.com/iShyboy) commented on [2016. okt. 17. 21:59 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254316001 "2016-10-17T19:59:11Z - Replied by Github Reply Comments"):
> [@mzso](https://github.com/mzso) did you try with the icon in the addon bar, jut to see if the panel it's really opening upwards.

Yes. I put the the TG icon there. Didn't change anything.

**Comment by Quicksaver** [comment]
I loaded those preferences into my CTR, removed TG's button from the toolbar. Works just fine. I even restarted a couple of times and moved the window around to force the panel to open in different places, it always works.

Can you please confirm that if you disable all your other add-ons except for TG and CTR, it still does that?

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 17. 22:45 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254328465 "2016-10-17T20:45:26Z - Replied by Github Reply Comments"):
> Can you please confirm that if you disable all your other add-ons except for TG and CTR, it still does that?

It's still broken.

**Comment by Quicksaver** [comment]
Anything in your [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&printable=yes)? What's your OS?

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 17. 23:07 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254334492 "2016-10-17T21:07:58Z - Replied by Github Reply Comments"):
> Anything in your [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css&amp;printable=yes "UserChrome.css&amp;printable=yes")? What's your OS?

Nothing... (Win 8.1) I even tried setting CTR to Firefox defaults.
It's just this no matter what I do: If both buttons (TG, and FF hamburger) is missing it doesn't work.

It doesn't even work if I have CTR disabled and hide the FF button via CSS: 
(Meanwhile having the TG button removed of course)
```
#PanelUI-button{
	display:none !important;
}
```

It works this way on FF47 stable and mozilla-central (FF52)

**Comment by mzso** [comment]
I tried 2.1b4 with a new profile. Only adding TG and then hiding the TG button, then the hamburger button via userchrome CSS. Then setting the hotkey.
The same thing happened for both FF47 and FF52: Pressing the hotkey didn't do anything. No doorhanger.

**Comment by Quicksaver** [comment]
Well, I have no idea why it won't work without an anchor for you, it seems to do just fine for me. So, let's force an anchor on it. Please try [beta version 2.1b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b5) and see if it helps, it should anchor the panel to the selected tab when it can't find either the Tab Groups button or the hamburger button.

**Comment by mzso** [comment]
[**@Quicksaver**](https://github.com/Quicksaver) commented on [2016. okt. 18. 12:04 CEST](https://github.com/Quicksaver/Tab-Groups/issues/437#issuecomment-254463624 "2016-10-18T10:04:28Z - Replied by Github Reply Comments"):
> Well, I have no idea why it won't work without an anchor for you, it seems to do just fine for me. So, let's force an anchor on it. Please try [beta version 2.1b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b5) and see if it helps, it should anchor the panel to the selected tab when it can't find either the Tab Groups button or the hamburger button.

This seems to fix it.
(What if someone hides the tabbar for some reason? :) Maybe you could add something that's always present as an ultimate fallback? #main-window? )

**Comment by Quicksaver** [comment]
I believe that's already what the panel anchors to when it has no anchor.
