### ISSUE TITLE
Tab Groups 'title icon' Incompatible with Puzzle Bars

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Tab-Groups#438]
If I place the Tab Groups icon onto a toolbar from your Puzzle Bars add-on and have it set to show the current group title as the icon graphic, TG disappears from the PB toolbar and from the customization screen. I get the icon back when I uncheck the "icon as title" option in Tab Groups.

**Comment by Quicksaver** [comment]
Already fixed by https://github.com/Quicksaver/Puzzle-Toolbars/commit/42bf00047a16e12c142d1f5bb237371fc642e114.

**Comment by jmain33** [comment]
Done before you're even asked. It's wonderful how efficient you are :grinning: 
I'll be showing my appreciation shortly.
