### ISSUE TITLE
Horizontal padding on main toolbar button on macOS sierra

### ISSUE THREAD

**Issue by omega** [Quicksaver/Tab-Groups#441]
The button on the main toolbar could use a bit more horizontal padding

![screenshot of padding issue](https://dl.dropboxusercontent.com/s/bcbjrckxf4j96nh/Screen%20Shot%202016-10-18%20at%2008.33.35.png?dl=0)

Firefox nightly, macOS sierra.

Moved out of issue #278

**Comment by Quicksaver** [comment]
Yep, you were absolutely right, it was just a coincidence that it was appearing correctly for me. Please try [beta version 2.1b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b5) and let me know how it works.

**Comment by omega** [comment]
Hey, the new beta has more, but I would have doubled it (or thereabout), so it is more similar to above and below, and more similar to the other buttons

tab groups button: 

https://dl.dropboxusercontent.com/s/50ivo9wdz21evp1/Screen%20Shot%202016-10-20%20at%2009.33.05.png?dl=0

button next to it:

https://dl.dropboxusercontent.com/s/7gpc1k54sbfoi48/Screen%20Shot%202016-10-20%20at%2009.33.30.png?dl=0

**Comment by Quicksaver** [comment]
That's an unfair comparison, that arrow icon is much smaller by tradition than any other button. Try placing any other toolbar button next to TG's button, or even go to TG's preferences and disable showing the active group name, so it show the icon, and you'll see they're much more similar.

**Comment by omega** [comment]
the + button, which is more similar width, albeit still perhaps a bit narrower:

https://dl.dropboxusercontent.com/s/422x59c9s1xbx5w/Screen%20Shot%202016-10-20%20at%2009.49.56.png?dl=0

the tab-groups button:

https://dl.dropboxusercontent.com/s/qp24wcy6d3750ph/Screen%20Shot%202016-10-20%20at%2009.50.35.png?dl=0

My intention isn't to be unfair, just to give feedback that the button, while looking better, could look even better and more like it belongs, with a bit more padding.. I'll shut up now though, by saying thank you for maintaining this addon ❤️ , which is one of the reasons I love firefox still ❤️

**Comment by Quicksaver** [comment]
I didn't say you were unfair, I said the comparison was, because they're different kinds of buttons. ;)

The plus button and the arrow button use much smaller icons than any other toolbar button, on purpose. They are meant to be more subtle. If you look at those two last screenshots, you can see how the buttons are exactly the same width, even though the icon for TG's button is definitely bigger; this will happen for every single other toolbar button you'll want to place in that area. That's just how the Firefox theme itself is supposed to look.

**Comment by omega** [comment]
ok, I see your point. Wider buttons added there have less padding as well.
