### ISSUE TITLE
[CTRL–E] hotkey doesn't activate after restarting Firefox

### ISSUE THREAD

**Issue by jmain33** [Quicksaver/Tab-Groups#442]
Every time I launch FFox I need to go into TG's options and reapply the [Ctrl–E] hotkey. I assigned it to opening/exiting group manager. The binding is not lost it just doesn't seem to set its hook into FFox properly. By default FFox uses that hotkey to focus on search entry, but my search hotkey has already been changed to something else. The other hotkeys initialize OK and group manager activates after restart when using different hotkeys. I assume there's a problem with Firefox taking ownership of the original hotkey despite the fact that it's been reassigned.

*I know this is a fringe issue, so if you don't think it's worth looking into I'll close this topic and just assign a different hotkey to that purpose.*

Firefox v47.0.1 w/ Tab Groups v2.1b5

Might be the same as #428 though that's supposedly been fixed since v2.1b2.

**Comment by Quicksaver** [comment]
How are you re-assigning the original Ctrl+E?

**Comment by jmain33** [comment]
[Dorando Keyconfig](https://addons.mozilla.org/en-US/firefox/addon/dorando-keyconfig/)

**Comment by mzso** [comment]
I was about to report this. It feels natural to also use "E" for the quick access panel.

I also use keyconfig. I deactivated the default shortcut (which I only used by accident to much frustration) then set it in TG. It also gout unbound for me.

Also apparently alt+E or anything with just just the "alt" modifier (besides Fxx) is unavaible. Any good reason for this? I have a prerence for one hand (left hand) shortcuts for which alt and control is convenient.

(BTW, why doesn't TG allow hotkey overrides? )

**Comment by Quicksaver** [comment]
See #171.

> Also apparently alt+E or anything with just just the "alt" modifier (besides Fxx), and even shift+alt is unavailable. Any good reason for this?

Those are used traditionally to open menus (try <kbd>alt</kbd>+<kbd>e</kbd> to open the Edit menu), which can also change with locales, which would be a whole other level of uncertainty to find out automatically which ones exist and are active. I decided to just not allow any of those to avoid (potentially troublesome) conflicts.

> BTW, why doesn't TG allow hotkey overrides?

Because that's not the goal of the add-on. ;)

> CTRL+ALT+E just simply doesn't work. (I suppose it's the usual firefox realm bug with the third character of keys)

It's actually OS realm, not Firefox at all, but yep.

**Comment by mzso** [comment]
I always hated the alt+key thing for menus. Never used them. They're not even real shortcuts. pressing alt just gives focus to the menubar, sometimes. And I have many alt+something shortcuts in FF already.
