### ISSUE TITLE
Sort Tabs by URL compatibility

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/Tab-Groups#448]
For the add-on [Sort Tabs by URL](https://addons.mozilla.org/en-US/firefox/addon/sort-tabs-by-url), I want it to only sort tabs within the current tab group (rather than all groups). What changes need to be made to make that possible?

See https://github.com/andymckay/sort-tabs-by-url/issues/6

**Comment by Quicksaver** [comment]
> What changes need to be made to make that possible?

Good question...

**Comment by Quicksaver** [comment]
Probably won't happen until Tab Groups becomes a WebExtension itself, that will take a while.

**Comment by Keith94** [comment]
I see, would it be easier to add compatibility for an alternative [Unique Tabs](https://addons.mozilla.org/en-US/firefox/addon/uniqtabs/) ? It has the same problem but, hasn't been updated in a while too.

**Comment by Quicksaver** [comment]
I'll have to check it out. Does it work on its own at least? As you mentioned, it's a bit old now, and I've seen some reports that it's not working very well anymore.

**Comment by Keith94** [comment]
Yes, it works fine on its own, just the multiple tab groups issue like I mentioned.

**Comment by Quicksaver** [comment]
Unfortunately no, Unique Tabs fetches all tabs specifically, there's no way for me to override that with only the current group's tabs from within Tab Groups. :(

**Comment by Keith94** [comment]
Bummer, thanks for taking a look though. I guess you can close this if there's no way around it. :p

**Comment by Quicksaver** [comment]
I'll leave it open to remind me to check out Sort Tabs by URL when I can do something about it. ;)

**Comment by Keith94** [comment]
Luís, what about adding tab sorting functionality to Tab Groups, or is it outside the scope of the project?

I know you can sort *group titles* through the add-on but not *tab addresses*.

Since the issue seems to be regarding Tab Groups itself, I thought maybe a built-in solution would work.

**Comment by Quicksaver** [comment]
Yeah it's something already planned (I thought there was an issue for that already, but I can't seem to find it right now so maybe I was wrong...). I'm keeping this issue open though until then, because I may add compatibility to those types of add-ons first, or I might not, depending on how I tackle the issue; adding the ability directly to Tab Groups might just be simpler in the end. ;)

**Comment by Keith94** [comment]
Of course, whichever solution is easier and quicker to implement works for me.

Having a lesser amount of installed add-ons in the browser is usually good too.

**Comment by Keith94** [comment]
>I thought there was an issue for that already

Seems the tab sorting idea was first mentioned in #414, just FYI :)
