### ISSUE TITLE
Preferences window not functioning

### ISSUE THREAD

**Issue by rrkk** [Quicksaver/Tab-Groups#449]
I've been trying to get to the preferences for the add-on but can never get to it. When I press the Preferences button, a new window opens, but the page is blank, nothing loads on it.

I tried disabling all of my other add-ons, and it still remains blank.

**Comment by Quicksaver** [comment]
What operating system, Firefox version and add-on version are you using?

**Comment by rrkk** [comment]
The most recent version.

**Comment by Quicksaver** [comment]
That's really not helpful. Please check your Firefox's about dialog for its version, and the add-on's manager for Tab Groups version. And what operating system are you on?

**Comment by Quicksaver** [comment]
And please try [beta version 2.1b8](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b8) and let me know if it helps at all.

**Comment by Quicksaver** [comment]
Please re-open if you still have this problem with the latest version 2.1.
