### ISSUE TITLE
Allow mapping of "control" in OS X

### ISSUE THREAD

**Issue by commandline** [Quicksaver/Tab-Groups#45]
With Firefox on my Linux machines, I can use control, with a back tick, just like the original feature this re-implements. At some point, that stopped working on my one OS X machine. Looking at the preferences, this is not a booster key under OS X I can assign even though I have a keyboard with command, option and control. It is really frustrating to have different key mappings across operating systems, especially since what might be a suitable alternative, command-back tick is a global hotkey for cycling windows for the active application so cannot actually be mapped by the add on.

**Comment by Quicksaver** [comment]
Can you confirm this is the same as #39?

**Comment by commandline** [comment]
Yes, the build linked in that issue completely addresses my issue--any ETA on a signed release of that version?

**Comment by Quicksaver** [comment]
If not tomorrow, over the weekend. :)

**Comment by commandline** [comment]
Awesome--thanks for the quick response and the great add on.

**Comment by Quicksaver** [comment]
You're very welcome, I hope you keep enjoying it.
