### ISSUE TITLE
Lacks open=true attribute for button

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/Tab-Groups#450]
Other toolbar buttons have a changing background color while the panel is open, and those buttons have that `open="true"` attribute, but Tab Groups button doesn't have the same. Is that intentional?

**Comment by Quicksaver** [comment]
Not really, I just never remembered to add that :) (Most other add-ons with similar buttons probably use the SDK, which automates this I believe.)

**Comment by Quicksaver** [comment]
Should be fine in [beta version 2.1b7](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1b7).
