### ISSUE TITLE
I cannot find the "Tab Groups" icon on the Firefox Toolbar

### ISSUE THREAD

**Issue by sivulabill** [Quicksaver/Tab-Groups#452]
Tuesday Oct-25-2016, 1028 (Central Time, U.S.)
I just installed "Tab Groups" (PortableApps Firefox v49.0.2)..  (I did a "Memory Restart", AND fully terminated, with two windows, and re-opened same instance of Firefox.)
I appear to have approximately nine Icons on my toolbar, but none (I think) are "Tab-Groups".
     (I hovered over each, to check.)
I include (I think) a  Screen-Capture of upper-area of my Firefox Screen.
![1p-16ar-a3](https://cloud.githubusercontent.com/assets/23057525/19692445/9370c07a-9a9d-11e6-81aa-51a7c6145f3a.png)

**Comment by Quicksaver** [comment]
The button should appear next to your tabs, but because your tabs on the side, it may not be showing buttons in that area because of that. If you disable whatever it is you're using to place your tabs like that, can you find the button then?

What are you using to show your tabs like that by the way?

**Comment by iShyboy** [comment]
It's not Tree Style Tab? Hm, it seem more neat than TST from the screenshots of AMO. I'm curious of what addon it's the one with the 3 line hamburguer menu.

**Comment by Keith94** [comment]
>What are you using to show your tabs like that by the way?

Seems like the one called "[Vertical Tabs (Simplified)](https://addons.mozilla.org/addon/vertical-tabs-simplified/)" or perhaps modified version of that.

**Comment by iShyboy** [comment]
hm, my TG icon still appear with the addon. What's the name of the addon at left of Tab-Memory @Keith94 ?

**Comment by Keith94** [comment]
No idea, I guess the thread author would know :p

**Comment by sivulabill** [comment]
"Vertical Tabs" (Firefox AddOn) causes each tab's icon/short-description to show on left margin, going down the webpage, allowing approximately 45 tabs, before they force scrolling. (The user can decrease/increase the width of ALL the tabs.)  Unfortunately, when I disable "Vertical Tabs", they do not go away.  (Note: To make  Vertical-Tabs "work", the user must disable, then enable them, after starting Firefox. (A change to Firefox requires the user to do this, or Vertical-Tabs will not work! 
MAYBE someday, the developer will fix this problem.)
To follow your advice (due to my tendency to open MANY tabs), I will probably install one additional copy of PortableApps Firefox, WITHOUT installing Vertical-Tabs, but WITH installing Tab-Groups, to test ability to "see" the Tab-Groups icon.  
Thanks for the information (that the icon appears after EACH tab, NOT on the toolbar.)  
I will return after I implement the test.

**Comment by sivulabill** [comment]
"Vertical Tabs" (which I just read, has been discontinued), is the AddOn that normally puts my Tabs going down the left margin. (Apparently both "Vertical Tabs Reloaded" and "Vertical Tabs Simplified are available alternatives.
To iShyBoy, the AddOn (in my file) to the left of Tab-Memory, was "List Tabs" (which when executed, creates information on every tab in the current window, on separate ASCII lines, placed onto the 
Windows Clipboard). In installing the new copy of Firefox, I could not find the AddOn "List Tabs".
I installed another copy of PortableApps Firefox.  Perhaps because I have just installed "Tab Groups", the (3 icons: a "+", a down arrow, and a "bricks" icon) appear to the right of the rightmost "tab".
I enclose one Screen-Capture, which shows both my AddOns screen, and my Tabs (with 3 icons for Tab-Groups showing, located to the right of ALL my Tabs!.) I did not correctly remove two prior 
Screen-Captures (if 3 show up, please ignore the first two; 1p-16ar-a3h.png is the correct one). 
After I submit this update, I'll try activating each, separately, of the DIFFERENT  "Vertical Tabs" AddOn's.
![1p-16ar-a3h](https://cloud.githubusercontent.com/assets/23057525/19795971/5287eae2-9ca6-11e6-82ce-96d5dd8eb1ca.png)

**Comment by sivulabill** [comment]
1242am(Central Time US), 28Fri-2016-Oct...
I tried enabling (separately)  each of "Vertical Tabs Simplified", and "Vertical Tabs (Reloaded)". 
Both allowed me to extend very-far-to-the-right, from the default width of the Tabs-area, but neither view 
showed any of the "Tab-Groups" (3 icons). 
It appears that I cannot simultaneously have BOTH  
"Tab-Groups" organizational (& memory/CPU savings) ability, 
AND  ability to display 45 tabs simultaneously (i.e., running down the left margin of browser window). 
When I get time, I may explore other  Tab AddOns (to minimize the RAM/CPU usage of many Tabs, while being able to recall them to active-state after disposing of some/many of 
the currently-active Tabs.)
I am leaving this topic, probably for a couple days, but will return (both to check on your comments, 
and to document any additional experiments/conclusions of mine.)

**Comment by Quicksaver** [comment]
Before anything I should mention, your tabs look very weird in that screenshot. There's no active tab, and they seem much large and much taller than they should be. Are you sure none of your other add-ons are affecting them? Or even a custom theme or userChrome.css? Have you restarted Firefox after disabling each of the Vertical Tabs add-ons? I've had trouble disabling them on occasion and needed to restart Firefox to do it.

I have a feeling that whatever is causing your tabs to look like that is also causing the buttons to not appear when you enable any Vertical Tabs add-on.

> with 3 icons for Tab-Groups showing, located to the right of ALL my Tabs!

Only the "bricks" icon as you put it is the Tab Groups button, the others are from Firefox itself. But yeah, that's where it's supposed to be. ;)

If you can't figure out what's causing your tabs to look like that, you have a couple of alternatives. Disable Vertical Tabs temporarily, then enter customize mode and move the Tab Groups button somewhere else in your toolbar. Then you can re-enable Vertical Tabs.

Or you can try Test Pilot's [Tab Center](https://testpilot.firefox.com/experiments/tab-center/) instead. :)

**Comment by sivulabill** [comment]
I realized I should share a Screen-Capture of my success with the combination of 
"Tab Groups" and "Vertical Tabs (reloaded)". (Note: once again I simply DELETED the characters on screen, 
when I updated the Screen-Capture.  If two show, it is the 2nd one that I wanted to keep.)
![1p-16ar-a3p](https://cloud.githubusercontent.com/assets/23057525/19808441/85a38ba4-9cea-11e6-8e26-ecba87730ca9.png)

**Comment by sivulabill** [comment]
Note:  now only 33 Tabs (vs 45) show up (before I have to start scrolling), but it's a worthwhile tradoff, to achieve "Tab-Groups" functionality!.
