### ISSUE TITLE
gTaskbarTabGroup is undefined

### ISSUE THREAD

**Issue by Keith94** [Quicksaver/Tab-Groups#453]
Managing tab groups (opening and closing) gives these errors... are they important?

```
TypeError: gTaskbarTabGroup is undefined[Learn More]  TabView.jsm:150:5
TypeError: gTaskbarTabGroup is undefined[Learn More]  TabView.jsm:159:5
```

**Comment by Quicksaver** [comment]
They're not, I just missed a check in there to prevent those from appearing, but they're not blocking execution of anything luckily. Actually, by coincidence I just fixed it earlier today locally. I'll push a proper commit tomorrow.
