### ISSUE TITLE
Remove and Save

### ISSUE THREAD

**Issue by KitchM** [Quicksaver/Tab-Groups#454]
What is the length of time that Tab-Groups will save the complete forward and back history on each tab?  Also, is there a way to actually remove and save a tab into a separate repository so that it does not have to be listed within the Tab-Groups system.  My Firefox is too slow with all my tabs even separated into groups.

Thanks.

**Comment by Quicksaver** [comment]
Neither of those is controlled by Tab Groups. Page history is all Firefox, Tab Groups doesn't touch that at all. And the tabs still exist even though they are in other groups. You may want to try add-ons that unload tabs to try and improve that (a feature already planned for Tab Groups but not yet implemented). But all Tab Groups does is organize your tabs, their memory management is still all Firefox.

**Comment by KitchM** [comment]
Thanks much.  You are the first person to actually help me narrow down the way to solve my problem.  I appreciated it.

**Comment by Quicksaver** [comment]
You're very welcome, I'm glad to hear it's working better now. Please let me know if you ever run into any issues with Tab Groups.
