### ISSUE TITLE
Grid diplay: when drag group on another group do move instead exchange

### ISSUE THREAD

**Issue by deltaone** [Quicksaver/Tab-Groups#458]
if its not bug, please do question what i need - move or exchange (move ruin my layout)

**Comment by Quicksaver** [comment]
As explained in the release notes, this was an intended change. The previous exchange method wasn't very intuitive, so it was replaced with the current method. I realize it will take some getting used to, but I believe in the end it's for the best.

**Comment by deltaone** [comment]
you can add a question when moving about what action I want to accomplish?

**Comment by Quicksaver** [comment]
Is there a need for it? If you want to exchange groups, just move the group you want to change to place of the other group, and then move that other group to the place where the original group was. That should work just fine, doesn't it?

**Comment by deltaone** [comment]
possible but inconvenient

**Comment by Quicksaver** [comment]
True, it takes two gestures instead of one, but "inserting" a group in between two other groups was much more inconvenient before, as you had to move around a lot more groups to accomplish it.
