### ISSUE TITLE
Grid display: all layout in [+] icons

### ISSUE THREAD

**Issue by deltaone** [Quicksaver/Tab-Groups#459]
please remove [+] image from groups, i have fixed number of groups and all my layout filled with these icons (add groups button also invisible in huge massive of these icons)

or add option for this

![example](https://cloud.githubusercontent.com/assets/822865/19771159/03a24dc4-9c73-11e6-91e5-84c4aa270757.jpg)

**Comment by Quicksaver** [comment]
Those appear only on empty groups, which is what you have. They're there should you want to open new tabs quickly in those groups. If you don't you can just ignore them, you don't really gain anything by hiding them, the groups themselves would still occupy the exact same amount of space without them. Although you can do that easily with Stylish if you want to.

**Comment by deltaone** [comment]
how i can do it with Stylish ?

**Comment by Quicksaver** [comment]
Something like this:
```CSS
.groupItem .create-new {
  display: none;
}
```
Although again, you really don't gain anything by doing it.

**Comment by deltaone** [comment]
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document url("chrome://tabgroups/content/tabview.xhtml) {
  .groupItem .create-new {
   display: none;
  }
}

not work, what url i must provide ?

**Comment by Quicksaver** [comment]
Works for me, you're missing the end quote in the moz-document line though.
