### ISSUE TITLE
Plugin updates automatically without user's permission.

### ISSUE THREAD

**Issue by yuriyav** [Quicksaver/Tab-Groups#461]
I was not able to find a knob to control autoupdate settings besides of updating the plugin silently or notifying the user about the performed update post factum.
IMO uncontrollable autoupdate is a deviant behavior/bug.
In general there must be no non- user initiated and non-user controllable activities in the software.
I would prefer the typical three choice update model also available in firefox: {automatic | automatic check for new updates and notification | manual check} and to have the ability to read the release notes/changelog before accepting an update.

**Comment by Quicksaver** [comment]
That's all done in Firefox's Add-ons Manager, the add-on itself plays no part in either auto or manual updating. Go to your Add-ons Manager and change your auto-update settings there, you can do it either globally or per-addon.
