### ISSUE TITLE
Losing all tabs because of incorrect Firefox closing

### ISSUE THREAD

**Issue by ArtRet** [Quicksaver/Tab-Groups#462]
Hello!

Today I lost all my tabs. Firefox was very slow, switching among tabs was slow, opening new tabs was slow. So I decided to restart Firefox. I did it but it didn't help. Then I did it again but while Firefox was opening slowly I decided to reboot my system. I saw a window that Firefox didn't response than my system rebooted. I opened Firefox on rebooted system and there were no tabs at all except a blank one.

Tab Groups 2.1, Firefox 49.0, Ubuntu 16.04.

It is the second time. The first time it happened without system reboot, killing of Firefox process during its lag led to this situation.

It would be great if you fix the problem.

**Comment by Quicksaver** [comment]
When Firefox crashes and fails to save your session, sometimes you can still get it back, by immediately going to the History menu and click on "Restore Previous Session" or open one of the "Recently Closed Windows".

If those don't work or aren't available to you, you can try the Backup & Restore feature in the add-on's preferences, to restore your tabs from a recent automated backup. Start with the most recent backup first, probably one of the crash recovery ones, and work your way down in backup creation time until you find the tabs closest to what you had before.

As for Firefox being slow, is it related to Tab Groups? P*lease try disabling Tab Groups, but before restarting Firefox, immediately go to your Firefox's options and change "When Firefox starts" to "Show my windows and tabs from last time". Now you can restart Firefox without losing your tabs, including tabs from other groups (they are still there, they are just hidden and you won't be able to access them without Tab Groups of course) and see if Firefox still lags. You can re-enable Tab Groups without losing any of your groups and tabs after testing this.

**Comment by ArtRet** [comment]
Unfortunately "Recently Closed Windows" and "Restore Previous Session" weren't active after the crash.
I can't judge whether Tab Groups add-on is responsible for Firefox slowness. Next time it occurs I will perform your recommendations.

**Comment by claell** [comment]
Have you tried to use the "Backup & Restore feature" from the addon? Sounds like it does automatic backups and they might help.

Probably the data loss is not caused by the addon, but by killing Firefox, although Firefox normally still recovers the last session or starts with a recovery window when this happens.

**Comment by ArtRet** [comment]
I haven't tried yet but I'm going to try =)


Also my Firefox works fine so far after the latest crash. And that is why I didn't kill it again.

**Comment by claell** [comment]
Nice to hear that. I also didn't know about this auto-backups before.

**Comment by Quicksaver** [comment]
Please let me know if it starts happening and you believe the slowness or the crash is related to Tab Groups.
