### ISSUE TITLE
Black border when there's only one tab

### ISSUE THREAD

**Issue by garyking** [Quicksaver/Tab-Groups#463]
This is a visual bug. When there's only one tab in a group, then there's a black border around it. If there's two or more tabs, then this border does not appear.

Please fix it so that the black border does not appear when there's only one tab. Screenshots attached.

![black border on one tab](https://cloud.githubusercontent.com/assets/343940/19819202/9a859418-9d21-11e6-8100-d76496441038.png)
![no border on two tabs](https://cloud.githubusercontent.com/assets/343940/19819315/0a9d8dbe-9d22-11e6-99bc-d8a667520700.png)

**Comment by Quicksaver** [comment]
That is because apparently the page itself is smaller than the dimensions of the snapshot it tries to take. That's not supposed to happen though. Do you have any sidebars open, or anything else that takes space that would otherwise be reserved for the tabs?

**Comment by garyking** [comment]
I use [Zoom Page](https://addons.mozilla.org/en-US/firefox/addon/zoom-page/) and that was causing this problem. I will continue using Zoom Page since the problem is just a minor visual bug.

**Comment by Quicksaver** [comment]
Ah, you're right that it's not considering zoom at all. I'll be sure to look into it as soon as I can.

**Comment by claell** [comment]
I can confirm that this happens when zooming into a page (without any special addon for it)

**Comment by Quicksaver** [comment]
FYI it is considering zoom, but a high enough zoom can cause the page to be smaller than the actual thumbnail.
