### ISSUE TITLE
Lost all my Tabs groups ! :(

### ISSUE THREAD

**Issue by mikhoul** [Quicksaver/Tab-Groups#469]
Hi,

I was busy since few weeks on a project so I was using a spacial group for that time and today I needed a old tab in my other projects that I don't have in my bookmarks but when I go to see my other group there was none of them :crying_cat_face:  .

Since I have a daily backup scheduled I should be able to retrieve them but I need to know where to look to find them... 

Also tell me if you need to have some information to fix the "bug".

I use latest Firefox under Windows 7/64 and latest Tabs Group.  :octocat: 

Thanks ! 😊

**Comment by Quicksaver** [comment]
> Since I have a daily backup scheduled I should be able to retrieve them but I need to know where to look to find them...

How are you scheduling this? Have you tried going to the Backup & Restore page in the add-on's preferences to see if you can restore your tabs from a recent automatic backup?

> Also tell me if you need to have some information to fix the "bug".

That will depend on what the bug actually was. Of course it's not supposed to lose groups and tabs out of the blue just like that. But from your words it sounds like you only noticed the problem much after it actually occurred. For instance, did you at any point notice that you started Firefox with only your homepage instead of the current group? Any "Oops, Firefox couldn't restore your tabs." or Firefox crashed at any time or anything of the sort?

Or could you have opened a new window and those other groups have been in another window? Remember that groups are window-specific (for now), so if you open a new window and close the previous one, you'll lose your groups (unless you re-open that window before exiting Firefox of course).

**Comment by mikhoul** [comment]
> Have you tried going to the Backup & Restore page in the add-on's preferences to see if you can restore your tabs from a recent automatic backup?

It's not in the recent backup sadly, worst come to worst I've made backup from tab group in august but I don't remember what's change I could have done since that time.

> How are you scheduling this? 

I use EaseUS To do incremental backup for my whole system daily so I have the last 90 days. :computer: 

I need to know if TabsGroup is able to import sessions without losing my current session ?  

If I'm right I could find old session in the Firefox Session folder from my backups.

I've see the the my session now are around 500K and the old one's were around 10Mb 
I can also tell that the last backup from tabgroups update was 27-10-2016  and was only 28k


A good idea could be to have an option to automate the backup of the tabgroups once in a while automatically, like a small scheduler where we could choose daily weekly or monthly.


Regards :smile_cat:

**Comment by Quicksaver** [comment]
> I need to know if TabsGroup is able to import sessions without losing my current session ? 

If you can find a backup of the sessionstore.js file, by default located in the root of your [Firefox profile folder](http://kb.mozillazine.org/Profile_folder_-_Firefox#Finding_the_profile_folder), you can load that file through the Backup & Restore page of Tab Groups' preferences and choose only the groups and tabs that are missing. Your already existing opened tabs and groups will be unaffected, the restore will add new groups with those imported tabs into the Firefox window.

> A good idea could be to have an option to automate the backup of the tabgroups once in a while automatically, like a small scheduler where we could choose daily weekly or monthly.

You can do that with [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/), it should be fully compatible with Tab Groups, so there's no need to add the same functionality to it. :)

**Comment by leodag** [comment]
Also if the backup occurred while Firefox was open, the session should be stored in `<profile directory>/sessionstore-backups/recovery.js`. I think if you close Firefox, copy from your backup to that directory, delete `<profile>/sessionstore.js`, then next time you open it you'll be presented a "restore session" tab.

**Comment by Quicksaver** [comment]
> Also if the backup occurred while Firefox was open, the session should be stored in <profile directory>/sessionstore-backups/recovery.js.

Very good point! Thanks for the reminder.

> I think if you close Firefox, copy from your backup to that directory, delete <profile>/sessionstore.js, then next time you open it you'll be presented a "restore session" tab.

This will cause you to lose your current session, which is not optimal in this specific case, which is why I suggested using the add-on's backup and restore feature with that file instead. ;)

**Comment by leodag** [comment]
> This will cause you to lose your current session, which is not optimal in this specific case, which is why I suggested using the add-on's backup and restore feature with that file instead. ;)

That's indeed a better way to do it.

**Comment by mikhoul** [comment]
Thanks a lot for all the information,  :smiley_cat:  most of the time Firefox is open when my backup run ;-)  So I will try to find the latest "recovery.js." with all my old sessions and load it from  the Backup & Restore page of Tab Groups. 

Daily backup prove again to be very useful... :desktop_computer: 

Session Manager is a "big" addon that slowdown the startup time of Firefox, that's why I'd like to have a simple save tabs feature that can save only the URL's without  all the other sessions data.


Best Regards :octocat:

**Comment by mikhoul** [comment]
Done everything is back !  😄

**Comment by Quicksaver** [comment]
That's good to hear. If you keep losing your groups like that please let me know. Of course that's not supposed to happen. If it was a one time thing, then we can assign that to bad luck potentially after a crash, but if it keeps happening we'll have to figure out what's happening. :)

**Comment by innov8tor3** [comment]
For someone who is a FireFox newbie, could someone recap on this, as I have also lost several pages of tabs, including summary Tabs I created using OneTab, and then deleted from Chrome, hence I also have no backup ...

The first time I relaunched Firefox, the Tab Groups came back, but not this time.

Would the Crash information be helpful ...?

about:crashes

Thanks.
