### ISSUE TITLE
Manage my groups button not on toolbar

### ISSUE THREAD

**Issue by dmac91** [Quicksaver/Tab-Groups#473]
![tab groups](https://cloud.githubusercontent.com/assets/23230761/19957612/3fd4c6fe-a1ec-11e6-833b-5e3ea320b2ba.png)

I'm not sure if this is a bug or request for a feature but it would be super handy to have that button on the toolbar. As you can see I had disabled all add-ons and restarted firefox but the issue didn't resolve.

Thank you for the great application.

**Comment by Quicksaver** [comment]
You can change that behavior by going to the add-on's preferences and disable "Click to open the quick access panel" in the Toolbar button section, it will go directly to groups view then.
