### ISSUE TITLE
Automatic Backup at user-defined intervals

### ISSUE THREAD

**Issue by nisargshah95** [Quicksaver/Tab-Groups#474]
I love the backup/restore feature, but is it possible to have automatic backup at a user-defined time interval by either creating a new backup file or simply synchronizing with the last backup file.

**Comment by Quicksaver** [comment]
You can do that with [Session Manager](https://addons.mozilla.org/firefox/addon/session-manager/), it should be fully compatible with Tab Groups, so there's no need to add the same functionality to it. :)

**Comment by allo-** [comment]
Maybe you can add a link to the Session Manager addon on the save/restore settings page.
