### ISSUE TITLE
Tab Group button is grey on Linux

### ISSUE THREAD

**Issue by sabret00the** [Quicksaver/Tab-Groups#477]
![tabgroupbutton](https://cloud.githubusercontent.com/assets/203217/20140615/0cb71f1e-a684-11e6-8379-988cd232c8c0.png)

**Comment by Quicksaver** [comment]
Are you using the latest version 2.1 of the add-on?

**Comment by sabret00the** [comment]
Yes I'm using 2.1. It was actually fine before the latest update.

**Comment by Quicksaver** [comment]
Looks fine to me on Linux, it shows the light icon on the dark toolbar as expected. If you disable all your other add-ons and themes (except for Tab Groups of course), does it still look like that? It could be some sort of incompatibility.

I forgot to ask before, what Firefox version are you on?

**Comment by sabret00the** [comment]
52.0a1 (2016-11-10) (64-bit)
I'm using Ubuntu 16.10 BTW

**Comment by Quicksaver** [comment]
Have you tried without other add-ons and with the default Firefox theme as I mentioned?

**Comment by DavidRegev** [comment]
I have the same issue, but it occurs only if `layout.css.devPixelsPerPx` (in `about:config`) is set to anything higher than `1.1`. So I think the dark theme is not being detected when the UI is scaled up.

**Comment by Quicksaver** [comment]
Ah you're right. The package has the wrong icon... I don't know how this happened... I'll be sure to correct this for the next update.

**Comment by DavidRegev** [comment]
Thanks!

**Comment by Quicksaver** [comment]
[Beta version 2.1.4b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1.4b1) should now show the correct icon. I'm very sorry about this, I don't know how I could have missed this before.

**Comment by DavidRegev** [comment]
The beta fixed the problem. Thanks!
