### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mikhoul** [Quicksaver/Tab-Groups#479]
Hi, 

I usually just use one Windows with multiple tabs but today I was using 2 Windows and when I look in TG from my second windows I only see the tab I have in this window, I don't see any tabs or tab-group from my first windows.

Is this normal ?  Cause I was looking to store one of my tabs in another tab-group but there was no tab group. :disappointed: 

Here's a screenshot of the 2 windows with Tabs-Group manager open.
http://i.imgur.com/9mxwrij.png

**Comment by Quicksaver** [comment]
Yep, groups are window specific just like tabs are. See #82 and #174.
