### ISSUE TITLE
Context Menu for Tabs in the Quick Access Menu

### ISSUE THREAD

**Issue by ThoDHa** [Quicksaver/Tab-Groups#481]
![2016-11-10 18_23_54-](https://cloud.githubusercontent.com/assets/4588986/20199826/e5b24b06-a772-11e6-8ba0-2524345fae36.png)

Can context menus be add for tabs in the Quick Access Menu :)

**Comment by Quicksaver** [comment]
Already planned, will be done as part of #5.
