### ISSUE TITLE
Wishlist: allow pinning a tab only to one tab group

### ISSUE THREAD

**Issue by zorkerz** [Quicksaver/Tab-Groups#483]
I love tab groups! Thank you for maintaining it. I use a tab group for home and a tab group for work. At home I have one set of tabs I would like pinned but at work I have an entirely different set of tabs I like to pin. It would be super cool if pinned tabs could be specific to tab groups.

**Comment by Quicksaver** [comment]
That's just not possible. Pinned tabs (a Firefox feature, not specific to Tab Groups) are implemented in a way specifically to always be visible. There is no easy distinction to be made, to implement something like this in the add-on will probably be impossible, and you wouldn't be gaining much from it anyway.
