### ISSUE TITLE
keyboard shortcut stopped working

### ISSUE THREAD

**Issue by escapewindow** [Quicksaver/Tab-Groups#485]
Command-shift-e worked until this morning.  I'm still able to use the mouse to get to the tab group view, but my muscle memory goes to cmd-shift-e every time.

I'm running OSX Firefox Nightly, 53.0a1 (2016-11-17) (64-bit)
I disabled a number of other addons to try to get to the bottom of this, and I installed Menu Wizard to see if another keyboard shortcut was interfering.  Looks ok.  Just for posterity, my addons list is

FxIF
Menu Wizard
Test Pilot: Min Vid, No More 404s, Page Shot, Tracking Protection
Open With
Privacy Badger
Tab Groups
Tree Style Tab

I had disabled everything but Tab Groups, Tree Style Tab, and Privacy Badger, but the shortcut still didn't work.

**Comment by Quicksaver** [comment]
Works fine for me. Is the shortcut still set in the add-on's preferences? Does it work if you disable all your other add-ons?

**Comment by escapewindow** [comment]
Ah, found it.  Boom 2 overrides cmd-shift-e.  Fixed!
http://www.globaldelight.com/boom/index.php
