### ISSUE TITLE
Export grouptabs does not save all tabs

### ISSUE THREAD

**Issue by JibsouX** [Quicksaver/Tab-Groups#489]
Hy i have many many tabs dispatch in 6 groups different when i want to export them in .json i dont have all the tabs (some group are missing and some tabs to)

i have try to load every tabs before the export but no change still the same bug, is there a tab limit because it export alway 101 tabs max... ?

Anyway Thanks for this plugin !!!

**Comment by Quicksaver** [comment]
There shouldn't be any limit. Does it work if you disable all your other add-ons except for Tab Groups?

Also, try this. Go to the Backup & Restore page in the add-on's preferences as usual, but don't backup yet. Open the browser console (Ctrl+Shift+J), clear it, and now try creating the backup. Does anything appear in the console when you do this?

**Comment by JibsouX** [comment]
Hy okey i found why and yes it's a bug : 
In fact if there is a about:blank tab the json parsing crash because the tab have in reality "no name"

<img width="1546" alt="capture 2016-11-20 a 17 17 51" src="https://cloud.githubusercontent.com/assets/5707449/20464354/23c0b808-af46-11e6-99a1-ccbb91b2f50c.png">

<img width="1548" alt="capture 2016-11-20 a 17 17 58" src="https://cloud.githubusercontent.com/assets/5707449/20464355/28119f76-af46-11e6-931d-0c9cfbdb95fc.png">

**Comment by Quicksaver** [comment]
The first error means one of your tabs apparently has no history, including having no "current page" open; it's probably a "Customize Firefox" placeholder tab, or some other kind of placeholder tab. This is probably the cause, the script will halt at this point, and of course it shouldn't, it should just skip that tab and move on to the next one.

This should be fixed now in [beta version 2.1.2b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1.2b2). Please give it a try and let me know how it works for you.

Also, backing up about:blank tabs, and any other about: tab, should work just fine. The fact they don't have a title is inconsequential, the function really doesn't care about that, if it doesn't have a title, it'll save a blank title.

The second error, related to the second screenshot, is also inconsequential. It just means it's a recently created tab that doesn't yet have any groups information related to it. It will just default to the current group (which is the only possibility for newly created tabs).
