### ISSUE TITLE
Small Glitch with Naming of Backup Files

### ISSUE THREAD

**Issue by AndrewFlet** [Quicksaver/Tab-Groups#49]
I noticed a small glitch today in the naming of backup files, both for tab groups and for preferences.

I noted your excellent scheme for including  year, date, and time (minutes and seconds)—the  scheme  worked perfectly during the closing months of the year (e.g.,  “tabGroups-2015-11-12-12-5-37.json”), however, currently (e.g., today January 12) the system is applying only zero for the month, rather than 01 (e.g., “tabGroups-2016-0-12-14-43-11.json” & “tabgroups-prefs-2016-0-12-14-44-10.json”); I suspect it will continue to do this for all months preceded by a zero—January through September—then work again for October through December. 

I continue to enjoy very much using your new Tab Groups  add-on following its untimely removal from Firefox. Not only is your new version is already well ahead of the original version from Mozilla, I note that you are continuing to work hard on improving it further. Again, many thanks!

Best regards!
~AF

**Comment by Quicksaver** [comment]
No, it's actually because the add-on is using a method to get the month that's zero-based (0 is January, 1 is February, 2 is March...). I never noticed that until now, thanks for letting me know. This'll be easy to fix.

**Comment by AndrewFlet** [comment]
Great--you are most welcome. Thanks for the explanation of how it works. I suspected that it might be relatively easy (for you) to fix. Keep up the good work!
