### ISSUE TITLE
Tab Groups Layout Panels Should NEVER Resize or Move

### ISSUE THREAD

**Issue by stricq** [Quicksaver/Tab-Groups#493]
The Tab Groups are always moving and rearranging and generally getting messed up and I keep having to rearrange them at least once or twice a week.  There should be a setting to set all of the Tab Group's panel size in concrete and not change the values no matter what.

**Comment by Quicksaver** [comment]
> The Tab Groups are always moving and rearranging and generally getting messed up and I keep having to rearrange them at least once or twice a week.

Why? Are you resizing the window?

**Comment by stricq** [comment]
Windows does it.  When your monitor is connected with HDMI or Display Port and the monitor is either turned off or goes to sleep Windows will resize the desktop and that causes the browser to resize and in turn the Tab Groups to get all jumbled up.  Also, just adding a new Tab Group panel will cause the existing panels to rearrange automatically.  Sometimes new panels are added automatically and everything gets moved around, and not just a little bit, they completely change size and location.

**Comment by Quicksaver** [comment]
> When your monitor is connected with HDMI or Display Port and the monitor is either turned off or goes to sleep Windows will resize the desktop

Why would it do that? Screen turning off is not the same as screen resizing. If it's doing that for you, you definitely have something misconfigured somewhere in your Windows settings. My screen turns off all the time and this never happens for me.

> Also, just adding a new Tab Group panel will cause the existing panels to rearrange automatically.

Please see #201 for my thoughts on that. Short answer: I don't plan on making any enhancements on this point any time soon.

> Sometimes new panels are added automatically

New panels should never be added automatically like this. I assume you meant about when creating new groups in other modes (single view or grid layout), or when importing from a backup, as those are the only cases when new groups can "appear" without being given proper dimensions (although that's still expected). Either way I think #201 also covers my thoughts on that, unless that's not what you meant, in which case please let me know.
