### ISSUE TITLE
"Restore Tab Groups" from Groups Manual Backup reverses tab order

### ISSUE THREAD

**Issue by iG8R** [Quicksaver/Tab-Groups#495]
Hello.
I found the same issue mentioned here https://github.com/Quicksaver/Tab-Groups/issues/128
I'm observing similar behavior.
After making manual backup and restoring it I'm getting, e.g.
Before backup:
"1st group" 1 2 3 4 5 6 7 (tabs)
After restoring:
"1st group" 7 6 5 4 3 2 1 (tabs)
I saw that you couldn't reproduce it so, what additional logs could I introduce you this issue will be fixed?
Best regards,
Igor.

**Comment by Quicksaver** [comment]
That's weird. Does it happen if you disable all your other add-ons except for Tab Groups? (Make the backup and after you disable the add-ons as well, to see if the problem is in creating the backup or in restoring from it.)

**Comment by iG8R** [comment]
Sorry for disturbing you. I found out what was the cause of such behavior.
It was due to the following item has been selected TabMixPlus -> Options -> Events -> New Tabs -> Open other tabs next to current one.
Please, add it to FAQ.
Thank you for your job.

**Comment by Quicksaver** [comment]
You're not disturbing at all, this what this page is here for after all. :)

[Beta version 2.1.2b4](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1.2b4) should import in the correct order with that preference enabled now. Please give it a try and let me know how it works for you.

**Comment by iG8R** [comment]
Now everything with the order of restored tabs is OK. Thank you :)
But I noticed some strange behavior after restoring a group.
E.g. I have following already launched groups:
Group 1 (1 2 3 4 **5** 6 7 8 9 Tabs) - active group with active tab #5
Group 2 (1 2 3 4 5 6 7 8 9 Tabs)
Group 3 (1 2 3 4 5 6 7 8 9 Tabs)
After restoring
Group 1 (1 2 3 4 **5** 6 7 8 9 Tabs) - active group with active tab #5
**Group 1*** (1 2 3 4 5 6 7 8 9 Tabs) (yes, this group has the same name as the first one, lets mark it with asterisk)
Group 2 (1 2 3 4 5 6 7 8 9 Tabs)
Group 3 (1 2 3 4 5 6 7 8 9 Tabs)
Then I switch from Group 1 with active tab #5 to Group 1* and 1st tab of this group is become active.
After this I return to Group 1 and tab #1 become active not tab #5.

**Comment by iG8R** [comment]
Also, one more wish.
Is it possible to add following menu items to the "Restore Tab Groups" list?
Select all groups and tabs, Deselect all groups and tabs, Select tabs only in current group, Deselect tabs only in current group, Revert selection, Collapse all, Expand all
It would be more comfortable to restore groups with these menu items.
Thank you.

**Comment by Quicksaver** [comment]
> Select all groups and tabs, Deselect all groups and tabs
> Revert selection, Collapse all, Expand all

That's #403.

> Select tabs only in current group, Deselect tabs only in current group

Not currently possible, it doesn't really know what exist groups correspond to what is on the backup. It would need some sort of unchanging unique identifier, and to be completely honest I don't see much gain from it other than some very specific situations.

Could still happen though, I just meant to say it's not really a priority. And either way would deserve its own issue, although I'd probably track it also in #403 anyway.

**Comment by Quicksaver** [comment]
> Then I switch from Group 1 with active tab 5 to Group 1* and 1st tab of this group is become active.
After this I return to Group 1 and tab #1 become active not tab #5.

Works as expected for me. Tab 5 is the active tab in both groups (the backup also knows that was the active tab when it was backed up, so it will restore that way as well).

Please try disabling all your other add-ons again to see if you can pinpoint a cause for this behavior and let me know in a new issue (it's unlikely it's related to the original issue here). It could be another TMP preference interfering too but at least from a quick try I'm not finding any.

**Comment by iG8R** [comment]
I tried it in absolutely blank profile with TabGroups add-on is only active.

> Works as expected for me. Tab 5 is the active tab in both groups (the backup also knows that was the active tab when it was backed up, so it will restore that way as well).

Not quite so, Tab 5 was active only in "Group 1", in "Group 1*" tab 1 was active before backing up.

**Comment by Quicksaver** [comment]
As I mentioned, please create new issues for... well, new issues. :wink: #498

**Comment by iG8R** [comment]
I'm very sorry for my slowpoke behavior :)

**Comment by Quicksaver** [comment]
Don't worry about it. I'm the one who's grateful for your bug reporting, the more you report, the less problems the add-on has. :wink:

**Comment by iG8R** [comment]
Thank you ;)
