### ISSUE TITLE
All tabs in all groups suddenly disappear

### ISSUE THREAD

**Issue by lepstep** [Quicksaver/Tab-Groups#499]
It's the second time this happens in two months.
All tabs disappear  after browser restart

**Comment by Quicksaver** [comment]
Does Firefox crash when you shut it down or reopen it? It's very likely a crash is the cause, and you should first try to determine what is the source of the crash (check if disabling your other add-ons helps with preventing crashes, start a new session (or even a new profile) in case your current one is corrupted, etc).

When Firefox crashes and fails to save your session, sometimes you can still get it back, by immediately going to the History menu and click on "Restore Previous Session" or open one of the "Recently Closed Windows".

It also could just be that Firefox failed to load your previous session for some reason, in which case the above should also work just fine.

If those don't work or aren't available to you, you can try the Backup & Restore feature in the add-on's preferences, to restore your tabs from a recent automated backup. Start with the most recent backup first, probably one of the crash recovery ones, and work your way down in backup creation time until you find the tabs closest to what you had before.

Other than this, there's really nothing I can do. Tab Groups is not handling session saving at all, it just appends the groups information to the tabs and Firefox saves it when it saves the tabs on its session.

**Comment by lepstep** [comment]
There was no crash. 
I had a few groups maybe 5, or 6 -  each with up to 15 tabs. 
I had an open group and then opened a new window (ctrl+N)
firefox was slow for some reason. 
I closed the named tabs window. then I closed the new window that I just opened.
when I started firefox again all groups disapeared. Later I noticed tabgroups has also been upgraded.
hope this helps.
I havn't used backup. will "Recently closed windows" would have helped to retrieve all tab groups?

**Comment by Quicksaver** [comment]
Yes, if you close your windows one by one, the next time you start Firefox, it will only restore the window closed last. The "Recently closed windows" menus should let you get back the previous window with all its tabs and groups. See #410.
