### ISSUE TITLE
Better Touch Support

### ISSUE THREAD

**Issue by tevi** [Quicksaver/Tab-Groups#50]
I'm trying to modify Firefox to be more touch friendly on my surface. I'm hoping this add-on will eventually completely replace the tab bar for me - I don't think that will happen because it will take a large redesign but simple tweaks should get the addon most of the way there.

Simple Tweaks
1. Option for larger close buttons
2. An undo close tab button
3. New Tab Button
4. Larger grabber spaces for group movement and resize

Hopefully you will consider some of the suggested changes and make them toggleable in the options.

**Comment by Quicksaver** [comment]
Most of those I'm already planning to add. And I'm also planning a few other changes (some are a bit extensive) that should also help with your situation. I have no ETA right now, but stay tuned. :)

**Comment by tengwar** [comment]
Perhaps using another method of closing would be better than enlarging the close buttons? For example: when user starts dragging a tab, display a trash icon somewhere. When used drops a tab onto the trash icon, the tab gets closed. (If the trash was displayed in the corner this wouldn't require aiming, unlike the close button.)

When I think about it, this trash icon could be also used for restoring tabs.

**Comment by tevi** [comment]
Great to hear. Mozilla really dropped the ball with this idea. Instead of writing an entire new code section for metro they could have just used tab groups and heavyweight themes to adopt some of the style guides. 

Looking forward to future changes. Fingers crossed this doesn't break too bad when they depreciate XUL, XPCOM, and the permissive add-on model support.

**Comment by Quicksaver** [comment]
aa6ff8156e1cc27dc4bc9892677ee743ffa8bfe9

**Comment by Quicksaver** [comment]
I've made several changes to buttons, icons, tabs, areas... etc, in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6), to hopefully improve touchscreen support. Please give it a try and let me know if you have any problems with it.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.

**Comment by tevi** [comment]
Overall a very good improvement. The buttons on the right side bar could be a little larger but they are still usable. Thanks for the update.
