### ISSUE TITLE
Close button for tabs clipping to next line

### ISSUE THREAD

**Issue by IsaacKhor** [Quicksaver/Tab-Groups#504]
I am hoping that this is not intended behaviour:

![untitled 2](https://cloud.githubusercontent.com/assets/6264789/21074272/b3d0ee10-bf2f-11e6-9feb-ee6d58d82bba.png)
![untitled 3](https://cloud.githubusercontent.com/assets/6264789/21074273/b421761e-bf2f-11e6-94fa-295b502ded13.png)
![untitled 4](https://cloud.githubusercontent.com/assets/6264789/21074274/b42676d2-bf2f-11e6-948d-dc7b17ae4df0.png)

As you can see, this problem persists for all views.

**Comment by Quicksaver** [comment]
It's not of course. Thanks for telling me about it, I must have broken it somehow with a recent patch. I'll be sure to fix it for the next update.

**Comment by Quicksaver** [comment]
[Beta version 2.1.3b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2.1.3b1) should fix this. Please give it a try and let me know if you still have any problems with it.

**Comment by IsaacKhor** [comment]
Fix confirmed: 

![untitled 5](https://cloud.githubusercontent.com/assets/6264789/21077637/021a7368-bf8d-11e6-9898-3bb19a9b2819.png)
