### ISSUE TITLE
signed version compatible with TMP

### ISSUE THREAD

**Issue by WilDieteren** [Quicksaver/Tab-Groups#51]
L.S.,

Any idea when there will be a signed version of Tab-Groups that is compatible with TMP? 1.0.2b1 works fine, but I would like to once again enable 'signatures.required'.

Wil Dieteren

**Comment by Quicksaver** [comment]
I've already uploaded version 1.0.2 to AMO. It will be signed as soon as it is reviewed and it should update automatically when that happens.

**Comment by Quicksaver** [comment]
Reviewed and signed now. :)
