### ISSUE TITLE
Since version 2.1.3 Firefox doesn't open with my Tab-Groups

### ISSUE THREAD

**Issue by NeoSeeU** [Quicksaver/Tab-Groups#513]
Hi

I'm on FF 50.1.0 and starting FF with last open Windows and Tabs setting. Having >10 Tabgroups, but FF opens with stored page set in FF Settings. Though I can restore my Tab-Groups using Session Manager. 

Difficult to rectify where the problem is, but it happens since Version 2.1.3 of Dec. 12.
What does "cs and de (not yet complete) locales" say? I am in Germany.

Thanks for your most appreciated work on Tab-Groups, you do alot for us. I can't browse without.

**Comment by Quicksaver** [comment]
What do you have set in Session Manager to do at startup?

> What does "cs and de (not yet complete) locales" say? I am in Germany.

This just means the german translation isn't complete yet, so some things will still be in the original english.

**Comment by NeoSeeU** [comment]
uuh despite I didn't change anything in SesssionMgr Setttings since installation, I can see under Start & End the start option says "windows and tabs from last session", which is the setting on my FF preferences. But the radio button above says "none". (confuses me) Have set it now to "Fixed Session" and "Last Session". It seems last SessionMgr update has brought this behavior.

**Comment by NeoSeeU** [comment]
btw: Have send u some bucks for your phenomenal efforts ... just a little clap on your shoulder. Well done ;-)

**Comment by Quicksaver** [comment]
First of all, thank you very much, I appreciate that. :)

Both of those options should actually do the same thing, only the first is Firefox's doing and the other is SM's. I wonder if SM could interfere with the normal restoring session function from Firefox, it seemed to work fine when I last tried it.

But I didn't fully understand, does it restore your tabs and groups now at least?

**Comment by Quicksaver** [comment]
> Everytime I start FF first thing I need to do is, clicking for once on the TabGroup button to manage my groups as an initial start, in order seeing my tabs sorted the way they should. If I don't do it, all tabs are in one tab all together.

Have you tried disabling all your other add-ons to see if it helps? This sounds a lot like #411 and #507.

> At the lower size I'm missing more stability when switching between thumb and small icons. - Hard to make it stay on small thumbs

You can disable tiling the icons if that's what you mean. You can do this in each group's options individually (the gear icon in each group), by disabling ```Tile page icons when thumbnails are too small``` or globally in the add-on's preferences page (in which case don't forget to click the ```Set these options for all groups``` button).

> Waiting for better adjustment at the quick end for your Version 1.4.7 slide down address row,

To be honest, I don't understand what this means. If you have a problem with it, please open an issue in its page. :wink:

**Comment by NeoSeeU** [comment]
There is a bit in common with this issues you posted, but I got it fixed when looking into FF and SessionMgr settings for security. Either off or choice. -> (pls see this shots, directLinks)
http://prntscr.com/dphq2o
http://prntscr.com/dphqpf
http://prntscr.com/dphs4b

It loads the TabGroups at FFstart.
My Addons are this ->
http://prntscr.com/dphtcg
http://prntscr.com/dphtvi

Regarding Thumbs arrangement I mean the free arrange mode jumps from smaller with thumbs to wide with tiles. I like the small thumbs staying. And the text format for title only mode on groups seems a bit bold and big to me.
I touched to resize         ->   http://prntscr.com/dpjalr
the frame jumps to this ->   http://prntscr.com/dpjhfw

So the OT is sorted out, thanks your help is very much appreciated by us tab jockeys ;)

**Comment by Quicksaver** [comment]
Ah yes, if you set Firefox to clear your browsing history when closing, you will lose your currently open tabs when you next open it. There's really no avoiding this from within Tab Groups, Firefox intends to clear the session when clearing browsing history.

So in short, you can't set Firefox to clear your browsing history if you wish to keep your groups on restart. There may be a way to do it through Session Manager, I haven't investigated that part of it to be honest.

> jumps from smaller with thumbs to wide with tiles. I like the small thumbs staying. And the text format for title only mode on groups seems a bit bold and big to me.

Could you please open separate issues for these? :wink:
