### ISSUE TITLE
Ctrl+shift+e shortcut doesn't work if TMP is installed too

### ISSUE THREAD

**Issue by FatOrangutan** [Quicksaver/Tab-Groups#514]
STR:

1) Install Tab Groups v2.1.3. Try the ctrl+shift+e shortcut - it works, as expected.
2) Install the latest dev build of Tab Mix Plus (TMP), v0.5.0.2pre.161211a2 from [here](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/versions/). Restart the browser. Try the shortcut - it triggers TMP's merge windows feature, but this is expected because it is also TMP's [new default shortcut](http://tabmixplus.org/forum/viewtopic.php?f=3&t=19581&start=160#p71376) for the feature.
3) Go into TMP's settings (TMP Options > Menu > Shortcuts) and either delete or change the shortcut for 'Merges windows together.' Now try the shortcut. Nothing happens.
4) Go into Tab Groups settings and change the shortcut to something else and then back to ctrl+shift+e. Try the shortcut - it works! Except restart the browser and it stops working again :(

I am testing things at FF v52.0a2, but can also reproduce on v51.

**Comment by FatOrangutan** [comment]
Fixed with the [latest](http://tabmixplus.org/forum/viewtopic.php?f=3&t=19581&start=180#p71439) dev build of TMP.

**Comment by Quicksaver** [comment]
Yeah, TMP's devs are experimenting with a couple of new keyboard shortcuts, and one of its versions was using the default shortcut for groups. It seems they changed it in the meantime, but they can always change it back. Please let me know if this happens again.
