### ISSUE TITLE
Firefox doesn't open in a group?

### ISSUE THREAD

**Issue by ddt000** [Quicksaver/Tab-Groups#517]
Hi, 

Sorry if this has already been addressed.  I searched but didn't read all 80 tickets.  

When I open Firefox it does open on my last used tab but it does not open in a tab group.  Instead it opens with what looks like all tabs from all groups on top.  The group button on the upper right says "MAIN GROUP", and if I click it I get your Panorama, and can enter a group.  

This started happening after restoring a complete loss of all tabs/groups from an older Session Manager save.

**Comment by ddt000** [comment]
Also, I've noticed now that when I click on the Group button (upper right) it doesn't take me directly to Panorama as it used to; instead it gives me a drop down list of groups, where I can select "manage my groups" at the bottom to open Panorama.  Can't find where to change this behavior.

**Comment by Quicksaver** [comment]
Does this happen if you disable all your other add-ons except for Tab Groups? It sounds a lot like #411 and #507.

> Also, I've noticed now that when I click on the Group button (upper right) it doesn't take me directly to Panorama as it used to; instead it gives me a drop down list of groups, where I can select "manage my groups" at the bottom to open Panorama. Can't find where to change this behavior.

It's in the add-on's preferences, ```Toolbar button``` - ```Click to open the quick access panel```.

**Comment by ddt000** [comment]
Not sure how "click to open the quick access panel" got checked.  Thanks for reminding me as I forgot that's what you call the drop down menu.  

I reviewed 411: its one of the ones I found by searching but with the discussion of unresponsive scripts and other errors I don't have I thought it wasn't the same issue.  I do have Session Manager enabled, and as I said this started happening when I recovered (most of) my tabs from an older session save.  

I reviewed #507: I don't have Grammarly.  My add ons consist of: Tab Groups, Session Manager, FireFTP, Flagfox, and a YouTube Video and Audio downloader.  I've added your FindBar Tweak since this behavior began (looking forward to exploring it).  Flashblock and Ghostery have been disabled for many moons, as have Adobe Acrobat Create PDF and Logitech Set Point Smooth Scrolling (disabled automatically by Firefox long ago).  But I assume by your questions that disabled add ons don't play a part (even though they are still installed).  

I'm going to try disabling all other add ons and then enabling them one by one to see if there is a conflict.  But I was guessing that loading the old Session Manager save may have corrupted something.  I wonder if the save was from Panorama days, prior to your Tab Groups?

**Comment by ddt000** [comment]
Disabling all other add ons, then restart, and I opened into the "main group" instead of all tabs or some amalgam!  Promising.  Now I will enable others one at a time.

**Comment by ddt000** [comment]
OK, I enabled the other add ons one at a time, starting with those I thought least likely to be involved.  I ended with Session Manager and am happy to report that Firefox continued to open into the Main Group.  

I'm fixed!  Thanks for the guidance.  I'm sure you are wondering why this behavior occurred, so if you want more info let me know.  I'm wondering if the old Session Manager save caused it.

**Comment by Quicksaver** [comment]
On the plus side, it's good that it's working as expected for now at least. 😄 

How many tabs and groups do you have? Does it usually take the browser long to startup?

Restoring an old session **could** have caused it, although it really shouldn't, but only the first time it loaded. After closing Firefox with the groups properly displayed, they should have remained the same when next starting, so that seems unlikely at least.

**Comment by ddt000** [comment]
I spoke too soon... I didn't think a computer restart could influence this.  But upon restart this morning Firefox did not open into a group.  I will keep an eye on this special behavior.  

I have 10 tab groups containing a bit over 200 tabs.  Startup and shutdown are fine; they don't all try to load.  In fact, if I eventually open to many my 32-bit Win7 PC complains (max 3GB memory).

**Comment by ddt000** [comment]
Luis, 

I have seen your statement on your add-ons.  It was well written and I appreciate your points and agree: I hope Mozilla is making the right choice.  However, since their choice is alienating or driving away great independent programmers like you I think their choice is necessarily flawed.  The community is one of the prime reasons Firefox is great; without it they are necessarily diminished.  

Thank you for all your work on Tab Groups, because when Panorama was removed from Firefox I despaired.  I find Tab Groups to be a very intuitive way of organizing, um, groups of tabs... in a way that allows users to not only quickly select a group but a specific tab within a group.  But I am very visually oriented, which I gather is uncommon.  

Best of luck in your future endeavors, 
David

**Comment by ddt000** [comment]
BTW, 

I noticed that a Firefox General option "when firefox starts" was changed from "show my windows and tabs from last time" to "show selected Session Manager session".  Changing back to "show my windows and tabs from last time" seems to have fixed my problem, and a session opens within a Tab Group instead of... without?  :D
