### ISSUE TITLE
High CPU usage in both Nightly and Aurora on "update" page

### ISSUE THREAD

**Issue by Pike** [Quicksaver/Tab-Groups#52]
I just got an update on the tab groups addon, and the new-version page spiked CPU usage in both Nightly and Aurora.

**Comment by Quicksaver** [comment]
Was this resolved when you closed the new version page or did you have to restart your browser?

**Comment by Pike** [comment]
It cooled down pretty quickly after I closed the tab. Also it was the content process of those firefoxens that spiked.

**Comment by Quicksaver** [comment]
If you open it manually does it also spike? (Open the add-on's options, it's the "About" pane on the left.)

**Comment by Pike** [comment]
Nope, both Nightly and DevEdition are fine if I do that manually.

**Comment by Quicksaver** [comment]
Could it have been the blinking in the checkbox at the top? If you have a free minute, please try this out for me, go to about:config and
- change "extensions.tabgroups.lastVersionNotify" to "1",
- make sure "extensions.tabgroups.userNoticedTabOnUpdates" is false
- make sure "extensions.tabgroups.showTabOnUpdates" is true.
Then restart your browser.

The new version page should open again, can you check if the CPU spikes? If it does, when you move your mouse over the blinking checkbox it should stop blinking. Does the CPU cool down then?

**Comment by Quicksaver** [comment]
For what it's worth, the blinking does need some CPU resources (otherwise it wouldn't blink obviously). But that's pure (and very simple) CSS, I don't believe there's anything I can do to optimize that.

**Comment by Pike** [comment]
Can't reproduce that. How about I'll keep an eye out when the next update comes, and kick of a devtools profiler?

**Comment by Quicksaver** [comment]
If you can that'd be great. Hopefully that was a one-time fluke.

**Comment by Quicksaver** [comment]
Please reopen if it ever happens again as you said. ;)
