### ISSUE TITLE
Can you give us an option to adjust the cache for thumbs?

### ISSUE THREAD

**Issue by NeoSeeU** [Quicksaver/Tab-Groups#523]
I discovered cache for thumbs must be limited, because new thumbs make older ones disappear.

Knowing it's a matter of RAM and speed, I feel I could spent some more bytes for thumbs. And resolution in free mode could become even some pixel lower to still recognize the layout of particular sites. 

Can you give us an option to adjust the cache for thumbs anytime when you do some hands on on GUI?

**Comment by Quicksaver** [comment]
All of that is handled by Firefox itself. All Tab Groups does is say "hey take a screenshot of that tab and save it". Everything else is all Firefox and I would rather not mess with it in order to avoid complications with other things that rely on it.
