### ISSUE TITLE
No Groups

### ISSUE THREAD

**Issue by TwisterMc** [Quicksaver/Tab-Groups#528]
I love this extension for showing me a preview of all the open tabs I have. I however don't use the grouping feature. Was wondering if there was a way to disable groups, or only show groups if you had two or more.

Personally I'd rather have additional screen space to show more open tabs instead of a section dedicated to creating/showing groups.

I know that's not the focus of this extension but I thought I'd ask.

**Comment by Quicksaver** [comment]
You can disable the group thumbnails in the add-on options, so that the group names at the top take up less space. But other than that, a no-groups mode is out of the scope of this add-on I'm afraid.
