### ISSUE TITLE
Have tab group manager/selector as an option for startup

### ISSUE THREAD

**Issue by eyecreate** [Quicksaver/Tab-Groups#529]
I'm not certain if it's possible, but it would be handy to have firefox startup act like the preference "show windows and tabs from last time", but first have a custom group selector page or the main tab group manager view show up first. This would allow picking the initial tab group to be loaded when the browser restores tabs.

**Comment by Quicksaver** [comment]
See #474.

**Comment by eyecreate** [comment]
The linked issue does not address my suggestion. The session manager extension listed there has no visibility into the tab groups.

**Comment by Quicksaver** [comment]
You're right of course, that was meant for another issue, I'm sorry about that. I'm afraid I won't be working on it anyway. See https://github.com/Quicksaver/Tab-Groups/blob/master/README.md

**Comment by eyecreate** [comment]
I didn't realize mozilla was phasing out xul extensions so soon. Sad news.
