### ISSUE TITLE
Tab groups stops working in 56b2

### ISSUE THREAD

**Issue by sgala** [Quicksaver/Tab-Groups#548]
Every time I start all tabs are empty, not even name/url is remembered. Using beta channel under Ubuntu 17.04

As the extension has an EOF that is close in time and I made a mistake and lost all my groups, I just deleted it and resigned to the old way of working.

But I still think it is worth reporting so that other people is careful enough to keep backup before upgrading to the 56 release

**Comment by dgutov** [comment]
FWIW, it's still working okay here.

I do remember having to restore the groups from a backup once, though, after upgrading to 56 beta.

**Comment by sgala** [comment]
After I lost them, I started recreating, but rebooting made them disappear again in exactly the same way: empty sets where the names of the groups and the number of empty "New Tab" was the only thing preserved.

So for me it has already been three times I have lost them, about once every reboot or so.

**Comment by dgutov** [comment]
Reboot or Firefox restart?

Maybe try restoring from backup, after all. It's inside this extension's Preferences.

I've closed and reopened Firefox multiple times without problem since.

**Comment by sgala** [comment]
Reboot, I have restarted without problems a number of times. It might be related with some problem saving status, or not waiting.

I don't think I can afford depending on myself remembering to backup/restore every time I exit firefox with the idea of rebooting, and in any case it will stop working soon. Now that I have lost my hundreds of tabs in like 10 groups (yes, I was stupid enough to not keep backup of those), it is the right moment to say goodbye.

I'm reporting mostly to help avoiding other people to suffer the same loss.

**Comment by sgala** [comment]
Incredible and fully unexpected:
* I uninstalled the extension after it failed by the third time. I had been deleting and reloading tabs at will after the two problems
* firefox 55 arrived to ubuntu and I decided to downgrade. While 56b1 was very good, 56b2 is almost unusable, as it has big lag and freezes related with UI and video...
* When I started firefox 55, I reinstalled the add-on and my old tab groups and tabs got restored.

So now I have time to note and save some of the most obscure and forgotten ones

Still the bug in 56b2 (it never happened with 56b1 to me) seems to be still there. I'm not sure why after deleting a number of tabs, uninstalling and rebooting, a downgrade got the old tabs in again...

**Comment by dgutov** [comment]
> 56b2 is almost unusable, as it has big lag and freezes related with UI and video

Could it be related to some other extension or config settings? I'm not having these kind of problems either.

**Comment by mechalynx** [comment]
56b2 on win7 here and I'm also not experiencing these issues. Not denying they're there for the OP just mentioning it for completeness.

**Comment by sgala** [comment]
I was running it on linux (Ubuntu 17.04) and few extensions as I already had to stop using a few because of e10s. The remaining legacy ones are:
* Addblock Plus
* SignText JS
* Tab Groups
* Ubuntu Modifications (the one from the ubuntu packaging)

Addblock Plus is the most intrusive with a difference, but the biggest lagging problems I see are related to video or animation/page interaction and they have not been present in 56b1 or in 55 now, so they are beta2 only.

I'm guessing it is a linux only problem. I can't discard a configuration change, but inspecting "about:config" does not show anything that looks strange.

In any case, going back to firefox 55 from 56b2 restored the tabs, so I'm not sure what went on. When I checked the profile manager, the number of profiles has not changed, so it is not like going to the -next PPA created a new profile. This is really puzzling.

**Comment by ximex** [comment]
@sgala replace AdBlock Plus with uBlock Origin. They have already a beta web-extension version

**Comment by Nerothos** [comment]
For now you can still set extensions.legacy.enabled to true but the FirefoxNightly twitter account already confirmed that it will not last long.

**Comment by dgutov** [comment]
> I'm guessing it is a linux only problem.

Could be, but I'm using Ubuntu 16.10. With uBlock Origin instead of ABP and with "Ubuntu Modifications" disabled.

**Comment by mausalimi** [comment]
why do you guys even bother? once you update to v57 (not long to go...) it will be dead anyway.

**Comment by mechalynx** [comment]
@mausalimi why did you bother making that comment?

**Comment by mausalimi** [comment]
my question is valid, yours is nothing but silly.

anyway, i'm out, good luck with workarounds here...

**Comment by sgala** [comment]
Update:
* When I went back to 55 I could recover the tabs, and make a backup
* I upgraded to ubuntu 56b3 (they had updated the beta on the while) and restored the tab groups. Went to the uBlock extension instead of AdBlock Plus, and things are working well apparently

What I'm doing: I opted into containers and installed "Sea Containers" I am gradually moving most of my Tab Groups into Container Groups, and with Sea Containers I have a reasonably similar UI to Tab Groups...

56b3 is more usable than 56b2, but I need to exit and restart every so and so or the UI gets unresponsive to keyboard and key presses (like I typed the whole "presses" word and had to wait 5 seconds after for it to appear). 55 is much better in this respect.

**Comment by mechalynx** [comment]
Not contesting, just mentioning for completeness, I'm on 56.0b3 win7 with AdBlock Plus and not experiencing any issues yet.

**Comment by sgala** [comment]
I'm on 56b4 and after the first failures in b2 that seem unable to be verified, it is working alright with b3 and now b4. So I think it is better to close the issue as such...

**Comment by odessa2** [comment]
Just to mention, i now have the same problem in Firefox 55.0.2 64bit Archlinux... Really sucks, half of my tabs are lost.. not even backups that worked before are restored correctly!
