### ISSUE TITLE
How to make it work?

### ISSUE THREAD

**Issue by mr-brunes** [Quicksaver/Tab-Groups#57]
Hi

This sounds like a great add-on but how does one use it?
There is no Tab Groups button visible (there is nothing next to the tabs as I'm using Tree Style Tab for vertical tabs), nor does the keyboard shortcut Ctrl+Shift+E work. Using FF 43.0.4.

**Comment by Quicksaver** [comment]
The add-on should be compatible with Tree Style Tab, and the button should appear at the bottom of the vertical tabs. It's likely that you have an incompatibility that's preventing the add-on from initializing properly. Please try disabling all your other add-ons except for Tab Groups and see if it works then.

**Comment by Eeems** [comment]
@mr-brunes You may also want to check the browser console to see if there are any errors there that may be useful for determining what is interfering.
https://developer.mozilla.org/en/docs/Tools/Browser_Console#Opening_the_Browser_Console

**Comment by Quicksaver** [comment]
I just tried with Tree Style Tab and everything seems to work fine for me. Without more information, there's nothing I can do.
