### ISSUE TITLE
Open a bookmark in a specific grouptab

### ISSUE THREAD

**Issue by Michel-Rotta** [Quicksaver/Tab-Groups#59]
Hi all,

I think a good feature willl be to join a bookmark and a group. With that, when you open a bookmark, it'll auto open in a specific group and the group is activated. 

Do you think it possible ?
Regards
Michel

**Comment by Quicksaver** [comment]
Possible, yeah. Don't know how how complex this would be though.

**Comment by Quicksaver** [comment]
I don't think I will add this specific ability any time soon. This would require somehow joining the concepts of "groups" and "bookmarks", and I fear that may end up being far too complex to implement. Instead I'll be working on #130, which should allow you some degree of what you would expect from this.
