### ISSUE TITLE
Using Tab Groups scatters Windows tabs thumbnails

### ISSUE THREAD

**Issue by mirhl** [Quicksaver/Tab-Groups#62]
I wouldn't know if this has something to do with using 44.0b9, or with your plugin version 1.02.. 
But it does seem like I'm experiencing [this problem](https://bugzilla.mozilla.org/show_bug.cgi?id=1070773) again.

**Comment by Quicksaver** [comment]
That's a weird one, I'll take a look and see if I can reproduce it. One question, do you have e10s (multiprocess) enabled?

**Comment by mirhl** [comment]
Not that I'm aware of. 
Besides, afaik e10s is still only shipped in auroras and nightlies.

**Comment by Quicksaver** [comment]
Scratch that question, those only work in e10s in Nightly. So I'll assume you don't have e10s enabled.

**Comment by Quicksaver** [comment]
It's turned on in some builds for some experiments in the latest beta. I don't know the specifics of how each is chosen or how to turn it on and off individually in beta though. But since it's not your case apparently there's no need to worry about it.

**Comment by Quicksaver** [comment]
That patch essentially does two things:
- update the taskbar previews accordingly when switching into and out of tab groups,
- when it does show previews, show only tabs in the current group.

Would you mind giving beta version 1.0.3b1, which has that patch, a try and let me know how it works for you? https://github.com/Quicksaver/Tab-Groups/releases/tag/v1.0.3b1 Note that it is not signed, so you'll have to flip the preference "xpinstall.signatures.required" to true to install it for now.

**Comment by mirhl** [comment]
Cool, it seems to work. 
Now I no longer have tab previews of every one of my 400 tabs :p
