### ISSUE TITLE
Closing a group and clicking on the x

### ISSUE THREAD

**Issue by klonamy** [Quicksaver/Tab-Groups#63]
Hello again,

Closing a group and clicking on the x causes the group to reappear an not to disappear entirely.

Firefox 44 Beta
Windows 10

**Comment by Quicksaver** [comment]
Are you closing the last group? That's expected if you are because technically you can't have no groups.

**Comment by klonamy** [comment]
I have 4 groups open, that was the 5th one.
It did close after i closed the overview and opend it again.

**Comment by Quicksaver** [comment]
That's weird, please let me know if it happens again.

**Comment by klonamy** [comment]
I can reproduce it.

**Comment by Quicksaver** [comment]
It happens on every group?

**Comment by Quicksaver** [comment]
If not, can you give me some exact steps to reproduce it then?

**Comment by klonamy** [comment]
- Open Tabgroups
- Open a new Group and close it or close an existing group with the 'X'

It does not create an error in the browser console.

**Comment by Quicksaver** [comment]
Ok, so when you say it "reappears", do you mean the group and its tabs come back or does the "Undo close group" button appear?

**Comment by klonamy** [comment]
Normal you could close the massage "Undo close group" with the 'x'.
That doesn't happen and the group with the tabs reappears.

**Comment by Quicksaver** [comment]
Does that also happen if you disable all your other add-ons, themes, etc, except for Tab Groups?

**Comment by klonamy** [comment]
Yes.

**Comment by Quicksaver** [comment]
Do you know if it worked correctly before? Or did it always do that for you?

**Comment by klonamy** [comment]
That is one i don't know. I just know that without the addon it was functioning, but that was the old beta waay back then.

**Comment by Quicksaver** [comment]
Hmm that's very weird. Can you try the add-on in a clean profile please and see if it still does that then? https://support.mozilla.org/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by klonamy** [comment]
It was a fresh clean profile xD

**Comment by Quicksaver** [comment]
Since you can still close the group by leaving the groups view, it's not very urgent. But it's definitely not supposed to do that, I'll investigate.

**Comment by Quicksaver** [comment]
BTW, don't know if this helps you, but the undo button auto-dissapears after 15 seconds if you don't move the mouse over it as well. The things I still find buried within the code... :)

**Comment by Quicksaver** [comment]
I still can't reproduce this. However, I made several changes to how the undo close button is constructed and to how it works as well. Would you mind giving [beta version 1.0.3b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v1.0.3b2) a try and see if it helps at all?

Please note that version is not signed, so you'll have to disable the preference "xpinstall.signatures.required" in about:config to use it. You can enable that again when you go back to the release version (or when I upload a new one and it updates of course).

**Comment by klonamy** [comment]
It is fixed.

**Comment by klonamy** [comment]
Or not... O.o
Maybe it is because it is still in the implemented in the beta?

**Comment by Quicksaver** [comment]
I don't understand. The beta I linked you to should has the changes I mentioned, the release version (1.0.2) does not of course.

**Comment by klonamy** [comment]
I meant in the firefox beta not the addon beta.
Or maybe another addon is interfering.

Name |Version|Aktiviert|ID
------------|-------------
Adblock Plus|2.7.1|true|{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Addon Update Checker|2.15|true|{891f0410-aaa2-11e0-9f1c-0800200c9a66}
Bookmark All|1.3.2.1-signed|true|{a76cd07b-f0d7-4ef9-9566-8faef6e290e4}
Classic Theme Restorer|1.4.6.1|true|ClassicThemeRestorer@ArisT2Noia4dev
Cookie Time|6|true|cookietime@darktrojan.net|
Element Hiding Helper für Adblock Plus|1.3.6|true|elemhidehelper@adblockplus.org
Firebug|2.0.13|true|firebug@software.joehewitt.com
Firebug Autocompleter|1.4.1.1-signed|true|{9aad3da6-6c46-4ef0-9109-6df5eaaf597c}
Firefox Hello Beta|0.1|true|loop@mozilla.org
Greasemonkey|3.6|true|{e4a8a97b-f2ed-450b-b12d-ee082ba24781}
HTTPS-Everywhere|5.1.0|true|https-everywhere@eff.org
Magic Actions for YouTube™|6.8.8.8|true|jid0-UVAeBCfd34Kk5usS8A1CBiobvM8@jetpack
Mind the Time|1.3.2|true|jid0-HYNmqxA9zQGfJADREri4n2AHKSI@jetpack
New Tab Override (browser.newtab.url replacement)|2.3.1|true|newtaboverride@agenedia.com
Notifier for GitHub|1.4.1|true|jid1-DMjSwVBPnk7a1Q@jetpack
Omnibar|0.7.28.20141004.1-signed|true|omnibar@ajitk.com
Roomy Bookmarks Toolbar|1.4.11|true|ALone-live@ya.ru
Sitzungs-Manager|0.8.1.9pre20160115b|true|{1280606b-2510-4fe0-97ef-9b5a22eafe30}
Slim Add-ons Manager|13|true|slimaddonmanager@opendfki.de
Stylish|2.0.6|true|{46551EC9-40F0-4e47-8E18-8E5CF550CFB8}
Tab Badge|2|true|badge@darktrojan.net
Tab Counter|1.9.9.1-signed|true|tabcounter@morac
Tab Mix Plus|0.4.2.0|true|{dc572301-7619-498c-a57d-39143191b318}
Tabgruppen|1.0.3b2|true|tabgroups@quicksaver
Textarea Cache|0.9.3.2.1-signed|true|{578e7caa-210f-4967-a0d3-88fe5b59a39f}
uMatrix|0.9.3.2|true|uMatrix@raymondhill.net

Will test it in the other profile too.

**Comment by klonamy** [comment]
Ok now it seems it is an addon.

**Comment by Quicksaver** [comment]
The Firefox version shouldn't make a difference at all in this case. You'll have to enable and disable your add-ons one / a bunch at a time to figure out which one is causing this.

**Comment by klonamy** [comment]
I will do that next week.

**Comment by Quicksaver** [comment]
Any news? In particular, can you tell if it still happens with [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1)? It has a few more changes to that button.

**Comment by klonamy** [comment]
Oh sry.
It does what it is expected to.
