### ISSUE TITLE
Turning off the Keep tab groups across restarts feature

### ISSUE THREAD

**Issue by Kyle4G** [Quicksaver/Tab-Groups#64]
Once the Keep tab groups across restarts feature has been turned on, how do you turn it off? 

I understand how this might be a great feature for some but it should be optional. At least for me, once turned on, I either have to uninstall the addon and no longer use it or live with this feature. I relay on the addon Session Manager to save my sessions if I WANT to save it for next time. So far that has been working great for me. But with the Tab Groups addon installed I don't get a choice anymore. 

I'm using Firefox 43.0.4 on Windows 7 SP1

Suggestions?

**Comment by Quicksaver** [comment]
Either "Startup and Shutdown" in Session Manager's preferences (through the add-ons manager) or "When Firefox starts" in Firefox options (they're the same thing) change it to whatever you want.

Tab Groups doesn't have its own session store feature, it merely changes those by default on the first time it is installed. If you change it now, it will keep whatever preference you choose, it won't change automatically anymore.
