### ISSUE TITLE
Shortcut Ctrl-Shift-` doesn't work on default US Windows keyboard layout

### ISSUE THREAD

**Issue by totalamd** [Quicksaver/Tab-Groups#65]
Default shortcut "Switch to prev. group" ``Ctrl-Shift-` `` doesn't work on Firefox 44b. `Ctrl-Shift-~` or just `Ctrl-~` works fine.

**Comment by Quicksaver** [comment]
It depends on the keyboard layout, on many layouts (like mine!) it won't work because you need to press shift to get to  ` . That is the default shortcut for now because that's the original shortcut in Firefox's native groups feature. I will change this default shortcut in the future though.

**Comment by Quicksaver** [comment]
I'm switching tracking to the other thread because it has more info.
