### ISSUE TITLE
Shortcuts settings checkboxes' layout moving depend on selected ticks

### ISSUE THREAD

**Issue by totalamd** [Quicksaver/Tab-Groups#66]
![](http://i.imgur.com/f46SpGH.png)
![](http://i.imgur.com/8CsHcH1.png)
![](http://i.imgur.com/f6GaoGL.png)
![](http://i.imgur.com/uodZ2he.png)
![](http://i.imgur.com/6LQaCVl.png)
![](http://i.imgur.com/QYHbcv7.png)

**Comment by Quicksaver** [comment]
#27
