### ISSUE TITLE
How to call it use javascript?

### ISSUE THREAD

**Issue by wideweide** [Quicksaver/Tab-Groups#68]
I use pentadactyl - https://github.com/5digits/dactyl  just like vimperator,and I call TabView like this:
map -modes=n,hints	gd   -javascript TabView._initFrame(function(){let tabItem=TabView._window.GroupItems.getNextGroupItemTab();if(tabItem)window.gBrowser.selectedTab=tabItem.tab;else{TabView._initFrame(function() {var tab = gBrowser.addTab();TabView.moveTabTo(tab, null);gBrowser.selectedTab = tab;});}});

How do I use when change to Tab-Groups?

**Comment by Quicksaver** [comment]
That should still work.
