### ISSUE TITLE
New capabilitiy : Add multiple tab to a tab group at once

### ISSUE THREAD

**Issue by ErwanLeroux** [Quicksaver/Tab-Groups#7]
Hello. Thank you for your addon, I find it very useful.

Could you add the possibility to add multiple tabs at once to a group ?

Currently, I can move tabs between windows using this addon : https://addons.mozilla.org/firefox/addon/cut-copy-paste-tabs/
Additionaly, the precedent addon use this addon : https://addons.mozilla.org/firefox/addon/bug-566510/ to permit the selection of multiples tabs at once.

**Comment by Quicksaver** [comment]
I do plan to add some more tab management capabilities to the add-on, but not exactly as those add-ons apply them.

Having said that, I'll be sure to try and make Tab Groups compatible with those add-ons. ;)

**Comment by ErwanLeroux** [comment]
Thanks !

**Comment by Quicksaver** [comment]
I whipped up a quick patch for compatibility with the bug 566510 add-on, it should work in the next version, at least for now it should work. I'll keep this issue open until I actually add multiple tab management capabilities to the add-on itself.

I should mention, e10s breaks CCPT, so I didn't even bother checking if that works or not, as it will stop working altogether soon.

**Comment by ErwanLeroux** [comment]
What are e10s ?

**Comment by Quicksaver** [comment]
Multiprocess Firefox, should be released sometime in the first half of next year.

**Comment by ErwanLeroux** [comment]
Okay, thanks !

**Comment by ErwanLeroux** [comment]
Got the 1.0.1 version installed, now I can add multiple tab to a group, thank you very much
