### ISSUE TITLE
Add a drop down menue left to the symbol

### ISSUE THREAD

**Issue by gusowski1** [Quicksaver/Tab-Groups#70]
In the Firefox feature there was an arrow next to the groub symbol, where you could select a tab from an other group and jump directly in this tab in the other qroup.
It would be glad if this feature will be included in the addon to.

**Comment by Quicksaver** [comment]
I'm almost sure the button never had a dropmarker at any point. You must be using an add-on like TabGroups Menu for that. Either way, see #5.
