### ISSUE TITLE
Zoom and Pan in the UI

### ISSUE THREAD

**Issue by viluon** [Quicksaver/Tab-Groups#71]
What if the panorama interface allowed for zooming and panning? I frequently feel that I am running out of visual space for my tab groups, especially on smaller screens. Zooming into small tab groups and allowing the tab group area to overflow the borders of the screen while letting the user to pan the whole view would be great! I could finally keep low priority tabs out of my view and focus on what's important right now (I feel like I am not the only person who keeps a "Read this later" tab group :stuck_out_tongue: )

**Comment by Quicksaver** [comment]
It's an interesting idea, but realistically speaking I doubt I'll ever get to this. It would mean a lot (a lot!) of code to create and maintain for relatively little gain, not to mention that pretty much everything else would have priority over this. I hope you understand.

**Comment by viluon** [comment]
It's okay, if the codebase isn't ready for this then, oh well, what can I do :stuck_out_tongue: Thanks for the quick response!
