### ISSUE TITLE
How to add Tab-Groups to localhost-only proxy Firefox instance from file?

### ISSUE THREAD

**Issue by LacrociviousAcrophosist** [Quicksaver/Tab-Groups#73]
I run more than one Firefox instance/profile. One instance/profile is restricted by manual proxy to localhost. It does not and must not see the Intertubes.

Having done a git clone, I cannot figure out how to use the 'Install Add-on from File' feature of Firefox (44 in this case) to add Tab-Groups to that proxy-restricted intance. I am not a dev but I do know how to build things from source, generally. Is there a way to do this?

For your efforts and your attention to this questions, a contribution has just now been made. Thank you!

**Comment by Quicksaver** [comment]
Can't you just download the [xpi from here](https://addons.mozilla.org/firefox/downloads/file/385190/tab_groups-1.0.2-fx.xpi) to your desktop and drag and drop it into your local Firefox instance?

**Comment by Quicksaver** [comment]
BTW that xpi I linked you to is what works with the "Install Add-on From File" button as well.

**Comment by LacrociviousAcrophosist** [comment]
That worked perfectly! I didn't know where the .xpi file was located. Thank you so much! ;-)

**Comment by Quicksaver** [comment]
You've very welcome. Don't forget to keep it updated, I'll be releasing tons of improvements and new features soon. ;)
