### ISSUE TITLE
Archive feature

### ISSUE THREAD

**Issue by maverick74** [Quicksaver/Tab-Groups#74]
For groups not usually used, it would be good to be able to archive them!

In another words: it would create a list with the name of the group and the links to the pages it had for later review (we could borrow a few ideas from the OneTab addon)

**Comment by Quicksaver** [comment]
You can easily use the backup and restore feature for that.

**Comment by maverick74** [comment]
LOL!!! That was fast!!! LOLOL

Sorry, didn't remember that!!! LOLOL

**Comment by Quicksaver** [comment]
No problem. ;)
