### ISSUE TITLE
Cycle through tab groups with 'Switch to next group'

### ISSUE THREAD

**Issue by ionutmarin** [Quicksaver/Tab-Groups#76]
Hello,

Thanks for creating this extension. It is one of the features I love in Firefox.

In the old tab group in Firefox we could cycle through tab groups by repeatedly pressing "Ctrl + \`". In this extension I see that this doesn't work. I need to press "Ctrl + \`" to go forward in the tab group and "Ctrs + Shift + \`" to go backwards. Do you think you will add the feature to cycle through the tab groups?

Thanks,
Ionut.

**Comment by Quicksaver** [comment]
I don't understand. That's what those shortcuts are doing isn't it?

**Comment by ionutmarin** [comment]
Hello,

With the builtin feature in firefox when I had three group tabs (A, B, C) I could cycle through them by just using one shortcut "Ctrl+`". So I would go A -> B -> C -> A -> B.

Now I can go A->B->C with Ctrl+`, but if I need to go back at A I have to user Ctrl+Shift+`.

Maybe it is a misconfiguration on my side.

Thanks,
Ionut.

**Comment by Quicksaver** [comment]
There's definitely something going on, it should go from C -> A, it works for me as well. If you disable all your other add-ons except for Tab Groups, does that also happen?

If you can do a little test for me, open the browser console (Ctrl+Shift+J) and clear it. Now if you try to go from C -> A and it doesn't, does anything show up in the console?

**Comment by ionutmarin** [comment]
Hello,

I applied the IT first rule and restarted Firefox :). Now everything works perfectly.

Thanks for your time,
Ionut.

**Comment by Quicksaver** [comment]
Great! Let me know if it starts happening again.
