### ISSUE TITLE
Ability to change language

### ISSUE THREAD

**Issue by AdrianoCahete** [Quicksaver/Tab-Groups#79]
Although people thinks portuguese is all the same, isn't.
European Portuguese (pt_PT) is too different from Brazilian Portuguese (pt_BR).

My Fx is in pt_BR, but the extension is in pt-PT. It's more difficult to read in pt_PT than in English, for example. So, please, put an option to change language on the fly.

**Comment by Quicksaver** [comment]
There isn't any kind of switch for this, and there never will be. That's because the add-on currently only has a pt-PT localization included. It will automatically show you a pt-BR locale as soon as one is included. See the Localization notes at https://github.com/Quicksaver/Tab-Groups if you want to help with that.

**Comment by AdrianoCahete** [comment]
But why extension load pt-pt if pt-br don't exist? Isn't the same.
The logical is to load default extension language, which I believe it's english.

Actual logic is something like "let's load spanish if pt-br or pt-pt isn't exist".
Don't make sense at all.

**Comment by Quicksaver** [comment]
I think you're confusing language and locale; they are not the same thing. Of course it won't load spanish if those don't exist, spanish isn't portuguese. ;)

That's not the extension doing either. Firefox (as well as pretty much every other application I've ever seen) is set up to load first the exact locale if it exists, in your case pt-BR. If it can't, it tries to load the same language in another locale if there is one, in this case pt-PT (no matter how different you see them, they are still the same language). Only if that fails will it load the default en-US locale.
