### ISSUE TITLE
Dropdown menu doesn't work

### ISSUE THREAD

**Issue by Jellby** [Quicksaver/Tab-Groups#80]
I have the Tab Groups button on by toolbar, it used to have a triangle on its right (i believe), where I could click, get the list of groups and change group without going to the (cluttered in my case) main Tab Groups interface. Now the menu is gone and I can't get the list. When I go to Customize toolbars, a small triangle appears, as an independent button, called "14/62", but it disappears in the real GUI.

**Comment by Quicksaver** [comment]
I don't know about that 14/62 thing, I'm sure it's unrelated to this add-on, but the rest is #5.
