### ISSUE TITLE
Unable to use 'Shift' in keycombos with 'lowercase' letters/characters

### ISSUE THREAD

**Issue by computertechie** [Quicksaver/Tab-Groups#81]
Key combos that include both **shift** and 'lowercase' letters or characters (such as **`** or **;**) are processed incorrectly. The plugin interprets the command as using the 'uppercase' characters on those same keys, such as **~** for **`** or **:** for **;**.

**Comment by Quicksaver** [comment]
They do work for actual a-z letters, but won't for those because the character is different yeah. That's a problem that can't be fixed, just choose whichever character that shift brings in that key and you should be fine.
