### ISSUE TITLE
Issues on FF45b1

### ISSUE THREAD

**Issue by mzso** [Quicksaver/Tab-Groups#83]
Hi!

It seems like at every startup the the active group was merged to another group. As far as it appeared in the tab bar anyway. When I pressed ctrl+e the two groups got separated again and appeared correctly.
Also after this the alt+d hotkey to get focus to the urlbar didn't work. (I can't really tell if it's actually because of this addon or another.)

Or maybe it was just after a crash after which session manager restored the session. Because I had this other annoying issue that every time I shut down the computer firefox apparently didn't shut down correctly because session manager always showed a crashed session.

Anyway now I'm back on stable, just thought I'd mention.

**Comment by Quicksaver** [comment]
> It seems like at every startup the the active group was merged to another group. As far as it appeared in the tab bar anyway. When I pressed ctrl+e the two groups got separated again and appeared correctly.

This should be already fixed for the next version. But you could try [beta version 1.0.3b2](https://github.com/Quicksaver/Tab-Groups/releases/tag/v1.0.3b2) to confirm, you'll have to disable "xpinstall.signatures.required" in about:config though to use that version as it's not signed.

> Also after this the alt+d hotkey to get focus to the urlbar didn't work.

This could well be another add-on interfering. It works fine for me and I don't see any reason off the top of my head for why Tab Groups would prevent the urlbar from being focused like this.

If you can confirm either of these issues, feel free to reopen this or open new ones. ;)

> I had this other annoying issue that every time I shut down the computer firefox apparently didn't shut down correctly because session manager always showed a crashed session.

I believe this is a known issue, it's happened for me a few times as well (a long time ago though). The groups information is stored in the session, so if Firefox fails to save the session properly then it could likely affect your next session in a variety of ways. There's not really much I can do there.

**Comment by mzso** [comment]
I upgraded to 1.0.3b2 and still experiencing the alt+D and the groups merging issues.
Also what I forgot to mention is when after the groups are unmerged when I go to and from Panorama The tab width stays the same width as it was when the tabs were merged. So I might have a single tab with the minimum tab width. The size will only correct itself if I open/close a tab or resize the window.

**Comment by Quicksaver** [comment]
Does any of that still happen if you disable all your other add-ons except for Tab Groups?

**Comment by mzso** [comment]
With Tab Groups and Session Manager enabled to restore the sessions the tab merger/un-merger happens. The tab resizing and the alt+d stuff didn't happen when I tried.

**Comment by mzso** [comment]
Weird thing: Now that I downgraded to 44 again the same symptoms were present. Restarted a couple of times, it kept happening. I the opened and closed a tab, and restarted again and then it didn't happen.
So I guess whatever causes this was saved into the session when I closed 45 before downgrading.

**Comment by Quicksaver** [comment]
Check out #93 by the way. This could definitely be because of Session Manager. As I mention there, I'll investigate more thoroughly over the weekend.

**Comment by mzso** [comment]
I see.
You could also try contacting the session manager dev.
I remember him as one of the more active devs.

**Comment by Quicksaver** [comment]
I probably will of course. :)

**Comment by Quicksaver** [comment]
A new update for Session Manager was just released that includes a fix for compatibility with Tab Groups. Please update it, reconfigure your groups and tabs (**after** updating Session Manager) and see if they stick after exiting and reopening Firefox.

**Comment by mzso** [comment]
So far so good, it seems.

**Comment by mzso** [comment]
(PS: I determined that the alt+d thing is caused by "[Hide GUI Bars](https://addons.mozilla.org/firefox/addon/hide-gui-bars/)", so definitely not this addon)

**Comment by Quicksaver** [comment]
> (PS: I determined that the alt+d thing is caused by "Hide GUI Bars", so definitely not this addon)

Just to confirm, it does that by itself and not in conjunction with Tab Groups, is that right?

**Comment by mzso** [comment]
Yes, it looks like it.

**Comment by Quicksaver** [comment]
Did this ever happen again since updating Session Manager?

**Comment by mzso** [comment]
No.
No merging since then, I only have the older issue: #118 
Ironically this issue might have prevented the groups from actually merging, because I don't remember that actually happening while this transient merge happened.

The alt+d things was a bug of a different addon, so that doesn't happen anymore.

The firefox not closing properly thing still happens all the time. But I doubt this addon has anything to do with it.
