### ISSUE TITLE
Make Groups resizeable from all edges and corners

### ISSUE THREAD

**Issue by Kasijjuf** [Quicksaver/Tab-Groups#84]
Currently Groups can only be resized by dragging the handle on the lower right corner of the Group. I would very much like to be able to resize a Group by dragging any corner or edge.

**Comment by Quicksaver** [comment]
Easier said than done I'm afraid, but I'll look into it.

**Comment by Kasijjuf** [comment]
Thank you

**Comment by Quicksaver** [comment]
Unfortunately a rewrite was necessary to use HTML5 resize abilities, which simply don't allow this. You can only resize from the one corner with those.

**Comment by Kasijjuf** [comment]
:frowning: sadness
