### ISSUE TITLE
Incompatibility with Tab Control add-on

### ISSUE THREAD

**Issue by famfop** [Quicksaver/Tab-Groups#85]
Before (the addon), when being in the tab groups view and closing a tab, it would just stay in the tab groups view and close the tab. Now, the same procedure closes the tab but makes me enter into the tab group, the closed tab was from. Is there a way to customize this or is it even a bug?

I'm using firefox 44.0 and the (up-to-date!?) version 1.0.2 on GNU/linux.

**Comment by Quicksaver** [comment]
That's definitely a bug, closing a tab should only close the tab, it should remain in groups mode. Does that also happen if you disable all your other add-ons except for Tab Groups?

**Comment by famfop** [comment]
Ok, I just tried out my tabs and could reduce it to "Tab Control". It only happens when having (at least...) both addons on. Do you guess the bug is in Tab groups or should i post a bug report in tab control? ^^

**Comment by Quicksaver** [comment]
I'll take a look tomorrow and let you know. Thanks for following up. ;)

**Comment by famfop** [comment]
Sorry for the spam if you were just about to go to sleep, but I could reduce it a bit further:
The error seems to only occur when having tab control's "focus left tab when closing current tab" activated.

**Comment by Quicksaver** [comment]
That sounds about right, focusing a tab by definition makes you leave groups mode (for instance if there's a dialog or a notification in that tab that would normally make the switch to that tab anyway). Maybe I can prevent this from happening from within tab groups, I'll definitely need to check it out.

And of course, spam away, the more info the better, even if I couldn't reply now I'd reply tomorrow for sure. :)

**Comment by Quicksaver** [comment]
This will be fixed with the next update. I've also let the developers of Tab Control know about this in case they want to integrate it into TC as well.

**Comment by famfop** [comment]
Thank you very much! Very good support over here =)

**Comment by zeird** [comment]
Compatibility fix with Tag Groups is live on AMO in TabControl `0.7.8.2`. Just for you to know.

**Comment by Quicksaver** [comment]
Since @zeird beat me to it, the fix I added before is useless so I've removed it. Thanks for the quick work. :)

**Comment by famfop** [comment]
Thanks a lot! Has been working the last few days, I guess issue can be closed. :)
