### ISSUE TITLE
Pinned Tab Options

### ISSUE THREAD

**Issue by ThoDHa** [Quicksaver/Tab-Groups#87]
Is there a way to get the pinned tabs to just be pinned to the specific tab group and not every tabgroup? Can that be an option?

**Comment by Quicksaver** [comment]
Unfortunately it doesn't work like that, they would be no different than any other tab except the title doesn't appear. In fact I'm already planning better pinned tabs behavior in groups mode (#34) to better mimic their behavior as tabs. I'm going to give priority to that for now. If by that time you still feel like this could be a good improvement, please reopen or open a new issue then.
