### ISSUE TITLE
Open "New Tab" on closing last tab option

### ISSUE THREAD

**Issue by arthoz** [Quicksaver/Tab-Groups#88]
Would it be possible to add in such a feature, so not to lose and having to remake groups?

I'm used to having a main group, where i do all my regular browsing in that often gets cleared out, but with the new Tab-Groups the group is closed when i close the last open tab, while old behavior (might have been an option) was to open a new tab on empty group, handy in my case as i'm using Fast/Speed Dial.

**Comment by Quicksaver** [comment]
Already in the to-do list. :)

**Comment by Quicksaver** [comment]
In [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6) I have made some behavior changes that should (hopefully) help with your situation.

Closing the last visible tab of a group will no longer close the group if: a) you disable that option in the add-on's preferences; or b) if you give that group a name (if it has a name, it's never considered fully empty).

So, if you're not in groups view (just browsing normally) and you close the last tab, it will simply open a new tab (you can never not have any visible tabs). If you then close that new tab, it will take you to groups view where you'll be able to choose another group for instance.

Please give it a try and let me know if you have any problems with it. By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.
