### ISSUE TITLE
Is Tab Groups addon compatible with Electrolysis?

### ISSUE THREAD

**Issue by peterallcdn** [Quicksaver/Tab-Groups#89]
I see tab groups is being removed from Firefox 45 and Mozilla recommends the Tab Groups addon to replace that functionality. I'm wondering however if installing Tab Groups addon is just delaying the inevitable. It sounds like many addons will stop working once Firefox Electrolysis is released.

So can anyone tell me if Tab Groups addon will still work once Electrolysis is released, or is it doomed like so many other great addons?

Thanks!

**Comment by Quicksaver** [comment]
Tab Groups is perfectly compatible with electrolysis.

**Comment by Kasijjuf** [comment]
I couldn't find Tab Groups listed on https://www.arewee10syet.com .  As I understand it, that is the site tracking Electrolysis compatibility.

**Comment by Quicksaver** [comment]
The add-on is new and no one's bothered to report it there as working yet, not to mention most add-ons on that list were added quite a while ago.
