### ISSUE TITLE
Lost access to all Tab Groups

### ISSUE THREAD

**Issue by El-Koder** [Quicksaver/Tab-Groups#90]
This occurs in one profile only and not in any others. It occurred after a crash while trying to move 8 tabs from a tab group to another tab group. Now I can no longer display the tab group bar and can only access the last accessed tab group's tabs. I have 330 tabs acoss 16 tab groups and need a way to recover the tabs at least. I can still see both the tabs and tab groups in Session Manager add-on backups, but this profile will not let me display the tab groups or access the tabs. Can you tell me where the Tab Group backups are stored so I can at least manually save the tabs?

**Comment by Quicksaver** [comment]
What Session Manager add-on backups do you mean? Do you mean from this add-on: https://addons.mozilla.org/firefox/addon/session-manager/ ?

If yes, Session Manager uses its own system to save session data, you should just follow the "Open session folder" item in its menu and it should take you there if that's what you want. Note that you can't use these files in this add-on's Backup and Restore feature, but you should be able to use them within Session Manager itself. Have you tried loading any of them?

**Comment by Quicksaver** [comment]
(Replying to other parts of your review) There's also no guarantee this add-on will work in Pale Moon, it is becoming increasingly different from Firefox and I simply don't have the availability to ensure compatibility with it.

And I couldn't really tell from what you wrote if Tab Groups Helper is them problem or only another symptom of your session getting corrupted somehow. Have you tried disabling it?

**Comment by El-Koder** [comment]
Thanks for the quick reply. It seems it is Tabs Groups Helper that is the culprit. I can now access the Tab Groups for this profile, but cannot display the Tab Groups bar or access the Tab Groups via Tab Groups Helper under v1.0.5, yet my other profiles work okay with v0.2.8. Tab Groups Helper is almost essential when working with this many tabs. So thankfully I haven't lost the tabs, but am back to the position where my browser vs add-on vs backup of working solution has become problematic. Again. Tried disabling and restarting Tab Groups Helper to no avail. It was definitely a combination of this add-on and Palemoon that caused the probelm in this profile. I will ask the developer if I can revert to the previous version, or how to create a copy of the profile maintaining the tabs and groups.

**Comment by Quicksaver** [comment]
I just now realized what you meant by 0.2.8, that's a **very** outdated version of that add-on, and it won't work at all with this add-on.
