### ISSUE TITLE
Pinned tabs should also be highlighted in searching

### ISSUE THREAD

**Issue by kidwm** [Quicksaver/Tab-Groups#91]
Ref #34

**Comment by Quicksaver** [comment]
Rewrote search interface in [beta version 2b5](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b5), which should also list pinned tabs now. Please give it a try and let me know if you find any problems.

**Comment by kidwm** [comment]
@Quicksaver LGTM, maybe adding tab thumbnails would be better.

**Comment by Quicksaver** [comment]
I plan to, but it won't happen immediately for the next update though.
