### ISSUE TITLE
Use another icon for exiting panorama mode

### ISSUE THREAD

**Issue by kidwm** [Quicksaver/Tab-Groups#92]
maybe a more intuitive one like close symbol.

**Comment by Eccenux** [comment]
I think back arrow would be better. Close symbol (cross) would suggest closing the toolbox.

BTW. You can use close window button and you will also exit Tab Groups.

**Comment by Quicksaver** [comment]
There's a whole new set of icons in [beta version 2b6](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b6). Please give it a try and let me know if you have any problems with it.

By the way, as you'll notice, there are a lot of changes in that beta, so it's definitely worth it giving the "How to use" section a once-through in the add-on's preferences, to get acquainted with the new and changed features.

**Comment by kidwm** [comment]
Does not look good in dark theme and maybe bigger would be better.
![2016-05-13 23-17-43](https://cloud.githubusercontent.com/assets/822446/15252540/ff7df8b8-18f3-11e6-8167-3e025dbc74f5.png)

**Comment by Quicksaver** [comment]
Yeah it's the same thing as what I mentioned in #33, I'll try to see if I can distinguish GTK's dark theme.
