### ISSUE TITLE
Irregular selection of keyboard short cut options

### ISSUE THREAD

**Issue by ethus3h** [Quicksaver/Tab-Groups#94]
Hi! I am having a regression from switching from Firefox 44.0 to 45 beta + this addon: the keyboard shortcut no longer works. I see that there are some options in the addon preferences for keyboard shortcuts, but many keys are missing, including the one I would like ("E"). I would be grateful if this was remedied! Thank you!

**Comment by Quicksaver** [comment]
The key selection boxes only gives you available combinations. So if there is another native Firefox shortcut, or even one from another add-on, that uses the same combo you're looking for, it won't show up there. In your example, for "E" you can only really use Ctrl+Shift+E or Ctrl+Alt+E or Ctrl+Alt+Shift+E, since Ctrl+E takes you to your homepage (I think), and E by itself is just a character and can't be used as a shortcut at all.

Unless you mean that the default shortcut Ctrl+Shift+E doesn't work, which would be very weird. Can you please explain exactly what it is you're looking for in there, or what isn't working that you think should work?

**Comment by ethus3h** [comment]
Well, I desire the shortcut Command+E. I don't use it for home page or whatever. I did have it set for Tab Groups in earlier versions of Firefox using the Customizable Shortcuts addon, but it stopped working when I updated. Thanks! :)

**Comment by Quicksaver** [comment]
It's not really within the scope of the add-on to override existing shortcuts, so there isn't anything I can do here. But if you find at least a way to disable the Cmd+E shortcut then it should appear in the list.

**Comment by ethus3h** [comment]
Aah, okay, thanks! :) I hacked around it by using Spark to autotype command y when I press command E, so that works well enough :)

It may be good to indicate that this isn't a drop-in replacement for the previous tab groups feature somewhere in the blog post about it then https://support.mozilla.org/kb/tab-groups-removal, cause I thought it was supposed to be the same...

**Comment by Quicksaver** [comment]
It is the same in terms of functionality, which is what it says there. But now that it's in my hands I do plan on making enhancing it wherever I can. It's not like you could modify the original shortcut at all before. ;)

**Comment by ethus3h** [comment]
Um, well the other addon modified the original shortcut before. I figured this provided whatever APIs the old Tab Groups did, so it would respond to the other addons the same as the old Tab Groups.

**Comment by Quicksaver** [comment]
I don't know how Customizable Shortcuts worked honestly, but I'm almost sure it was looking for the keyboard shortcuts themselves and not the APIs they use, in this case it was looking for a shortcut that toggled groups mode, which in turn uses the actual API of the feature to do it.

But, in the same way as I've explained in the other thread for the toolbar button, the shortcuts the add-on includes have a different id for both compatibility and restriction purposes. Customizable Shortcuts probably doesn't know about these ids (they would have to be hardcoded in it), so it doesn't know the add-on's shortcuts exist at all.

You should understand, when the tab groups removal article says "direct replacement", that is **only** as far as Firefox itself is concerned. Other add-ons aren't guaranteed, and many have updated already with some quick fixes to support this add-on (and I do mean quick fixes, as you can see for the most part it's just replacing a few ids and little else). I also try to add compatibility for other existing add-ons wherever I can, but in this particular case at least that's just not possible.

**Comment by ethus3h** [comment]
Ah, I see. Thanks!
