### ISSUE TITLE
Tool bar icon color incorrect

### ISSUE THREAD

**Issue by ethus3h** [Quicksaver/Tab-Groups#95]
Hi! I am having a regression from switching from Firefox 44.0 to 45 beta + this addon: the color of the toolbar icon for the tab groups is grey instead of green, even with "SVG colors for default toolbar icons" enabled. I would be grateful for this to be resolved. Thank you for continuing to provide the tab group function!

**Comment by Quicksaver** [comment]
> "SVG colors for default toolbar icons"

What is this? Does this come from an add-on?

**Comment by ethus3h** [comment]
Oh, yes, I meant to mention that! It's a Classic Theme Restorer option.

**Comment by ethus3h** [comment]
This might be related to another regression I noticed also, which is that the Stylish style below for the Tab Groups is no longer respected. (I assume this is an issue with this addon wrapper as it uses the same code as the previous implementation according to the Mozilla blog post https://support.mozilla.org/kb/tab-groups-removal?)

`@-moz-document url("chrome://browser/content/tabview.html")
{
  /* edited 2015-jan-13 */
/*Hide these:*/
.appTabTrayContainer {display:none !important}

/*Style Tabs*/
.tab {
 background-color: rgba(255,255,255,0.4) !important;
 border-radius: 0 !important;
 padding:3px 5px 5px 3px !important;
}
.tab-title, input.name {
 color: #000 !important;
  font-family:"Linux Biolinium O" !important;
 font-weight: bold !important;
 text-shadow: none !important;
  font-size:16pt;
}

/*Show Close Tab Button only on hover*/
.tab .close{display:none;}
.tab:hover .close{display:inline;}
body {
  color:rgba(0,0,0,0) !important;

}
  #bg {
      background:none !important;
    background-image:url('https://archive.org/download/walls20150113/Morning_II_by_Tadas_N.jpg')!important;

  }
/*Style Tab Groups*/
.groupItem {
 background-color: rgba(255,255,255,0.3) !important;
 border-radius: 0 !important;
 box-shadow: rgba(0,0,0,0.8) 2px 2px 5px !important;
}
.groupItem.activeGroupItem {
 box-shadow: 
  0  1px  0  #FFFFFF inset,
  0 -1px 1px #FFFFFF inset,
  -1px 0 1px #FFFFFF inset,
  1px  0 1px #FFFFFF inset,
  0 1px 3px  rgba(4, 38, 60, 0.6) !important;
}

/*Style Tab Favicon*/
.favicon{background-color: rgba(255,255,255,0.8)!important;
 border: 0 !important;
 border-radius: 0 !important;
}
.favicon img{
 padding-left:1px !important
}
}`

**Comment by ethus3h** [comment]
This may be a result of the same issue in #94 that the addon is not actually the same as the feature removed from Firefox. Feel free to close this as invalid if so :)

**Comment by Quicksaver** [comment]
It is indeed, I was about to reply here, I was just checking how CTR implements this feature. CTR has its own filters set to add colors to these buttons, which is something I can't just "toggle" from within my add-on (other than copying that whole CTR code, which is hardly optimal).

Basically, the toolbar button that the add-on includes (with id ```#tabGroups-tabview-button```) is not "the same" as the original button (with id ```#tabview-button```), so it's not default anymore. It can't be because of compatibility restrictions. However, on CTR's side it's just a matter of using the same code to style the add-on's button in the same way by adding that extra id in there. You could try contacting Aris (CTR's developer) and point him here if you'd like, to see if here would be interested in doing this.

**Comment by Quicksaver** [comment]
Oh, and for your userstyle, change the top line to
```@-moz-document url("chrome://tabgroups/content/tabview.xhtml")``` and it should work. Note that there could be a few minor changes already that could affect that userstyle (although honestly just by looking at it I don't really see any). But there definitely will be big changes in the future that could render that style completely useless.

**Comment by ethus3h** [comment]
Cool, thanks! And thanks again for the addon :)

**Comment by Quicksaver** [comment]
You're very welcome. :)
