### ISSUE TITLE
Feature request: allow rearranging the stacked tabs when preview

### ISSUE THREAD

**Issue by yfdyh000** [Quicksaver/Tab-Groups#96]
No interrupt the preview when drag a tab to another position (within the group).

**Comment by Quicksaver** [comment]
What do you mean preview? Do you mean updating its thumbnail?

**Comment by yfdyh000** [comment]
`<!ENTITY howto.resize.description2 "If you make the group small enough, the tabs will get stacked on top of one another. Below this stack, a preview button will appear. Click the preview button to see what tabs are in the stack without changing the size of the group.">`

**Comment by Quicksaver** [comment]
Oh that preview. Right, good point.

**Comment by Quicksaver** [comment]
This should be possible now in [beta version 2b1](https://github.com/Quicksaver/Tab-Groups/releases/tag/v2b1). Let me know if that doesn't work for you still.

**Comment by yfdyh000** [comment]
Seems it has been resolved, thank you for your efforts.
