### ISSUE TITLE
Wondering whats there...

### ISSUE THREAD

**Issue by sugob** [Quicksaver/Tab-Groups#97]
Hi

Thanks v much for doing this add-on - don't quite understand what mozilla are thinking recently about removing things like this and totally preventing unsigned addons [hey, I still use Mr Tech toolkit]

Currently work mandates use of FireFox 38 ESR [so will presumably jump to FF45 ESR one fine day] so this addons 'em:minVersion' [41.0a1 in install.rdf] means I can't immediately try it out so i thought I'd ask...

1) Can I use the Ctrl+` [Control plus reverse single quote i.e. key left of '1' on main part of US keyboard] to rotate though my tab groups?

2) Does search in tab group work the same i.e. highlight tabs whose URL match entered string - I have 250+ tabs and I currently use this to search for a lost tab? I can see a magnifying glass in some images but I thought I'd check!

Maybe update your addon page on mozilla with answers so others don't have to ask silly questions... ;-)

P.S. if 1) is a positive answer, a useful enhancement for me would be to have 'shift' reverse through tab groups i.e. press shift+ctrl+` 
TIA

M

**Comment by Quicksaver** [comment]
First off, you're very welcome. And there are no silly questions. ;)

1) Short answer, yes. Long answer. you can customize your own keyboard shortcuts for toggling into and out of groups mode, switching to the next group and switching to the previous group (the defaults are the same currently in Firefox, Ctrl+Shift+E, Ctrl+`, and Ctrl+Shift+` respectively).

2) Short answer, yes. There's no long answer. :) Right now the add-on's search works in exactly the same way as in the native Firefox groups.

If at the time when you update from ESR 38 to 45 you need any help or run into any trouble just let me know. Although it should be a smooth transition: when you update, Firefox will create a backup of your groups and tabs. By that point you'll just have to install the add-on and click the "Load migration backup" button of the "Backup / Restore" pane in the add-on's preferences and import back any groups and tabs you want.

**Comment by sugob** [comment]
Hi Quicksaver [or should that be ultra quick answerer!]

1) Good stuff [and bonus points for the configurability] :-) Not sure what keys you suggest above [have final been filtered out in your answer?]. It didn't occur to try it until I read following link ["only for some keyboard layouts"], but switching Windows 7 to US keyboard [it is physically a UK keyboard and windows 7 was previously set to UK] then the Ctrl+Shift+` starts working as it is meant to
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly

2) More good stuff

Thanks for confirming what I thought would be necessary at update time - more good info that could be put on the Ábout this add-on' mozilla page?

Hopefully mozilla won't now keep change the internals and give you a maintenance headache ...

Thanks v much

M
