### ISSUE TITLE
Default keyboard shortcut to move back through the groups doesn't work

### ISSUE THREAD

**Issue by mattytrentini** [Quicksaver/Tab-Groups#98]
Out of the box I expect **Ctrl+`** to cycle forwards through the tab groups and **Ctrl+Shift+`** to move back through the tab groups.

I think that's the intent too:
![tabgroupsconfig1](https://cloud.githubusercontent.com/assets/194201/12934142/95dde0e6-cfe0-11e5-8528-8a6af6275a2b.png)

However moving forward works, moving backwards does not. **Ctrl+Shift+`** doesn't work.

If the config is changed to using the tilde:
![tabgroupsconfig2](https://cloud.githubusercontent.com/assets/194201/12934206/fde58be4-cfe0-11e5-8a1b-37080958bcd5.png)

Then the shortcuts operate _exactly_ as expected.

**It seems that the shift key is affecting the selected shortcut key.** Obviously, the backtick can't be pressed if shift is held.

Suggested solution: Remove any of the shifted keys from the keyboard shortcut key list (including tilde). Respond to the shortcut key combination and, if shift is included as part of the shortcut, match on the 'unshifted' key. 

Whew that was hard to explain generically. :)

In easier terms: The shortcut **Ctrl+Shift+`** should work.

Firefox 44.0.1 on Windows 8 64 bit.

**Comment by Quicksaver** [comment]
See #75. Especially my last comment, please try that beta out and let me know.

**Comment by Quicksaver** [comment]
> Suggested solution: Remove any of the shifted keys from the keyboard shortcut key list (including tilde). Respond to the shortcut key combination and, if shift is included as part of the shortcut, match on the 'unshifted' key. 

And BTW this can never be a solution. Keyboards have different layouts around the world, shift doesn't change every character consistently across all of them.
